README.md

Added bold to mission in readme to test PR config

Added bold to mission in readme

---

packages/api/src/controllers/createUserController.js
packages/api/src/controllers/userController.js

* Added input validation in the backend (see userController's changes as it's almost the same thing in createUserController - the latter one has a lot of changes because I shifted the entire block of code leftward)
* Add user case:
* Validates if all required fields exist
* Validates email and wage amount (identical checks as front end)
* Fixed an issue where wage is not being picked up
* Add pseudo user case:
* Validates if all required fields exist
* Validates if email is in the form of user_id@pseudo.com
* Validates wage amount (identical check as front end)

Added user backend validation

---

packages/webapp/src/containers/Profile/People/index.js
packages/webapp/src/containers/Profile/People/styles.scss
packages/webapp/src/containers/Profile/index.js
packages/webapp/src/containers/Profile/styles.scss

Made changes in tab bar
Styled 'Invite User' button on Profile/People page
Add user page on first render (Need to select role before expanding view - expanded view is scrollable)
Farm Worker (Email is optional - only fields needed are First and Last Name)
Farm Owner (Email is required - hence invitation button is disabled)

Add user frontend with navbar displayed

---

packages/api/src/auth0Config.js
packages/api/tests/dummySignUp.js
packages/api/tests/signup.test.js

cases followed outlined in table here: https://lite-farm.atlassian.net/browse/LF-122

signup api tests seperated out

---

packages/webapp/src/containers/AddFarm/index.js

Refactoring variable initialization being done on each render.

Making USD default currency upon entering add_farm view.

---

packages/api/db/migration/20200817123803_station_binding_field.js
packages/api/package-lock.json
packages/api/package.json
packages/api/src/controllers/fieldController.js
packages/api/src/jobs/sendFarmData/sendFarmData.js
packages/api/src/jobs/station_sync/mapping.js
packages/api/src/jobs/waterBalance/waterBalance.js
packages/api/src/models/fieldModel.js
packages/api/src/models/weatherHourlyModel.js
packages/api/src/models/weatherModel.js
packages/api/src/routes/fieldRoute.js

IMPORTANT: Removing dependency of the field from weather and weatherHourly tables.
Adding new table weather_station that will represent (for now) the result of the city id from OW API.
Adding dependency to field, weather and weatherHourly table to the new weather_station table.
This way we are clustering most of the OW API to the unique locations on the weather station table

LF86 Throttling OpenWeather API to one a second to comply with API limits

---

packages/webapp/src/containers/ChooseFarm/index.js

https://lite-farm.atlassian.net/browse/LF-89

weird dropdown was showing up when select was setting size as 1 only

---

README.md

- Removed following lines: create .env.local file, add env vars to packages/api

Updated info about where env vars should be added

---

packages/webapp/src/containers/Field/NewField/index.js

- Back button renders drawing page

Back button redirects to draw page

---

packages/webapp/cypress/integration/field.js
packages/webapp/src/containers/Field/NewField/index.js
packages/webapp/src/containers/Field/NewField/styles.scss

- Save field button disabled until user enters field name
- Save field button changes color based on active/disabled state
- Input field changes color based on active/disabled state
- Colors are consistent with figma

Lf 157 disable save field button

---

packages/api/db/seeds/put_all_datasets.js
packages/api/package.json

fixing seed, modifying package json to avoid the need to run knex globally

---

packages/api/doc.api.yaml
packages/api/package.json
packages/api/src/controllers/fieldController.js
packages/api/tests/crop.test.js
packages/api/tests/cropRelatedAPI.test.js
packages/api/tests/endToEnd.test.js
packages/api/tests/farm.test.js
packages/api/tests/farmAPI.test.js
packages/api/tests/fertilizer.test.js
packages/api/tests/field.test.js
packages/api/tests/fieldAPI.test.js
packages/api/tests/fieldCrop.test.js
packages/api/tests/insightsAPI.test.js
packages/api/tests/mock.factories.js
packages/api/tests/mock.factories.test.js
packages/api/tests/pesticides.test.js
packages/api/tests/saleAPI.test.js
packages/api/tests/tasktype.test.js
packages/api/tests/testEnvironment.js
packages/api/tests/userAPI.test.js

modifying package.json to avoid token retrieval if not necessary modified doc.api to fix typos removed console logs

Modifying tests so they use the general cleanup script

---

packages/webapp/src/Auth/Auth.js
packages/webapp/src/containers/saga.js

It seems that the bug is gone but I am not sure whether I introduced new bugs

Lf 268 auth0 pg inconsistency

---

packages/api/db/migration/20200921102320_add_deleted_fields_for_soft_delete_sprint_10.js
packages/api/src/models/activityLogModel.js
packages/api/src/models/expenseTypeModel.js
packages/api/src/models/farmExpenseModel.js
packages/api/src/models/planModel.js
packages/api/src/models/priceModel.js
packages/api/src/models/roleModel.js
packages/api/src/models/saleModel.js
packages/api/src/models/todoModel.js
packages/api/src/models/yieldModel.js

- Added migration file
- Changed corresponding models to support soft delete

Soft delete migrations

---

packages/api/src/server.js

- Commented out usage in server.js

Commented out usage in server.js

---

package-lock.json
package.json
packages/api/package-lock.json
packages/webapp/package-lock.json

Remove dependencies under top-level package.json

Lf 320 lerna

---

packages/api/src/middleware/acl/hasFarmAccess.js
packages/api/tests/logs.test.js
packages/api/tests/mock.factories.js
packages/api/tests/mock.factories.test.js

fix bug: Can't change field of a log to a different field

LF-354-Logs middleware patch

---

packages/webapp/src/Routes.js
packages/webapp/src/components/Navigation/slideMenu/index.js

- Added Finance to manager/EO routes and slider menu

Manager and EO can see/use Finance

---

packages/webapp/src/containers/Profile/People/reducer.js

Removing incorrect reference to roles that expected a no whitespaced role string

---

packages/api/src/controllers/createUserController.js
packages/webapp/src/containers/Profile/People/reducer.js

fixing faulty logic that duplicated users

General fixes so the invitation email reaches local, and modifying people reducer

---

packages/webapp/src/containers/Profile/Farm/index.js

Commented our raw farm data button

---

packages/webapp/src/containers/Log/MyLog/index.js
packages/webapp/src/containers/Shift/MyShift/index.js
packages/webapp/src/containers/Shift/StepOne/index.js

also removed some dead code that existed in the Create Shift flow

F21-56/66/67 Remove elements for FW

---

packages/api/src/controllers/insightController.js

Query filters out expired and deleted crops

---

packages/webapp/src/components/LogFooter/styles.scss
packages/webapp/src/containers/Log/FertilizingLog/index.js
packages/webapp/src/containers/Log/styles.scss

fix add fertilizer popup style and add log footer style

fix log footer width

---

packages/webapp/src/containers/Field/NewField/index.js

rerender polygon if polygon exists after user clicks the back button on new field (2 of 2) page

rerender polygon if polygon exists

---

packages/webapp/src/components/Forms/NewCropModal/index.js

Commented out crop group and subgroup

---

packages/webapp/src/components/CreateUserAccount/index.js
packages/webapp/src/components/CreateUserAccount/styles.scss

- Create Account instead of sign in
- Microcopy placeholder
- Create Account on 1 line instead of 2

Changes to create account

---

packages/webapp/src/components/Inputs/DateContainer/index.js

broken date picker

---

packages/api/db/migration/20210115131743_user_status_id_field_name.js
packages/api/src/controllers/loginController.js
packages/api/src/controllers/passwordResetController.js
packages/api/src/controllers/userController.js
packages/api/src/controllers/userFarmController.js
packages/api/src/middleware/acl/checkInviteAndGoogleJwtContent.js
packages/api/src/middleware/acl/checkPasswordCreated.js
packages/api/src/models/organicCertifierSurveyModel.js
packages/api/src/models/shiftModel.js
packages/api/src/models/userModel.js
packages/api/tests/jwt.test.js
packages/api/tests/login.test.js
packages/api/tests/mock.factories.js

change user.status to user.status_id

update shift.user_id when sso user accept invitation

---

packages/api/src/templates/es/send_confirmation_email.html

I just remembered the software shows the updated lines :-D

Updated send_confirmation_email

---

packages/api/db/migration/20210129162452_alter-user-address-column-name.js
packages/api/src/controllers/userController.js
packages/api/src/models/userModel.js
packages/webapp/src/Routes.js
packages/webapp/src/components/Help/index.js
packages/webapp/src/containers/Field/EditField/index.js
packages/webapp/src/containers/Field/index.js
packages/webapp/src/containers/Navigation/slideMenu/index.js
packages/webapp/src/containers/Profile/Account/index.js
packages/webapp/src/containers/Profile/Account/styles.scss
packages/webapp/src/containers/Profile/Farm/index.js
packages/webapp/src/containers/Profile/Farm/styles.scss
packages/webapp/src/containers/Profile/People/index.js
packages/webapp/src/containers/Profile/People/styles.scss
packages/webapp/src/containers/Profile/index.js
packages/webapp/src/lang/en/translation.json

disable submit button until message and support type are filled
Worker should be able to see fields and field crops. BUt they can't edit
add /field /edit_field when user is worker
profile style fixes
change user role modal style fixes

change user.address to user.user_address

---

packages/api/src/templates/pt/help_request_email.html

I think I got all the text that need to be translated.

Translated help_request_email.html

---

packages/webapp/src/containers/ChooseFarm/index.js
packages/webapp/src/containers/Log/FertilizingLog/index.js

fix add fertilizer modal container on android.
fix switch farm modal

style fix. Switch farm modal fix

---

packages/webapp/src/components/WelcomeScreen/index.js
packages/webapp/src/containers/CustomSignUp/saga.js
packages/webapp/src/index.js

Display english welcome svg by default
set litefarm_lang on sign up
remove language detection on index.js

Display english welcome svg by default

---

packages/webapp/public/global.css
packages/webapp/src/assets/images/map/zoomIn.svg
packages/webapp/src/assets/images/map/zoomOut.svg
packages/webapp/src/components/Map/CustomZoom/index.js
packages/webapp/src/components/Map/CustomZoom/styles.module.scss
packages/webapp/src/components/Map/Header/index.js
packages/webapp/src/containers/Map/index.js
packages/webapp/src/containers/Map/styles.module.scss
packages/webapp/src/stories/Pages/Map/CustomZoom/CustomZoom.stories.js

- fix map height
- add custom zoom buttons
- remove google logo and bottom bar

[LF-784] improvements

---

packages/webapp/src/containers/fieldCropSlice.js
packages/webapp/src/containers/locationSlice.js

Reverts LiteFarmOrg/LiteFarm#738

Revert "fieldCropSelectors"

---

packages/webapp/src/components/CropTile/index.js
packages/webapp/src/components/CropTile/styles.module.scss

failed to notice some subtle detail differences on figma. fixed now

past crop style fixes

---

packages/api/src/middleware/validation/deleteLocation.js
packages/webapp/public/locales/es/message.json
packages/webapp/src/components/Shift/StepTwo/index.js
packages/webapp/src/containers/Shift/StepTwo/StepTwo.js

Delete location middleware updated

Sending pure date instead of timezone date on post shift. 

---

packages/webapp/src/components/Crop/transplant.js

LF-1410 fixes

---

packages/webapp/src/components/Crop/Transplant/index.js

cover crop or harvest radio required before clicking continue bug fix

---

packages/api/src/controllers/organicCertifierSurveyController.js
packages/api/src/jobs/certification/zip.js
packages/api/src/jobs/index.js

naming all files to document-filename in case of multiple files on doc. zip changes

---

packages/api/src/middleware/validation/task.js
packages/api/src/routes/taskRoute.js
packages/webapp/src/components/Task/PureManageCustomTasks/index.js
packages/webapp/src/components/Task/PureTaskDetails/index.js
packages/webapp/src/components/Task/PureTaskTypeSelection/index.js
packages/webapp/src/components/TaskCard/index.js
packages/webapp/src/containers/Task/AddCustomTask/index.js
packages/webapp/src/containers/Task/TaskAssignment/index.js
packages/webapp/src/containers/Task/TaskTypeSelection/index.js
packages/webapp/src/containers/Task/saga.js

- show custom task types in task type selection screen
- make flow usable for custom task creation

[ST-19] custom task flow

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Task/AbandonTask/index.js
packages/webapp/src/components/Task/TaskReadOnly/index.js

task page related bug fixes

---

packages/api/src/templates/locales/pt.json
packages/webapp/public/locales/pt/common.json
packages/webapp/public/locales/pt/expense.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json

Did the translations to Portuguese

PT translations

---

packages/webapp/src/components/MapDrawer/index.js
packages/webapp/src/components/Task/PureTaskTypeSelection/PureManageCustomTasks.js
packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.js
packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.js

Note that "select task type" screen shows alphabetized standard types followed by alphabetized custom types. If we want one alphabetized sequence of both standard and custom types, I'll need to take another run at this.

St 250/alphabetize selections

---

packages/api/src/jobs/certification/pdf.js
packages/webapp/src/containers/RenderSurvey/RenderSurvey.js

Add missing translation file on render survey page

fix-puppeteer-async-issue

---

packages/webapp/src/components/AddFarm/index.js
packages/webapp/src/containers/AddFarm/index.js
packages/webapp/src/containers/Map/index.js

[TDC-6] Better integrate maps autocomplete, lat/lng input

---

packages/webapp/src/containers/AddFarm/index.js
packages/webapp/src/containers/AddFarm/saga.js
packages/webapp/src/containers/hooks/useThrottle.js

replace useEffect with defaultValues

---

packages/api/src/controllers/organicCertifierSurveyController.js
packages/api/tests/organicCertifierSurvey.test.js

Set bufferzone organic status to non-organic

LF-2045/fix-organic-status-of-location-without-active-management plans

---

packages/api/src/controllers/shiftController.js
packages/webapp/src/containers/Finances/index.js

This query was generating an error on the backend when the finances page load. Although, most likely this is not used anymore.

Fixing query made on the load of finances page.

---

packages/webapp/public/locales/en/message.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json

There were some missed Pt translations as well, those have been corrected with this PR.

Changing Management plan to Crop plan in EN

---

packages/webapp/src/containers/Finances/Labour/Task/index.js
packages/webapp/src/containers/Finances/index.js
packages/webapp/src/containers/Finances/util.js
packages/webapp/src/util/index.js

Started as bug fix for inconsistent labour cost totals. Expanded to fix many floating point and/or rounding problems across finances.

[LF-2097] Fix financial calculations

---

packages/webapp/src/apiConfig.js

Add env var for API URL

---

packages/api/db/migration/20220224183435_update_country_id_production.js

Please do not merge this after reviewing. I want to observe the running process as it goes into the integration environment to see what we can learn about when if works vs. fails.

Run job in integration env

---

package-lock.json
packages/api/package-lock.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/components/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/Task/TaskReadOnly/index.jsx

Added a field to the UI on the read-only task view of abandoned tasks to show the due date per [LF-2391](https://lite-farm.atlassian.net/browse/LF-2391). Updated UI can be seen below

Lf 2391/add due date abandoned task view

---

packages/webapp/src/components/CardWithStatus/TaskCard/TaskCard.jsx
packages/webapp/src/components/CardWithStatus/TaskCard/styles.module.scss

Dates and and underlines on cards do not appear if card is set to completed or abandoned

LF-2378/Bug fix for completed and abandoned cards showing underlined under data and assignee

---

packages/api/src/controllers/taskController.js
packages/api/src/routes/taskRoute.js
packages/webapp/cypress/integration/taskFlow.spec.js

The api returned the updated harvest task in a form different from the front-end's expectations. This "corrupted" the Redux store.

Lf 2360/completing harvest task hangs

---

packages/webapp/src/components/CardWithStatus/TaskCard/TaskCard.jsx

This is a bugfix for the bug on beta where the crop plan page could not open.

Fixed bug where crop page could not load

---

.github/workflows/automated_tests.yml

This action should run all of the jest tests in a docker container through github actions. 
@smattingly you will need to add the required repository secrets for this to work

Setup tests github action

---

packages/webapp/src/containers/Task/saga.js

Looks like this bug was occurring when you tried to create a task at a location without any management plans.

Fixed error where you can't create a task

---

packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx

@AbdusShaikh please check to see if you are getting the same looping behaviour when trying to return to original page from crop plans

bug fix for Clicking < from variety detail page should be contextual

---

packages/api/.env.default
packages/api/db/migration/20220525200540_populate_farm_timezones.js
packages/api/package-lock.json
packages/api/package.json
packages/api/src/jobs/station_sync/updateTimeZoneOffsets.js

To test this:
1. Copy the `VITE_GOOGLE_MAPS_API_KEY` from `packages/webapp/.env` to the `GOOGLE_MAPS_API_KEY` in `packages/api/.env`
2. Make multiple farms locally (ideally in multiple timezones)
3. Run the migrations
4. Query the `farm` table in postgres and check if the `utc_offset` values are correct. They should be the utc offset in minutes for the location of the farm

Made migration to add time zones to every farm with latlng

---

packages/api/src/jobs/certification/recordD.js
packages/api/src/jobs/certification/survey_record.js
packages/api/src/jobs/index.js

This PR addresses requested changes to [LF-2322](https://lite-farm.atlassian.net/browse/LF-2322).
See [PR #1929 ](https://github.com/LiteFarmOrg/LiteFarm/pull/1929) for instructions on how to test this. 
With these changes, a PDF of the survey questions should not be included in the final export, and the xlsx document should include the relevant farm id and survey id in the header. Additionally, questions nested inside multiple groups/pages should export correctly now.

Export document bugfixes

---

packages/webapp/src/containers/Task/TaskComplete/index.jsx

This fixes a bug where you are unable to complete a task

Fixed complete task

---

packages/webapp/public/locales/en/message.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/fr/filter.json
packages/webapp/public/locales/fr/message.json
packages/webapp/public/locales/fr/translation.json

This PR adds the missing french translations for the webapp.

Added missing french translations

---

packages/api/src/jobs/notifications/notifyAllUsers.sql

Ticket: [F21-555](https://lite-farm.atlassian.net/browse/F21-555)
I updated the notifyAllUsers scripts default values so that we do not have null values in places we don't want.

fix: notify all users sql command

---

packages/webapp/src/containers/InvitedUserCreateAccount/index.jsx

To test: 
1. I have created a sandbox environment to test the undefined issue with google_id_token.
2. Please check the following link to the sandbox:
https://codesandbox.io/s/priceless-leakey-stsvl4?file=/src/App.js
For more details, please check: 
1. https://sentry.io/organizations/litefarm/issues/3045842282/?project=5777759&query=is%3Aunresolved
2. https://lite-farm.atlassian.net/browse/F21-591

F21-591 : Fix - cannot read properties of undefined (reading 'google_id_token')

---

packages/api/src/templates/locales/fr.json
packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/en/message.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/es/message.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/common.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/PasswordResetAccount/index.jsx
packages/webapp/src/components/Signup/EnterPasswordPage/index.jsx

Resolves
F21-614 #comment we need translations for PT and FR
F21-610
F21-615

Fixing issues regarding reset password error messages and labels.

---

packages/webapp/src/containers/LocationDetails/LocationTasks/index.jsx
packages/webapp/src/containers/Task/TaskCard/index.jsx
packages/webapp/src/containers/Task/TaskReadOnly/index.jsx

This PR resolves https://lite-farm.atlassian.net/browse/F21-646
To test:
1. Create a task and assign it to a location
2. Go to the map and click on that location
3. Change the date of the task from the location page
4. The divider above the task  on the location page should update to show the proper date

Fixed date strings to be parsed correctly

---

packages/webapp/src/components/Crop/Detail.jsx
packages/webapp/src/components/Crop/Management.jsx
packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
packages/webapp/src/components/CropListPage/index.jsx
packages/webapp/src/components/RouterTab/index.jsx
packages/webapp/src/containers/Crop/CompleteManagementPlan/AbandonManagementPlan.jsx
packages/webapp/src/containers/Crop/CompleteManagementPlan/CompleteManagementPlan.jsx
packages/webapp/src/containers/Crop/CropDetail/index.jsx
packages/webapp/src/containers/Crop/CropManagement/index.jsx
packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
packages/webapp/src/containers/CropVarieties/index.jsx
packages/webapp/src/containers/LocationDetails/LocationManagementPlan/index.jsx

Per https://lite-farm.atlassian.net/jira/software/c/projects/F21/boards/3?modal=detail&selectedIssue=F21-666 
When you abandoned a crop management plan and then click on it's detail page, you would be caught in an infinite loop. This PR fixes the routing to remove the infinite loop

Fixed infinite loop

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/containers/Map/index.jsx

This new approach should have much better browser compatibility than before.
To test:
1. Go to your farm map
2. Click the download button
3. Click the "Donwload now" button
4. The map should download successfully in your browser

Improved browser compatability of our map download

---

packages/webapp/src/containers/filterSlice.js

Ticket [F21-558](https://lite-farm.atlassian.net/browse/F21-558)
This PR fixes the issue where cypress test was failing. Read the discussion on the Jira ticket.
To Test:
1. Run cypress and make sure the notification flow test passes

F21-558/cypress test failing fix

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Form/DateRangePicker/index.jsx
packages/webapp/src/containers/AddFarm/currency/commonCurrency.json
packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx
packages/webapp/src/containers/Finances/index.jsx

Added MWK currency, and a tooltip for the date range picker in the "Estimated Revenue" page.
To test:
1. Ensure the correct currency appears all across the "Finances" page. Use farms in different countries to be thorough
2. Navigate to the "Estimated Revenue" section in the "Finances" page, and ensure the tooltip is appearing and working right above the date range picker.

Estimated Revenue Tooltip and MWK

---

packages/webapp/src/containers/Home/index.jsx

- Setup:
Make sure to have 2 different farms
Create X number of tasks for farm A (I just created 2) and assign these tasks to yourself. Any tasks is fine I just did cleaning task as it is the easiest to work with. You will notice the notification bell update when you have created the task.
Create Y number of tasks for farm B (I just created 3) and do the same thing above, assign to self and make sure the notification bell on this second farm has 3 tasks. 
- Test
Switch between the two farms and the notification bell alerts number should update based on the amount of alerts in each farm.

Need to ensure after a user switches to a new farm that they receive alerts for that farm

---

packages/webapp/src/containers/Map/styles.module.scss
packages/webapp/src/containers/Map/useMapAssetRenderer.js

This PR resolves https://lite-farm.atlassian.net/browse/F21-698
To test:
1. Either retire all existing locations on one of your farms, or create a new farm without any locations
2. Go to the farm map
3. You should see a pin with the name of your farm beneath it at the latlong coordinates of your farm

Added default map pin

---

packages/api/src/controllers/notificationUserController.js
packages/api/src/models/notificationUserModel.js
packages/webapp/src/containers/Navigation/Alert/saga.js

This fixes a problem related to alert tracking opening too many subscriptions.
See [LF-688](https://lite-farm.atlassian.net/browse/F21-688) for details.

Track and limit subscriptions per user, browser

---

packages/webapp/public/locales/fr/translation.json

This fixes a small translation error for FR

Fixed translation error

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/pt/common.json
packages/webapp/src/components/Form/ReactSelect/index.jsx

Tickets: [F21-701](https://lite-farm.atlassian.net/browse/F21-701), [F21-696](https://lite-farm.atlassian.net/browse/F21-696)

fix: select and create language fix for all drop downs - F21-696, F21-701

---

packages/api/src/middleware/acl/checkScope.js

The permissions check server would crash when the farm_id came through as the string literal `'undefined'`.
You can test the data screening and the query error handling by explicitly assigning that string to `farm_id` at checkScope.js line 20 and/or line 58.

Prevent server crash

---

packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx

To test:
1. Add a new expense in the finances page
2. Enter 0 as the value and attempt to submit. You should see an inline error but no alert

Remove greater than 0 alert

---

packages/webapp/src/containers/saga.js

For more details: https://lite-farm.atlassian.net/browse/F21-602
To test:
Steps to reproduce:
1. Go to “My information”
2. Switch your language
Expected Results:
All the language tags will display properly
 
Actual Results:
The language tag for the current language does not change, and the snack bar displayed in the wrong language. When you switch to a language that has already been used in the current session, it works properly. This only occurs when switching to a new language.

F21-602- Fix : Some language tags don't update when initially switching languages

---

packages/api/src/endPoints.js
packages/api/src/util/ensemble.js

Ticket: [LF-2453](https://lite-farm.atlassian.net/browse/LF-2453)
Bulk sensor claim helper function for the ensemble communications flow.
To test:
- Add a function call to `bulkSensorClaim` at the end of the file with valid arguments
- Make sure the response is appropriate (you can add a break point or use a console log to check, since we do not have the endpoint that would call this set up yet, so `res.send` will not be available).

Feature/ensemble communications LF - 2453: Bulk sensor claim helper function

---

packages/api/db/migration/20220610171351_create-integrating-partners-table.js
packages/api/db/migration/20220610171713_create-farm-external-integrations-table.js
packages/api/src/controllers/farmExternalIntegrationController.js
packages/api/src/models/farmExternalIntegrationsModel.js
packages/api/src/models/integratingPartnersModel.js

Ticket [LF-2482](https://lite-farm.atlassian.net/browse/LF-2482)
**integratingPartners**
- partner_id
- partner_name
- access_token
- refresh_token
- root_url
- deactivated
**farmExternalIntegrations**
- farm_id
- partner_id
- organization_uuid
- webhook_address

LF-2482/structures to support ensemble integration

---

packages/api/src/models/integratingPartnersModel.js
packages/api/src/util/ensemble.js

Ticket: [LF-2482](https://lite-farm.atlassian.net/browse/LF-2482)

Feature/ensemble communications LF-2483: refresh token logic

---

packages/webapp/src/components/Notifications/MoreRecentNotificationWarning/styles.module.scss
packages/webapp/src/stories/WarningBox/WarningBox.stories.jsx

Quick fix for notification timeline border and icon specificity issues.

Notification timeline - border and icon fix

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/CreateUserAccount/index.jsx

Ticket [LF-2472](https://lite-farm.atlassian.net/browse/LF-2472)
To Test:
1. Create a new account
2. Make sure the language preference selection works (it should detect the browser language and selecting a different language will change the language of the app immediately)

LF-2472 add a language selector drop down on the account creation information page

---

packages/webapp/src/containers/Map/saga.js

To test: 
1. mock the API response of bulk upload as 202. (for me the add sensors is giving 500)
2. check after bulk upload, if you can see the following modal.
for more details 
https://lite-farm.atlassian.net/browse/LF-2524

Handling of async bulk upload on frontend.

---

packages/api/src/controllers/taskController.js
packages/api/src/controllers/userController.js
packages/api/src/controllers/userFarmController.js
packages/api/src/models/emailTokenModel.js
packages/api/src/models/userFarmModel.js
packages/api/src/templates/emails/invitation_to_farm_email/html.pug
packages/api/src/templates/emails/send_confirmation_email/html.pug
packages/api/src/templates/emails/welcome_email/html.pug
packages/api/tests/taskNotification.test.js
packages/webapp/cypress/integration/happyPath.spec.js
packages/webapp/cypress/plugins/index.js
packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/CreateUserAccount/index.jsx
packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
packages/webapp/src/components/Form/Unit/index.jsx
packages/webapp/src/components/InviteSignup/index.jsx
packages/webapp/src/components/InviteUser/index.jsx
packages/webapp/src/components/InvitedUserCreateAccount/index.jsx
packages/webapp/src/components/JoinFarmSuccessScreen/index.jsx
packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/containers/Callback/index.jsx
packages/webapp/src/containers/Callback/saga.js
packages/webapp/src/containers/CustomSignUp/index.jsx
packages/webapp/src/containers/Home/utils/season.js
packages/webapp/src/containers/InviteSignUp/index.jsx

Dealing with merge conflicts between `collab/sensors` and `integration`.

Merge conflicts collab sensors with integration

---

packages/api/src/controllers/sensorController.js
packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js

To Test.
1. select an invalid file format and check the validation errors.
https://lite-farm.atlassian.net/browse/LF-2616

Fix validation condition to show errors for selecting invalid CSV file

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Map/DrawingManager/index.jsx
packages/webapp/src/components/Map/DrawingManager/styles.module.scss
packages/webapp/src/containers/Map/index.jsx
packages/webapp/src/containers/Map/useDrawingManager.js

This PR resolves https://lite-farm.atlassian.net/browse/LF-2576
To test:
1. Go to the farm map
2. Try to create a watercourse or a buffer zone with no length (i.e. just a point)
3. You should get a popup prompting you to redraw the line

Fixed bug on map

---

packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js

To test: 
1. Open bulk upload sensor modal.
2. click on "Download this template"
3. check if part number and brand are not present as the columns in the downloaded CSV file.

Removal of part number and brand from the bulk sensor template

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/sensorModel.js
packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js

Fixes enums in the csv to match the spec

Fixed some csv reading types

---

packages/webapp/src/components/CreateUserAccount/index.jsx

Create a new lite farm account and you should be able to change the gender field to any value instead of the field being stuck to one fixed value. Make sure to also do this in different languages as well.

Fix immuntable gender when changing languages bug

---

packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/containers/Profile/EditUser.jsx

To test:
1. Create a new user on your farm
2. Try and change their role - this should work
3. Go to your own user
4. You should not be able to change your own role, and the dropdown for this should be disabled

Made cherry pick

---

packages/api/src/models/locationModel.js
packages/api/src/models/sensorModel.js
packages/api/src/routes/sensorRoute.js
packages/webapp/src/containers/Map/saga.js

To test:
- Run latest migrations
- Try adding new sensors

Lf 2683/refactor add sensor to remove sensor id and farm id

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/sensorModel.js
packages/api/src/routes/sensorRoute.js
packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/saga.js

To make sure this is working:
Upload a sensor if you have not already
Check the sensor details and make sure all it's fields are populated, mainly the brand and reading types.
I think there is a bug where the model does not get inputted from the bulk sensor upload so if model has not been populated it is likely because it has not been uploaded to the database in the first place. Without having the model the sensor will not update.
Try to update the sensor fields and make sure there are no errors.

Refactored get reading types, patch sensor, and get brand name for sensor

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/sensorModel.js
packages/api/src/models/sensorReadingModel.js
packages/api/src/routes/sensorRoute.js
packages/webapp/src/containers/SensorReadings/saga.js
packages/webapp/src/containers/sensorSlice.js

To test: 
- Make sure you have at least on sensor location on the map
- Use the sql code below to generate sensor readings. Then go to the sensor readings tab. 
```sql
CREATE OR REPLACE FUNCTION generate_sensor_readings(
readingType TEXT,
unit TEXT,
valid BOOLEAN,
startDate DATE,
endDate DATE,
tMax REAL,
tMin REAL	
) RETURNS INTEGER AS
$func$
DECLARE 
currentDate DATE := NOW();
valueData REAL := 0;
r RECORD;
s RECORD;
intervalDuration TEXT := '1 hour';
returnedID TEXT := '';
counter INTEGER := 0;
BEGIN
EXECUTE $$ TRUNCATE TABLE sensor_reading $$;	
FOR s IN SELECT * FROM sensor LOOP 
FOR r IN SELECT * FROM generate_series(
startDate,endDate, 
intervalDuration::INTERVAL) AS s(i) LOOP
valueData := ROUND((RANDOM()*(tMax-tMin)+tMin)::NUMERIC, 1);
EXECUTE $$
INSERT INTO public.sensor_reading( …
```

Lf 2683/refactor get and invalidate readings to remove sensor

---

packages/webapp/src/containers/Profile/EditUser.jsx

This PR resolves https://lite-farm.atlassian.net/browse/LF-2649 as well as https://lite-farm.atlassian.net/browse/LF-2648
To test:
1. Invite a user with an email to your farm
2. Add a salary to that user in the edit user page
3. Try to save - this should work!
4. Invite a pseudo user to your farm
5. Add a salary to that user in the edit user page
6. Try to save - this should work!

Fixed update user

---

packages/api/db/migration/20220718193208_add_sandbox_column.js
packages/api/src/models/userModel.js

This PR adds the sandbox_user column to the users table.

Added sandbox_user column to users table

---

packages/api/src/controllers/sensorController.js

This PR addresses a bug where a new webhook is still registered with Ensemble when there are no ESCI sensors in the upload.
To test:
1. Create a new farm
2. Upload a file with no Ensemble sensors
3. There should be no webhook for Ensemble in the database for that farm

Fixed bug where webhook is registered when there are no ESCI devices in the upload

---

packages/api/src/controllers/organicCertifierSurveyController.js

(cherry picked from commit 7bd523989284b1d8b4b8dfaed7475bc5c11819c2)

Fix date range logic

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/SensorReadings/constants.js
packages/webapp/src/containers/SensorReadings/index.jsx
packages/webapp/src/containers/SensorReadings/saga.js
packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/SensorReadingsLineChart/useSensorReadingsLineChart.js
packages/webapp/src/containers/bulkSensorReadingsSlice.js

To Test,
1. go to http://localhost:3000/sensor/<location_id>/readings. check the nearest station name. dates on the x-axis and try switching from Celsius to Fahrenheit.
For more details, please check: 
https://lite-farm.atlassian.net/browse/LF-2502

LF 2502 - temperature component UI refinements

---

packages/webapp/public/locales/en/translation.json

This PR makes a small fix to the copy for the bulk upload modal as explained [here](https://lite-farm.atlassian.net/browse/LF-2645)

Upadted copy

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/sensorModel.js

To test:
- Upload sensors where the model column in the csv is empty

fix: bulk sensor upload model should be optional

---

packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/containers/Profile/EditUser.jsx

This PR addresses the case sensitive check for pseudo user emails
Resolves https://lite-farm.atlassian.net/browse/LF-2676

Updated email check to be case insensitive

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/locationModel.js
packages/api/src/util/ensemble.js

To test:
- Retire an esci sensor

fix: retire ESCI sensor bug

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Task/AbandonTask/index.jsx

Ticket [LF-2640](https://lite-farm.atlassian.net/browse/LF-2640)
To Test:
1. Create a task and assign it to someone
2. Click "Abandon this task"
3. There should be an info tooltip next to "Was any work completed for this task?"
4. When hovering over, an info text should appear (click when on mobile)

LF-2640 add helptext to abandon task screen informing that hours still count toward payroll

---

packages/api/src/models/sensorReadingModel.js
packages/api/src/routes/sensorRoute.js
packages/webapp/src/containers/SensorReadings/saga.js

To test,
1. Add sensor readings to the sensor_reading table. 
2. check if you can see sensor readings.

Lf 2502/hotfix in temperature component due to database migration changes

---

packages/webapp/pnpm-lock.yaml

fix: updated pnpm-lock.yaml file

---

packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

To test:
1. open the sensor upload modal. 
2. add the following attached files and check the validation is passing successfully.
3. Also, try editing the same files to see the validation error. 
[test-sensors-multilanguage.zip](https://github.com/LiteFarmOrg/LiteFarm/files/9194077/test-sensors-multilanguage.zip)
For more details, please check: 
https://lite-farm.atlassian.net/browse/LF-2659

Addition of English language support in multi language translation of bulk sensor upload error handling

---

packages/api/src/controllers/sensorController.js
packages/webapp/src/components/Sensor/EditSensor.jsx

To test:
Upload a Non Ensemble Scientific Sensor
When updating a sensor - make sure to input a value > 10,000 in the depth field and see if it throws an error
Update the name depth long, lat, etc and make sure it updates correctly

Maximum depth of 10,000 and able to update sensor properties on a non ensemble sensor

---

packages/api/db/migration/20220804164229_estimated_seeds_unit_add_tonnes.js
packages/api/src/models/plantingManagementPlanModel.js

Patch fix issue on production.
Related PR: #2218
Related ticket: https://lite-farm.atlassian.net/browse/LF-2521

PATCH: fix: crop plan 400 error on setting estimated seeding to mt

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/components/LocationPicker/SingleLocationPicker/drawLocations.js
packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
packages/webapp/src/components/Map/MarkerCluster/index.jsx
packages/webapp/src/containers/Map/useMapAssetRenderer.js
packages/webapp/src/containers/Task/TaskLocations/index.jsx

This PR resolves an issue where some points were being clustered when they shouldn't have been clustered.
To test:
1. Add two gates to your map, which are very close but not touching each other when the map is on max zoom
2. When you zoom out, they should be grouped into a marker
3. When you zoom in, they should separate out into two separate icons

Lf 2632 point locations are being inappropriately clustered

---

packages/webapp/src/containers/Map/useMapAssetRenderer.js

This PR fixes a few bugs caused by updating the clustering library for the map
To test:
1. Create an area type location
2. Reload the map
3. It should still render
4. Try filtering out some point locations
5. The marker numbers should update accordingly

Fixed various bugs on the map

---

packages/webapp/src/components/SensorReadingsLineChart/PredictedRect.jsx
packages/webapp/src/components/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/SensorReadings/constants.js
packages/webapp/src/containers/SensorReadings/index.jsx
packages/webapp/src/containers/SensorReadings/saga.js
packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/bulkSensorReadingsSlice.js

To test:
1. go to the http://localhost:3000/sensor/<location_id>/readings.
2. add some sensor reading using the following script.
```
CREATE OR REPLACE FUNCTION generate_sensor_readings(
readingType TEXT,
unit TEXT,
valid BOOLEAN,
startDate DATE,
endDate DATE,
tMax REAL,
tMin REAL 
) RETURNS INTEGER AS
$func$
DECLARE 
currentDate DATE := NOW();
valueData REAL := 0;
r RECORD;
s RECORD;
intervalDuration TEXT := '1 hour';
returnedID TEXT := '';
counter INTEGER := 0;
BEGIN
EXECUTE $$ TRUNCATE TABLE sensor_reading $$;  
FOR s IN SELECT * FROM sensor LOOP 
FOR r IN SELECT * FROM generate_series(
startDate,endDate, 
intervalDuration::INTERVAL) AS s(i) LOOP
valueData := ROUND((RANDOM()*(tMax-tMin)+tMin)::NUMERIC, 1);
EXECUTE $$
INSERT INTO public.sensor_reading(
location_id, 
read_time, …
```

Lf 2502/addition of projected temp rect

---

packages/webapp/src/components/Map/SelectionHandler/index.jsx
packages/webapp/src/util/device.js

Ticket: [LF-2722](https://lite-farm.atlassian.net/browse/LF-2722)
To test:
- Upload sensors with the same latitude and longitude.
- Run ngrok and access the farm map on a mobile device.
- Click the clustered sensors to see the list of sensors in one location.
- Long press a sensor to see the preview

[ngrok required to test] LF-2722: Long press for sensor reading preview on map is not working for clustered sensors

---

.github/workflows/deploy.yml

This PR sets up the basics for running a deployment through Github Actions. It currently will not run automatically, however once we have this script working it will be made to do that. 
Ideally, this can be merged to integration as you can't test these actions until they are on the integration branch.

Added deployment script

---

.github/workflows/deploy.yml

To test:
1. Do to the "Actions" tab in this repo on GitHub
2. Select the "Deploy" workflow from the list of workflows
3. Press the "Run workflow" button, and ensure that you select this branch (`github-actions-deployment`) from the "Use workflow from" dropdown.
4. The workflow should run successfully
@fsayyid can you ping me on slack when you are about to merge this so that I can pause deployments on TeamCity before this goes live?

GitHub actions deployment

---

packages/webapp/src/components/Map/PreviewPopup/utils.js

Read the latest comment on https://lite-farm.atlassian.net/browse/LF-2528
To Test:
1. Have sensors uploaded to the map.
2. Have sensor readings data in the database.
3. Long press a sensor on the map to see the preview.

LF-2528 temperature symbols spacing fix

---

packages/webapp/src/components/Modals/UpdateTaskDateModal/index.jsx

This PR resolves https://lite-farm.atlassian.net/browse/LF-2727
To test:
1. Create a task
2. Try to update the due date of the task to a date in the past
3. This should work

Removed min date from task due date update modal

---

packages/webapp/src/containers/CropCatalogue/index.jsx
packages/webapp/src/containers/Documents/index.jsx
packages/webapp/src/containers/Task/index.jsx
packages/webapp/src/containers/filterSlice.js

To Test,
1. Apply filters to each module (Crop catalogue, Documents, Tasks)
2. click on "Clear all filters" to check all the filters are removed and you can see all the items in the list.
for more details: 
https://lite-farm.atlassian.net/browse/LF-2621
Adding screenshot:

Lf 2621/clear all filters at the root pages of the entity component (Crop catalogue, Documents, Tasks)

---

.github/workflows/deploy.yml

This PR fixes the issues with the beta deployment when more than on runs at the same time.

Added concurrency to deployment workflow

---

packages/webapp/src/containers/SensorReadings/index.jsx
packages/webapp/src/containers/SensorReadings/saga.js

To test:
1. Open http://localhost:3000/sensor/<location_id>/readings page.
2. check the temperature unit to be C unit and the values should be between 10 and 30 degree C.
3. Go to http://localhost:3000/farm. and change the units from "Metric" to "Imperial".
4. Go back to http://localhost:3000/sensor/<location_id>/readings page.
5. check the temperature unit to be F unit and the values should be between 60 and 85 degree F.
Before: 
After:

Temperature unit conversion

---

packages/webapp/src/components/Map/Footer/index.jsx
packages/webapp/src/components/Map/Footer/styles.module.scss
packages/webapp/src/containers/Map/index.jsx
packages/webapp/src/containers/Map/mapFilterSettingSlice.js

To Test,
1. go to the farm maps page.
2. select any filter from the map footer filter option.
3. check if you can see the green dot on top of the filter icon.
Adding screenshot:
https://lite-farm.atlassian.net/browse/LF-2625

Added green dot to show filter activation on farm maps

---

packages/webapp/src/containers/WeatherBoard/utils/index.jsx

Ticket: [LF-2562](https://lite-farm.atlassian.net/browse/LF-2562)
To test: 
- Go to the home page with the weather board
- Switch languages
- Go back to the home page and see that the date is in that language

LF-2562: weather board multi language date support

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Profile/Account/index.jsx
packages/webapp/src/components/Profile/Farm/index.jsx
packages/webapp/src/containers/Profile/Account/index.jsx

Ticket: [LF-2566](https://lite-farm.atlassian.net/browse/LF-2566)
To test:
- Input a first name and last name with a leading and trailing spaces. Save the name and refresh. Leading and trailing spaces should be removed.
- There should be an (optional) label next to the fields "Phone Number" and "User Address"
- Input a phone number greater than 20 characters in length. This should result in an inline error.

LF-2566: various issues on account info page

---

packages/webapp/src/components/Map/SelectionHandler/index.jsx
packages/webapp/src/containers/Map/useSelectionHandler.js

Ticket: [LF-2750](https://lite-farm.atlassian.net/browse/LF-2750)
**TO TEST:** create at least one location from each of the following categories. The location should route to the appropriate tab. 
- **Crop enabled area:** Field, Green House, Garden
- routes to crop tab
- **Non crop enabled area:** Barn, Ceremonial Area, Farm Site Boundary, Surface Water, Natural Area, Residence
- routes to details tab
- **Crop enabled line:** Buffer Zone 
- routes to crop tab
- **Non crop enabled line:** Fence, Water Course 
- routes to details tab
- **Non sensor points (clustered and non-clustered):** Gate, WaterValve 
- routes to details tab
- **Sensor (clustered and non-clustered):** Sensor 
- routes to readings tab

LF-2750: map routing bug

---

packages/api/src/models/sensorModel.js

To test,
1. create 3 - 4 sensors at different locations. 
2. check the station name in the readings tab and verify if they belong to the same location.

Retriveing the correct coordinates of a sensors using sensor query

---

packages/webapp/src/assets/variables.scss
packages/webapp/src/components/GlobalScss/index.jsx
packages/webapp/src/components/Map/Header/styles.module.scss
packages/webapp/src/components/Navigation/NavBar/index.jsx
packages/webapp/src/containers/Map/styles.module.scss

Ticket: [LF-2729](https://lite-farm.atlassian.net/browse/LF-2729)
To test:
- Make a new farm
- Upload sensor with some vertical distance apart
- These coordinates worked for me to get the issue: (49.360945, -123.238492) and (49.250945, -123.238492)
- Make sure the sensors zoom out accordingly

LF-2729 ~ fix: made map top position relative to header heights

---

packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/fr/message.json
packages/webapp/public/locales/fr/translation.json

This PR adds translations for some of the missing french language tags.

Added some FR translations

---

packages/webapp/src/components/Modals/QuickAssignModal/index.jsx
packages/webapp/src/components/Profile/People/index.jsx
packages/webapp/src/components/Table/index.jsx

To Test,
1. go to http://localhost:3000/people
2. check if you can find the names to be sorted alphabetically as shown below:
1. go to the task page.
2. open task modal.
3. check if you can find the names to be sorted alphabetically in the dropdown as shown below:
For more details, Please check:
https://lite-farm.atlassian.net/browse/LF-2650

Sorting of names alphabetically in the people's page and task assignment modal

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/InviteUser/index.jsx
packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/containers/InviteUser/index.jsx
packages/webapp/src/containers/Profile/EditUser.jsx

To test:
1. go to edit the user
2. add a salary amount greater than 999,999,999. check if you can find a validation error in the input form.
3. add a salary amount e.g 123.1212312313. check after clicking on save, the amount that gets saved is 123.12.
Try steps 2 and 3 for the invite user page.
For more details, Please check: 
https://lite-farm.atlassian.net/browse/LF-2568
Adding Screenshot:

Lf 2568 - Fix: enforce character limit on salary

---

packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/SensorReadingsLineChart/styles.module.scss
packages/webapp/src/containers/SensorReadingsLineChart/useSensorReadingsLineChart.js

To Test: 
1. go to the sensor readings page.
2. check if you can find the loader on page mount.
For more details, please check:
https://lite-farm.atlassian.net/browse/LF-2731

Lf 2731  Add loading screen while generating readings visualizations

---

packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx

To test: 
1. go to http://localhost:3000/Finances from the sidebar.
2. select the "Add New Expense" option.
3. this will take you to http://localhost:3000/expense_categories. 
4. check if you can find the expense types list.
5. logout from the app.
6. login again.
7. from the home page, try a direct redirect to http://localhost:3000/expense_categories
check if you can find any errors in the browser logs.
for more details: 
https://lite-farm.atlassian.net/browse/LF-2767

Fixed the null and undefined handling of array.length inside the render function.

---

packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
packages/webapp/src/components/Crop/ManagementDetail/styles.module.scss

Jira ticket: https://lite-farm.atlassian.net/browse/LF-2617?atlOrigin=eyJpIjoiZjcyNTljMDZiODBkNGM0M2EwNmU5YmIyMDZkODA3YTYiLCJwIjoiaiJ9
Copied format of Rating in Task/TaskReadOnly/ to Crop/ManagementDetail/ManagementPlanDetail

LF-2617-stars-for-crop-plan-rating-active-without-editing

---

README.md
packages/webapp/pnpm-lock.yaml

I added workarounds for 2 issues I came up against while trying to start a local development version on my Mac. I did find a closely related ticket that nobody claimed so I though I'd grab it, even though the change to the readme here is slightly larger in scope.
The first is related to the version of node.js the person is starting to start the server with.
The second is related to an issue starting the postgres database.

edit readme to help guide new people to start a local dev version

---

packages/webapp/src/containers/Task/TaskLocations/index.jsx

New pull request. Old PR here: https://github.com/LiteFarmOrg/LiteFarm/pull/2314

Lf 2798 select the task location

---

packages/webapp/src/components/Task/PureIrrigationTask/index.jsx

In beta environment changing to other irrigation type option, provide the value  and go back, the state for the input irrigation type is not displayed.

Fix state management

---

README.md

Updated readme to include contribution section.

Small change for beta testing

---

packages/webapp/src/components/Task/PureIrrigationTask/index.jsx

Fixes elements  CSS styling and remove click event on overlay  https://lite-farm.atlassian.net/browse/LF-2800

fix irrigation task css

---

packages/api/src/controllers/taskController.js

To: 
1. go to the tasks page
2. click on create a task.
3. select fieldwork task
4. select other as the task type 
5. and then create a task.
check if the task creation is working fine.

Hotfix: create field Work task 

---

packages/webapp/src/components/Form/Unit/index.jsx
packages/webapp/src/components/Modals/WaterUsageCalculatorModal/index.jsx
packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/util/convert-units/unit.js

Reset total water usage and irrigated area

Water use calculator

---

packages/api/db/migration/20221205230703_sensor_readings_sql_function.js
packages/api/src/models/sensorReadingModel.js

To Test,
1. Run the migration script
2. get the latest dump of beta
3. go to the farm map and click on the sensor. it will take you to the visualization page
4. check the network tab having  endpoint '/visualization'
5. check if you can find "read_time" and "actual_read_time".
6. compare both the values and verify the values are close. 
Please connect with me on slack

Finding nearest sensor read time

---

packages/api/src/controllers/sensorController.js
packages/api/src/models/sensorReadingModel.js
packages/webapp/src/containers/Map/saga.js

To Test:
1. add sensors to the farm / take a dump of the beta database in a local database.
2. check the store output under 'persistedStateReducer' > 'mapSensorReducer' in beta 
3. now check the store output under 'persistedStateReducer' > 'mapSensorReducer' in the local database which will be less than 10. 
4. you will find the count on the beta will be around 24k which is causing the data overflow.
Before:
After:

Fix: the issue of data overflow in the redux in the farm map page.

---

packages/api/.env.default
packages/webapp/.env.default

This PR is poorly named and is being made late at night after watching a sick toddler for a week. Kindly ensure I haven't given away any sensitive keys!
Changes:
- Commented where certain sensitive keys can be found for both api and webapp 
- Grouped keys from like providers
- Removed a few duplicate keys

Incrementally better guidance on env vars

---

packages/webapp/src/components/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/SensorReadings/index.jsx
packages/webapp/src/containers/SensorReadings/saga.js
packages/webapp/src/containers/SensorReadings/utils.js
packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
packages/webapp/src/containers/bulkSensorReadingsSlice.js

To Test,
1. go to the sensor readings page 
2. check the text of the "last updated" sensor readings

Fixed the issue of last updated text in the visualization 

---

packages/api/db/migration/20230106112659_add_extra_columns_irrigation_table.js
packages/api/src/controllers/taskController.js
packages/api/src/models/irrigationTaskModel.js
packages/api/src/models/irrigationTypesModel.js
packages/api/src/models/locationDefaultsModel.js
packages/webapp/src/components/Modals/WaterUsageCalculatorModal/index.jsx
packages/webapp/src/components/Task/TaskComplete/index.jsx
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/containers/slice/taskSlice/irrigationTaskSlice.js
packages/webapp/src/containers/taskSlice.js

Add default columns to store boolean values and include them in the post request.
https://lite-farm.atlassian.net/browse/LF-2804?focusedCommentId=14497

Lf 2804 manual irrigation task

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/containers/Insights/index.jsx
test.md

[Jira ticket 2851](https://lite-farm.atlassian.net/browse/LF-2851)
I commented out the code that fetches and displays biodiversity data in the file, in case we need to use it in the future.
Sorry about the 2 useless commits, I was having git issues and those were for testing my GitHub access.

LF-2851 Biodiversity text now displays Click to calculate

---

packages/webapp/src/components/Modals/QuickAssignModal/index.jsx
packages/webapp/src/components/Modals/QuickAssignModal/styles.module.scss
packages/webapp/src/components/Task/AssignTask/HourlyWageInputs.jsx
packages/webapp/src/components/Task/AssignTask/constants.js
packages/webapp/src/components/Task/AssignTask/index.jsx
packages/webapp/src/components/Task/AssignTask/styles.module.scss
packages/webapp/src/components/Task/AssignTask/useTaskAssignForm.jsx
packages/webapp/src/components/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/Task/TaskCard/index.jsx
packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/Task/taskCardContentSelector.js

This is part of [LF2643](https://lite-farm.atlassian.net/browse/LF-2643)
(parent PR: https://github.com/LiteFarmOrg/LiteFarm/pull/2426)
- Create `AssignTask` component and `useTaskAssignForm` hook and use them in `QuickAssignModdal`
(they are going to be used in another component later on)

LF-2643(2): Create assign task component

---

packages/api/src/jobs/index.js
packages/api/src/jobs/loadEnv.js

This PR fixes the problem where organic certification data can't be exported and sent to users. 
Many thanks to @JimmyRowland for identifying the problem and provided a solution! 
The problem:
- Somehow the old way of loading environment variables isn't working anymore
The solution:
- Make sure the environment variables are loaded before anything else is executed by creating a loadEnv.js file and import it at the beginning of jobs/index.js. [StackOverflow Credit](https://stackoverflow.com/a/64622082)
Note: It doesn't seem like node version has anything to do with this, this solution works with node v16.15.0
Jira link: [LF-2759](https://lite-farm.atlassian.net/browse/LF-2759?atlOrigin=eyJpIjoiYWYwNWZlMTYzMjI1NDRiYmIxYzMzZTUwOTExMGZiM2UiLCJwIjoiaiJ9)
Please delete options that are not …

LF-2759 changing how env vars are loaded in export jobs

---

.github/workflows/beta-export-deploy.yml

This PR integrates the auto deployment to the beta export server using github actions. It would be nice to containerize the export server in the future to utilize the microservice architecture. The deploy script found in the .git/beta-export-deploy.yml file does the following:
- cd to the folder of this project
- pull from the integration branch
- make sure the node version is 16.15.0 by using nvm
- list the current export server status
- restart the export server
- list the current export server status again
An example of this process can be viewed [here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/4118591051/jobs/7115935051) 
Jira link: [LF-2758](https://lite-farm.atlassian.net/browse/LF-2758?atlOrigin=eyJpIjoiZTFiNjg3NDUyNDAxNDExYmI1YmQzMDQ1MWI2MWUwNTEiLCJwIjoia …

Lf 2758 export server cicd

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/AddNewCrop/index.jsx

This PR addresses the following issues brought up in verification:
> 1. I’m seeing that the nominate Checkbox is not disabled until “New crop name”, “Genus”, “Species”, and “Crop group” are populated
> 2. Not sure if this is related to this ticket but i’m seeing a white screen and errors in the console when i attempt to access the crop_catalogue as a farm worker
> 3. The default value of the Genus and species inputs is in english for non english language users(Spanish, Portuguese and French)
> 4. The character limit on Genus and Specie is not enforced at the API
> 5. Should changes to Genus (to upper case) and species (to Lower case) happen inline or on submit?
1. No longer a requirement to disable the ability to nominate a crop
2. Not related to this ticket
3. Corrected …

Lf 2072 verification update

---

packages/webapp/src/components/Form/InputAutoSize/index.jsx
packages/webapp/src/stories/Form/InputAutoSize/InputAutoSize.stories.jsx

Fixes deprecated props for rowsMin and rowsMax
Jira link: [LF-2845](https://lite-farm.atlassian.net/browse/LF-2845?atlOrigin=eyJpIjoiY2I2MTMyODdhMjc3NDIxMGJkYzUzNzQzNDNjNDZjMzQiLCJwIjoiaiJ9)
**Checklist:**
[LF-2845]: https://lite-farm.atlassian.net/browse/LF-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

find and replace rowsMin and rowsMax

---

packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
packages/webapp/src/containers/Map/index.jsx

Fixes console error and upgrade two components to React 18.
Jira link:
**Checklist:**

upgrade ReactDOM.render to createRoot

---

packages/webapp/src/components/Task/PureIrrigationTask/index.jsx

This PR is to add a missing dependency array to useEffect.

Add dependency to useEffect

---

packages/webapp/src/components/Form/Unit/index.jsx
packages/webapp/src/components/Form/Unit/useReactSelectStyles.jsx
packages/webapp/src/components/Form/Unit/useUnit.jsx

- create a file for `useReactSelectStyles` hook
- add more logic to `useUnit` hook
(I am working on refactoring the Unit component, and I plan to do it in 3+ PRs. The PRs I am creating are going to be merged to the "LF-2995+3002/Unit_displays" branch, and when everything is ready, the branch is going to be merged to the integration branch.)
Jira link: https://lite-farm.atlassian.net/browse/LF-3004
**Checklist:**

LF-3004: Update Unit component

---

packages/webapp/package.json
packages/webapp/prod.Dockerfile

Thanks to @javiscript13 for testing this! Essentially he tested his docker instance and saw the memory leak on integration, with the changes build was successful. Logs are avail in DMs in chat if requested.
Essentially moving previous solutions in .npmrc and package.json to the Dockerfile. 
Please see https://github.com/LiteFarmOrg/LiteFarm/pull/2495 by @kathyavini for more info
Jira link:
**Checklist:**

move memory increase to dockerfile

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml

- Add @storybook/test-runner
- Add `test-storybook` to package.json scripts
This will allow us to run storybook tests through terminal. (you still need to run `pnpm storybook`)
https://storybook.js.org/docs/react/writing-tests/test-runner

Add @storybook/test-runner and update package.json scripts

---

packages/api/src/jobs/certification/survey_record.js

Certification document export will fail (the whole export process will crash and no documents will be sent) if an exported certification survey has a structure with nested null values.
Nested null values means that a skipped question/group also contains one or more child questions/groups, e.g. when a whole section of a survey is not shown due to [Relevance Expressions](https://our-sci.gitlab.io/software/surveystack_tutorials/relevance_expressions/) (conditional scripts) set up in the survey. Note that skipped questions in themselves are not a problem if they don't contain child questions/sections.
This PR adds a check for undefined parent groups so that this kind of nested null value does not lead to document export crashing.
Jira Link: …

LF-3008 Augment additional survey questions xlsx to handle nested null responses without failing

---

packages/webapp/src/components/Forms/Sale/index.jsx
packages/webapp/src/components/Forms/Sale/styles.module.scss
packages/webapp/src/containers/Finances/AddSale/index.jsx
packages/webapp/src/containers/Finances/EditSale/index.jsx

Adds some style in the form of Harvest Task Form. 
Jira link:
**Checklist:**

Refactor crop variety style to adjust for unit updates

---

packages/webapp/src/components/Crop/BedPlan/PurePlanGuidanceForm.jsx
packages/webapp/src/stories/Pages/ManagementPlan/PlanGuidance.stories.jsx
packages/webapp/src/stories/Pages/Tasks/PlantingTaskReadOnly.stories.jsx

Integration tests for `/packages/webapp/src/components/Crop/BedPlan/PurePlanGuidanceForm.jsx`.
- Read-only view
- `pnpm test-storybook /src/stories/Pages/Tasks/PlantingTaskReadOnly.stories.jsx`
- [storybook UI](http://localhost:6006/?path=/docs/form-crop-tasks-plantingtaskreadonly--docs)
- Creation view
- `pnpm test-storybook /src/stories/Pages/ManagementPlan/PlanGuidance.stories.jsx `
- [storybook UI](http://localhost:6006/?path=/docs/form-managementplan-planguidance--docs)
Jira link: https://lite-farm.atlassian.net/browse/LF-3031
**Checklist:**

LF-3031: Unit displays tests - PurePlanGuidanceForm (2)

---

packages/webapp/src/containers/Documents/saga.js

This adds a path redirect to `/documents` on successful document upload.
Jira link: https://lite-farm.atlassian.net/browse/LF-3083
A NOTE ON TESTING: this flow involves document upload so you will need a local solution for document upload configured (e.g. MinIO, see the LiteFarm readme) if you want to run through the whole flow on localhost.
**Checklist:**

LF-3083 The user is not redirected to any page once he uploads a new document and clicks on "Save"

---

packages/webapp/src/containers/CropCatalogue/useStringFilteredCrops.ts

[Deployment failed](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/4660306485/jobs/8248215519) for https://github.com/LiteFarmOrg/LiteFarm/pull/2534 due to type issues. This PR is to resolve those issues.
- add a missing field to `CropVariety`.
- update `check` function to take string, null or undefined instead of an array.
- update filter's callback not to cause type error.
**Checklist:**

Resolve type issues in useStringFilteredCrops

---

packages/webapp/public/locales/fr/translation.json

Fixed SENSOR_READING_TYPES translation

---

packages/webapp/src/components/Form/Unit/useUnit.jsx

When modifying values in a `Unit` component on a field where the unit was initially disabled, the value was not being properly updated in the form. This led to Pest Control tasks not having the "Quantity" field updated properly when completing the task.
Jira link: https://lite-farm.atlassian.net/browse/LF-3125
**Checklist:**

Fixed Pest Control task to update values correctly

---

packages/webapp/src/components/Filter/Pill/index.jsx
packages/webapp/src/components/Form/Radio/index.jsx

We wanted to use the `<Pill />` in Radio, but it was not possible because Radio (`<label />`) cannot have Pill that has  `<div />` inside it. So, performed the following changes to accept `<Pill />` component inside `<Radio />` component. 
- updated the Radio component(change `<p />` to `<span />` )
- updated the Pill component (change `<div />` to `<span />`) 
Jira link: https://lite-farm.atlassian.net/browse/LF-2996
- got to `/tasks`
- The `<Pill />` component having logged in person name, should be in `<span />`. Use Inspect element to verify that.
- Click on any task and then click on "Abandon this task" link.
- The label for date options for "When was the task abandoned?" should be in `<span />`
**Checklist:**

Lf 2996 update radio component

---

packages/webapp/public/locales/fr/translation.json

Improved the French translations. They should be a lot more accurate even though some translations might still be a bit strange (I also didn't edit agricultural vocabulary I didn't understand).
It should take care of the following Jira Tickets: 
- https://lite-farm.atlassian.net/browse/LF-3164
- https://lite-farm.atlassian.net/browse/LF-3147
- https://lite-farm.atlassian.net/browse/LF-3146
- https://lite-farm.atlassian.net/browse/LF-3149 (maybe, but I am not sure because the text is split on different substrings)
**Checklist:**

Improved French translation

---

packages/api/src/controllers/taskController.js
packages/webapp/src/components/Task/FieldWorkTask/index.jsx
packages/webapp/src/components/Task/TaskComplete/index.jsx

Fixed an issue where the complete endpoint for "field_work" tasks was attempting to create a new type of field work when changing the field work type upon completing the task.
When you selected a value on the "Type Of Field Work" dropdown it appended an object property "field_work_task_type" to the payload, which is used by the create task endpoint if you are attempting to create a new (custom) type of field work. 
Since the user is not attempting to create a new type of field work the appened data is incomplete as one would expect.
The frontend however does have to inform somehow that the user is attempting to **change** the field work type. I achieved this by sending only the work_type_id. 
I modified the backend to ignore the current functionality if the sent attribute …

LF-3113  Fixing issues with the field work complete endpoint 

---

packages/api/src/models/emailTokenModel.js
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

Farm invitations are re-sent every time someone tries to log into an invited (but not yet created) account without accepting the invitation email. Currently, these emails cap out at three, at which point no more emails are sent. If all three emails had been sent sometime in the past, this can cause issues like the one documented in this Jira ticket because the error message will reference an invite email but no new emails will have been sent.
This PR adds a 24-hour reset to the sent email count, so that after 24 hours three more farm invitations can be sent. This mirrors the behaviour of the password reset email, which also sends up to three times and resets after 24 hours.
To implement this functionality the `emailToken` model also had to be fixed so that it correctly …

LF-3122 Cannot login with institutional domain hosted on Google via SSO and don't receive email

---

packages/webapp/src/containers/Map/useMapAssetRenderer.js

From what I can tell this affects clustered sensors specifically over water/ocean. Possibly other areas with low quality imagery. The max zoom level google provides in maps.getZoom() does not exceed our maxZoomRef value.
This also reverts a change that caused another error ([LF-2632](https://lite-farm.atlassian.net/browse/LF-2632)) -- but I can no longer reproduce that error. EDIT: actually I can kind of reproduce it on the map zoom out only one level and then click the cluster – it will both open the cluster menu and separate sensors but I think thats a good compromise.
The top of the file also has a warning, which this change would be respecting by reverting the change:
```
/**
*
* Do not modify, copy or reuse
*/
```
Jira link: …

Revert PR-2251

---

packages/webapp/src/components/Modals/WaterUsageCalculatorModal/index.jsx
packages/webapp/src/stories/Form/Unit/Unit.stories.jsx
packages/webapp/src/util/convert-units/unit.js

Save "Estimated duration" for an irrigation task in "minutes" not "days" in the database.
- update `time` databaseUnit to `min`
- update `crop_age` `databaseUnit` to `d`
(changing this to `min` will require some adjustments on calculations for seeding date and initial harvest. I think we should keep it the same as before)
- remove unnecessary calculation (database unit (min) -> min) for TotalWaterUsage
- update storybook tests for Estimated duration hidden value
Jira link: https://lite-farm.atlassian.net/browse/LF-3117
**Checklist:**

LF-3117: Mismatch between entered and db duration unit on irrigate task

---

packages/api/src/controllers/taskController.js
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Notifications/index.jsx

This adds a notification to task deletion.
I just copied task abandonment. Thanks @Cali0707 for writing such an organized and extensible function. 
**To test this ticket:**
- Delete a task that has been assigned to you or someone else
- Verify you have not received a notification if you are not the assignee
- If you are the assignee, verify that you have received a notification with the text: "A {{taskType}} task assigned to you has been deleted by {{abandoner}}"
**Notes:**
- The "Take me there" button has also been removed from the notification details view for this task type
- If you go to the notification details page and use the history timeline to find a "Take me there" button and click it, it will currently crash the app. That task details view will be replaced by a …

LF-3022 Notify a user when a task assigned to them has been deleted

---

packages/webapp/public/locales/es/translation.json

MISSING tags changed.
Jira link:
**Checklist:**

SP T APR14

---

packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx

Correcting props on CropHeader on ManagementPlanTasks
Jira link:
**Checklist:**

Correcting props on CropHeader on ManagementPlanTasks

---

packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/src/components/Pill/index.jsx

Reverts LiteFarmOrg/LiteFarm#2593
Included a few changes that were unintended

Revert "SP translations - Release APR23"

---

packages/webapp/public/locales/es/translation.json

Update Spanish Translations 
Jira link:
**Checklist:**

Spanish translation update Release APR23

---

packages/webapp/src/containers/Consent/locales/fr/Owner.Consent.md
packages/webapp/src/containers/Consent/locales/fr/Worker.Consent.md

Improved the French translation of the data policy
Jira link:
- [x ] Translation
**Checklist:**

Improved the French translation of the data policy

---

packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
packages/webapp/src/containers/Task/saga.js

- Irrigation task is not formatted correctly when data is modified before completion. (the object is now the argument of `getObjectInnerValues`, so it seems to be a lot of change, but it is not)
- format `irrigation_type_name` correctly
- other fields related to units
call `getObjectInnerValues` that formats `{estimated_water_usage_unit: { label: 'm2', value: 'm2' }, ...}` to `{estimated_water_usage_unit: 'm2', ...}`. Fields for units are fixed by this.
- delete `location_size` before sending an API request.
- send missing `locations` which was causing a crash in the depth water calculator
**Checklist:**

Resolve irrigation task completion 1

---

packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
packages/webapp/src/components/Crop/ManagementDetail/EditManagementPlanDetail.jsx
packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx

Removing the remaining CropHeader usages that destructured variety
**Checklist:**

LF-3199 remaining crop usages

---

packages/webapp/public/locales/pt/translation.json

Jira link:
- [x ] missing translations
**Checklist:**

PT corrections

---

packages/webapp/src/components/Profile/ProfileLayout/index.jsx

preventDefault not to submit Profile form on hitting enter.
Jira link: https://lite-farm.atlassian.net/browse/LF-3129
**Checklist:**

LF-3129: Pressing enter in while searching for People at my farm takes me to Invite User flow

---

packages/api/src/templates/locales/es.json
packages/api/src/templates/locales/pt.json
packages/webapp/public/locales/es/message.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/message.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json

**Corrections to PT, SP and FR.**
Jira link:
- [x ] Translation fixes
**Checklist:**

Feature/pt/sp additions 4.15.2023

---

packages/webapp/src/containers/Consent/index.jsx

Consent version 5 code change.
Jira link:
**Checklist:**

Code change for update to version 5 of consent

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/containers/Consent/index.jsx
packages/webapp/src/containers/Consent/locales/es/Worker.Consent.md
packages/webapp/src/util/constants.js

- Bump version numbers
- Fix version number in Worker.Consent for Spanish
Jira link: https://lite-farm.atlassian.net/browse/LF-3209

LF-3209: Bump version numbers

---

packages/api/src/controllers/userFarmController.js

sending welcome email only if second and third steps are not completed.
Jira link:
**Checklist:**

sending welcome email only if second and third steps are not completed.

---

packages/api/src/controllers/cropVarietyController.js

automated test fix
Jira link:
**Checklist:**

check query params

---

packages/api/package.json
packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/util/constants.js

Ensure changes made directly to main on August 5th won't conflict with what's on integration; and other conflicts 
Jira link: https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/10?modal=detail&selectedIssue=LF-3208
Smoke test and testing the two August 5  2022 tickets  
**Checklist:**

LF-3208  resolve conflicts with main

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Card/NewReleaseCard/NewReleaseCard.jsx

Updates welcome message and link on main page and password page.
Jira link: https://lite-farm.atlassian.net/browse/LF-3202
**Checklist:**

LF-3202 Update username and password pages to include new release notes

---

packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

Language tags for lf 3023

---

packages/webapp/src/components/AddCropVariety/index.jsx

My changes in LF-3209 broke crop variety creation because I didn't pass the data object from React Hook Form into the onSubmit functions.
This PR fixes that. 
Jira link: https://lite-farm.atlassian.net/browse/LF-3214
**Checklist:**

LF-3214 FIx bug in LF-3209 empty data object 

---

packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

SP, PT, and FR changes

---

packages/webapp/src/containers/Task/TaskReadOnly/useReadonlyTask.js

A hook was modified in a way that the component didn't render the same way each time, which is a hook rule and it was being broken.
It caused issues on delete tasks.
Jira link:
**Checklist:**

fix the order of hooks issue

---

README.md

@kcussen requested more clear instructions about .env files. This PR clarifies that most are available with instructions in the .env.default files.
In the future we should consider having shareable file with verified contributors/team members.
**Checklist:**

Update to readme about .env files

---

packages/webapp/src/components/LocationCreationModal/index.jsx
packages/webapp/src/components/LocationCreationModal/styles.module.scss

- Update the style of "Go back" button to "secondary" color  in `LocationCreationModal`.
- Align the two buttons to the left.
Jira link: https://lite-farm.atlassian.net/browse/LF-3130
**Checklist:**

LF-3130: Two main buttons on pop up

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Documents/Add/index.jsx

This is pretty much the same as https://github.com/LiteFarmOrg/LiteFarm/pull/2572.
Adds the cancel button and functionality to the add documents workflow
Jira link: https://lite-farm.atlassian.net/browse/LF-3148
**Checklist:**

LF-3148 - add cancel pop-up to add document header

---

packages/webapp/vite.config.ts

Well this is what happens when I try to take a quick ticket... This edits the vite configuration to allow for a proper compile of emotion css through @emotion/react. If you don't know how react-select works this is how I landed on this solution:
- I tried to find the css that was out of place in ReactSelect under multiValueRemove -- everything looked correct and I tried fidgeting around with it with no success
- I found that react-selects native MultiValueRemove was being overridden to add in a different cross (x) than the provided one and so maybe the css wasn't being passed down
- css was being passed down but not to styles and class element attributes instead to a css element attribute
- I tried passing the css attribute to element style attribute -- it mostly worked …

LF-3186 filter pill is wonky

---

packages/webapp/src/components/Task/AddProduct/index.jsx

Add "(optional)" tag to the supplier field in the Clean, Pest Control and Soil Amendment task creation flow when the farm is not interested in certification.
Jira link: https://lite-farm.atlassian.net/browse/LF-3108
**Checklist:**

LF-3108: There is a need to add "Optional" tag to the "Supplier" field during the soil amendment task creation

---

packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
packages/webapp/src/containers/Finances/NewExpense/AddExpense/styles.module.scss

Hi @bailey-mc Thank you for your work on LF-2975 sorry it is a weird release time and are pushing it through. Normally there would be more time for you to work on it at your own schedule. Looks like we were hoping to get out another release patch today. 
Basically the InputAutoSize works with react-hook-forms so it wasn't working with the model to register values. This component needs to be completely refactored as it uses the old react-redux-forms. Pretty much everything else I kept the same I think.
Jira link:
**Checklist:**

LF-2975 Revert to react-redux-form style and adopt css suggestion

---

packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/index.jsx
packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/styles.module.scss
packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
packages/webapp/src/containers/Finances/NewExpense/AddExpense/styles.module.scss

This addresses the points made by @kathyavini  about the following but forgotton on the last merge request:
1. Doesn't this need to be on edit expense as well?
- yes good point added
2. Expense detail view is now breaking for me on long item names
- nice did a quick fix here but I am no css expert -- obviously this view needs a reimagine overall
3. Doesn't the input need to vertically resize to show all the lines of the item name? I thought that was actually the main point of what David was saying.
- I did look at that and I think thats why Bailey used the InputAutoSize -- this component wasn't built to accomodate that auto size behaviour. 
- What I did last time: let the textarea elements natural behaviour with the bottom right stretchy corner be the ability to size -- …

updated edit expense and fixed detail view increased text area size

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/util/constants.js

Update version to 3.3.1

---

packages/webapp/src/components/MapDrawer/index.jsx

GOOD TO MERGE NOW! 😄 
This PR restores sensors to the Farm Map drawer.
Jira link: https://lite-farm.atlassian.net/browse/LF-3236
**Checklist:**

LF-3236 Uncomment "Add sensor" to Add farm map drawer

---

packages/api/src/controllers/sensorController.js
packages/webapp/src/containers/Map/saga.js
packages/webapp/src/util/sensor.js

Note: This is a change that is only going to be visible until a fix for [LF-3240](https://lite-farm.atlassian.net/browse/LF-3240) is implemented.
If sensors fail to save to the database (something that was happening regularly with bulk sensor upload due to concurrent knex transactions, see ticket LF-3240 above), the same error message is used as when an ensemble sensor fails to be registered. This error message prints the name of the ensemble external ID for the sensor, and hardcodes the problematic column as "External_ID", leading to cryptic and confusing error messages for sensors without external IDs.
This PR fixes that error message to show the sensor name when External ID is not available and removes the "External_ID" column value in the case of database save failures …

LF-3193 Sensors fail to upload for cryptic reasons

---

packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx

The reported bug is a back loop on editing crop plans.  
For fixing it, I just replaced the history.back with the goBack function that was passed as props (that wasn't usted)
Jira link: https://lite-farm.atlassian.net/browse/LF-3245
**Checklist:**

LF-3245-Back-arrow-loop

---

packages/api/src/middleware/validation/deleteLocation.js
packages/api/src/routes/sensorRoute.js
packages/webapp/src/components/LocationDetailLayout/PointDetails/Sensor/index.jsx
packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/index.jsx
packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/saga.js

This PR adds a check before retiring a sensor if there is a related task for the sensor.
- update `validateLocationDependency` middleware to be able to handle not only `req.param.location_id` but also `req.body.location_id`
- add `validateLocationDependency` middleware (and more) to sensor's `/unclaim` API
- update `retireSensorSaga` to run a function that opens the error modal when the API fails due to incomplete tasks
- add `UnableToRetireModal` and make related changes
- remove unused code
If you are interested how other location components work...
Here is one of the files you can refer how it's done in other components:
https://github.com/LiteFarmOrg/LiteFarm/blob/046a2d3233324fb8544a8676bec604ba5d96628f/packages/webapp/src/containers/LocationDetails/AreaDetails/BarnDet …

LF-3279: Sensor are retire-able with active tasks

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/util/constants.js

Update version to 3.3.2
Jira link: https://lite-farm.atlassian.net/browse/LF-3314

Update version to 3.3.2

---

packages/webapp/public/locales/es/translation.json

Just some MISSING tags on spanish.
**Checklist:**

Spanish missing tags

---

packages/webapp/cypress.env.json
packages/webapp/cypress/support/commands.js
packages/webapp/src/components/CardWithStatus/TaskCard/TaskCard.jsx
packages/webapp/src/components/Form/Checkbox/index.jsx

This PR fixes flakiness associated with clicking on the checkbox on the consent page
Jira link:
https://lite-farm.atlassian.net/browse/LF-3311
**Checklist:**

applied discussed fix

---

.github/workflows/beta-export-deploy.yml
.github/workflows/deploy.yml

Previously, both the deployment of the beta export server and the deployment of the beta application itself were triggered upon merge to integration. This PR updates the export server deployment so it is instead triggered by the successful completion of the application's deployment.
Additionally, two related changes were made to address silent failures of the application's deployment as we have seen several times over the last few months (e.g. when the `git pull` within the deployment script has failed with error, but the GitHub Actions workflow still shows completed)
1. (Included in this PR) add `script_stop: true` to the [`appleboy/ssh-action`](https://github.com/marketplace/actions/ssh-remote-commands) GitHub Actions. This was inspired by its addition in …

LF-3067 Appropriately link deployment of beta export server to successful completion of beta server deployment

---

packages/webapp/lint-staged.config.js
packages/webapp/package.json

Run `tsc` before making a commit (precommit) to validate TypeScript files in the webapp folder.
- create `lint-staged.config.js` file to use a function in `lint-staged`. (https://www.npmjs.com/package/lint-staged#example-run-tsc-on-changes-to-typescript-files-but-do-not-pass-any-filename-arguments)
- run `tsc --noEmit` against TypeScript files
Note: Since our `api` folder is not ready for TypeScript, this PR is just for `webapp`.
Jira link: https://lite-farm.atlassian.net/browse/LF-3272
Reference: https://github.com/microsoft/TypeScript/issues/27379#issuecomment-883154194
Add problematic TypeScript code like below to a TypeScript file, and try to make a commit.
```
const test = (a) => {
console.log('test');
};
``` …

LF-3272: Catch type errors before being able to merge PR

---

.github/workflows/beta-export-deploy.yml
.github/workflows/deploy.yml
beta-export-deploy.sh

After the merge of 
- https://github.com/LiteFarmOrg/LiteFarm/pull/2483
the beta export server deployment script is now in our repository (rather than in a GitHub secret). This PR moves that same script into its own `.sh` file for ease of lining and editing, as was done in PR https://github.com/LiteFarmOrg/LiteFarm/pull/2713 for beta application deployment.
This PR uses the same workaround regarding accessing the repository script from `appleboy/ssh-action` as was used here:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2719
however, a newer (and more popular) GitHub Action repository has been adopted for both workflows to avoid the [deprecation warnings](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/5181284332) that were seen on deploy of that PR.
The export …

LF-3346 Move beta export server deploy script into repository .sh file

---

packages/api/src/middleware/acl/hasFarmAccess.js
packages/api/tests/task.test.js

The API request body for POST `task/harvest_tasks` contains `location_id`  (in `locations`) and `planting_management_plan_id` (in `managementPlans`, `planting_management_plan` has `location_id`), but there was no check if `location_id` belongs to the farm sent in the request header. It is because the function `fromTaskManagementPlanAndLocation` that verifies `locaiton_id`:
- is not compatible with the harvest tasks API's request body which is an array.
- does not check planting_management_plan's `location_id`.
This PR updates `fromTaskManagementPlanAndLocation` to be able to validate both single tasks and arrays of tasks as well as validate planting_management_plan's `location_id`.
Jira link: https://lite-farm.atlassian.net/browse/LF-1970
**How Has This …

LF-1970: Fix has farm access middleware on post harvest tasks endpoint

---

packages/api/src/server.js
packages/webapp/nginx.conf

Disables sending information of nginx version and application server used.
Jira link:
* Checking the response headers in the network tab, e.g. https://api.beta.litefarm.org/
* Before - `nginx/1.15.12` After: `nginx`
* Before - `X-Powered-By: Express`, After: Not present
**Checklist:**

LF-3337 disable tokens

---

.husky/pre-commit
README.md
lint-staged.config.js
package-lock.json
package.json

Our root directory was not currently linted within the precommit hook, which is only set up to run `lint-staged` on the packages managed by Lerna.
This means there was no consistent linting rule applied to the markdown files (such as `README.md`) in the root directory -- besides the linting that would be automatically applied by developers who have Prettier set as the editor default formatter in VS Code.
This PR:
- Adds lint-staged and Prettier to the package root so files there can be linted as well
- Adds lint-staged to the husky pre-commit hook
- Lints `README.md`
Jira link: https://lite-farm.atlassian.net/browse/LF-3391
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

LF-3391 Add linting to markdown files in root directory

---

docker-compose.yml

The development environment Dockerized export server relies on a Docker Hub-hosted image that currently uses Node 16.15.0. When the application and its packages are updated to Node 18.16.1-compatible versions, this image should be changed as well. The new image is tagged as version **0.0.2**
(The packages, which the export server also relies on, are mutually incompatible between Node 16 and Node 18)
The Dockerfile has been updated in our [LiteFarmOrg dockerfiles repository](https://github.com/LiteFarmOrg/dockerfiles/tree/main/node-awscli), and the newly tagged image has been pushed to the [LiteFarm Docker Hub](https://hub.docker.com/repository/docker/litefarm/node-awscli/general).
Jira link: https://lite-farm.atlassian.net/browse/LF-3405
**How Has This …

LF-3405 Update development export server image Node version

---

packages/webapp/src/components/Form/Input/index.jsx
packages/webapp/src/components/Form/Input/input.module.scss
packages/webapp/src/stories/Form/Input/Input.stories.jsx

This PR adds the option of a stepper control (up and down buttons) to the number `<Input />` component. This will be used within the Repeat Crop Plan modal and potentially elsewhere in the app.
The stepper control has been given a pleasing hover effect 😁 
Jira link: https://lite-farm.atlassian.net/browse/LF-3403
This was created and tested in Storybook on the Node 18 branch with -- my understanding is that this is important! -- a pnpm lockfile generated with pnpm v.8.5.3.
Because of complications with pnpm + React Icons, Storybook may or may not be working …

LF-3403 Number Input component with stepper

---

packages/webapp/src/components/InviteUser/index.jsx

The error occurs when inputting email before selecting a role. This PR adds null check for the role.
Jira link: https://lite-farm.atlassian.net/browse/LF-3408
**Checklist:**

LF-3408: TypeError: Cannot read properties of undefined (reading 'value')

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Form/DaysOfWeekSelect/index.jsx
packages/webapp/src/components/Form/DaysOfWeekSelect/styles.module.scss
packages/webapp/src/stories/Form/DaysOfWeekSelect/DaysOfWeekSelect.stories.jsx

This PR creates a new component for use with the Repeat Crop Plan view (and other views in the future), a selector for picking days of the week.
Notes:
- The default behaviour of the component is to allow only one selection at a time, but this is configurable with the property `maxSelect`
- It is a controlled component of multiple checkboxes, more or less following the checkboxes example from the [React Hook Form Documentation](https://react-hook-form.com/docs/usecontroller)
-  It can be situated within the React Hook Form using the `<Controller />` component following the pattern used for `<ReactSelect />`
```jsx
<Controller
control={control}
name={'days_of_week'}
rules={{ required: true }}
render={({ field: { onChange, value } }) => (
<DaysOfWeekSelect …
```

LF-3421 Days of Week Select component

---

packages/webapp/src/components/Form/Input/index.jsx
packages/webapp/src/components/Form/Input/input.module.scss
packages/webapp/src/stories/Form/Input/Input.stories.jsx

This is Part II of #2743 (Number Input Component with Stepper)
The original new component lacked the correct handling of min and max (which I misunderstood as referring to validation; they are actually the hard reset of the number value onBlur in a normal number `<Input />`). This has now been added.
After @SayakaOno kindly helped me understand better the rationale for interaction testing this component, I have added play tests for the Number Input with Stepper with and without min/max.
In support for play testing, I had also unintentionally broken the interaction on the Input with password!! (See LF-3417) I added an interaction test for that as well, but please note the bug was caused by the icon being covered by another component (in the CSS layer sense); this is not …

LF-3403a Fixes and tests for number input stepper

---

ci/build-prod-images.sh

This PR fixes build issues with the front end image on apple silicon using the build script in the ci directory.
Jira link:
**Checklist:**

LF-3435 removed platform flag to fix issue on apple silicon

---

packages/api/src/models/managementPlanGroupModel.js

Adds `ManagementPlanGroup` model
Jira link: https://lite-farm.atlassian.net/browse/LF-3448
**Checklist:**

LF-3448 Adds `ManagementPlanGroup` model

---

packages/webapp/src/components/CardWithStatus/ManagementPlanCard/ManagementPlanCard.jsx
packages/webapp/src/components/CardWithStatus/ManagementPlanCard/styles.module.scss
packages/webapp/src/components/Crop/Management.jsx
packages/webapp/src/components/Modals/CropModals/CropPlansModal.jsx
packages/webapp/src/stories/Modal/CropPlansModal.stories.jsx
packages/webapp/src/stories/Pages/ManagementPlan/CropManagement.stories.jsx

- complete `repeatPlanInfoOnClick` function to open the modal
- add the modal
- implement dismiss function
- create a story (http://localhost:6006/?path=/story/form-crop-management--management-with-repeat-plan-cards)
Jira link: https://lite-farm.atlassian.net/browse/LF-3371
**Checklist:**

LF-3371 (2) Repeat crop plan | Show repeated plan disambiguation modal

---

packages/webapp/src/components/Crop/ManagementPlanName/index.jsx
packages/webapp/src/components/Task/AssignTask/useTaskAssignForm.jsx

Missed the functionality when there is only 1 user, then pre-populate that user in input when assigning all tasks
Jira link: https://lite-farm.atlassian.net/browse/LF-3308
**Checklist:**

LF-3308 Assign all tasks to one assignee pre-populate only user 

---

packages/api/src/controllers/managementPlanController.js
packages/api/tests/managementPlan.test.js
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
packages/webapp/src/containers/managementPlanSlice.js

Refert  to LF-3001 prev PR https://github.com/LiteFarmOrg/LiteFarm/pull/2783
**Checklist:**

[LF-3001] Adding harvest to date to date field for management plans

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/util/constants.js

Update application versions - For release
Jira link: https://lite-farm.atlassian.net/browse/LF-3512
**Checklist:**

LF-3512 Update application versions

---

packages/webapp/src/containers/Documents/DocumentTile/index.jsx

Correcting tooltip position and fixing bug on closing
Jira link:
**Checklist:**

Correcting tooltip position and fixing bug on closing

---

packages/webapp/src/components/RepeatCropPlan/index.jsx

Jira link: https://lite-farm.atlassian.net/browse/LF-3534
**Checklist:**

LF-3534 On repeat crop plan, symbols not displaying correctly

---

packages/webapp/public/locales/fr/message.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json

PT translations
Jira link:
**Checklist:**

PT & FR translations

---

packages/api/src/models/pestControlTask.js

Fixed null value - recent fix from pest control task may have caused this.
Jira link:
**Checklist:**

Fix null value

---

packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx

This code was lost when https://github.com/LiteFarmOrg/LiteFarm/pull/2825/ was merged
Jira link: None
**Checklist:**

LF-3001 Restore code lost when LF-3482 was merged

---

packages/webapp/public/locales/es/translation.json

Jira link:
- [X ] Translation change
**Checklist:**

We changed "Registrarse" with the "Iniciar sesión"

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/pt/common.json
packages/webapp/src/components/Forms/SimpleCustomType/index.jsx
packages/webapp/src/components/Task/PureAddCustomTask/index.jsx
packages/webapp/src/stories/Pages/Forms/SimpleCustomType.stories.jsx

Creates a reusable component for a custom type creation, update and edit. 
Copied the basic implementation of adding a custom task type but combined the three views into one component.
Fixes one console error in Task Type creation that had an issue with hookFormSetValue prop. relevant because I was copying this code.
Local storybook link: [http://localhost:6006/?path=/story/form-simplecustomtype--add-custom-type](http://localhost:6006/?path=/story/form-simplecustomtype--add-custom-type)
New issue to refactor custom task type: [LF-3571](https://lite-farm.atlassian.net/browse/LF-3571)
Jira link: [LF-3555](https://lite-farm.atlassian.net/browse/LF-3555)
Please describe the tests that you ran to verify your changes. Provide …

Lf 3555 create custom finance type individual component

---

initdb.d/000-init.sql

Exported using:
docker compose exec db pg_dump --host localhost --port 5432 --user postgres --no-owner --no-privileges --no-acl --create pg-litefarm > initdb.d/000-init.sql
Jira link: https://lite-farm.atlassian.net/browse/LF-3436
**Checklist:**

LF-3436 Update sample dataset to most recent changes

---

packages/api/src/controllers/farmExpenseTypeController.js

The check in PR #2872 was missing a return statement.
That will crash Express if that conditional is true 🙂 
Jira link: None
Tested by sending a bunk `farm_id` to the endpoint.
**Checklist:**

Patch for PR #2872

---

packages/api/src/controllers/farmExpenseTypeController.js

Several requests made in succession to some of the routes of
- https://github.com/LiteFarmOrg/LiteFarm/pull/2849
(done in Postman; for the most part the frontend prevents these particular requests) leads to the the beta API hanging with knex timeout error. It was belatedly observed that some logical paths in the controllers were lacking either a `trx.commit()` or `trx.rollback()`.
Noted, but not undertaken in this PR because it would be a significant refactor, is that the other Objection.js transaction sytnax described [in this ticket](https://lite-farm.atlassian.net/browse/LF-355) automatically closes transactions. For me that is arguably preferable (safer at the cost of being less explicit) but this is subjective and team member opinions differ.
Syntax or transaction …

LF-3649 Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

---

packages/api/db/migration/20230920151515_add_guernsey_aland_to_countries.js

**Please wait to merge until fixes verified by QA.**
This adds country codes for Aland Islands and Guernsey for user requests. (can i just say its a weird coincidence its exactly 100 issues later).
Jira link: https://lite-farm.atlassian.net/browse/LF-3563 , https://lite-farm.atlassian.net/browse/LF-3653.
**Checklist:**

LF-3653 - Add Guernsey and Aland Islands to countries in db

---

packages/api/src/controllers/saleController.js
packages/api/tests/sale.test.js
packages/webapp/src/components/Forms/GeneralRevenue/index.jsx
packages/webapp/src/containers/Finances/ActualCropRevenue/index.jsx
packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
packages/webapp/src/containers/Finances/ActualRevenueItem/index.jsx
packages/webapp/src/containers/Finances/AddSale/index.jsx
packages/webapp/src/containers/Finances/EditSale/index.jsx
packages/webapp/src/containers/Finances/OtherExpense/index.jsx
packages/webapp/src/containers/Finances/constants.js
packages/webapp/src/containers/Finances/index.jsx
packages/webapp/src/containers/Finances/util.js

- update `saleController` to update `value` and `note` for general type and handle `crop_variety_sale` only when the type is crop sale (It will be properly done in [LF-3595](https://lite-farm.atlassian.net/browse/LF-3595))
- create `revenueFormTypes` constant and `getRevenueFormType` function
- update `GeneralRevenueForm` to be able to be used for edit view (fix default values, add delete button)
- update `EditSale` to show `GeneralRevenueForm` based on `revenueType`
- update `ActualCropRevenue` (renamed to `ActualRevenueItem`) to show non crop revenue
- update `getExpenseType` to show custom expense type name
- skip a test for patchSales that cannot pass until the controller is updated
Other tweaks:
- correct persistedPaths for the revenue flow (remove …

LF-3599: Review finances dashboard and check that new custom expenses and revenues function properly in these views

---

packages/webapp/src/containers/Finances/saga.js

This completes the custom revenue types sagas by adding the pathing to the container newly created in:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2879
Jira link: https://lite-farm.atlassian.net/browse/LF-3586
**Checklist:**

LF-3586 Add pathing to manage_custom_revenues

---

.gitignore
.vscode/launch.json
packages/api/.vscode/launch.json
packages/api/package.json

Another developer experience PR, my favourite 😁 
This adds the ability to attach a debugger when running `npm test` (a run script that can safely be modified as it is only used locally).
Following @Duncan-Brain's excellent suggestion I have added `.vscode/launch.json` to the repo as launch configurations for the repo can and should be shared among developers for a consistent debugging experience. Configurations are included for the API (local or Dockerized), the `export_server` as configured by `docker compose up`, and the tests (to use with current `package.json` addition).
Please use by running `npm test` and then attaching using the "Debug Jest Tests" configuration from VS Code Run and debug:
If you don't attach the debugger the test script(s) will behave as normal. …

LF-3671 Add debugging to npm test script and vs code debug configurations to repository

---

packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
packages/webapp/src/components/Finances/AddExpense/index.jsx
packages/webapp/src/components/Finances/AddExpense/styles.module.scss
packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx

This PR:
- moves the "Date" field in the Add Expense flow from the outer form (= 1 per form) to the `<ExpenseItemInputs />` (= 1 per expense item) and updates the data formatting in the container to accommodate the change. The saga and backend were already setup to receive one date per item.
- for readability, renames some variables in `handleSubmit` (particularly the one-letter iterators) in favour of more descriptive names to make the logic clearer.
I recommend reading the [logic commit](https://github.com/LiteFarmOrg/LiteFarm/pull/2905/commits/f97b6b4c74c562bc1c67110f2580e42d9281bfe7) separately from the [refactor commit](https://github.com/LiteFarmOrg/LiteFarm/pull/2905/commits/581a2fe7fccc3cab2c14496a8073f21f7a1d4ec8) for the `handleSubmit` function because otherwise …

LF-3678 Update expense instances entry page to have dates for all entries

---

packages/webapp/src/containers/Finances/CustomRevenueType/CustomRevenueRadios/index.jsx

So sorry guys for this zombie PR that just won't die 😅 (And that's not even counting the incoming changes to the requirements!!)
I accidentally had the updated text logic in the wrong file -- the one that was was eventually deleted after the CSS file creation -- and only noticed when this when the feature went live on beta.
This just fixes the translations as they were meant to be on add and edit and temporarily were about two commits before merge 🙂 
Jira link: https://lite-farm.atlassian.net/browse/LF-3595
**Checklist:**

LF-3595a Restore accidentally deleted translation switching logic

---

packages/api/src/controllers/insightController.js
packages/api/src/controllers/insightHelpers.js
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Modals/BiodiversityLoadingModal/BiodiversityLoadingModal.jsx
packages/webapp/src/containers/Insights/Biodiversity/index.jsx
packages/webapp/src/containers/Insights/saga.js

Changes to how we query the data from GBIF. Essentially, instead of querying for all occurrences and then filtering out those ones that match the kind of species we’re interested in, I’ve re-written it so that we make a query for each class/kingdom (plants, birds, mammals, etc) and then filter out how many unique occurrences there are for each of those classes. This will mean that we’re less likely to hit the 100,000 limit from their API. I’ve also limited concurrency so that we only make calls for one specific boundary concurrent. So if we have one boundary, we’ll do 1 chunk of calls, if we have two we’ll make 2 chunks, and so on. This also means that if we do hit that API limit, the user could solve the problem by splitting their boundary into several smaller ones.
Jira …

LF-3675 improve biodiversity calculation performance

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/tests/dateRange.test.js
packages/webapp/src/util/date.jsx
packages/webapp/src/util/dateRange.js

- install `vitest`
- add `test` script to run tests
- Create `DateRange` class that calculates `startDate` and `endDate` for each date range option. The class handles both week start day - Monday and Sunday, and tests were written for both.
Jira link: https://lite-farm.atlassian.net/browse/LF-3637
```
pnpm test src/tests/dateRange.test.js
```
**Checklist:**

LF-3637 (2): Update the date inputs used in date range selector [DateRange class]

---

packages/api/src/controllers/managementPlanController.js

Added functionality to send a notification for each task on a management plan that is being abandoned.  The logic used was the same used for delete management plan.
Jira link: https://lite-farm.atlassian.net/browse/LF-3682?atlOrigin=eyJpIjoiNjE0ZjUyZTI2MWE0NDg2OGI2NWFiNmFiMjhlMGE4NGYiLCJwIjoiaiJ9
The new functionality was tested abandoning managements plans with 1 to 3 tasks assigned to a user, or assigned to none.
**Checklist:**

added abandoned task notification for tasks on a management plan being abandoned

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/assets/images/chevron-down.svg
packages/webapp/src/components/Table/v2/TableHead.jsx
packages/webapp/src/components/Table/v2/index.jsx
packages/webapp/src/components/Table/v2/styles.module.scss
packages/webapp/src/stories/Pages/config/Decorators.jsx
packages/webapp/src/stories/Table/TableV2.stories.jsx
packages/webapp/src/util/sort.js

- create a Table component using the [Material UI table](https://mui.com/material-ui/react-table/) (the component was written based on this [example code](https://mui.com/material-ui/react-table/#system-EnhancedTable.js))
- create [stories](http://localhost:6006/?path=/docs/components-tables-v2--docs)
Note: 
- the table could show `Load More` button or a pagination, but I didn't try to finalize it as I don't think we are at that stage yet.
- the regular footer is shown by adding `Footer` prop to `columns` as the existing table works.
(this is just an example)
- the irregular footer is shown by passing `FooterCell` as table's prop.
- Why material UI table?
[react-table v6](https://www.npmjs.com/package/react-table-v6) is being used for the existing tables. It was released 4 …

LF-3747: Duplicate current table component and update styling

---

.github/CODEOWNERS
.prettierignore

Setting up a `CODEOWNERS` file. In theory code owners should be automatically assigned to review PRs. Docs for this file here https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners.
I've setup two teams that are code owners:
- Mandatory reviewers. This is just me for now, which would mean if this works I'd be assigned to all PRs.
- Reviewers. Previous team, should select up to 2 members. If it works as I intend to, I should count as member for this team too, so if I'm added it would only add one extra reviewer.
Jira link:
More of a dev workflow enhancement.
Please describe the tests that you ran to verify your changes. Provide instructions so we …

Add codeowners file

---

packages/webapp/src/containers/Finances/util.js
packages/webapp/src/containers/revenueTypeSlice.js

- add one change that was missing in this [PR](https://github.com/LiteFarmOrg/LiteFarm/pull/2916)
- remove unused function
Jira link: [LF-3684](https://lite-farm.atlassian.net/jira/software/c/projects/LF/issues/LF-3684)
**Checklist:**
[LF-3684]: https://lite-farm.atlassian.net/browse/LF-3684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-3685(2): Correct revenue type translation key

---

packages/api/db/migration/20231024164318_null_agricuture_associated.js
packages/api/src/controllers/revenueTypeController.js
packages/api/src/models/revenueTypeModel.js
packages/api/tests/mock.factories.js
packages/api/tests/revenue_type.test.js
packages/api/tests/sale.test.js
packages/webapp/src/containers/Finances/CustomRevenueType/CustomRevenueRadios/index.jsx
packages/webapp/src/containers/Finances/CustomRevenueType/CustomRevenueRadios/styles.module.scss
packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
packages/webapp/src/containers/Finances/CustomRevenueType/ReadOnlyCustomRevenue.jsx
packages/webapp/src/containers/Finances/saga.js

Kevin's instructions in the Slack thread (linked in Jira) read:
> I'm hoping we can just hide the question and null the values for now rather than remove it from the schema.
So I initially removed `agriculture_associated` everywhere except the database (because of the reference to schema), but the phrase "hide the question" (i.e. comment out, I think) makes me believe we want to keep this as reversible as possible. Therefore I have:
- nulled the value in the database (without changing underlying database schema) or default value
- ~~_commented out_~~ deleted all references to the dependent logic between `agriculture_associated` and `crop_generated` in backend and frontend
- retained `agriculture_associated` as a required property but set it to `null` in the model. This …

LF-3757 Remove associated with agriculture question and logic from revenue types

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/common.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Forms/GeneralRevenue/CropSaleItem.jsx
packages/webapp/src/components/Task/AddProduct/index.jsx
packages/webapp/src/components/Task/HarvestingTask/ReadOnly.jsx
packages/webapp/src/components/Task/HarvestingTask/index.jsx
packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
packages/webapp/src/components/Task/TaskComplete/HarvestComplete/Quantity.jsx

Add "Quantity" to the common file, and delete other "Quantity".
I decided to create a separate PR rather than adding changes to https://github.com/LiteFarmOrg/LiteFarm/pull/2938.
Jira link: N/A
**Checklist:**

LF-3761: Cleanup Quantity translations

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/pt/common.json
packages/webapp/src/components/Finances/Transaction/Mobile/List.jsx
packages/webapp/src/components/Finances/Transaction/Mobile/styles.module.scss
packages/webapp/src/containers/Finances/util.js
packages/webapp/src/tests/financeUtil.test.js
packages/webapp/src/util/date.js

- create `isSameDay` function 
- create `formatTransactionDate` function with tests
- add transaction dates to `TransactionList`
Jira link: https://lite-farm.atlassian.net/browse/LF-3746
**Checklist:**

LF-3746: Group transactions by date

---

packages/webapp/src/components/Drawer/index.jsx
packages/webapp/src/components/Drawer/style.module.scss

Generic drawer component which opens from bottom with content of desired choice.
Jira link:https://lite-farm.atlassian.net/browse/LF-3751
As this is not a standalone component, to test we need to integrate into required part of the app.
**Checklist:**

generic drawer component

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/common.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Finances/Transaction/ExpandedContent/GeneralTransactionTable.jsx
packages/webapp/src/components/Finances/Transaction/ExpandedContent/index.jsx
packages/webapp/src/containers/Finances/OtherExpense/index.jsx
packages/webapp/src/containers/Finances/index.jsx

- update translation files
- add "Amount" to `common.json` and deleted ones in `translation.json`, and update tags in the code
(I copied existing `cost` and `expenses`, but I didn't delete existing ones)
- create and add `GeneralTransactionTable` component
Jira link: https://lite-farm.atlassian.net/browse/LF-3749
**Checklist:**

LF-3749: Iimplement other transactions expandable content

---

packages/api/db/migration/20231103204600_add_custom_revenue_types_spotlight.js
packages/api/src/controllers/showedSpotlightController.js
packages/api/src/models/showedSpotlightModel.js
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/containers/Finances/AddSale/ManageCustomRevenueTypeSpotlight/index.jsx
packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
packages/webapp/src/containers/showedSpotlightSlice.js

Added spotlight for managing custom revenue types, behaves the same as the one for custom expense types.
Jira link:
**Checklist:**

LF-3594 add custom revenue types spotlight

---

packages/webapp/src/components/CardsCarrousel/index.jsx
packages/webapp/src/components/CardsCarrousel/styles.module.scss

Added animation to cards carrousel when you swap cards.
Jira link:
**Checklist:**

Add animation to carrousel

---

packages/api/src/templates/locales/fr.json
packages/webapp/.storybook/preview-head.html
packages/webapp/index.html

Update 'Lite Farm' to 'LiteFarm'.
Jira link: https://lite-farm.atlassian.net/browse/LF-3604
**Checklist:**

LF-3604: Remove space in application title

---

packages/webapp/public/locales/fr/translation.json

Translate "Missing" to French

---

packages/webapp/src/components/DateRangeSelector/index.jsx
packages/webapp/src/containers/Finances/index.jsx
packages/webapp/src/containers/Finances/useTransactions.js
packages/webapp/src/containers/Finances/util.js
packages/webapp/src/containers/saga.js

- Fixed crash in Finances dashboard that happened when switching farms. This was due to the sales and expenses for the new farm being fetched, but not the related entities such as revenue types, expense types and crop varieties.
- Since crop varieties are now used in the dashboard to display revenue transactions, added fetching them to the `useEffect` in the finances screen as well.
- Added several undefined checks for revenue and expense types and crop varieties to prevent crashing if above solutions fail, as well as default empty arrays for entities in the useTransactions hook.
- Added resetting date and types filters when loading finances dashboard. This will reset the filtering when switching farms, but will also add intended behavior of resetting when navigating away …

LF-3796, LF-3765 fix finances crashes

---

packages/webapp/src/containers/Filter/Transactions/index.jsx
packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
packages/webapp/src/containers/Finances/selectors.js

This PR uses the sorting functions from the finance type lists (tile lists) to sort the dashboard filters.
Jira link: https://lite-farm.atlassian.net/browse/LF-3804
**Checklist:**

LF-3804 Dashboard and report filters should be sorted

---

packages/webapp/nginx.conf

This adds a no-cache directive to the `index.html` page served by the Docker container nginx.
This was added specifically so that the fallback `index.html` (the under maintenance splash screen -- not part of our repo code but rather defined directly on the Droplet) is served immediately when the Docker containers go down. Please see Jira ticket for details and the configuration that controls this.
This code change _may_ have some additional benefit in applying our code changes more immediately upon PR merge (i.e. by pointing to the new main.js file built by Vite and referenced in the Vite-created `index.html` without manual reload). However I'm not sure if that will happen, and ~~in any case that is a benefit that has no real significance to production anyway~~ except …

Add no-cache directive to index.html (Docker nginx)

---

packages/webapp/src/containers/Finances/actions.js
packages/webapp/src/containers/Finances/constants.js
packages/webapp/src/containers/Finances/index.jsx
packages/webapp/src/containers/Finances/reducer.js
packages/webapp/src/containers/Finances/saga.js
packages/webapp/src/containers/Finances/selectors.js
packages/webapp/src/containers/saga.js

LF-3825 wait until data is fetched to load finances

---

packages/webapp/src/containers/Finances/useTransactions.js

Include expenses with amount 0 (gifts) in transactions hook.
Jira link:
**Checklist:**

LF-3853 show expenses with amount 0

---

packages/api/src/controllers/managementPlanController.js
packages/api/src/controllers/taskController.js
packages/api/src/models/taskModel.js

Deleting or abandoning a plan with deleted tasks currently fails because the `getTaskType` method on `TaskModel` called here (to formulate the notification text):
```js
const { task_translation_key } = await TaskModel.getTaskType(task_id);
```
filters for deleted tasks, while the controllers for plan abandonment and delete themselves do not (presumably because there is no harm in re-deleting a deleted task or assigning an abandonment date to a deleted task). This means the method above gets called on deleted tasks, returns nothing, and then fails on the destructuring.
This PR:
- removes the check for deleted from that method (because logically speaking it should return the correct `task_type` regardless of the deletion status of the task in question
- Adds a check for task …

LF-3844 The user is not able to delete or abandon the crop plan once he deletes a task which is associated with this crop plan

---

packages/api/src/templates/locales/pt.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/certifications.json
packages/webapp/public/locales/pt/expense.json
packages/webapp/public/locales/pt/message.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Form/InputDuration/index.jsx
packages/webapp/src/components/RepeatCropPlan/Confirmation.jsx
packages/webapp/src/components/Task/PureTaskDetails/index.jsx

- Added Portuguese translation improvements.
- Added SPan
Jira link:
**Checklist:**

LF-3827 translations

---

packages/webapp/public/locales/pt/translation.json

Jira link:
- [x ] Translations 
**Checklist:**

PT_Missing translations for November release

---

packages/api/package.json

We did this change because we run into an error every time while running the command npm run nodemon. There was an extra space near variable.
Jira link:
**Checklist:**

Fixed nodemon script in package JSON

---

packages/webapp/src/containers/Finances/Report/index.jsx

Use translations for "date".
Jira link: N/A
**Checklist:**

Fix: "date" in finance report export drawer

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/util/constants.js

Bump to version 3.5.1 for hotfix

Bump to version 3.5.1

---

packages/webapp/src/components/Navigation/NavBar/index.jsx

_Drafted until #3027 is merged (needs to follow that code change going live)_ 
This is just a test PR to force a re-build of the frontend container. I removed the navbar gradient from the main page, as it is on its way out shortly anyway (and it's very easy to see when the change goes live)!
The question is whether the new Nginx settings will resolve the MIME type crashes when this is merged and the new service worker goes live 🤞 
Jira link: https://lite-farm.atlassian.net/browse/LF-3921
Can't be tested locally; will be tested on beta
**Checklist:**

LF-3921b Remove navbar gradient (test code change)

---

packages/api/src/util/digitalOceanSpaces.js

Added missing https:// before endpoint 'nyc3.digitaloceanspaces.com'
Jira link: https://lite-farm.atlassian.net/browse/LF-3916
**Checklist:**

LF-3916 Fix beta issue for aws-sdk v3

---

packages/webapp/src/assets/mixin.scss
packages/webapp/src/components/Navigation/NavBar/index.jsx
packages/webapp/src/components/Navigation/NoFarmNavBar/styles.module.scss

This re-applies the visual changes from:
- #3034 
Which were reverted in
- #3035 
Both the revert and the restoration are for test beta's behaviour on merge.
Jira link: https://lite-farm.atlassian.net/browse/LF-3923
**Checklist:**

LF-3923d Restore visual changes from LF-3923b

---

packages/webapp/src/App.jsx
packages/webapp/src/assets/variables.scss
packages/webapp/src/components/Navigation/NavBar/index.jsx
packages/webapp/src/components/Navigation/NavBar/slideMenu/index.jsx
packages/webapp/src/components/Navigation/NavBar/slideMenu/styles.module.scss
packages/webapp/src/components/Navigation/NavBar/styles.module.scss
packages/webapp/src/containers/Map/styles.module.scss
packages/webapp/src/containers/Navigation/SlideMenu.jsx
packages/webapp/src/containers/Navigation/index.jsx
packages/webapp/src/hooks/useIsFarmSelected.jsx
packages/webapp/src/stories/Navigation/NavBarDrawer.stories.jsx
packages/webapp/src/styles.module.scss

- create `SlideMenu` container
- modify `App` component to add `SlideMenu` (it will not slide anymore, but I think I should rename it in another PR since github wouldn't show the diffs if I renamed... I failed to do `git mv` and suffered for a while to get it fixed)
- update NavBar height
- update `NavBar` component to use `SlideMenu` container instead of `SlideMenu` component. (some of NavBar's state are moved to its grandchild component `SlideMenu`)
- create `useIsFarmSelected` hook
- adjust map's width
- adjust stories
- move styles written with makeStyles that I had to update to scss files
NOTE:
- side menu for tablet view will be broken until LF-3912 is completed (let me know if you think I should do better...)
- snackbar's style is currently broken ~~and map's drawer …

LF-3910: Fix side menu on the left for desktop and tablet views

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/common/logger.js
packages/api/src/controllers/cropVarietyController.js
packages/api/src/controllers/documentController.js
packages/api/src/controllers/insightController.js
packages/api/src/controllers/managementPlanController.js
packages/api/src/controllers/organicHistoryController.js
packages/api/src/controllers/taskController.js
packages/api/src/server.js
packages/webapp/nginx.conf
packages/webapp/src/main.jsx

Branch for patch 3.5.2, only ngnix and logger changes, no PWA auto reloading.
Jira link:
**Checklist:**

Patch 3.5.2 (only ngnix and logger changes)

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/main.jsx

This reverts commit 9b44c28b6350c47b3599dda9df31a0e00e11a010, reversing changes made to ca1fd5114ca006c789912da77a80a7f8b38e685c.
Reverts auto-reloading to match integration to main.
Jira link:
**Checklist:**

Revert auto-reloading in integration

---

.github/workflows/lint_translation_files.yml
packages/api/.eslintrc.cjs
packages/api/package-lock.json
packages/api/package.json

I added a GitHub workflow to run linters against translation files in /webapp ([#3020](https://github.com/LiteFarmOrg/LiteFarm/pull/3020)), but the check didn't fail for Denis' [PR](https://github.com/LiteFarmOrg/LiteFarm/pull/3038) that had invalid JSON. I realized that Denis had added invalid JSON to files in /api, so I created this PR to add another job to run linters against translation files in /api.
- update the workflow
- install `eslint-plugin-json`
- update `.eslintrc.cjs` to use `eslint-plugin-json`
Jira link: https://lite-farm.atlassian.net/browse/LF-3085
I added invalid JSON in `/api`.
**Checklist:**

LF-3085 update Lint Translation Files github workflow for /api

---

README.md
docker-compose.yml
packages/api/dev.export.sh

Note: these are not high-priority changes! They are small quality of life improvements with `docker compose up` that were nonetheless going to bug me until fixed 🙂 
We have an overarching task titled [Move to 'docker compose up' for new contributors](https://lite-farm.atlassian.net/browse/LF-3335) aimed at full containerization. This task is currently on pause; however, the modifications in this PR are smaller in scope and focus on making the current `docker compose up` command more user-friendly and efficient. These changes were partly inspired by feedback received during our August candidate search.
Changes:
- Improved the `minio_create_bucket` script: It now displays a success message instead of a confusing error if the bucket already exists. Additionally (as a …

LF-3915 Clean up 'docker compose up' for new contributors

---

packages/webapp/src/components/Crop/CropHeader.jsx
packages/webapp/src/components/Crop/styles.module.scss
packages/webapp/src/components/Task/PureTaskTypeSelection/styles.module.scss
packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx
packages/webapp/src/containers/Finances/Labour/index.jsx
packages/webapp/src/containers/Finances/OtherExpense/index.jsx
packages/webapp/src/containers/Finances/actions.js
packages/webapp/src/containers/Finances/constants.js
packages/webapp/src/containers/Finances/saga.js
packages/webapp/src/routes/DeprecatedRoutes.jsx

- Fixes missing entities errors in Finances subsections.
- Fixes tasks cards not sizing gracefully.
- Fixes buggy styling on crop detail page.
Jira link:
**Checklist:**

Navigation fixes

---

packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
packages/webapp/src/components/Navigation/TopMenu/styles.module.scss

I didn't have much time to vet this and I hate using !important but..
The clicking out of menu thing David identified: It seems like it can be fixed but it is actually one of the things MUI does not (yet) support for its menu -- I have an alternative here that uses popper instead of popover workaround here t: https://github.com/mui/material-ui/issues/9893#issuecomment-475149728
Discussion here: https://github.com/mui/material-ui/issues/9893#issuecomment-475149728 and here from MUI https://github.com/mui/material-ui/issues/11243
Jira link:
**Checklist:**

Fix for menu

---

packages/webapp/src/components/Navigation/SideMenu/index.jsx
packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
packages/webapp/src/components/Navigation/TopMenu/styles.module.scss
packages/webapp/src/components/Navigation/index.jsx

Address comments in https://github.com/LiteFarmOrg/LiteFarm/pull/3055
- wrap the logo with `TextButton`
- rename a prop 
**Checklist:**

LF-3932: Address comments in #3055

---

packages/webapp/src/containers/hooks/useHistoryLocation.js

After looking into `useHistoryLocation` hook, I found that `history.listen()` in which `setHistoryLocation` is called was not being called in `useEffect`.
So, we were referencing the old `historyLocation` here:
Replacing `useEffect` with `useLayoutEffect` seems to work fine.
I can't explain better than what ChatGPT did, so I will just copy and paste...
> The useEffect hook runs asynchronously after the render, which means it might not guarantee that the DOM has been fully updated or that certain events, like history changes, have been processed.
> 
> When you use useEffect with history.listen, there's a possibility that the initial render or reload might not immediately trigger the history change event, leading to the callback not being executed right away.
> 
> On the …

LF-3956: Navigation bar is displayed on the login page

---

packages/webapp/src/App.jsx
packages/webapp/src/assets/colors.scss
packages/webapp/src/components/Map/DrawingManager/styles.module.scss
packages/webapp/src/components/Map/Header/styles.module.scss
packages/webapp/src/components/Navigation/SideMenu/styles.module.scss
packages/webapp/src/components/Profile/ProfileLayout/index.jsx
packages/webapp/src/containers/Map/index.jsx
packages/webapp/src/containers/Map/styles.module.scss
packages/webapp/src/routes/index.jsx
packages/webapp/src/styles.module.scss

- Updated active state styling for menu subitems so they're different from items.
- Removed tabs from settings since they're no longer needed (we now have direct links navigating through each section in the navigation).
- Make map full width (approach extendable to future full width pages as well) and center Redraw / Confirm buttons.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3948
https://lite-farm.atlassian.net/browse/LF-3950
https://lite-farm.atlassian.net/browse/LF-3952
**Checklist:**

Nav menu styling fixes

---

packages/api/package-lock.json
packages/api/package.json
packages/webapp/package.json
packages/webapp/src/main.jsx
packages/webapp/src/util/constants.js

Update release version

---

packages/webapp/src/hooks/useGetMenuItems.jsx

Hide admin actions in side menu for non admin users.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3959
**Checklist:**

LF-3959 hide admin actions for non admin users

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/containers/Finances/saga.js

Financial report should have the following name format:
[Farm Name] [translated: Financial Report] [Date Range]
Example:
Cultivando sonrisas Reporte financiero 2022-01-01 - 2022-12-31
Jira link:https://lite-farm.atlassian.net/browse/LF-3904
Go to finances section and download report in different languages. The filename should change accordingly.
**Checklist:**

financial report filename dynamic

---

packages/webapp/src/containers/Finances/saga.js

Just a few more edits based on testing PR https://github.com/LiteFarmOrg/LiteFarm/pull/3081
Jira link: https://lite-farm.atlassian.net/browse/LF-4015
**Checklist:**

LF-4015b Route hotfix additional changes

---

packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
packages/webapp/src/components/Navigation/index.jsx
packages/webapp/src/containers/Navigation/index.jsx

Not as urgent but fixes a tiny sercurity hole when a invited user accepts the invite on the same computer as a logged in user they are shown the navigation which is not ideal. For example a worker follows invite and can then navigate as the manager.
Jira link: https://lite-farm.atlassian.net/browse/LF-4007 
**Checklist:**

Add another condition for how the navbar should render

---

packages/webapp/src/components/Finances/PureExpenseDetail/index.jsx

This appears to be only reproducible in certain situations. 
**Editing an expense value that is between 1-9**
To reproduce:
1. Add an expense between $1 - $9 and save.
2. Try to edit the expense by pressing backspace, then entering a new value. The save button will remain disabled not allowing you to submit form. However, if you blur the input field after clearing it before entering a new value then it still works.
**Editing any expense value by first clearing the input at once**
To reproduce:
1. Add an expense with more than 1 digit and save.
2. Clear the input by highlighting the entire number at once and delete. 
3. Try to edit right away without blurring, you will find the save button remains disabled.
What seems to be happening is that when the value becomes empty, it …

LF-3872-not-able-to-edit-expense-value

---

packages/api/db/migration/20240125214641_create_animal_batch_and_batch_sex_tables.js

This adds the tables for animal_batch and animal_batch_sex_detail. It is a branch of #3083  and copies the structure of those tables.
Jira link:[ LF-3983](https://lite-farm.atlassian.net/browse/LF-3983)
- migrates up and down
**Checklist:**

Lf 3983 create animal batch table and supporting table

---

packages/api/src/controllers/animalGroupController.js
packages/api/src/controllers/customAnimalTypeController.js
packages/api/src/models/animalBatchGroupRelationshipModel.js
packages/api/src/models/animalGroupModel.js
packages/api/src/models/animalGroupRelationshipModel.js
packages/api/src/routes/animalGroupRoute.js
packages/api/src/server.js

TODO:
Jira link: https://lite-farm.atlassian.net/browse/LF-3998
(shape of endpoint described here: https://lite-farm.atlassian.net/browse/LF-3989)
HAVE TESTED NOTHING
**Checklist:**

LF-3998 Create POST endpoint to create a new animal group

---

.github/workflows/automated_tests.yml
.github/workflows/cypress_tests.yml
.github/workflows/webapp_unit_tests.yml

Attempt to fix E2E tests CI

---

packages/end-to-end/cypress/e2e/farm_people.js

Added random e2e test failure to test CI.
Jira link:
**Checklist:**

test e2e ci

---

packages/end-to-end/cypress/e2e/farm_people.js

Reverts LiteFarmOrg/LiteFarm#3107

Revert "test e2e ci"

---

packages/api/db/migration/20240125214641_create_animal_batch_and_batch_sex_tables.js
packages/api/db/migration/20240130190029_create_animal_group_tables.js
packages/api/src/controllers/animalGroupController.js
packages/api/src/controllers/customAnimalTypeController.js
packages/api/src/models/animalBatchGroupRelationshipModel.js
packages/api/src/models/animalGroupModel.js
packages/api/src/models/animalGroupRelationshipModel.js
packages/api/src/routes/animalGroupRoute.js
packages/api/src/server.js
packages/api/tests/animal_group.test.js
packages/api/tests/mock.factories.js

Co-authored with @kathyavini
- Created animal group table and tables relating group to animals and batches.
- Created POST request to add new groups.
- Created GET request to get groups for a farm along with their related batches and animals.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4002
https://lite-farm.atlassian.net/browse/LF-3998
https://lite-farm.atlassian.net/browse/LF-4028
Run migration locally.
**Checklist:**

LF-4002, LF-3998, LF-4028: create animal group tables and GET/POST requests

---

packages/api/db/migration/20240202201923_update_animal_batch_permissions.js
packages/api/src/controllers/animalBatchController.js
packages/api/src/controllers/animalGroupController.js
packages/api/src/controllers/baseController.js
packages/api/src/models/animalBatchModel.js
packages/api/src/models/animalBatchSexDetailModel.js
packages/api/src/routes/animalBatchRoute.js
packages/api/src/server.js
packages/api/src/util/errorCodes.js
packages/api/src/util/util.js
packages/api/tests/animal_batch.test.js
packages/api/tests/animal_group.test.js
packages/api/tests/mock.factories.js
packages/api/tests/testEnvironment.js

This adds the Get and post requests for batches. 
- Added in some new error handling based on previous PR where we discussed handling other errors.(I am open to removing this part) Model calls in objection validate against the jsonSchema. This handles many of those errors  and allows deletion of several pre-checks (now deleted you can see from commits).
- relationMapping is used for a clean insert function. @kathyavini (this is what I was thinking)
Jira link:[
](https://lite-farm.atlassian.net/browse/LF-3984, https://lite-farm.atlassian.net/browse/LF-3994) …

Lf 3994 create get endpoint to fetch all animal batches for a farm

---

packages/webapp/src/locales/i18n.js

Fixes the errors shown on login when a specific language variant is not supported.
[https://www.i18next.com/overview/configuration-options](https://www.i18next.com/overview/configuration-options)
Jira link: [LF-4060](https://lite-farm.atlassian.net/browse/LF-4060)
To Test: 
1. On integration: clear cookies - see error on login
2. On this branch: clear cookies - see no errors
**Checklist:**
[LF-4060]: https://lite-farm.atlassian.net/browse/LF-4060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4060 - add supported languages option

---

packages/webapp/src/components/EditCropVariety/index.jsx

- Added missing varietal and cultivar input fields and changed label for variety name to common name.
- Did minor refactoring by moving field names out of the component and into an object.
Jira link: https://lite-farm.atlassian.net/browse/LF-3566
**Checklist:**

LF-3566 add common name, varietal, and cultivar to edit varietal screen

---

packages/webapp/public/locales/fr/translation.json
packages/webapp/src/components/Modals/CancelFlowModal/index.jsx

Removed the unwanted encoding characters in the french translation.
Jira link: https://lite-farm.atlassian.net/browse/LF-3777
- [+] Bug fix (non-breaking change which fixes an issue)
- [+] UI components visually reviewed on desktop view
**Checklist:**
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] My changes generate no new warnings

LF-3777- Removed unwanted characters in the French translation files.

---

packages/webapp/src/components/CardWithStatus/ManagementPlanCard/ManagementPlanCard.jsx

The height of the managemen plan card would be of the same size.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3526
**Checklist:**

LF-3526 : Added the minHeight: 150px to the management plan card

---

packages/api/db/migration/20240311212608_add_animal_removal_date.js
packages/api/src/controllers/animalBatchController.js
packages/api/src/controllers/animalController.js
packages/api/src/models/animalBatchModel.js
packages/api/src/models/animalModel.js
packages/api/tests/animal.test.js
packages/api/tests/animal_batch.test.js
packages/webapp/src/components/Animals/RemoveAnimalsModal/index.tsx
packages/webapp/src/store/api/types/index.ts
packages/webapp/src/util/moment.js

Adds `removal_date` to the backend and frontend.
Jira link: https://lite-farm.atlassian.net/browse/LF-4137
**Checklist:**

LF-4137 Add support for removal date

---

packages/webapp/public/locales/en/common.json
packages/webapp/public/locales/es/common.json
packages/webapp/public/locales/fr/common.json
packages/webapp/public/locales/pt/common.json
packages/webapp/src/components/Table/TableV2.jsx
packages/webapp/src/components/Table/styles.module.scss
packages/webapp/src/containers/Animals/Inventory/index.tsx
packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
packages/webapp/src/util/animal.ts

Addressed comments on https://github.com/LiteFarmOrg/LiteFarm/pull/3154
- add `selected` prop to TableRow and fix broken styles
- update generateInventoryId function
- change "Select all {{count}}" to "Select all"
- add 2px gap between table rows (requested by Loïc)
Jira link: https://lite-farm.atlassian.net/browse/LF-4087
**Checklist:**

LF-4087(2): Create or modify containers to associate action bar and table

---

packages/webapp/src/util/siteMapConstants.ts

We removed the extra curly bracket symbol "}" in the returned statement for a function
Jira link: https://lite-farm.atlassian.net/browse/LF-4115
- [+] Bug fix (non-breaking change which fixes an issue)
That we tested this on the local server.
**Checklist:**
- [+] My changes generate no new warnings
- [+] The precommit and linting ran successfully

LF-4115 Removed the extra curly bracket symbol "}"

---

packages/webapp/src/assets/colors.scss
packages/webapp/src/assets/images/stepper/active-dark.svg
packages/webapp/src/assets/images/stepper/active-light.svg
packages/webapp/src/assets/images/stepper/disabled-dark.svg
packages/webapp/src/assets/images/stepper/disabled-light.svg
packages/webapp/src/assets/images/stepper/done-dark.svg
packages/webapp/src/assets/images/stepper/done-light.svg
packages/webapp/src/components/StepperProgressBar/index.tsx
packages/webapp/src/components/StepperProgressBar/styles.module.scss
packages/webapp/src/stories/StepperProgressBar/StepperProgressBar.stories.tsx

This creates a `<StepperProgressBar />` (a styled [MUI React Stepper](https://mui.com/material-ui/react-stepper/)) to be used with multi-step forms such as the upcoming add animals. This is a good component for investigating with the [Storybook controls](http://localhost:6006/?path=/docs/components-stepperprogressbar--docs) to see the different states (step through `activeStep`).
[Figma specification](https://www.figma.com/file/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?mode=dev)
There was an element of the Figma specification I could not implement. The mobileLayout (`alternativeLabel`) specification of the MUI stepper centres all elements within their flex container:
You can write manual logic to left + right justify the first and last element labels, but he other components …

LF-4153 Create animal creation wizard progress bar

---

packages/api/src/controllers/insightController.js
packages/api/tests/insightsAPI.test.js

This PR modifies the raw SQL used to retrieve data regarding sales in the Price page.
The constraint added to the query is "when sale is not deleted, display item".
The behaviour still the same as when there's no item in the chart to be displayed.
Also activated some ignored tests cases that seems to be forgotten. Although more work is needed in this particular test suite.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4132
**Checklist:**
- [] I have commented my code, particularly in hard-to-understand areas

LF-4132 Remove from Price page the soft deleted sales

---

packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx

Changed the redirection once the user clicks on the < button on the "Estimated revenue page"
Jira link:
- [+] Bug fix (non-breaking change which fixes an issue)
- [+] UI components visually reviewed on desktop view
**Checklist:**
- [+] My changes generate no new warnings
- [+] The precommit and linting ran successfully

LF-4012 Changed the redirection once the user clicks on the <  button

---

packages/webapp/src/assets/colors.scss
packages/webapp/src/components/Crop/Detail.jsx
packages/webapp/src/components/Form/Button/button.module.scss
packages/webapp/src/components/Form/Button/index.tsx
packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
packages/webapp/src/stories/Button/Button.stories.jsx

This updates the `<Button />` component used app-wide with the new colours and variant names found in [here in Figma](https://www.figma.com/file/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=3080%3A37232&mode=dev).
- Added
- Secondary-CTA button variant
- Focus states for all buttons
- Styling to control the color of an embedded icon (as show in Figma)
- Updated
- Primary, Secondary, and disabled variants throughout app
- 'Success' variant (used twice in app); now called 'Secondary-2' per Figma
- Removed:
- ~Warning and error style variants; they are not used in App and not present on the component chart~ Thank you @Duncan-Brain for spotting they are indeed both used in `<DeleteBox />`! So they will be preserved, although they don't have styles defined for all states …

LF-4178 Update button colours and variants throughout app

---

packages/api/src/controllers/organicCertifierSurveyController.js
packages/api/tests/organicCertifierSurvey.test.js

When requesting for a certification through API, the user is able to get it even the farm is not pursuing it (interested = false). 
This PR adds a validation to make sure the farm is interested on certifications and returns `202` status code
[Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) 
Also updates the test cases that are not mocking this property from the DB therefore they were expecting a 200 status code. 
Tests related to validate status code 202 can be added but it's a bit daunting the amount of test cases and code in organicCertifierSurvey.test.js file so I decided to skip that for now.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3360
Please describe the tests that you ran to verify …

LF-3360 Add "interested" validation to organic certifier survey

---

packages/api/db/migration/20240403202900_data_migration_fix_default_types_chicken.js
packages/webapp/public/locales/en/animal.json
packages/webapp/public/locales/es/animal.json
packages/webapp/public/locales/fr/animal.json
packages/webapp/public/locales/pt/animal.json
packages/webapp/src/containers/Animals/Inventory/KPI/index.tsx
packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
packages/webapp/src/containers/Animals/types.ts

Replaces chicken broilers and layers with just chicken.
NOTE: Specific DATA IS NOT RECOVERABLE for custom animals, batches, breeds.
Jira [LF-4189](https://lite-farm.atlassian.net/browse/LF-4189)
**Checklist:**
[LF-4189]: https://lite-farm.atlassian.net/browse/LF-4189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4189 - remove excess chicken type

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Task/AssignTask/constants.js
packages/webapp/src/components/Task/AssignTask/useTaskAssignForm.jsx
packages/webapp/src/components/Task/PureTaskAssignment/index.jsx
packages/webapp/src/containers/Task/TaskAssignment/index.jsx
packages/webapp/src/containers/Task/TaskComplete/HarvestComplete/Quantity.jsx
packages/webapp/src/containers/Task/TaskComplete/StepOne.jsx
packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/util/siteMapConstants.ts

Thanks Sayaka for the speedy help! Adding the persisted paths to the step one like pages vs the page before solved the problem.
~~I might need some help figure out the persistForm flow. I did not expect it to have these problems.~~
~~Custom tasks flow should actually be working. But not distinct complete flow groups for Harvest, and All others.~~
Essentially copying the `onComplete()` function from` /containers/Task/TaskReadOnly`. 
~~Problem is once I click continue on the first complete flow page - the persist data present is purged and errors on saving/ continuing the complete flow.~~
~~The `useHookFormPersist()`  seems to run the unlisten() function on the push from the `onReqSuccessSaga` because the persisted paths weren't in the original call.~~
~~I have tried …

LF-4174 - Add checkbox and transition to complete flow

---

packages/webapp/src/components/Animals/FixedHeaderContainer/styles.module.scss
packages/webapp/src/components/Drawer/style.module.scss

For Loïc to evaluate. Letting Drawers take up all the available vertical screen space if needed.
Jira link: https://lite-farm.atlassian.net/browse/LF-4203
**Checklist:**

LF-4203 Remove max height on drawer

---

packages/webapp/src/components/Form/InFormButtons/index.tsx
packages/webapp/src/components/Form/InFormButtons/styles.module.scss
packages/webapp/src/stories/InFormButtons/InFormButtons.stories.tsx

Create InFormButtons component and [stories](http://localhost:6006/?path=/docs/components-informbuttons--docs).
Jira link: https://lite-farm.atlassian.net/browse/LF-4217
**Checklist:**

LF-4217: Create component for product section buttons

---

.github/workflows/deploy.yml

Jira link: n/a. See discussion on Slack [here](https://litefarm.slack.com/archives/C05B9KJLJ82/p1716829130544919)
Test with deploy script on this branch
**Checklist:**

Add new github secret to deploy script

---

packages/api/db/migration/20240504185218_create_soil_amendement_task_products_table.js
packages/api/src/controllers/managementPlanController.js
packages/api/src/controllers/productController.js
packages/api/src/controllers/taskController.js
packages/api/src/middleware/validation/checkProductValidity.js
packages/api/src/middleware/validation/checkSoilAmendmentTaskProducts.js
packages/api/src/models/cleaningTaskModel.js
packages/api/src/models/irrigationTaskModel.js
packages/api/src/models/pestControlTask.js
packages/api/src/models/productModel.js
packages/api/src/models/soilAmendmentFertiliserTypeModel.js
packages/api/src/models/soilAmendmentMethodModel.js
packages/api/src/models/soilAmendmentProductModel.js
packages/api/src/models/soilAmendmentPurposeModel.js
packages/api/src/models/soilAmendmentTaskModel.js
packages/api/src/models/soilAmendmentTaskProductPurposeRelationshipModel.js
packages/api/src/models/soilAmendmentTaskProductsModel.js
packages/api/src/util/copyCropPlan.js
packages/api/tests/mock.factories.js
packages/api/tests/organicCertifierSurvey.test.js
packages/api/tests/product.test.js
packages/api/tests/task.test.js
packages/api/tests/testEnvironment.js

There have been updated requirements to the soil amendment task.
This reflects those changes
Completed:
- Migrations
TODO
- Everything else
Jira link: [LF-4216](https://lite-farm.atlassian.net/browse/LF-4216)
**Checklist:**
[LF-4216]: https://lite-farm.atlassian.net/browse/LF-4216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4216 - updated requirements

---

packages/webapp/src/components/Navigation/styles.module.scss

The top bar of the application didn't stay at the top of the screen after scrolling.
Jira link: https://lite-farm.atlassian.net/browse/LF-4222
**Checklist:**

LF-4222: Fix sticky top bar

---

packages/webapp/src/containers/saga.js
packages/webapp/src/containers/userFarmSlice.ts
packages/webapp/src/routes/index.jsx

Check `has_consent` and `consent_version` in `getUserFarmsSuccess` and override `has_consent` before storing in the Redux store.

LF-4256 (2): Old consent version is shown after setting has consent to false

---

packages/webapp/public/locales/es/translation.json

This change adds the "Missing" tag in the Spanish Language to the filters.
Jira link:https://lite-farm.atlassian.net/browse/LF-4252
**Checklist:**

LF-4252 This change adds the MISSING tag in the Spanish language

---

packages/webapp/src/components/Finances/AddExpense/ExpenseItemInputs.jsx
packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
packages/webapp/src/components/Finances/AddExpense/styles.module.scss

The _Add another item_ button disappeared when the user removed the last expense item from a selected expense type and reloaded the page.
The aforementioned UI issue is tackled with the new design for [the new expense items page](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=91-13211&t=hv5MLnMbMYzxTWFg-0), which requires some changes regarding the _Remove item_ button:
In the new design, expense items will have the _Remove item_ button **only if there are two or more** items in the expense type they belong to. Therefore, users won't be able to remove the last item per expense type, which prevents the _Add another item_ button from disappearing. To remove the last item, users will have to unselect the expense type in the previous page:
Jira …

LF-4212: Fix "Add another (expense) item" button and adapt it to the new design

---

packages/api/db/migration/20240504185218_create_soil_amendement_task_products_table.js

There is a check requiring `all null OR all not null` on quantity types volume and weight.
This sets null when quantity value does not exist. Only cases on prod where this might be true are initial task migrations mentioned in[ LF-4246 ](https://lite-farm.atlassian.net/browse/LF-4246)
EDIT Also: 
- Some record could not being inserted correctly in theory without product_quantity. I assumed defaultTo == notNullable which is not the case.
- Some records were not being rolled back correctly. Anything without product_quantity would lose other properties. On prod all without product_quantity are empty records, but I should still handle this case.
Error from docker log litefarm-api:
Jira link:
Please describe the tests that you …

LF-4216 - Add case to insert null values when quantity does not exist

---

packages/api/db/migration/20240504185218_create_soil_amendement_task_products_table.js
packages/api/src/middleware/validation/checkSoilAmendmentTaskProducts.js

Removes purpose check in favour of moving forward Soil Health V1
Jira link: 
**Checklist:**

LF-4216 - remove purpose check for future see LF-4246

---

packages/webapp/.storybook/preview.jsx
packages/webapp/src/assets/colors.scss
packages/webapp/src/components/Form/Switch/index.tsx
packages/webapp/src/components/Form/Switch/styles.module.scss
packages/webapp/src/stories/Form/Switch/Switch.stories.jsx

This PR updates the existing switch (`packages/webapp/src/components/Form/Switch/index.jsx`) to the new switch. Specifically, it:
- converts the component to typescript
- updates the default (on/off) switch to the [new styles specified in Figma](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=2674-72350&m=dev)
- (Needed for weight/volume): adds left-right toggle and disabled variants and the option to supply a left-hand label
- updates the [Storybook stories](http://localhost:6006/?path=/docs/components-switch--docs)
Misc notes:
- I also briefly looked into the [MUI React Switch](https://mui.com/material-ui/react-switch/) but rejected it for our purposes because
1. our base switch component was already quite clean and readable,
2. MUI was …

LF-4230 Create a switch component

---

packages/webapp/src/containers/Finances/TransactionFilter/index.jsx

No results were shown on the "Finances" page when the user tries to "Clear" all the previously selected filters.
Jira link: https://lite-farm.atlassian.net/browse/LF-4238
**Checklist:**

LF-4238: Fix cleared filters on the Finances page

---

packages/api/package-lock.json
packages/api/package.json

Based on dependabot update, package is not a primary dependency. Email still works fine locally.
Jira link:[#3215 ]( https://github.com/LiteFarmOrg/LiteFarm/pull/3215 )
**Checklist:**

Remove pug dependabot

---

.github/workflows/crowdin-upload.yml

add workflow dispatch

---

.github/workflows/crowdin-upload.yml

adjust source pattern

---

.github/workflows/crowdin-upload.yml

adjust souce and translation path

---

.github/workflows/crowdin-download.yml

no config file setup download

---

.github/workflows/crowdin-download.yml

This adds options to remove unapproved and untranslated files in the download action.
Jira link:
**Checklist:**

crowdin - add options to reduce unwanted translations

---

.github/workflows/crowdin-download.yml

Options for skipping cant be combined
Jira link:
**Checklist:**

crowdin - remove option that cant be combined

---

.github/workflows/crowdin-download.yml

Switch option based on results.
Jira link:
**Checklist:**

crowdin switch option

---

.github/workflows/crowdin-download.yml

crowdin revert setting change

---

.github/workflows/crowdin-upload.yml

This adds to the upload action the remaining sources and translations. Also attempts options to auto approve initial inport and allow key == string or source == translation.
Jira link:
**Checklist:**

crowdin - add remaining source and translations

---

.github/workflows/crowdin-upload.yml

Sytax error
Jira link:
**Checklist:**

crowdin sytax error

---

.github/workflows/crowdin-upload.yml

Typo forgot to copy details
Jira link:
**Checklist:**

crowdin typo

---

.github/workflows/crowdin-upload.yml

crowdin action matrix syntax error

---

.github/workflows/crowdin-upload.yml

preserve hierarchy ignore pdf
Jira link:
**Checklist:**

crowdin preserve hierarchy, ignore pdf

---

packages/webapp/public/locales/en/animal.json

delete angus test
Jira link:
**Checklist:**

crowdin test delete angus

---

.github/workflows/crowdin-download.yml
.github/workflows/crowdin-upload.yml
packages/webapp/public/locales/en/animal.json

Now that initial translations are in we do not need to auto approve them. This PR reverts the test action that removes ANGUS. 
Test was for case where we revert integration to select only specific commits for release. Test action resulted in ANGUS being deleted, and edited translation in UI being overwritten. 
Future tests include trying the same thing again now that auto approvals are done.
Jira link:
**Checklist:**

Crowdin GitHub action

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

These are the translation strings required by the quantity/application rate portion of the new soil amendment task, cherry-picked from the feature branch so translation can begin ASAP.
The base branch is `integration` (as it has been for all the soil amendment tickets we have done so far) @SayakaOno if I should create a new PR based off of `main` or the patch branch instead please let me know.
Jira link: https://lite-farm.atlassian.net/browse/LF-4249
**Checklist:**

LF-4249 Translation strings for Create QuantityApplicationRate component

---

.github/workflows/crowdin-download.yml
.github/workflows/crowdin-upload.yml

This PR does the following:
- updates the upload action to allow specifying the feature branch name (issue was that some github env variables are only populated when a push action is done versus a workflow dispatch, and that the examples for the crowdin github action were missing details)
- updates the download action to create a branch based on the feature branch name
- attempts to get the correct syntax for github push actions
Otherwise, I think this will do what we want of it with exception to:
- MISSING strings
- Other normalization string changes
I have cleared the crowdin translations waiting for this PR's approval because of the line "make sure to upload master first as all others will be considered feature branches". 
Jira link: …

LF-4276 - crowdin extras

---

packages/webapp/public/locales/en/translation.json

I'm sorry 🙇  I missed a word in one of the strings of my previous PR:
- #3265 
Jira link: https://lite-farm.atlassian.net/browse/LF-4249
**Checklist:**

LF-4249 Amend translation string

---

.github/workflows/crowdin-download.yml
.github/workflows/crowdin-upload.yml

Adds a new github action.
Jira link:
**Checklist:**

LF-4276 - checkout new action files to main

---

.github/workflows/crowdin-upload.yml

Update `crowdin-upload.yml` to set `upload_translations` to `false`.

CrowdIn set upload_translations to false

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/main.jsx

Update version numbers to `3.6.4.1`

Bump version numbers

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/containers/saga.js
packages/webapp/src/main.jsx

Hotfix 3.6.4.1
- https://github.com/LiteFarmOrg/LiteFarm/pull/3279

Hotfix 3.6.4.1

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json

Add missing translations for LF-4221. Sorry...
Jira link: https://lite-farm.atlassian.net/browse/LF-4221

LF-4221 (0-2): Add more translations for application method

---

packages/webapp/src/apiConfig.js
packages/webapp/src/containers/hooks/useCurrencySymbol.js
packages/webapp/src/containers/saga.js
packages/webapp/src/containers/userFarmSlice.ts
packages/webapp/src/store/api/apiSlice.ts
packages/webapp/src/store/reducer.js
packages/webapp/src/store/store.ts

Include animals unrelated code from https://github.com/LiteFarmOrg/LiteFarm/pull/3122. (RTK query setup)
Jira link: https://lite-farm.atlassian.net/browse/LF-4291
**Checklist:**

LF-4291: Cherry pick RTK query setup code unrelated to animals

---

packages/api/src/controllers/organicCertifierSurveyController.js
packages/api/src/jobs/certification/record_i_generation.js
packages/api/src/jobs/locales/en/translation.json
packages/api/src/jobs/locales/es/translation.json
packages/api/src/jobs/locales/fr/translation.json
packages/api/src/jobs/locales/pt/translation.json
packages/api/tests/organicCertifierSurvey.test.js

- Unskipped tests
- Queries updated with `volume` and `weight` ( deprecated `product_quantity`)
- Translations for export updated
Jira link: https://lite-farm.atlassian.net/browse/LF-4225
**Checklist:**

LF-4225 Fix for certification document export process

---

packages/api/src/controllers/taskController.js

Type Ids are the definitive test for if the task is of a type. Soil amendment task details may not be present due to legacy migrations.  See [LF-4299](https://lite-farm.atlassian.net/browse/LF-4299) for corrective action on that  
Jira link:
**Checklist:**
[LF-4299]: https://lite-farm.atlassian.net/browse/LF-4299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4221js - add type id to check instead of task details existence

---

packages/api/tests/task.test.js

Fixes test failure.
Jira link:
**Checklist:**

LF-4221js - add insertion for test and controller

---

packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/containers/Task/TaskLocations/index.jsx
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/util/task.ts

Bugs fixed for :
- furrow hole depth persisted from form after changing method selection away from FURROW_HOLE
- TRANSLATION KEY ALERT! - selecting a location that is not crop based - (Note made on [LF-4301](https://lite-farm.atlassian.net/browse/LF-4301) to investigate if any sensors or barns have soil amendment tasks)
Jira link:
**Checklist:**
[LF-4301]: https://lite-farm.atlassian.net/browse/LF-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4221_2 - fixing bugs 

---

packages/api/db/migration/20240703142448_data-migration-and-add-constraints-to-soil-amendment-task-and-relations.js
packages/api/src/controllers/taskController.js

TODO:
The choice was made to delay the implementation of https://lite-farm.atlassian.net/browse/LF-4246 .
This covers some other small migrations that were going to be handled as part of that.
- add constraints to disallow negative numbers
- handle existing negative numbers on soil_amendment_task
- ~~rename tables to the singular form instead of plural (most file changes are this)~~
- add uniqueness constraint on soil_amendment_task_product to prevent duplicate (product_id, task_id)
- add not null constraint on product table for column ‘type’
- repair created_by and and created_at on soil_amendment_task_product
Jira link:
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …

Lf 4286 cherrypick address minor changes

---

.github/workflows/crowdin-download.yml

This downloads all data sources matching the upload pattern.
Jira link:
**Checklist:**

crowdin - update download to include all sources

---

packages/api/src/controllers/baseController.js

Will add to it if I find more :) Right now it's only
- Copy over missing `removeAdditionalPropertiesWithRelations` from integration. It was added in this animal ticket commit: d55438851cb9dffd2ee28922e22eba0487d09eca
**Checklist:**

Fixes for Patch 3.6.5

---

.github/workflows/crowdin-download.yml

Makes a pr for each locales section since it force pushes first commit.
Benefit of choosing which to keep/not merge.
Jira link:
**Checklist:**

Crowdin update download function for all sources

---

packages/webapp/src/containers/Task/TaskComplete/StepOne.jsx
packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/productSlice.js

Fixes task type error shown in a few areas around app.
Jira link: [LF-4304](https://lite-farm.atlassian.net/browse/LF-4304)
Only area I could test was in notifications, @kathyavini if you can test your task with the deleted error that would be swell!
**Checklist:**
[LF-4304]: https://lite-farm.atlassian.net/browse/LF-4304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4304 deleting a soil amendment task throws an error page

---

packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
packages/webapp/src/components/Task/AddSoilAmendmentProducts/index.tsx
packages/webapp/src/components/Task/SoilAmendmentTask/index.tsx
packages/webapp/src/containers/Task/saga.js

The cause of the strange behaviour was that `fields` returned from `useFieldArray` is updated every time any change is made on the product form inputs. This triggers re-render on `ProductCard`. The problematic was the `useEffect` in `ProductDetails`, which is supposed to be called when a new product is selected or the product is created or updated. Because of the re-render of `ProductCard`, `products` in the dependency array was updated every time any field is updated, triggering the useEffect unexpectedly.
The solution:
Replace `products` (object) in the dependency array to `productsVersion` (number) so that the useEffect is called only when productId is updated or a product is created or updated.
Changes:
- Call `setProductsVersion` when the product form is submitted.
- …

LF-4315: Magnetic supplier input field

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/main.jsx
packages/webapp/src/util/constants.js

Update version number

---

.github/workflows/crowdin-download.yml
.github/workflows/crowdin-upload.yml

Just tested
- #3343 
against integration, dispatching upload with the new dispatch inputs toggled into all their variations and it works PERFECTLY! 👌 Mostly we can use it with neither checkbox checked and it will continue to work as it has before, but when we want to update our base branch `main` we can check both.
(And the third option, uploading without auto-approving might even have its uses too if we ever add some content via PR instead of CrowdIn...)
Jira link: https://lite-farm.atlassian.net/browse/LF-4349
**Checklist:**

LF-4349 (PR against main) Finish CrowdIn setup to support the addition of new languages

---

packages/webapp/src/components/CertificationSurvey/RegisteredCertifierQuestions/index.jsx

Requires new env variable on BETA. (added to frontend .env)
This updates the URL of the iframe for surveystack to the 'staging' endpoint. It will need to be changed to 'app' once the new endpoint is live.
Jira link:[LF-4353](https://lite-farm.atlassian.net/browse/LF-4353)
[LF-4344 (original jira ticket)](https://lite-farm.atlassian.net/browse/LF-4344)
**Checklist:**
[LF-4353]: https://lite-farm.atlassian.net/browse/LF-4353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4353 surveystack integration link deprecation

---

packages/api/src/jobs/certification/pdf.js
packages/api/src/jobs/certification/survey_record.js

This adds the staging links to api also to make the completion flow work.
Locally, export now completes successfully.
Originally and without indication these links existed the assumption was only the new iframe link was necessary to test.
Jira link: [LF-4353](https://lite-farm.atlassian.net/browse/LF-4353)
**Checklist:**
[LF-4353]: https://lite-farm.atlassian.net/browse/LF-4353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4353 - add staging to api links also

---

packages/end-to-end/cypress/support/selectorConstants.ts
packages/webapp/src/components/OrganicCertifierSurvey/CertificationSelection/PureCertificationSelection.jsx

Thank you Duncan for the [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3357#discussion_r1699095164) in https://github.com/LiteFarmOrg/LiteFarm/pull/3357. That's what I initially wanted to do, but it didn't work for my first solution and was forgotten!

LF-4354 (2): Update data-cy for certification types

---

packages/webapp/src/components/Form/ReactSelect/CreatableSelect.tsx
packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx

I added validation of trimmed value length for the required field Supplier. This will fix the issue on this form only, but theoretically, we can add this check on all `required` validation options.
Jira link: https://lite-farm.atlassian.net/browse/LF-4339 
**Checklist:**

LF-4339: Create product form validation

---

packages/webapp/src/containers/Animals/AddAnimals/AddAnimalBasics/useUpdateBasics.ts
packages/webapp/src/containers/Animals/AddAnimals/types.ts

Fix field names for the animal details form.
**Checklist:**

LF-4164 Fix DetailsField names

---

packages/api/src/controllers/animalBatchController.js
packages/api/src/controllers/animalController.js
packages/api/src/middleware/validation/checkAnimalOrBatch.js
packages/api/src/routes/animalBatchRoute.js
packages/api/src/routes/animalRoute.js
packages/api/tests/animal.test.js
packages/api/tests/animal_batch.test.js
packages/webapp/src/apiConfig.js
packages/webapp/src/store/api/apiSlice.ts

Essentially renames the current edit endpoint to remove endpoint.
Consolidates body checks into middleware for animals and batches.
Adds a check for both removal and removal date -- database check makes sure both exist if only one provided. Otherwise both equal null would be valid.
Notes: 
- really disliked removing `trx` from checks -- made this jira ticket:  [LF - 4391](https://lite-farm.atlassian.net/browse/LF-4391)
- check if req.body is an array is currently duplicated on this endpoint (not ideal not bad) - considered making a 'util' like validation middleware that would be used on routes to specify that the endpoint accepts an array on the route itself. Should I do this? It would be a new pattern moving forward:
```
router.patch(
'/remove', …
```

Lf 4379 api route for remove add new route for remove animals and batches

---

packages/webapp/src/components/Animals/AddAnimalsSummaryCard/styles.module.scss
packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts

Address Duncan's [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3397#pullrequestreview-2270361189) in #3397.  There might be better solutions and it might require adjustments. Please feel free to update or close as needed. Thank you! 🙏 
- Filter out animal uses that are not for the currently selected animal type when coming back to the details view.
- Adjust summary image width (The image might look too small at some breatkpoints.)
Jira link: N/A
**Checklist:**

Add animal fixes

---

packages/webapp/src/components/CropCatalogue/CropStatusInfoBox/index.jsx
packages/webapp/src/components/MonthCalendar/index.jsx
packages/webapp/src/components/RepeatCropPlan/index.jsx
packages/webapp/src/components/RepeatCropPlan/utils.js
packages/webapp/src/containers/Documents/index.jsx
packages/webapp/src/util/moment.js

_**Please see Jira ticket [LF-4428 Never translated string on crop flow creation](https://lite-farm.atlassian.net/browse/LF-4428) for a visual table showing where in the app we will now start seeing localized date strings.**_
(LF-4428 is the bug ticket related to this issue, but the underlying cause is as I described in the comment of [LF-4421](https://lite-farm.atlassian.net/browse/LF-4421))
**BACKGROUND/EXPLANATION**
Our codebase used `moment(date).locale()` in several places. I'm not sure how we missed that it never worked. In order to use `moment(date).locale()` you need to import the locales, for instance like this
```js
import moment from 'moment/min/moment-with-locales';
```
(The [moment.js docs](https://momentjs.com/docs/#/i18n/loading-into-nodejs/) also describe …

LF-4221 investigate moment date locale and modify if necessary

---

packages/api/src/jobs/notifications/notifyAllUsers.sql

This is a utility function stored for manual sql use. No other file references it based on repo search. Added a further comment in the off chance it is not wholly deleted at some point.
```
-- This SQL is never executed by LiteFarm app or server code.
-- It is intended for manual use in order to send a notification to all users.
-- It could be modified to send to any arbitrary set of users.
- The syntax of this "comment" is intentionally incorrect, to prevent running this file as a script.
-- You should run the statements individually, modifying as you go.
```
Jira link: [LF-4420](https://lite-farm.atlassian.net/browse/LF-4420)
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

Lf 4420 investigate notify all users sql and modify if necessary

---

packages/api/dev.export.sh
packages/api/package.json
packages/api/src/jobs/locales/de/translation.json

Updates copying of crop translations source files. Fixes german string in code (will also fix in crowdin) 
Jira link:[LF-4439](https://lite-farm.atlassian.net/browse/LF-4439)
**Checklist:**
[LF-4439]: https://lite-farm.atlassian.net/browse/LF-4439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4439 the record d is not send to the user if the lite farm language is set up to german

---

packages/api/src/controllers/sensorController.js

Instead of error, default to english. 
(forgot to pass res to function anyways!)
Jira link:
**Checklist:**

Lf 4402 translate sensor csv js into new languages

---

.github/workflows/automated_tests.yml

@kathyavini  -- wondering if you are down to test this fix of updating node on actions! It would need to be done at some point anyways.
I do not believe I am seeing this bug locally when I run tests -- its hard to tell because I am seeing the tests run into memory issues again due to the time it takes to complete of our tests. But in the ones that complete and fail I couldn't see the specific error.
Jira link: [LF-4451](https://lite-farm.atlassian.net/browse/LF-4451)
**Checklist:**
[LF-4451]: https://lite-farm.atlassian.net/browse/LF-4451?atlOrigin=eyJpIjoiN …

LF-4451 Update node version to match nvmrc for backend

---

packages/api/babel.config.cjs

I guess I lied when I said I couldn't find the option – I now see the plugin so plainly – its as if I didn't look because I just thought I tried already sorry 😓 .
Tested on main branch and saw the test failing -- this option now has tests passing and was already installed a few years ago but not set as a plugin.
Jira link: [LF-4451](https://lite-farm.atlassian.net/browse/LF-4451)
**Checklist:**
[LF-4451]: https://lite-farm.atlassian.net/browse/LF-4451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4451 Add plugin for assertions to babel config

---

packages/webapp/src/components/CreateUserAccount/index.jsx
packages/webapp/src/components/InviteUser/index.jsx
packages/webapp/src/components/InvitedUserCreateAccount/index.jsx
packages/webapp/src/components/Profile/Account/index.jsx
packages/webapp/src/components/Profile/EditUser/index.jsx
packages/webapp/src/hooks/useGenderOptions.jsx

Just addressing @antsgar's comments from this PR:
- https://github.com/LiteFarmOrg/LiteFarm/pull/3442#issuecomment-2354080545
that weren't addressed at that time due to mini code freeze before yesterday's release.
Jira link: https://lite-farm.atlassian.net/browse/LF-4450
**Checklist:**

LF-4450 Clean up getGenderOptions refactor

---

packages/webapp/src/containers/GoogleLoginButton/saga.js

This fix checks the i18n language and the user language and align i18n as necessary.
Jira link: [LF-4455](https://lite-farm.atlassian.net/browse/LF-4455)
**Checklist:**
[LF-4455]: https://lite-farm.atlassian.net/browse/LF-4455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4455 on sso login language matches browser language not litefarm user language preference

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/main.jsx

Updates version numbers to 3.6.8. 
Based on : https://github.com/LiteFarmOrg/LiteFarm/pull/3450/files
Jira link: 
**Checklist:**

Bump version number to 3.6.8

---

packages/api/db/migration/20241108052304_update_animal_union_batch_internal_id_view.js
packages/api/db/sql/20241108052304_animal_union_batch_id_view.sql
packages/api/tests/animal_union_batch.test.js

Previously, animals/batches' `internal_identifier` was determined solely based on `created_at`. When `created_at` values were identical, animals and batches sometimes received different `internal_identifier` values upon regenerating the view.
This update assigns `internal_identifier` based on `created_at`, `id`, and `batch`, ensuring consistency.
- Add migration to recreate `animal_union_batch_id_view` for stable `internal_identifier`.
- Add a test. (In the test, the view is regenerated 10 times to ensure the test almost always fails with the original view)
The original migration and SQL can be found here ([PR](https://github.com/LiteFarmOrg/LiteFarm/pull/3125)):
- [migration](https://github.com/LiteFarmOrg/LiteFarm/blob/747f76be208ab40fd8bdb42390b0368b583b1fad/packages/api …

LF-4523: Animals internal identifier changes after data updates

---

packages/webapp/public/locales/de/translation.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/hi/translation.json
packages/webapp/public/locales/ml/translation.json
packages/webapp/public/locales/pa/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/containers/Task/TaskLocations/index.jsx
packages/webapp/src/containers/locationSlice.js

Adds the animal task locations slice and component. (closed my other PR because I messed up and committed to that branch by accident)
Jira link:[LF-4477](https://lite-farm.atlassian.net/browse/LF-4477)
**Checklist:**
[LF-4477]: https://lite-farm.atlassian.net/browse/LF-4477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4477 update task locations to account for animal movement task c

---

packages/webapp/src/containers/Animals/Inventory/index.tsx

LF-4483 refactor proposal for inventory container

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Form/Checkbox/checkbox.module.scss
packages/webapp/src/components/Form/Switch/index.tsx
packages/webapp/src/components/Form/Switch/styles.module.scss
packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
packages/webapp/src/components/LocationPicker/SingleLocationPicker/styles.module.scss
packages/webapp/src/components/Task/TaskLocations/index.jsx
packages/webapp/src/components/Task/TaskLocations/styles.module.scss
packages/webapp/src/containers/Task/TaskLocations/index.jsx
packages/webapp/src/containers/Task/useIsTaskType.js

Add the explicit option to not select a location. 
Notes:
- Won't be visible in task list yet.
- Any other ideas for disabling map? It almost _feels_ like it should re-center when disabled if zoomed in... but I don't actually want that because it is inconvenient zooming in (I have worldwide sensors on my farm)
- No stories exist for LocationPicker
Jira link: [LF-4556](https://lite-farm.atlassian.net/browse/LF-4556)
- custom task allows completion without location
**Checklist:**
[LF-4556]: https://lite-farm.atlassian.net/browse/LF-4556?atlOrigin=eyJpIjoiNWRkN …

Lf 4556 update location selection validation to allow zero locations using new checkbox flow

---

packages/webapp/src/stories/Form/Switch/Switch.stories.jsx

Forgot to push this little update I did for the switch stories
Jira link:
**Checklist:**

LF-4556 Add switch stories

---

packages/webapp/src/containers/Task/saga.js

Invalidate animal tags when movement task is completed. This will update animals' location immediately on the inventory/animal details view.

Invalidate animal tags when movement task is completed

---

packages/api/src/controllers/taskController.js
packages/api/src/middleware/validation/checkTask.js
packages/api/src/routes/taskRoute.js
packages/api/src/util/task.js
packages/api/tests/animalTask.test.js
packages/api/tests/task.test.js

The major changes are to:
- apply the same checks for animal tasks to custom tasks in POST and PATCH `/patch_due_date`.
- enable custom tasks completion while removing all animals/batches from the task.
============
- GET
- add tests
- POST
- Add validation to avoid `animals` and `animal_batches` to be sent from the client (this should be moved to the middleware in the future). Without this, animals/batches can be added to any tasks. (this will also be run for the completion API)
- PATCH
- complete
- Move the validations for missing animals/batches and invalid `complete_date` to the middleware (`checkAnimalCompleteTask`).
- Update `upsertGraph` options to relate/unrelate `animals` and `animal_batches`. (This shouldn't affect other task types that won't have animals or …

LF-4542: Allow custom task to have related animal ids on the backend

---

packages/webapp/public/locales/de/translation.json
packages/webapp/public/locales/en/translation.json
packages/webapp/public/locales/es/translation.json
packages/webapp/public/locales/fr/translation.json
packages/webapp/public/locales/hi/translation.json
packages/webapp/public/locales/pa/translation.json
packages/webapp/public/locales/pt/translation.json
packages/webapp/src/components/Task/PureTaskAssignment/index.jsx
packages/webapp/src/components/Task/PureTaskCrops/index.jsx
packages/webapp/src/components/Task/PureTaskDetails/index.jsx
packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
packages/webapp/src/components/Task/TaskDate/index.jsx
packages/webapp/src/components/Task/TaskLocations/index.jsx
packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
packages/webapp/src/containers/Animals/Inventory/useAnimalsExist.tsx
packages/webapp/src/containers/Task/TaskAnimalInventory/index.jsx
packages/webapp/src/containers/Task/TaskAssignment/index.jsx
packages/webapp/src/containers/Task/TaskCrops/index.jsx
packages/webapp/src/containers/Task/TaskDate/index.jsx
packages/webapp/src/containers/Task/TaskLocations/index.jsx
packages/webapp/src/containers/Task/constants.js
packages/webapp/src/containers/Task/util.js

Adds animal inventory selection to the custom task flow.
Notes: Custom task will stop working until backend is completed due to extra property `animalIds`
Jira link: [LF-4541](https://lite-farm.atlassian.net/browse/LF-4541)
**Checklist:**
[LF-4541]: https://lite-farm.atlassian.net/browse/LF-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4541 add animal inventory to custom task

---

packages/webapp/src/containers/Animals/Inventory/useAnimalOrBatchRemoval.ts

Fixed the id check by parsing id.
Jira link:
**Checklist:**

Parse id for check

---

packages/webapp/src/components/ActionMenu/index.tsx
packages/webapp/src/components/Animals/Inventory/index.tsx
packages/webapp/src/containers/Animals/Inventory/index.tsx
packages/webapp/src/stories/ActionMenu/ActionMenu.stories.tsx

Unless alternate solution decided - this now shows the action menu and animal select option for workers. But it hides the remove animals option.
Jira link:
**Checklist:**

Show action menu for worker

---

packages/webapp/src/containers/Animals/Inventory/useFilteredInventory.ts

Fix sex filter on animal inventory. It was only broken for batches, only missing the check for the count on each sex detail item on the batch (if the count was 0 it was still matching).
Jira link:
https://lite-farm.atlassian.net/browse/LF-4568
**Checklist:**

LF-4568 fix sex filter

---

packages/webapp/src/components/Task/MovementTask/index.tsx
packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
packages/webapp/src/util/task.ts

This PR solves the two form persistence / reset bugs from movement task completion
- LF-4592 the form data not resetting when "need changes" is toggled to false
- this has been addressed with the purpose-setting useEffect running upon toggle 
- LF-4587 the purposes not persisting when navigating to final page and back
- this was due to the database task formatting function also being run on persistedFormData (which is already in form format)
- I have added a type guard to not reformat already task-formatted data, which is also a better solution for a crash I had previously solved by mixing database types into the form types, to keep the function from crashing! Not running the formatting at all is a better solution I think
The code solutions are completely unrelated; I just …

LF-4592, LF-4587 Animal movement purpose form persistence and reset bugs

---

packages/webapp/src/components/Task/TaskComplete/index.jsx
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/util/siteMapConstants.ts

This was a `hookFormPersistReducer` bug that was specific to directing to the `/complete` part of the task complete flow (non-custom tasks direct to `/before_complete` when the "This task has already been completed checkbox" is selected).
The persistedFormData was being cleared -- probably, based merely on what fixed it -- due to a URL change off of a persisted path. There is a useEffect that updates persisted paths  in `/before_complete` that I tried replicating in `/complete` that did not fix the issue; I think to use with the setting of formData in the saga, I guess the paths should be enqueued before that?
PR additionally
- routes the "already completed" custom task to `/before_complete` if animals are present, so they can be adjusted (mirroring the normal complete …

LF-4551 App crashes if trying to complete a custom task via the "task has already been completed" flow

---

packages/webapp/public/locales/en/translation.json

This is the copy we discussed during the bug bash table review, and has been approved by Loïc.
Jira link: https://lite-farm.atlassian.net/browse/LF-4573
**Checklist:**

LF-4573 The message “These animals will be archived and accessible for future reference” is displayed when removing animals

---

packages/webapp/src/components/Task/MovementTask/styles.module.scss

The notes field was overlaying the Clear All in creation (no notes field in complete, therefore no such error). Error probably was present during bash too; I don't think code changes since then would have impacted 🤔 
Jira link: https://lite-farm.atlassian.net/browse/LF-4615
**Checklist:**

LF-4615 No actions are triggered once the user clicks on the "Clear All" button during the creation of the "Movement" task

---

packages/webapp/src/components/Table/TableV2.jsx

Moves the onclick handler up one.. easier than I thought it could be.
Jira link: [LF-4612](https://lite-farm.atlassian.net/browse/LF-4612)
**Checklist:**
[LF-4612]: https://lite-farm.atlassian.net/browse/LF-4612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4612 Move onclick handler up one in hierarchy

---

packages/webapp/src/components/Animals/AnimalSingleViewHeader/styles.module.scss
packages/webapp/src/components/Form/ReactSelect/styles.ts

- Remove white background from location in individual animal view.
- Totally unrelated bonus that was bugging me: Fix styling for remove button on pills on the multiselect component.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4610
**Checklist:**

LF-4610 fix location styling

---

packages/webapp/src/containers/Animals/AnimalsFilter/index.tsx

The `tempAnimalsFilter` was not being updated when the filters were cleared from outside the filter modal and retained its previous value.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4593
**Checklist:**

LF-4593 fix animals filter

---

packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx

Thanks @kathyavini !
Jira link: @den4ik1203  There was no ticket made for this one correct?
**Checklist:**

Fix console error using Joyce's solution

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Modals/NoAnimalLocationsModal/index.jsx

LF-4611 Update translation key

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Modals/NoAnimalLocationsModal/index.jsx
packages/webapp/src/components/Modals/NoAnimalLocationsModal/styles.module.scss
packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
packages/webapp/src/containers/Task/TaskTypeSelection/index.jsx
packages/webapp/src/containers/locationSlice.js

Adds a modal that prevents movement task creation without animal locations.
Jira link:[ LF-4611](https://lite-farm.atlassian.net/browse/LF-4611)
**Checklist:**

LF-4611 Add no animal locations modal

---

packages/webapp/src/components/Table/Cell/CellTypes/IconText.tsx
packages/webapp/src/components/Table/TableV2.jsx
packages/webapp/src/components/Table/styles.module.scss
packages/webapp/src/containers/Animals/Inventory/index.tsx
packages/webapp/src/containers/Animals/Inventory/styles.module.scss

Adjust margin using cell className

LF-4612c (2): Adjust margin with cell className

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Navigation/useSectionHeaders.tsx
packages/webapp/src/containers/Animals/AddAnimals/index.tsx

Add animals - only keep one of this or other
Jira link:
**Checklist:**

Fix beta badge keep title

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/containers/Animals/AddAnimals/index.tsx

Animal Inventory - only keep one of this or other
Jira link:
**Checklist:**

Change add animals title

---

packages/webapp/src/components/Badge/styles.module.scss
packages/webapp/src/components/Navigation/useSectionHeaders.tsx

Fix beta badge styling.
Show badge on animal creation flow.
Jira link:
**Checklist:**

Fix beta badge

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/components/Navigation/useSectionHeaders.tsx
packages/webapp/src/containers/Animals/Inventory/AnimalsBetaSpotlight.jsx
packages/webapp/src/main.jsx
packages/webapp/src/util/constants.js

Update links for release notes and beta.
Update version number for release.
Jira link:
**Checklist:**

update webpage links and version number

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/main.jsx
packages/webapp/src/util/constants.js

Updates version numbers throughout app. Maintains `APP_VERSION` (release badge, automatic logout) at 3.7.0.
**Checklist:**

Patch 3.7.1 (Consent) Update version numbers

---

packages/webapp/src/containers/Consent/locales/es/Owner.Consent.md
packages/webapp/src/containers/Consent/locales/es/Worker.Consent.md

Per comment from @antsgar 
Jira link:
**Checklist:**

Consent  v7 - Correct grammer ES files

---

packages/webapp/src/containers/Help/index.jsx
packages/webapp/src/containers/Help/saga.js
packages/webapp/src/containers/Home/index.jsx

After submitting the feedback form the user was redirected to home page. After this fix user will remain on same page and will get confirmation popup. Also, made feedback self-contained component, containing both form and popup in same container.
Jira link: https://lite-farm.atlassian.net/browse/LF-4598
Submit the feedback form on any page. Confirmation popup is shown and user is not redirected to home page.
**Checklist:**

LF-4598 Removed redirection and made feedback from self-contained

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.js
packages/webapp/package.json
packages/webapp/src/main.jsx

Version 3.7.4 --> 3.7.5
**Checklist:**

Patch 3.7.5 / Update version numbers

---

.github/workflows/cypress_tests.yml

Bumps version of a action that will cause workflow failure after Jan 30.
lets see if it passes branch cypress checks 
Jira link:[LF-4681](https://lite-farm.atlassian.net/browse/LF-4681)
**Checklist:**
[LF-4681]: https://lite-farm.atlassian.net/browse/LF-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4681 bump version

---

packages/api/src/controllers/farmAddonController.js
packages/api/src/controllers/sensorController.js
packages/api/src/util/ensemble.js

Thank you so much @SayakaOno uncovering both of these issues!
Two fixes are in this PR:
1. I failed to spot a parameter that should have been deleted in the Ensemble API call refactor that will make your (first) call to Ensemble fail if you don't have valid access tokens in your `addon_partner` table. **Once the access tokens expired, this same error became [visible on beta as well](https://litefarm.sentry.io/issues/6260073802/?project=4505387020648448)**!
3. This bug highlighted that errors were not being propagated correctly to the controller from the Ensemble service calls. For the two new Ensemble endpoints, now in addition to the 404 from before (no organisations), there is the possibility of getting 500 errors if Ensemble auth fails or an otherwise non-specified …

LF-4690b Fix Ensemble API call bug on token refresh and return descriptive errors on API call failure

---

packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
packages/webapp/src/components/Expandable/useExpandableItem.ts

This PR has 2 parts:
1. I bumped the webapp TypeScript version to match the backend, which was set on ^5.6.2. This will have to be done at some point (frontend was on 4.9.5) so I figured might as well do it now and try to grab all the type errors -- although hopefully at this point they are exhausted!
2. Fixes for type errors that block `pnpm build` with a fresh `node_modules` install (pnpm-lock deleted / regenerated). There were only two files that needed to be touched for my build to complete
Jira link: https://lite-farm.atlassian.net/browse/LF-4718
Reinstalled `node_modules` as described above (without pnpm-lock). `tsc` passed in both pre-commit hook and pnpm build.
**Checklist:**

LF-4718 (2) Repair Deployment of Webapp

---

packages/api/package.json
packages/api/prod.Dockerfile

This PR moves the backend's tsc (`npm run build`) step into the Dockerfile (image creation).
What is happening now:
1. Backend image is built according to Dockerfile, and all assets (ts) are copied
2. `npm run start:prod` is run once the image is complete. This is supposed to run `tsc` and output js. The output js (server.js) is then run
3. `server.js` file can't be located, and the container crashes (see Jira ticket). I don't know if `/dist` was output because it's not part of the image and the container is crashed at this point so I can't `exec -it` it!
What I would like to do is run tsc within the Dockerfile so the `dist/` file is included in the image
It's a diagnostic change because I want to inspect the `/dist` folder using the built image, but there are also a few …

LF-4722 Backend container crashes due to missing server.js file

---

packages/api/src/controllers/farmAddonController.js
packages/api/src/middleware/acl/hasFarmAccess.js
packages/api/src/middleware/validation/checkFarmAddon.js
packages/api/src/models/farmAddonModel.js
packages/api/src/routes/farmAddonRoute.js

Creates a DELETE endpoint for `farm_addon` and aligns the resource lifecycle for a farm_addon based on discussion in Jira. Will add tests for all of `farm_addon` in a follow up PR. 
Notes:
- modifies `hasFarmAccess()` to check that a farm owns a resource when the table does not name it's `id` property with `${resource}_id` and instead uses plain `id` property.
- Updates GET to return `id` necessary for deletion.
- Updates POST to insert or return 409 if resource already exists
Jira link: [LF-4700](https://lite-farm.atlassian.net/browse/LF-4700)
- Add a …

Lf 4700 create delete endpoint for farm addon

---

.github/workflows/cypress_tests.yml

@Duncan-Brain it really was easier than disabling 😭 
Jira link: https://lite-farm.atlassian.net/browse/LF-4719
Ran workflow on branch successfully, [see run here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/13659786770/job/38188012563)
**Checklist:**

LF-4719 Update Cypress node version

---

packages/webapp/public/locales/en/translation.json

Add strings for:
- [Individual sensor readings](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=30658-138099&t=JGQdAFGxU3AgqfNW-0)
- [Sensor array readings](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=31103-218431&t=JGQdAFGxU3AgqfNW-0)
Jira link: https://lite-farm.atlassian.net/browse/LF-4756
**Checklist:**

LF-4756: Add all new strings related to sensor readings to integration

---

.github/workflows/chromatic.yml
.github/workflows/cypress_tests.yml
.github/workflows/lint_translation_files.yml
.github/workflows/webapp_unit_tests.yml
README.md
packages/webapp/.npmrc
packages/webapp/package.json
packages/webapp/pnpm-lock.yaml
packages/webapp/prod.Dockerfile
packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
packages/webapp/src/stories/Form/NumberInput/NumberInput.stories.tsx

This enforces the use of `pnpm@10.6.5` (the latest version of pnpm) throughout webapp. Thank you @antsgar for discovering the release of pnpm's own version management in pnpm v9.7.0!! Using pnpm's version management:
- the `engines` property has still been retained to make sure that the user is on at least v9.7.0 (so the other `packageManager` property can be utilized)
- `.npmrc` has been updated with a boolean that is necessary for version management if [on v9 pnpm](https://pnpm.io/9.x/npmrc#manage-package-manager-versions) -- if [on v10](https://pnpm.io/npmrc#manage-package-manager-versions) it will default to `true`
- readme has been updated to reflect new requirements
- github workflows pull this version from the package.json as well now, so we should only have to bump …

LF-4652 Fix pnpm to exact version

---

beta-export-deploy.sh

Just fixing up a GitHub actions workflow which has been broken since the TypeScript update. I'll add a note to the most recent release checklist that this `nvm install` / `nvm use` needs to be done on prod (=imaginary) as well.
Error is just on version not being installed: https://github.com/LiteFarmOrg/LiteFarm/actions/runs/14065824720
Jira link: https://lite-farm.atlassian.net/browse/LF-4724
**Checklist:**

LF-4724 Fix beta export server deploy

---

.github/workflows/chromatic.yml

Another quick fix for a GitHub action that has failed since TypeScript update. This one lacked the `container` specifier the other workflows contain:
https://github.com/LiteFarmOrg/LiteFarm/actions/runs/14065680120/job/39387428996
Jira link: https://lite-farm.atlassian.net/browse/LF-4779
Please test on deploy
**Checklist:**

LF-4779 Repair Chromatic GitHub action workflow

---

packages/webapp/src/components/LocationFieldTechnology/index.jsx
packages/webapp/src/components/LocationFieldTechnology/styles.module.scss
packages/webapp/src/components/ManageESciSection/index.tsx
packages/webapp/src/components/ManageESciSection/styles.module.scss

Extract `ManageESciSection` from `LocationFieldTechnology` to reuse in other components.
Thank you for the code, Duncan! 🙏 
Jira link: ([LF-4702](https://lite-farm.atlassian.net/browse/LF-4702))
**Checklist:**
[LF-4702]: https://lite-farm.atlassian.net/browse/LF-4702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4702: Extract manage ESci section

---

packages/api/package-lock.json
packages/api/package.json

This dependabot merge:
-  https://github.com/LiteFarmOrg/LiteFarm/pull/3734)
broke our API unit tests with this error:
```bash
Details:
/__w/LiteFarm/LiteFarm/packages/api/node_modules/axios/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import axios from './lib/axios.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module
```
You can see this error both on that branch's unit tests and now on other branches (e.g. runs [here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/14342341179/job/40204435284) and [here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/14362759008/job/40268385112)).
I have referred to [this StackOverflow](https://stackoverflow.com/a/74297004/15876096) for the solution. …

Fix API tests error after axios upgrade: cannot use import statement outside a module

---

packages/webapp/src/assets/colors.scss
packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionMapView.tsx
packages/webapp/src/components/IrrigationPrescription/constants.ts
packages/webapp/src/components/IrrigationPrescription/styles.module.scss
packages/webapp/src/components/LocationPicker/LocationViewer.tsx
packages/webapp/src/components/LocationPicker/SingleLocationPicker/drawLocations.js
packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.d.ts
packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
packages/webapp/src/components/LocationPicker/SingleLocationPicker/types.ts
packages/webapp/src/components/Task/TaskReadOnly/index.jsx
packages/webapp/src/containers/Map/constants.js
packages/webapp/src/containers/Map/mapStyles.js
packages/webapp/src/containers/Map/styles.module.scss
packages/webapp/src/stories/IrrigationPrescriptionMapView/IrrigationPrescriptionMapView.stories.tsx
packages/webapp/src/stories/IrrigationPrescriptionMapView/mockData.tsx
packages/webapp/src/stories/IrrigationPrescriptionMapView/styles.module.scss

This is the first part of displaying irrigation prescription details for the IP view and the task view. It renders a pivot with radius based on a centerpoint (`lat`/`lng`) and radius. It also renders the underlying field [as in Figma here](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=32620-88255&m=dev) and irrigation zones [as in Figma here](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=31428-78859&m=dev).
Please see [Component Storybook here](http://localhost:6006/?path=/docs/components-irrigationprescriptionmapview--docs)
- Ability to draw a circle. This is included in the Google maps asset geometry but we hadn't used it yet
- Ability to overwrite several style properties by passing them in the location …

LF-4768 Display IP Detail (1) / Display IP on Map

---

.github/workflows/chromatic.yml
packages/webapp/package.json
packages/webapp/pnpm-lock.yaml

attempt to fix chromatic workflow

---

packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
packages/webapp/src/containers/IrrigationPrescription/useApproveIrrigationPrescription.ts
packages/webapp/src/containers/irrigationTaskTypesSlice.js
packages/webapp/src/containers/taskTypeSlice.js
packages/webapp/src/stories/Form/Unit/SystemUnmatch.stories.jsx
packages/webapp/src/stories/Pages/Task/TaskDetail/TaskDetail.stories.jsx
packages/webapp/src/stories/Pages/Tasks/CleaningTaskReadOnly.stories.jsx
packages/webapp/src/stories/Pages/Tasks/IrrigationTaskReadOnly.stories.jsx
packages/webapp/src/tests/convertUnits.test.js
packages/webapp/src/util/convert-units/unit.js
packages/webapp/src/util/siteMapConstants.ts

This is the first PR for LF-4770. It introduces a hook that returns a function to be called when the "Approve" button is clicked. The actual button and task creation logic will be added in the next PR.
- Add a temporary hook `useApproveIrrigationPrescription`
- This will eventually be used in the `IrrigationPrescription` container. For now, the irrigation prescription data is hard-coded and will be updated in the next PR.
- Extract a function to generate irrigation type options (eg. pivot, drip) for reuse in the hook
- Update `irrigationTaskTypesSlice`
- Remove `irrigationTaskTypesAdapter`, which was adding unused state to the slice
- Fix reducer logic
- Add selectors to select a specific task type and irrigation type.
- Fix `waterUsage` unit config
- (This enables …

LF-4770 (1): Display flow to approve an IP and create a task from it

---

packages/webapp/public/locales/en/translation.json
packages/webapp/src/assets/images/header-chevron-left.svg
packages/webapp/src/components/Animals/FixedHeaderContainer/styles.module.scss
packages/webapp/src/components/CropListPage/index.jsx
packages/webapp/src/components/IrrigationPrescription/index.tsx
packages/webapp/src/components/IrrigationPrescription/styles.module.scss
packages/webapp/src/components/IrrigationPrescription/types.ts
packages/webapp/src/components/Layout/CardLayout.tsx
packages/webapp/src/components/Layout/layout.module.scss
packages/webapp/src/components/LocationDetailLayout/PointDetails/Sensor/index.jsx
packages/webapp/src/components/LocationDetailLayout/PureLocationDetailLayout.jsx
packages/webapp/src/components/LocationFieldTechnology/index.jsx
packages/webapp/src/components/LocationTasks/index.jsx
packages/webapp/src/components/Navigation/styles.module.scss
packages/webapp/src/components/Navigation/useSectionHeaders.tsx
packages/webapp/src/components/PageTitle/index.jsx
packages/webapp/src/components/PageTitle/styles.module.scss
packages/webapp/src/components/PageTitle/v2/index.jsx
packages/webapp/src/components/PageTitle/v2/styles.module.scss
packages/webapp/src/components/Sensor/EditSensor.jsx
packages/webapp/src/containers/IrrigationPrescription/index.tsx
packages/webapp/src/containers/IrrigationPrescription/styles.module.scss
packages/webapp/src/containers/SensorReadings/index.jsx
packages/webapp/src/containers/SensorReadings/v2/index.tsx
packages/webapp/src/routes/index.jsx
packages/webapp/src/util/siteMapConstants.ts

This completes the irrigation prescription view by adding the container and situating the previous components (map view, table, time / date components) within it.
You can test the container in app and see the VRI view by supplying any fake IP primary key:
```
http://localhost:3000/irrigation_prescription/78734
```
To see the URI view though, specifically use this fake route:
```
http://localhost:3000/irrigation_prescription/uri_pk
```
IP Notes:
- mock data is partially pulled from Storybook (personally I'm a bit curious to know if the storybook folder is ending up in the beta build!) and partially defined right in the component... ultimately it will all come from the backend and the type should be moved to the RTK Query config
- @SayakaOno you probably have defined the …

LF-4768 (3) Display IP Detail - IP Detail Container

---

packages/api/src/controllers/locationController.js
packages/api/src/middleware/validation/location.js
packages/api/src/models/figureModel.js
packages/api/src/models/locationModel.js
packages/api/src/models/soilSampleLocationModel.js
packages/api/src/routes/locationRoute.js
packages/api/tests/location.test.js
packages/api/tests/testEnvironment.js

This is the backend for the new location type. It is based entirely off of following the existing pattern for (= code search on) gate / water valve.
Because the meaningful changes in most of these files are so small, I didn't open a separate linting PR. I'll indicate below what is the meaningful change in the one file where the linter made a huge diff.
Jira link: https://lite-farm.atlassian.net/browse/LF-4829
Tested in app with the frontend components I'll open shortly.
**Checklist:**

LF-4829 Create soil sample endpoints and update location controller

---

packages/webapp/public/locales/en/task.json
packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/Modals/NoSoilSampleLocationsModal/index.jsx
packages/webapp/src/components/Modals/NoSoilSampleLocationsModal/styles.module.scss
packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
packages/webapp/src/components/Task/getSupportedTaskTypesSet.js
packages/webapp/src/containers/Task/TaskLocations/index.jsx
packages/webapp/src/containers/Task/TaskTypeSelection/index.jsx

** This is a BRANCH off of LF-4831 so that the selectors work
- Adds a new task type. 
- Adds a new "no locations" modal
- Adds a new soil sampling task locations
Jira link: [LF-4840](https://lite-farm.atlassian.net/browse/LF-4840)
**Checklist:**
[LF-4840]: https://lite-farm.atlassian.net/browse/LF-4840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4840 new task type card form flow

---

packages/api/src/controllers/taskController.js

Saw this while working on documents - Small change to guarantee a response from the getTasksByFarmId endpoint.
Hopefully avoids endpoint hangups, open test handles.
**Checklist:**

return the response early and guarantee a response

---

packages/webapp/src/containers/Task/TaskReadOnly/index.jsx

I broke read only tasks with no location with the mocks. Didn't know whether I should wait to see the other PR remove them first but here is a fix.
Jira link:
**Checklist:**

Move mocking into an if statement

---

packages/webapp/src/components/Task/SoilSampleTask/index.tsx

Jira link: [LF-4849](https://lite-farm.atlassian.net/browse/LF-4849)
**Checklist:**
[LF-4849]: https://lite-farm.atlassian.net/browse/LF-4849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LF-4849 Prevent decimal value

---

packages/api/src/jobs/index.js
packages/api/src/jobs/notifications/index.js
packages/api/src/middleware/acl/checkJwt.js
packages/api/src/middleware/validation/checkTask.js
packages/api/src/routes/timeNotificationRoute.js
packages/api/src/server.ts
packages/api/tests/irrigation_prescription.test.ts
packages/api/tests/irrigation_prescription_request.test.ts
packages/api/tests/task.test.js
packages/api/tests/timeNotification.test.js
packages/webapp/src/containers/LocationDetails/LocationIrrigation/useIrrigationPrescriptions.ts
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/routes/index.jsx
packages/webapp/src/store/api/apiSlice.ts

This comments out:
- IP notifications
- IP external query
- IP request scheduler
- Prevents creation of `irrigation_task` with `external_id` on backend (tasks with external ips will still show on beta, but cannot be created on prod)
Jira link: [LF-4848](https://lite-farm.atlassian.net/browse/LF-4848)
**Checklist:**
[LF-4848]: https://lite-farm.atlassian.net/browse/LF-4848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lf 4848 comment out irrigation prescription module wip for mid june release

---

packages/api/src/jobs/index.js
packages/api/src/jobs/notifications/index.js
packages/api/src/middleware/acl/checkJwt.js
packages/api/src/middleware/validation/checkTask.js
packages/api/src/routes/timeNotificationRoute.js
packages/api/src/server.ts
packages/api/tests/irrigation_prescription.test.ts
packages/api/tests/irrigation_prescription_request.test.ts
packages/api/tests/task.test.js
packages/api/tests/timeNotification.test.js
packages/webapp/src/containers/LocationDetails/LocationIrrigation/useIrrigationPrescriptions.ts
packages/webapp/src/containers/Task/saga.js
packages/webapp/src/routes/index.jsx
packages/webapp/src/store/api/apiSlice.ts

This reverts commenting out IPs (WIP feature) for the sensors release so we can continue development.
**Checklist:**

Revert Merge pull request #3815 LF-4848 Comment out irrigation prescription module WIP for mid June Release

---

packages/api/src/controllers/taskController.js
packages/api/src/models/animalMovementTaskPurposeRelationshipModel.js
packages/api/tests/animalTask.test.js

Fix backend to accept empty string `""` for `other_purpose` when completing animal movement tasks.
- Update `AnimalMovementTaskPurposeRelationshipModel` to remove `other_purpose` `minLength` to allow `""`
- Fix `createMovementTaskForReqBody` function used for testing movement task completion
- Pre-commit flagged unused variables in the test file, so I removed them. The rest of the diffs are from the auto-formatting 🙏 
Jira link: https://lite-farm.atlassian.net/browse/LF-4905
**Checklist:**

LF-4905: Cannot complete animal movement task

---

packages/api/package-lock.json
packages/api/package.json
packages/api/src/server.ts
packages/webapp/package.json
packages/webapp/src/main.jsx
packages/webapp/src/util/constants.js

Jira link: [Release 3.8.0](https://lite-farm.atlassian.net/projects/LF/versions/10067/tab/release-report-all-issues)
**Checklist:**

Release 3.8.0 - version numbers, release badge, and release notes link

---

packages/api/src/util/ensembleService.types.ts
packages/api/src/util/generateMockPrescriptionDetails.ts
packages/webapp/public/locales/en/translation.json
packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionTable.tsx
packages/webapp/src/components/IrrigationPrescription/types.ts
packages/webapp/src/stories/IrrigationPrescription/PureIrrigationPrescription.stories.tsx
packages/webapp/src/stories/IrrigationPrescription/mockData.tsx

- Update `soil_moisture_deficit` to `available_soil_moisture`
- Update `soil_moisture_deficit_unit` to `available_soil_moisture_unit`
- Update the table header text
Jira link: https://lite-farm.atlassian.net/browse/LF-4916
Tested using mock data: `USE_IP_MOCK_DETAILS=true`
**Checklist:**

LF-4916: Update soil_moisture_deficit to available_soil_moisture

---

packages/webapp/public/locales/en/message.json
packages/webapp/src/containers/Task/saga.js

This has bothered me for years (and I ignored it), but testing the offline behaviour of the PWA has pushed me over the top, since this snackbar is triggering on every navigation to tasks and finances!
There should never have been an error snackbar for this situation of fetching the harvest use types, since it's not a user-initiated action, but rather part of the background fetch that we call when loading tasks and finances:
```js
export function* getManagementPlansAndTasksSaga() {
try {
yield all([
call(getCropsAndManagementPlansSaga),
call(getProductsSaga),
call(getHarvestUseTypesSaga), // <-- here
call(getTaskTypesSaga),
]);
yield call(getTasksSaga);
} catch (e) {
console.log(e);
}
}
```
The other sagas in that list all fail with just a console.log(), but …

LF-4942 "Failed to fetch harvest use types" error snackbar shows inappropriately

---

packages/webapp/src/components/Form/ProductDetails/index.tsx
packages/webapp/src/components/Form/ProductDetails/utils.ts
packages/webapp/src/components/ProductInventory/ProductForm/PureSoilAmendmentProductForm.tsx
packages/webapp/src/containers/ProductInventory/ProductForm/SoilAmendmentProductForm.tsx
packages/webapp/src/containers/ProductInventory/ProductForm/constants.ts
packages/webapp/src/containers/ProductInventory/ProductForm/index.tsx
packages/webapp/src/containers/ProductInventory/ProductForm/styles.module.scss
packages/webapp/src/containers/ProductInventory/index.tsx

This PR includes some small updates to support edit functionality. The main changes are:
- Reset the form with the selected product in `PureSoilAmendmentProductForm`.
- Keeping the values on close doesn’t seem harmful, so I didn’t add reset (Related [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3883#discussion_r2402754568) in the previous PR).
- Hide `InFormButtons` in read-only mode.
- Implement `handleRowClick` for the table.
**Drawer header fixed height** (https://github.com/LiteFarmOrg/LiteFarm/pull/3883#discussion_r2399572313):
I think the 35px height has always been there (The first PR for the drawer: https://github.com/LiteFarmOrg/LiteFarm/pull/2943/files), and even if we removed it, the cross icon's height is 36px, so the header height would be 36px. I'll …

LF-4964: Implement edit product functionality
