LiteFarmOrg/LiteFarm

- packages/webapp/src/containers/Field/NewField/index.js
- Removed BACK_TO_STEP_ONE which fixed map rendering when "Confirm" button hit
- Removed center: null in clear button and next button which fixed map rendering when "Redraw" button hit
> Removed center set to null in clear button and next button

- packages/webapp/src/containers/Navigation/index.js
problem fixed: when logo is clicked in the noFarmNavbar, we encounter an error that says history is not found.
> pass in missing props to noFarmNavbar

- packages/webapp/src/components/Map/DrawingManager/styles.module.scss
- packages/webapp/src/containers/Map/useMapAssetRenderer.js
- if a farm has no locations (ie: newly created farm), the map will centre over the centre of the farm
- warning box can no longer be clicked through
> Small map fixes

- README.md
An update to streamline onboarding new contributors.
1. Please note that I have changed the instructions' database name `mock_farm` to `pg-litefarm` in order to keep `.env` files more similar between Docker vs. local setups. I don't think that should create any problems, but let me know. The `mock_farm` name is used only in some CI contexts as far as I can tell.
2. I have no Mac to try out those instructions. Specifically, I suspect the Mac install of PostgreSQL would go much like the Linux process given here, but I don't know that for sure.
> Reorganize and update setup instructions

- packages/api/src/controllers/organicCertifierSurveyController.js
- packages/api/src/jobs/certification/do_retrieve.js
- packages/api/src/jobs/certification/pdf.js
- packages/api/src/jobs/certification/recordD.js
- packages/api/src/jobs/certification/record_d_generation.js
- packages/api/src/jobs/certification/record_i_generation.js
- packages/api/src/jobs/certification/upload.js
- packages/api/src/jobs/certification/zip.js
Previous server-side "scheduler" job created export as `farm_name.zip`. After copying that zip to aws (under a different filename), the inputs to the zip were deleted, but not the zip itself.
Later exports for the same farm would *refresh* the files in that existing zip, so that any old additional survey questions would remain in the zip though they were no longer appopriate.
This PR:
1. generates a uuid `exportId` for each export. The uuid is used for the zip file name instead of `farm_name`, to avoid possible collisions; and
2. deletes the zip file from the scheduler's file system after it has been copied to aws.
> [LF-2060] Name export zip with uuid, rm after upload

- packages/api/db/migration/20220301154943_soft-delete-countryless-farms.js
In standup, we agreed to run this on beta as well as production. As a result, nothing here checks the environment-- the updates will just run. @JimmyRowland let me know if you think that should be handled differently.
> LF-2028 Soft delete farms where country and grid pts are NULL

- packages/api/db/migration/20220309022932_update_country_id.js
- packages/api/src/jobs/station_sync/countrySync.js
Country sync script was only looking at first result for country; now tries all.
Added another migration to run the script again.
> Fix country matching; run sync migration

- packages/api/package.json
api .js files were not being checked by lint-staged. Apparently the curly braces can't be used around only one file extension.
`litefarm-api: [SKIPPED] No staged files match *.{js}`
> Fix file matching in lint-staged config

- packages/webapp/src/components/Crop/BroadcastPlan/PureBroadcastForm.jsx
- packages/webapp/src/components/Form/Unit/index.jsx
- packages/webapp/src/components/Form/Unit/unit.module.scss
There was an alignment issue when the left form field on the second row had text overflowed to two lines. Fixed by using existing flex box and removing position absolute. 
Story: [LF-2273](https://lite-farm.atlassian.net/browse/LF-2273?atlOrigin=eyJpIjoiOTJiODViNDUwODMyNGJlOWJiMzNkNmQyY2ZlNmQ0MDIiLCJwIjoiaiJ9)
> Lf 2273 UI error on broadcast planting method

- packages/api/src/middleware/validation/assignTask.js
- packages/webapp/src/components/Form/ReactSelect/index.jsx
- packages/webapp/src/components/Modals/QuickAssignModal/index.jsx
There was issue in validating the assignee_user_id where we were not accepting null as valid, when null is representing when a task is unassigned. So the validation was always throwing 400 when trying to make a task unassigned. 
Also added a check in the frontend such that if the task is currently unassigned, we can not assign it again to unassigned.
> LF-2323: error when unassigning task from task card and read only task view

- packages/webapp/src/components/Crop/RowMethod/PureRowForm.jsx
Ticket [LF-2332](https://lite-farm.atlassian.net/browse/LF-2332)
Estimated annual harvest calculation for row planting method
For example for Apricots, 
- 30 meter rows and plant spacing at 15 meters, should equal 3 plants (0, 15, 30) per row at 10 rows = 30 plants
- 30 plants at 47.5 kg/plant = 1425
To Test:
1. Select any crops and create a plan
2. Select Rows for planting method
3. Check the estimated annual yield is correct
You can find each crop's yield per plant in Crop table.
If the length isn't perfectly divisible by spacing (i.e. 16 meter spacing in a 30 meter row), you cannot plant 2.875 plants each row. You will plant 2 plants per row (at 0 meter and 16 meter) and the estimated yield is calculated accordingly.
> LF-2332/fix-estimated-yield-calculation-for-crops

- packages/webapp/src/containers/Filter/Tasks/index.jsx
Updated the filter on the task page to display all active task types, regardless of whether there is a task with that type currently.
To test:
1. Make sure you have at least one default task type and one custom task type on your farm which have no tasks associated with them
2. On the tasks page, go to filter tasks
3. Try to filter the tasks by type -> you should see all task types here, not just those which currently have a task
> LF 2364 augment type filter on task filter page

- packages/api/db/migration/20220504213459_update-apricot-plant-spacing-from-crop-table.js
Ticket [LF-2331](https://lite-farm.atlassian.net/browse/LF-2331)
To Test:
1. Check `crop` table using your choice of PostgreSQL GUI. `crop_id` for Apricot is 31. Check that the `plant_spacing` column has a value of 15 for Apricot.
2. Run `npx knex migrate:up` and check the table again. The value should be now updated to 457.2.
3. `npx knex migrate:down` will revert the changes.
> LF-2231/apricot plant spacing fix migration file

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
In order to see the changes:
Create a management plan and fill out the plan until you have reached the options to have rows, bed, or containers (select and fill out the details for any)
You will see the 'estimated annual yield" changed to "estimated annual harvest"
Once the plan has been created open the details of the plan you have created and you will again see 'estimated annual yield" changed to "estimated annual harvest"
> LF-2333/Change-Estimated-annual-yield-labels-to-read-Estimated-annual-harvest-throughout-the-app

- packages/api/package.json
- packages/webapp/src/components/Modals/QuickAssignModal/index.jsx
- packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
- packages/webapp/src/containers/Task/TaskCard/index.jsx
- packages/webapp/src/containers/Task/index.jsx
- packages/webapp/src/containers/Task/saga.js
Assign all tasks on a date, on the task quick assign modal does not work
To test:
1. Go to http://localhost:3000/tasks
2. In the list of tasks, add two or more unassigned tasks for the same date.
3. click on unassigned, change it to some assignee and then click on the checkbox "Assign all unassigned tasks on this date to this person". then click on update.
4. You'll be able to see that the unassigned task will get updated with the assignee name for the same date.
For more details please check. 
https://lite-farm.atlassian.net/browse/LF-2314
> Assign all tasks on date, on the task quick assign modal does not work

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
- packages/webapp/src/components/Crop/ManagementDetail/styles.module.scss
Select any crop and create a plan for the crop
When creating the crop plan, make sure to fill out
'plan notes'
'rating'
'completion notes'
in order to see in the details section of a completed crop plan
Go through the tasks created in the crop plan and complete the tasks and eventually complete the crop plan.
You can then see the details of the completed crop plan show as required in:
https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/1?modal=detail&selectedIssue=LF-2178
> LF-2178/Completed-notes-and-rating-not-showing-on-a-completed-crop-plan-detail-page

- packages/webapp/public/locales/en/common.json
- packages/webapp/public/locales/es/common.json
- packages/webapp/public/locales/fr/common.json
- packages/webapp/public/locales/pt/common.json
- packages/webapp/src/components/CropCatalogue/CropStatusInfoBox/index.jsx
- packages/webapp/src/components/CropTile/index.jsx
- packages/webapp/src/components/Square/index.jsx
- packages/webapp/src/containers/AddCropVariety/AddCropVariety.jsx
- packages/webapp/src/containers/CropCatalogue/index.jsx
- packages/webapp/src/containers/CropCatalogue/useCropCatalogue.js
- packages/webapp/src/containers/CropCatalogue/useFilterNoPlan.js
- packages/webapp/src/containers/CropVarieties/index.jsx
- packages/webapp/src/containers/CropVarieties/useCropVarietyCatalogue.js
- packages/webapp/src/containers/CropVarieties/useFilterNoPlan.js
- packages/webapp/src/containers/Filter/CropVariety/index.jsx
- packages/webapp/src/containers/Task/TaskCrops/managementPlansWithLocationSelector.js
- packages/webapp/src/containers/cropVarietySlice.js
Important! - this PR contains UI changes related to Lf-2163 and LF-2172. Please review the LF-2172 PR (https://github.com/LiteFarmOrg/LiteFarm/pull/1900)
and then this one.
To test:
- create a crop variety by selecting any crop from the crop catalog page. (http://localhost:3000/crop_catalogue)
- add more varieties for the same crop. (around 5)
- add a plan to any of the crop varieties.
- check for the count of active, planned, past, and needs plans.
For more details:
https://lite-farm.atlassian.net/browse/LF-2163
https://lite-farm.atlassian.net/browse/LF-2172
> LF-2163 and LF-2172  Addition of "Needs plan" counter in Crop catalogue and crop variety

- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/InviteUser/index.jsx
This PR ensures that numerical input fields on the "Invite user" page cannot accept non-numeric values.
To test:
1. Go to the "Invite User" page
2. Attempt to provide the “Birth Year”, “Hourly Wage”, and “Phone Number” inputs with non-numeric values. All non-numeric inputs should not be accepted
**Note:** This bug was found on iPhone. To properly test this PR one must do it using Safari because iPhone browsers behave similarly to Safari. Testing on an actual iPhone would be even better if possible.
> Lf 2250 able to input non numerical values in numerical inputs wage year phone

- packages/webapp/src/components/AddNewCrop/index.jsx
Go to crops and scroll all the way down on the varieties page. Fill out the name and crop group and the continue button should remain disabled. Once an option for "Can this be grown as a cover crop" is selected, the continue button should become active.
> Make Can this be grown as a cover crop required on add a crop type flow

- packages/webapp/src/components/Crop/Management.jsx
- packages/webapp/src/components/CropListPage/index.jsx
Access the variety detail page using the farm map as shown in 
https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/1?modal=detail&selectedIssue=LF-2318&assignee=626c0502a6d9be006abdad16&assignee=61f0981825edab006a0f0044
and press the back button and notice it goes back to the farm map.
Secondly access the variety detail page by clicking the menu icon on the top left and crops. Click any variety and then press the back button, you should return to the crop catalogue
> Clicking < from variety detail page should be contextual

- packages/webapp/src/components/Form/Unit/index.jsx
To test:
1. start with the create a task flow.
2. in the forms, look for the unit conversion dropdown.
3. add a value to the input field.
4. make changes in the drop-down unit field.
5. check if the value in the input field remains the same after selecting a different unit field.
> Lf 2393 - Disable unit conversion on changing the value of unit selection dropdown component

- packages/webapp/public/locales/fr/common.json
- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
- packages/webapp/src/components/Task/AbandonTask/index.jsx
Create and abandon a crop plan and create and abandon a task. When selecting the options for reasons of abandonment the placeholder select text should be correct for each language
> LF-2156 and LF-2395 Micro copy (Select...) on ghost text for MP and task abandonment reason needs to be dynamic

- packages/webapp/src/containers/Task/index.jsx
Before, there was a bug where the task page was unable to load. This PR fixes this by removing the use of undefined variables.
> Fixed task page loading error

- packages/api/.gitignore
- packages/api/src/jobs/certification/recordD.js
- packages/api/src/jobs/certification/survey_record.js
- packages/webapp/src/components/CertificationSurvey/RegisteredCertifierQuestions/index.jsx
This PR exports the answers to the questions asked during a certification document as an Excel sheet.
To Test:
First we need to set up the database to pull the correct surveys. In the psql client...
1. Connect to the 'pg-litefarm' database
2. run the following command `update certifiers set survey_id='627bdbff5b5f71000118f47c'`. This will update the surveys for all certifiers
Then we need to set up the Redis service
1. Under packages/api, you have to create a directory called exports
2. Install the aws cli https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
3. Authenticate the aws cli by running aws configure in your terminal, and using the DO_SPACES_ACCES_KEY_ID and DO_SPACES_SECRET_ACCESS_KEY values from the packages/api/.env file for the access key id and …
> Lf 2322 modify survey stack export document

- packages/webapp/src/components/Modals/QuickAssignModal/index.jsx
- packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
- packages/webapp/src/containers/Task/TaskCard/index.jsx
- packages/webapp/src/containers/Task/index.jsx
Per recent discussion on Ticket [LF-2323](https://lite-farm.atlassian.net/browse/LF-2323). 
There was issue in the task assign modal where it was relying on task card contents. This was causing an issue when the modal was being used from the read only view rather than from a task card. I have refactored the quick assign modal to grab the tasks from state instead. 
To test:
- Create a few tasks, and play around with assigning, unassigning, and assigning all unassigned tasks on date. Make sure there are no additional bugs I missed.
> Refactor task assign modal to not rely on task card contents

- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
There was not enough padding at the bottom of the second date field added in the original PR for this ticket. As you can see below, this has been fixed:
> Fixed padding

- packages/webapp/src/components/Task/PureTaskCrops/index.jsx
- packages/webapp/src/containers/Task/TaskCrops/index.jsx
**Description:**
- Ticket [LF-2330](https://lite-farm.atlassian.net/browse/LF-2330)
- When creating a task, if locations selected by the user are not referenced by active crop plans, bypass the "affect any plans" page
**To Test:**
1. Create one area with no crop plans associated with, one area with abandoned crop plans, and one area with active crop plans.
2. Create a task for the area with no crop plans. Upon selecting that location, you will be directed to the task details page rather than "affect any plans?" page.
3. Repeat for the area with abandoned crop plans (same result) and the area with active crop plans (should be redirected to "affect any plans?" page after location selection.
> LF-2330 skip crop plans when non-crop locations are selected (task creation flow)

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
Create 2 crop plans from any of the plants on the crop catalogue and complete one of the crop plans and abandon the other. Make sure to fill in the details of both the completed and abandoned crop plan such as abandon notes, reason for abandoning, completion notes, rating, etc. Once each of the crop plans have been completed you can then go on the details section of each and see that the completed crop plan does not show any abandonment details and the abandoned crop plan shows abandon details and reasoning.
> Abandon rating, reason, and notes not showing on an abandoned crop plan detail page

- packages/api/src/controllers/userController.js
This fixes the language of invitations
To test:
1. Create 2 users on an existing farm
2. Create a new farm with one of those users
3. Invite the second user to the new farm and select for the language drop down a language that is different than the preferred language of the second user (e.g. if the second user's preferred language is spanish, select english)
4. The email to the second user should be in their preferred language, not the language selected from the drop down
5. Invite a new user who does not yet have an account
6. The language of this invitation should be the one selected in the drop down
It is worth noting that any emails that should be in french will be in english because there are no existing french translations of the emails
> Fixed language of invitation

- packages/webapp/public/locales/fr/crop.json
French crops were not displaying before because of a syntax error in the translation file. This PR fixes the file
> Fixed displaying crops in french

- packages/api/src/controllers/timeNotificationController.js
- packages/api/src/jobs/notifications/index.js
- packages/api/src/models/taskModel.js
- packages/api/tests/timeNotification.test.js
Related to [F21-578](https://lite-farm.atlassian.net/browse/F21-578) - Notification driver/scheduler.
Added a flag to the notification endpoints to indicate whether "today" should be thought of as a day later than UTC time. 
To test:
- run tests in "timeNotification.test.js"
> fix: adding one day later flag to timed notification endpoints

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/containers/AddFarm/index.jsx
- packages/webapp/src/containers/AddFarm/saga.js
To Test:
1. Go to create a farm page in a frame name input field fill in characters more than 255.
2. check the error message.
"Scenario 1" - For the first time, it will call the post API of addFarm. 
3. Therefore, fill in a valid farm name and go to the next form page.
4. Now, come back to the same page and add a farm name having more than 255 characters.
"Scenario 2" - This time it will show the error from the update/patch API of the farm. 
match the error message from both scenarios.  
https://lite-farm.atlassian.net/browse/F21-592
> F21 592: Fix: farm name character limit error handling

- packages/webapp/src/containers/LocationDetails/AreaDetails/BarnDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/CeremonialAreaDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/FarmSiteBoundaryDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/FieldDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/GardenDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/GreenhouseDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/NaturalAreaDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/ResidenceDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/AreaDetails/SurfaceWaterDetailForm/saga.js
This fix addresses an unwanted loop in the location creation flow
To test:
1. Log in to system
2. Go to “my farm” > “farm map”
3. Click “+”
4. Select a type
5. Draw shape
6. Click redraw and redraw
8. Click “Confirm”
9. Click “<“
10. Click “Confirm” again
11. Enter all required attributes for barn and click “Save”
After all of that, you should arrive at your farm map with the new addition.
**Note:** This issue was originally discovered on Barns and Greenhouses. I noticed the same issue in other area types and I extended the fix to them as well.
> F21 608 creation flow for location (barn, greenhouse, field, farm boundary, potentially others ) loops 

- packages/webapp/src/containers/notificationSlice.js
- packages/webapp/src/store/actionTypes.js
- packages/webapp/src/store/reducer.js
Ticket [F21-582](https://lite-farm.atlassian.net/browse/F21-582) and [F21-583](https://lite-farm.atlassian.net/browse/F21-583)
**Description:**
This PR fixes the bug where a user was seeing notifications from multiple farms on notification center when switching farms.
When a user switches farms, the notification reducer state will be reseted. [Selective reset redux state](https://webdev99.com/resetting-redux-state-with-a-root-reducer-completely-selectively/)
**To Test:**
1. You need a user with multiple farms (create one or use the one you have if you already have one).
2. Please either clear site data or log out before you test this out.
3. Log into the user's account and select one of the farms.
4. Create a notification for yourself (by assigning a task, etc.).
5. You should see the …
> F21-582/switch farms reset notification reducer state

- packages/webapp/src/locales/i18n.js
Ticket: [F21-600](https://lite-farm.atlassian.net/browse/F21-600)
Fixed issue where landing page was not detecting french on iOS.
To test (If you have an iPhone):
- Set Up [Ngrok](https://ngrok.com/signup)
- After running both the backend and frontend servers, run `ngrok http 3000`
- Switch phone language to French (Canada)
- Set default language in Chrome to French (Canada)
- Go to ngrok tunnel link
- See if the landing page is french
> F21-600 iphone landing page not detecting french

- packages/webapp/src/components/Finances/FinanceGroup/GroupItem/index.jsx
- packages/webapp/src/components/Finances/FinanceGroup/Header/index.jsx
- packages/webapp/src/components/Finances/UpdateEstimatedCropRevenue/index.jsx
- packages/webapp/src/components/Finances/WholeFarmRevenue/index.jsx
- packages/webapp/src/containers/Finances/AddSale/index.jsx
- packages/webapp/src/containers/Finances/EditSale/index.jsx
- packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
- packages/webapp/src/containers/Finances/Labour/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
- packages/webapp/src/containers/Finances/OtherExpense/index.jsx
- packages/webapp/src/containers/Finances/index.jsx
This PR has the "finances" page display the correct currency based on the user's location.
Ticket: [F21-587](https://lite-farm.atlassian.net/browse/F21-587)
To test:
1. Go to the finances page
2. Add some expenses and sales
3. Explore the "Expenses" and "Revenue" tabs and ensure the correct currency is being displayed in every part
To thoroughly test this, I suggest testing with 2 or more farms that are in different locations so they use different currencies.
> F21 587 non usd denominated farms show hardcoded throughout the finances section

- packages/webapp/src/components/Crop/CropHeader.jsx
- packages/webapp/src/components/Crop/styles.module.scss
[Jira Ticket](https://lite-farm.atlassian.net/jira/software/c/projects/F21/boards/3?modal=detail&selectedIssue=F21-599)
Set the litefarm application to responsive view on dev tools
Select a crop variety with a large name (I used Big Leaf Mahogany (Mogno brasileiro) for testing purposes)
Decrease the width of the view and the large name should hide behind the picture instead of it shifting downwards and resizing the picture on the right
> text overflow on crop type varietal hybrid view

- packages/webapp/src/containers/Profile/People/saga.js
This PR fixes https://lite-farm.atlassian.net/browse/F21-621 
The error was that when you convert a pseudo user account to a normal user account and use an email of an existing user for the new invitation, the page would hang. It turns out this was happening because we were relying on the `user_id` parameter in the url, which would no longer be associated with any user once the user is updated to an existing account (with a different user id). To fix this, we need to make sure we navigate back before updating any of the user info as otherwise the code will fail.
> Fixed the page hang

- packages/webapp/src/containers/CropCatalogue/index.jsx
- packages/webapp/src/containers/CropCatalogue/useStringFilteredCrops.js
- packages/webapp/src/containers/Documents/util.js
Ticket [F21-664](https://lite-farm.atlassian.net/browse/F21-664)
**To Test:**
1. Go to Crops page and type in crops with accented characters without actually typing in accented characters (you can try it in different languages other than English) i.e. Guaraná, Acácia mangium, etc.
2. You should still get the appropriate crops in the search results.
> F21-664/accented characters allowed from search inputs

- packages/webapp/src/containers/LocationDetails/LocationManagementPlan/index.jsx
This was fixing https://lite-farm.atlassian.net/browse/F21-651 
This sentry error was caused when someone tried to search on the "crop" page associated with a location. I fixed the error, and also updated the filtering to filter the crops by the appropriate language.
To test:
1. Have at least one crop plan associated with a location. 
2. Go to map view, and click on that location
3. Go to the crops tab, and search. It should correctly filter out the crops based on the search term, and also on the language you are currently using
> Fixed filtering on crop management plans

- packages/webapp/src/components/ChooseFarm/ChooseFarmMenu/ChooseFarmMenuItem/chooseFarmMenuItem.module.scss
- packages/webapp/src/components/ChooseFarm/ChooseFarmMenu/ChooseFarmMenuItem/index.jsx
To Test: 
1. Go to http://localhost:3000/farm_selection page.
2. Inspect the page in your browser:-
3. Add some dummy text as shown below. 
For details: https://lite-farm.atlassian.net/browse/F21-612
Please check the CSS compatibility of word-break: https://caniuse.com/?search=word-break
> F21-612 - Fix: long farm name overflow on the farm selection page 

- packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
- packages/webapp/src/containers/Finances/index.jsx
- packages/webapp/src/containers/Finances/util.js
Ticket: [F21-660](https://lite-farm.atlassian.net/browse/F21-660)
FIxed finance page so that the revenue changes with the date range. 
To test:
- Make sure you have a crop variety with an active crop plan (not complete or abandoned);
- Got to Finances
- Click "Add new sale" and fill this out a couple times for different dates
- Make you are getting correct values for Actual Revenue where filtering by those date ranges
- Try making the start date after the end date, make sure the Actual Revenue is 0
>  F21-660 finances date range doesnt filter revenues appropriately

- packages/api/.env.default
- packages/api/src/controllers/farmController.js
- packages/api/src/jobs/station_sync/updateTimeZoneOffsets.js
We recently added `GOOGLE_MAPS_API_KEY` to the api package. That is the name used by the webapp package. api already had `GOOGLE_API_KEY`, which is the same value. This removes the new, redundant environment variable.
> Remove redundant env var

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Finances/DateRangeSelector/index.jsx
This PR gives the user an error message when they select an invalid date range in the "Finances" section
To test:
1. Navigate to the finances section
2. Play around with the "Filter Report by Date" date picker. When the end date is before the start date, or the start date is after the end date, you should see an error message warning you of this.
> F21 657 able to have end date before start date in the finances page

- packages/webapp/src/containers/CropCatalogue/useStringFilteredCrops.js
- packages/webapp/src/containers/Documents/util.js
Ticket [F21-671](https://lite-farm.atlassian.net/browse/F21-671)
**To Test:**
1. Go to Crop Catalogue.
2. Search crop names with non-alphabetical characters (i.e. spaces, commas, dashes, open and close parenthesis, and slashes).
3. You still should be able to search all the crops without typing all the non-alphabetical characters.
Examples: Chupa-chupa, Cabbage, Apple malay, etc.
> F21-671/Searching the crop catalogue should ignore non-alphabetical characters

- packages/webapp/src/components/Task/HarvestingTask/ReadOnly.jsx
- packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
I was able to recreate the error Sarah-Louise reported in https://lite-farm.atlassian.net/browse/F21-667 by using her credentials for her farm. However, the error was no longer occuring for custom task types (I imagine it got fixed somewhere else). So, the only error I was able to recreate on her farm was the blank page that occurred while completing a harvest task. This PR fixes that blank page bug.
To test:
1. Create a harvest task
2. Complete the task and only select one harvest use
3. You should not see a blank page once you complete the task
> Fixed complete harvest task leading to blank page

- packages/api/src/controllers/timeNotificationController.js
- packages/webapp/src/containers/Task/index.jsx
- packages/webapp/src/containers/filterSlice.js
See latest comments on this ticket: [F21-560](https://lite-farm.atlassian.net/browse/F21-560)
To test: see instuctions on this pull request ([1912](https://github.com/LiteFarmOrg/LiteFarm/pull/1912))
You can also try manually changing the notification.context.date object in postgres, to test if you view a notification later than it was created, it will still filter by the date sent.
> fix: made dates for time notifications static

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Modals/ExportMapModal/index.jsx
- packages/webapp/src/components/Modals/ExportMapModal/styles.module.scss
- packages/webapp/src/containers/Map/index.jsx
The issue we were experiencing with the map downloads may have been caused by the fact that we were  generating and clicking an `a` tag in the code. I have verified that in Chrome for iOS, `a` tags with the proper `download` and `href` attributes generally download fine.
To test:
1. Go to your map
2. Download it
> F21 639 download map fails silently on iPhone

- packages/webapp/src/components/Profile/People/index.jsx
To Test:
1. go to http://localhost:3000/people.
2. check the names displayed in the name column are retaining the capitalization.
3. check the search functionality based on the name.
https://lite-farm.atlassian.net/browse/F21-606
> F21-606 Fix : resolved the Incorrect capitalization on "People" tab

- packages/webapp/src/components/LocationDetailLayout/LocationPageHeader.jsx
- packages/webapp/src/components/LocationDetailLayout/PureLocationDetailLayout.jsx
This PR fixes a bug that was causing the "cancel" button in the location creation flow to behave incorrectly.
Ticket: [F21-686](https://lite-farm.atlassian.net/browse/F21-686)
To test:
1. Go to the farm map in my farm
2. Draw a new location
3. Click confirm
5. Click the back button
6. Click confirm again
7. In the details page, click cancel
You should be brought back to the farm map without the location you just drew.
> F21 686 canceling location creation not completed

- packages/webapp/src/components/Task/TaskLocations/index.jsx
- packages/webapp/src/containers/Task/TaskLocations/index.jsx
This resolves https://lite-farm.atlassian.net/browse/F21-579
To test:
1. Create a wild crop plan. (When making the plan ensure you select "in ground" to be able to make it a wild crop)
2. Create a new task from the crop management plan
3. As you go through the task creation flow, the "This task targets a wild crop" checkbox should be checked automatically. Additionally, the crop plan should be pre-selected when you reach that page
4. When you finish creating the task, you should be returned to the management plan, not the tasks page
> Added contextual navigation for wild crop plans

- packages/webapp/src/components/WeatherBoard/assets/weatherBoard.module.scss
To test: 
1. go to http://localhost:3000/
2. open the safari browser and check if the weather board is not stretching for all screen sizes.
For more details: https://lite-farm.atlassian.net/browse/F21-589
Before: 
After:
> Fix: Stretching of weather board on Litefarm homepage

- packages/webapp/src/components/Task/PureTaskAssignment/index.jsx
- packages/webapp/src/containers/Crop/ManagementDetail/ManagementTasks.jsx
- packages/webapp/src/containers/Task/index.jsx
- packages/webapp/src/util/convert-units/unit.js
Ticket: [F21-693](https://lite-farm.atlassian.net/browse/F21-693)
To test:
- Create a new soil amendment task from a crop plan
- Create a new product and supplier
- Immediately go to task read only page of the new task from the crop plan
- Ensure that the new product and supplier are showing up correctly
> F21 693 product and supplier not persisted when creating soil amendment task

- packages/webapp/src/containers/Notification/index.jsx
[Jira Ticket](https://lite-farm.atlassian.net/jira/software/c/projects/F21/boards/3?modal=detail&selectedIssue=F21-697)
To test: 
Go to the notifications page and check to see if the notifications are sorted in descending order. (ie. June 6 should be on top while June 5th notification should be below the June 6th notification)
> Notifications-are-sorted-in-the-wrong-order

- packages/webapp/src/components/Modals/ExportMapModal/index.jsx
- packages/webapp/src/components/Modals/ExportMapModal/styles.module.scss
- packages/webapp/src/containers/Map/index.jsx
This PR makes the changes requested by Kevin on https://lite-farm.atlassian.net/browse/F21-639
This PR removes the option for iOS users to directly download the map as different methods of downloading the map work on different browsers/iOS versions. It also reverts to the previous method of downloading the map image because that did not have need of a "Loading..." text on the download button before the user had clicked on it
> Removed download button for iOS users

- packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
- packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx
This PR resolves https://lite-farm.atlassian.net/browse/F21-669
To test:
1. Go to the "Finances" page
2. Set the date range to some initial value that is different from the default value
3. Go to both the "Actual Revenue" and "Estimated Revenue" pages and see if the date range there matches the value on the main finance page (it should)
4. Change the date range in the actual and estimated revenue pages and see if it updates on the main finances page (it should)
> Updated dates to mirror those on the other finance pages

- packages/webapp/src/containers/mapSlice.js
To test: 
1. On the farm map, select an existing location
2. Click “Edit”
3. Change some of the attributes
4. Click “Update”
Fix Results: 
e.g. “Surface water successfully updated”
Before Fix Results: 
e.g. “Surface waterSuccessfully updated”
https://lite-farm.atlassian.net/browse/F21-611
Before:
After:
> F21-630: Fix: Update snackbar for locations is missing a space and has wrong capitalization

- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/useMapAssetRenderer.js
Following up on the new desired behaviour described in the comments on https://lite-farm.atlassian.net/browse/F21-698
To test:
1. Create a new farm or retire all the existing locations on your current farm
2. You should see a pin (but no title) at the location of your farm
3. Add a location
4. As soon as you begin adding the location, the pin for your farm should go away
5. When there are 1+ locations on the farm, the pin should not appear
> F21 698 sticky pin based on gps location from farm creation flow on map until first area drawn

- packages/webapp/src/components/Form/Unit/index.jsx
To Test:
1. go to farm maps
2. select any farm and navigate to the farm details page.
3. check if the unit component's dropdown is disabled or not.
https://lite-farm.atlassian.net/browse/F21-630
Before: 
After:
> F21-630 : Fix: Area unit dropdowns not disabled on location detail page

- packages/webapp/src/containers/CropCatalogue/useStringFilteredCrops.js
- packages/webapp/src/containers/Documents/util.js
Ticket [F21-671](https://lite-farm.atlassian.net/browse/F21-671)
"_" underscore should be ignored from search strings.
To Test:
1. Go to Crop Catalogue and Documents
2. Search with underscore, the underscore should be ignored
> F21 671/ignore "_" in search string fix

- packages/webapp/src/components/Navigation/NavBar/index.jsx
Ticket: [F21-633](https://lite-farm.atlassian.net/browse/F21-633)
To test:
1. Open the My Farm floater by clicking "My Farm" in the navbar
2. Click something else, including items in the navbar. You should see the My Farm floater disappear when you click do so.
> Close Farm floater when other items in navbar are clicked

- packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
This PR prevents users from providing 0 as a value when adding a new expense
Ticket: [F21-167](https://lite-farm.atlassian.net/browse/F21-167)
To test:
1. Navigate to the finances page
2. Click 'Add new expense' and pick an expense type and proceed to the form
3. Here you should enter various different inputs for the "value" field. When you enter 0, or when the field is empty, you should see an inline error message. When you try to submit the form with invalid values, you should see an alert that prevents you from proceeding until you enter valid inputs.
> F21 167 able to have a value of 0 for expense

- packages/webapp/src/components/PopupFilter/PureSearchbarAndFilter/index.jsx
- packages/webapp/src/containers/Notification/index.jsx
- packages/webapp/src/containers/Notification/useStringFilteredNotifications.js
This PR fixes the search functionality in the notifications centre. It also allows users to receive accented character outputs from non accented search inputs. Additionally, the "filter" icon is no longer visible beside the search bar because filtering is not applicable here.
Ticket: [F21-695](https://lite-farm.atlassian.net/browse/F21-695)
To test:
1. Navigate to the notifications centre where all notifications are displayed
2. Ensure the "filter" icon is not appearing beside the search bar
3. Enter a search term into the search bar and ensure the appropriate notifications are appearing. Try testing searches against both the body and the title of the notification
To thoroughly test this functionality, try changing the language and searching for terms with accented characters in them. For …
> Update searchbar and filter on notifications listview

- packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
- packages/webapp/src/containers/Finances/EstimatedRevenue/index.jsx
This is a relatively messy bit of code to create the default values for the revenue date range, but the issue is that the `dateRange` object can have dates that are either a moment.js object, a string, or undefined. I did not have time to remove all of the moment.js instances throughout this part of the codebase, so I implemented a temporary fix here.
To test: 
1. Go to the "Finances" page
2. Set the date range to some initial value that is different from the default value
3. Go to both the "Actual Revenue" and "Estimated Revenue" pages and see if the date range there matches the value on the main finance page (it should)
4. Change the date range in the actual and estimated revenue pages and see if it updates on the main finances page (it should)
> Fixed various weird date problems

- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/Navigation/index.jsx
Ticket [F21-575](https://lite-farm.atlassian.net/browse/F21-575)
Please look at the discussion.
The bug:
1. User creates a new account
2. They see the navigation bar spotlight
3. They see the notification spotlight
To Test:
1. Create a new account
2. Go through the navigation bar spotlight
3. There shouldn't be notification spotlight anymore
> F21-575/spotlight twice bug fix

- packages/webapp/src/components/Form/Unit/index.jsx
[Jira Ticket:](https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/1?modal=detail&selectedIssue=LF-2491)
Create a crop plan and input values higher than the threshold that would convert the numbers to a smaller value. 
For example, input at least 100cm in plant spacing/depth etc in order for the values to be converted into meters. Do the same thing for estimated annual harvest (At least 1000kg to convert to mt). 
Once the crop plan has created open the details page of the plan and make sure the conversion occurred and the units are now in mt. Similarly check the plan spacing/depth etc in the planting task and make sure the cm have converted to meters.
> Unit Indicators are not dynamic

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Notifications/MoreRecentNotificationWarning/index.jsx
- packages/webapp/src/components/Notifications/MoreRecentNotificationWarning/styles.module.scss
- packages/webapp/src/components/Notifications/NotificationTimeline/index.jsx
- packages/webapp/src/components/Notifications/NotificationTimeline/styles.module.scss
- packages/webapp/src/components/Notifications/index.jsx
- packages/webapp/src/components/WarningBox/index.jsx
- packages/webapp/src/containers/Notification/NotificationCard/index.jsx
- packages/webapp/src/containers/Notification/NotificationReadOnly/index.jsx
- packages/webapp/src/containers/notificationSlice.js
- packages/webapp/src/stories/Notification/NotificationTimeline.stories.jsx
- packages/webapp/src/util/useTranslationUtil.js
Ticket: [LF-2462](https://lite-farm.atlassian.net/browse/LF-2462)
Created a notification timeline for viewing notifications related to the same entity (eg. a task).
To test:
- See [Figma](https://www.figma.com/file/F3f6DpGcxAaEsxfl7OZkI2/Litefarm?node-id=27547%3A88602&properties-panel-tab=code) for design expectations.
- Assign a task to yourself, then reassign/unassign it (we want to trigger two notifications);
- Go to the notification related to the above event, make sure that we see the notification timeline with the two notifications
- If you are viewing the "Assigned task" notification, make sure that the warning box shows up
- In the timeline, you should be able to click the different items to switch between related notifications
> LF-2462 - feat: created notification timeline

- packages/webapp/src/components/WarningBox/index.jsx
Fix for the colour of the notification timeline warning box. The border, icon, and hyperlink should all be the same colour.
> fix: border and icon colour override for warning box

- packages/api/src/controllers/userController.js
- packages/api/src/controllers/userFarmController.js
- packages/api/src/routes/userFarmRoute.js
- packages/webapp/src/components/Profile/EditUser/index.jsx
- packages/webapp/src/containers/Profile/EditUser.jsx
Ticket [LF-2478](https://lite-farm.atlassian.net/browse/LF-2478)
**To Test:**
1. Create a pseudo user (Go to people tab of the farm and invite a user without an email)
2. Click the pseudo user and click "Convert this worker to a user with account"
3. You should see all the fields same as regular invitation UI
4. Fill out the form and invite the user
5. Check in the users table from the database that the information has been correctly updated
> LF-2478/pseudo user conversion ui change

- packages/api/src/controllers/taskController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
Note that this intentionally inserts `MISSING` as a substring in a key for non-English languages where words are missing from the otherwise correct translation.
> Fix code, English for incorrect wording

- packages/api/db/migration/20220613141913_create_sensors_tables.js
- packages/api/db/migration/20220614195741_sensor_reading_types.js
- packages/api/src/controllers/sensorController.js
- packages/api/src/models/sensorModel.js
- packages/api/src/models/sensorReadingModel.js
- packages/api/src/routes/sensorRoute.js
- packages/api/src/util/ensemble.js
To test:
1. Run migrations from api folder, you should see two new db tables `sensor` and `sensor_reading`
2. Make calls to the sensor endpoints and ensure the data is stored in the db correctly.
Here is some general information to help you make the api calls
- To add a reading, the sensor that reading belongs to must exist in the db. I suggest creating sensors manually and adding readings through the api since the `add_sensor` endpoint is part of a different ticket
- Here is an example POST that ensemble may send to the `add_reading` endpoint
`[
{
"node_esid": "123",
"sensor_esid": "124",
"parameter_number": "Temperature",
"unit": "ºC",
"time": [
"02-09-2022, 22:53:52",
"02-09-2022, 22:54:07"
],
"value": [
1,
2
],
"validated": [
false,
false
]
},
{
"node_esid": "123",
"sensor_esid": …
> Lf 2484 structures to support sensors

- packages/webapp/src/containers/Crop/CropVarietySpotlight/index.jsx
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/saga.js
To test:
1. If you don't already have one, create a crop plan on your farm
2. Invite a farm worker from your current farm. Make sure the invitee would be making a fresh account when they receive the invitation
3. Sign in from this new worker and navigate to the crop plan you made.
4. You should see the appropriate spotlight only once. Click the details tab and ensure you do not see the spotlight again. You can also re-navigate to this same page to ensure you do not see the spotlight again
5. Navigate to the map and ensure you only see the spotlight once. Try creating an area or re-navigating to the map to make sure of this as well.
> Bug fix for map and crop variety detail page

- packages/api/db/migration/20220620183106_fix_notification_user_names.js
The issue on beta seems to have been that there were names that contained double quotes within them. This PR escapes those quotes
> Added quote escapes

- packages/api/src/controllers/sensorController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Card/NotificationCard/NotificationCard.jsx
- packages/webapp/src/components/util/getNotificationTypeIcon.js
- packages/webapp/src/containers/Map/constants.js
- packages/webapp/src/containers/Map/index.jsx
This PR should be merged into `collab/sensors` branch after `feature/ensemble-communications` is merged into `collab/sensors`
Ticket [LF-2526](https://lite-farm.atlassian.net/browse/LF-2526)
To Test:
1. Call `sensors/add_sensors` endpoint (you can comment out the actual functionality in `sensorController` if you only want to test the notification without actually uploading sensors)
2. A new notification should be created in the notification center
3. "Take me there" will take you to the map with all locations visible (you can set your map filters before clicking "Take me there" and see if the filter settings are gone)
> LF-2526 successfully created sensors notification

- packages/api/src/controllers/taskController.js
- packages/api/src/models/userFarmModel.js
- packages/api/tests/taskNotification.test.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
This PR addresses https://lite-farm.atlassian.net/browse/LF-2463
To test:
1. Create a task and assign it someone (you should be on an account with farm management permissions)
2. Unassign that task
3. You should get a notification on all management accounts for that farm that the task has been unassigned
4. The notification should not appear for any worker accounts
5. Because I did a little refactoring in the code that sends notifications based on tasks, test some other use cases of task notifications and ensure they are still sending properly
> Added unassigned notification, did small refactor

- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
This PR resolves https://lite-farm.atlassian.net/browse/LF-2519
To test:
1. Create a crop plan
2. Ensure that the only fields you can see in the "detail" tab are the plan name above the tabs, as well as the Plan notes, and Estimated annual harvest
3. Complete the crop plan. You should now be able to see all the same fields before in the details page, as well as: Completed date, Plan rating, and Completion notes
> Fixed which fields display on a completed crop plan

- packages/webapp/src/containers/Home/utils/season.js
Ticket: [LF-2480)](https://lite-farm.atlassian.net/browse/LF-2480)
Switched from using moment js to javascript date object to fix season image issue. (Note, the month value in the javascript date object is from 0-11. So June is 5 not 6 as we would expect).
To test:
- create a farm in the northern hemisphere (ex. Canada) and farm is the southern hemisphere (ex. Australia)
- Make sure the image being shown in the north is summer (since it is currently June 28).
- Make sure the image being shown in the south is winter
> LF-2480 home page background displays the wrong season

- packages/api/src/controllers/sensorController.js
- packages/api/src/util/sensorErrors.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/components/Notifications/index.jsx
- packages/webapp/src/util/sensor.js
This PR handles the sync/async outcomes based off how long the flow is taking.
To test:
1. In `sensorController.js` on line 42, set the timeout to something small, like `50`
2. Comment out line 134 in `sensorController.js` as the webhook won't register properly until we are on beta/avocado
3. Try uploading a test csv file - you should see an error snackbar appear, this is because the 202 response code is not currently handled on the frontend in this branch - that is being handled in #2099 
4. Go to the notification that has been generated, it should have a "take me there" button which either a) downloads a text file if there were errors, or b) takes you to the map if it was successful
A useful testing file is: 
[testBulkUpload.csv](https://github.com/LiteFarmOrg/LiteFarm/files/9002688/test …
> Lf 2525 handle asynchronous add sensor outcome

- packages/api/src/controllers/sensorController.js
- packages/api/src/models/sensorReadingModel.js
- packages/api/src/routes/sensorRoute.js
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/mapSensorSlice.js
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/store/reducer.js
Ticket [LF-2533](https://lite-farm.atlassian.net/browse/LF-2533)
7 last days sensor readings of a farm will be populated into the redux store when the farm map is opened.
To Test:
1. Create some dummy sensor reading data (you can manually create them into the db)
2. On `packages/webapp/src/containers/Map/index.jsx` you can console log `mapSensorReadings` from line 333 to see the data when the farm map is opened.
> Lf 2533 refresh store with last x days sensor readings when opening farm map

- packages/api/src/controllers/sensorController.js
- packages/api/src/util/sensorErrors.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/components/Notifications/index.jsx
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/bulkSensorUploadSlice.js
- packages/webapp/src/util/sensor.js
This branch has the changes from #2102 and #2099 on it as well, so until that is merged there will be a large number of changes here. This PR adds the frontend handling of the partial success scenario when claiming sensors.
To test:
1. Comment out line 132 in sensorController.js
2. Navigate to the map
3. Coordinate with @Cali0707 and whoever else is testing this to ensure that some of your sensors in you csv are claimed and some are not
4. If the sensors fail synchronously, you should be able to click on the link and view the text file
> Lf 2458/handling partial success bulk sensor upload

- packages/api/src/models/sensorModel.js
I believe this fixes a crash experienced with beta api. Operations using db transactions should be wrapped with `try`, and `catch` block should rollback transaction. Otherwise knex connection pool becomes exhausted.
> Add try/catch

- packages/api/src/controllers/userFarmController.js
- packages/webapp/src/containers/Callback/saga.js
This PR addresses the comment to this ticket [LF-2478](https://lite-farm.atlassian.net/browse/LF-2478)
To Test:
1. Create a user account (in a different language than English)
2. Log into a farm that you already have and create a pseudo user
3. Convert that pseudo user to a user with an account but invite the user from step 1 (select English or a language different from step 1 as the language of invitation)
4. The invite email and the app should be in the language of the existing user rather than the language from step 3
> LF-2478 conversion of pseudo user to use the existing user's language preference

- packages/webapp/src/containers/Map/useMapAssetRenderer.js
To test:
- Upload sensors where more than one point has the same lat and long
- Click on the cluster (green box with a number inside) with that lat long
- You should see something like this but for sensors:
> fix: overlapping sensor points

- packages/api/src/controllers/loginController.js
- packages/webapp/src/containers/CustomSignUp/constants.js
- packages/webapp/src/containers/CustomSignUp/index.jsx
- packages/webapp/src/containers/CustomSignUp/saga.js
- packages/webapp/src/containers/GoogleLoginButton/saga.js
- packages/webapp/src/containers/customSignUpSlice.js
- packages/webapp/src/store/reducer.js
Ticket: [LF-2614](https://lite-farm.atlassian.net/browse/LF-2614)
To test:
- Invite a user whose email is @gmail.com or backed by Google, such as a litefarm org user 
- Logout, or use a different browser to …
- Visit the app homepage. Click “Continue with Google”. Log in using the invited user’s email.
- You should see the inline error: `We've updated our infrastructure and you'll need to check your inbox for a farm invitation to proceed.`
> LF-2614: api crashes when user ignores invite and continues with google

- packages/webapp/src/containers/Filter/Tasks/index.jsx
- packages/webapp/src/containers/Task/index.jsx
- packages/webapp/src/containers/filterSlice.js
This PR fixes a class of bugs that were occurring on the tasks page (documented here: https://lite-farm.atlassian.net/browse/LF-2623). Whenever a user created or updated a task that referenced a resource (assignee, task type, location) that was created after the filter on the task page was initialized, the task would disappear. 
To test:
1. Go to the tasks tab
2. Create a new user
3. Go back to the tasks tab and assign a task to the new user
4. The task should still be there
5. Create a new task type
6. Create a task of the new task type
7. That task should show up
8. Create a new location
9. Create a new task with that location set as its location
10. That task should show up
> LF-2623 tasks not showing up

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/bulkSensorUploadSlice.js
- packages/webapp/src/util/sensor.js
This resolves https://lite-farm.atlassian.net/browse/LF-2645 and also translates all the error downloads
To test:
1. Without setting up an ngrok tunnel or commenting out the code to register a webhook with ensemble, upload sensors
2. You should get an error file instead of a snackbar
3. Set up an ngrok tunnel or comment out the code to register a webhook with ensemble
4. Upload sensors
5. See if the error download is translated (should be full of "MISSING" in other languages)
> Changed default error behaviour to be more consistent with other errors, translated error files

- packages/webapp/src/components/Map/LineMapBoxes/index.jsx
To test:
1. Navigate to your farm map
2. Begin the process to add a watercourse
3. Play around with the values in the input fields. If you surpass the maximum acceptable value, you should see a warning. Any values greater than the acceptable max should default to the maximum (not in the input field but visually) and not be accepted.
4. Repeat steps 2-3 for a buffer zone
**NOTE:** If you have any, please make suggestions on how to better deal with the constant defined on line 61 of packages/webapp/src/components/Map/LineMapBoxes/index.jsx.
> Lf 2577 shifting issue for watercourse and buffer zone

- packages/webapp/src/containers/LocationDetails/LineDetails/BufferZoneDetailForm/saga.js
To test:
1. Begin creating a buffer zone
2. Enter a very large value for the width, enough that it start shifting.
3. Click confirm, then enter random information in all fields of the form. The form doesn't let you continue when the width value is too big so adjust for that
4. Click the '<' button, click confirm again, then proceed to saving the buffer zone while entering all the info
You should be returned to the map with your new buffer zone
> User is returned to map after creating buffer zone

- packages/api/src/controllers/sensorController.js
There is a bug reported by Mwaya where the validation did not work properly if a non-csv file was passed in (e.g. a text file). 
To test:
1. Comment out line 176 in `sensorController.js`
2. Upload a text file to the endpoint using Postman or Insomnia or another http client
3. The API should return a 400 response if it is not a valid csv file that matches the spec
> Fixed validation of non-csv files

- packages/api/src/controllers/sensorController.js
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/components/Notifications/index.jsx
- packages/webapp/src/util/sensor.js
Due to recent changes to the `createSensorErrorDownload` function some issues resulted for the sensor fail notification which are dealt with in this PR.
To test:
- Add an item to local storage: `sensorUploadTimer : 10` to trigger the async flow
- Upload sensors to trigger failures and partial successes. See that the error download is working as expected in the notification when clicking "Take Me There"
- Try this in different languages as well
> LF-2527 - fix: sensor error download issue for sensor fail notification

- packages/webapp/public/locales/en/translation.json
Ticket: [LF-2527](https://lite-farm.atlassian.net/browse/LF-2527)
Quick changes to the notification title and text.
> fix: text for body and title of sensor upload fail notification

- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/index.jsx
To test:
1. Open the 'Network' tab in your browsers developer tools.
2. Navigate to a sensor's details view. In the network tab,  ensure the necessary callouts are being made once and not redundantly
> Sensor details only makes necessary callouts

- packages/webapp/src/components/SensorReadingsLineChart/index.jsx
- packages/webapp/src/components/SensorReadingsLineChart/styles.module.scss
- packages/webapp/src/containers/SensorReadings/index.jsx
To test, 
1. go to http://localhost:3000/sensor/<location_id>/readings.
2. make sure to have sensor readings in the pg-litefarm local database.
3. check if you can see legends with a dot.
4. click on the legend and see if the graph shows or hides the line.
Also, try adding some location ids as follows:
File Location: packages/webapp/src/containers/SensorReadings/index.jsx
You'll be able to see this after adding multiple location id:
After clicking on legends:
Repeat the above steps to test activate/inactivate lines on the legends click.
For more information, please check 
https://lite-farm.atlassian.net/browse/LF-2502
> Legends activation and deactivation on Line Chart

- packages/api/src/models/locationModel.js
- packages/api/src/models/sensorModel.js
This PR fixes issues with sensors not being undeleted on subsequent uploads (see comments on https://lite-farm.atlassian.net/browse/LF-2646)
To test:
1. Set deleted = true on a sensor's location
2. Re-upload that sensor
3. The sensor should now have deleted = false on its location
> Added undelete functionality

- packages/api/src/controllers/organicCertifierSurveyController.js
Per [LF-2692](https://lite-farm.atlassian.net/browse/LF-2692) this modifies certification exports to include documents that did not expire before the report’s start date. That is, include the document if `document.valid_until >= report.start_date`.
> Fix date range logic

- packages/api/src/controllers/sensorController.js
To test:
1. Upload a non-integrated sensor. A non-integrated sensor is one without a brand name or external id
2. After that sensor is successfully uploaded, go to that sensors details view by clicking on its icon in the map
3. Retire that sensor
4. You should see a success message snackbar. As an extra check, you can check to see if that sensor is deleted in the location table in your db.
> Retiring a non-integrated sensor no longer fails

- packages/webapp/src/components/LocationDetailLayout/PointDetails/Sensor/index.jsx
- packages/webapp/src/containers/SensorReadings/index.jsx
To Test:
Upload a sensor
Go on the sensor details page and flip through the readings details and task tabs and make sure the router tabs' padding are all the same
> Fixed differences in sensor pages UI

- packages/webapp/src/components/Modals/BulkSensorUploadModal/FileUploader.jsx
Ticket: [LF-2674](https://lite-farm.atlassian.net/browse/LF-2674)
To test: 
- Upload an invalid sensor upload file named “test.csv”
- View validation errors
- Click the upload symbol
- Upload a valid sensor upload file named “test.csv”
- Validation for the file should be run again
> LF-2674: Changing the contents of a sensor upload file but not the name requires restarting the upload flow

- packages/api/src/controllers/taskController.js
- packages/api/tests/task.test.js
This PR removes the check for dates in the past @smattingly per the discussion here: https://lite-farm.atlassian.net/browse/LF-2634
> Removed date check for update task

- packages/api/src/controllers/loginController.js
This PR fixes the API crashes from the login flow, although it doesn't address why users without a password in the password table were able to log in with a password through the UI as I was unable to recreate that.
To test:
1. Create a user with a password
2. Log out and verify that you can log back in with the password
3. Delete the password from the password table
4. Try to log in again - you shouldn't be allowed to login, but the API shouldn't crash anymore
> Prevented api from crashing

- packages/api/src/controllers/sensorController.js
- packages/api/src/models/locationModel.js
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/Map/useMapAssetRenderer.js
This PR makes the map update to show newly updated sensors on both a full success and a partial success. It also resolves  a small bug described in the comments on https://lite-farm.atlassian.net/browse/LF-2645 
To test:
1. Upload a file with one ESID which is claimed on another farm and one which is free - you should get one sensor added to your map, and a valid error message.
2. Unclaim the ESID which is claimed on another farm and upload the file again - you should be able to see both sensors on the farm map now
> Fixed map update for sensors

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/Form/Input/utils.js
- packages/webapp/src/components/Task/AbandonTask/index.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
Ticket [LF-2618](https://lite-farm.atlassian.net/browse/LF-2618)
To Test:
1. Go to an existing crop plan (or create one if not).
2. Go through the abandon crop plan flow.
3. Change the "Date of status change" to a future date by clicking the input form and manually typing in a future date (calendar selection is already disabled for future dates).
4. There should be an in-line error message and "Abandon" button should be disabled.
> LF-2618 Entering in an abandon/completion future date for a plan, doesn't change status

- packages/api/db/migration/20220804164229_estimated_seeds_unit_add_tonnes.js
- packages/api/src/models/plantingManagementPlanModel.js
Ticket (See latest comment):  [LF-2521](https://lite-farm.atlassian.net/browse/LF-2521)
To test:
- Run the latest migrations
- Start the flow to creating a planting crop plan
-  Choose rows as planting method
- Enter an amount for 'Estimated seeding' and change the unit to `mt`
- Complete plan creation flow
> fix: crop plan 400 error on setting estimated seeding to mt

- packages/api/src/controllers/sensorController.js
This PR just adds a little bit of extra safety into our sensor upload flow, and sends a generic error message if the ensemble API returns data that is not in the expected format for some/all of the sensors.
> Added extra case in handling the ensemble sensor claim response

- packages/api/src/controllers/supportTicketController.js
- packages/api/src/routes/supportTicketRoute.js
This PR makes it so that if you put down a separate email than your account email when requested support, you only get a single email.
To test:
1. Click on the profile icon in the top right corner
2. Click on "Help"
3. Try sending a help request with the default email for your account - make sure you get this email!
4. Try sending a help request with a different email than the one associated with your account - make sure you get this email!
> Lf 2595 received two requests for help when modifying the preferred contact method for email

- packages/api/src/controllers/userFarmController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Modals/InvalidRevokeUserAccessModal/index.jsx
- packages/webapp/src/components/Profile/EditUser/index.jsx
Ticket [LF-2253](https://lite-farm.atlassian.net/browse/LF-2253)
To Test:
1. Create a farm with one admin account (try one admin and no workers, try one inactive admin and one active admin, try two active admins, etc.).
2. Go edit the last admin's profile.
3. Click "Revoke User Access".
4. "Cannot revoke access" modal should pop up instead of "Revoke User Access" modal.
5. If you click "here" in the modal, it should redirect you to Request Help page.
> LF-2253 when revoking a users access ensure at least one fo fm or eo retains access to the farm

- packages/webapp/src/components/InviteUser/index.jsx
- packages/webapp/src/containers/InviteUser/index.jsx
To test:
1. Create a new user on a farm
2. Try and invite a second user who has the same email as either your current user or another user on the farm
3. There should be an inline error which prevents you from inviting the user until you have provided a valid email
> Fixed invite flow to have inline error when user with same email already exists

- packages/api/src/models/sensorModel.js
This PR resolves the issues reported by Mwaya on https://lite-farm.atlassian.net/browse/LF-2672 
To test:
1. Retire a sensors on a farm
2. Re upload that same sensor
3. The sensor should show up on your map without you needing to refresh
> Made retired sensors show up when re uploaded

- packages/webapp/src/components/InviteUser/index.jsx
This PR resolves the issue described in the comments of https://lite-farm.atlassian.net/browse/LF-2672
To test:
1. Try and invite a pseudo user
2. This should work
3. Try and invite a non pseudo user using an email of an existing user on the farm
4. You should be shown an inline error
> Fixed bug where it was impossible to invite a pseudo user

- packages/api/src/controllers/sensorController.js
To test:
1. Upload a csv file where the `Reading_types` column is empty for a sensor through your favourite http client to `http://localhost:5001/sensor/`. You will need to set the Bearer token to be the one used by your currently authenticated user, and also set the farm_id header appropriately for this to work. The upload is a POST request with a multipart form data field where the key for the csv file is `sensors`
2. You should get a validation error
> Fixed regex and validation of empty case

- packages/webapp/src/containers/CustomSignUp/index.jsx
Ticket: [LF-2626](https://lite-farm.atlassian.net/browse/LF-2626)
Unfortunately this issue happens intermittently so it is hard to test. My hunch is that this issue had to do with the component not re-rendering on email change since it wasn't state. And I am no longer able to replicate the issue after making it state.
To test: 
- Start the flow to create a new account
- Go back and forth between entering your email and creating the account 
- Try this while using the Slow 3G option in the network tab
- Complete create account flow to see if that still works
> LF-2626 - fix: email not appearing correctly on create account

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
Create a task and abandon the task and set the reason for task abandoning to other and fill in the explanation. 
You should be able to click on the task read only card and be able to see the reason set to "other" and explanation there as well
> Other reason not showing up on read only task view

- packages/api/db/migration/20220812191948_defualt_reading_types.js
- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/saga.js
To test:
- Create a non ESCI sensor if you don't have one already
- Remove and re-add a sensor reading type
> fix: sensor reading types for sensors without brand

- packages/webapp/src/components/SensorReadingsLineChart/index.jsx
- packages/webapp/src/components/SensorReadingsLineChart/styles.module.scss
- packages/webapp/src/containers/SensorReadings/index.jsx
- packages/webapp/src/containers/SensorReadings/saga.js
- packages/webapp/src/containers/bulkSensorReadingsSlice.js
To test: 
1. go to http://localhost:3000/sensor/<location_id>/readings
2. check if you can find the following changes on the x-axis in the line chart:
```
CREATE OR REPLACE FUNCTION generate_sensor_readings(
readingType TEXT,
unit TEXT,
valid BOOLEAN,
startDate DATE,
endDate DATE,
tMax REAL,
tMin REAL 
) RETURNS INTEGER AS
$func$
DECLARE 
currentDate DATE := NOW();
valueData REAL := 0;
r RECORD;
s RECORD;
intervalDuration TEXT := '1 hour';
returnedID TEXT := '';
counter INTEGER := 0;
BEGIN
EXECUTE $$ TRUNCATE TABLE sensor_reading $$;  
FOR s IN SELECT * FROM sensor LOOP 
FOR r IN SELECT * FROM generate_series(
startDate,endDate, 
intervalDuration::INTERVAL) AS s(i) LOOP
valueData := ROUND((RANDOM()*(tMax-tMin)+tMin)::NUMERIC, 1);
EXECUTE $$
INSERT INTO public.sensor_reading(
location_id, …
```
> Added the x-axix ticks and x axis labels

- packages/webapp/src/containers/Map/useMapAssetRenderer.js
This PR resolves the issues discussed in the comments on https://lite-farm.atlassian.net/browse/LF-2632
To test:
1. Create a new farm, or go to a farm without any other locations on the map.
2. Add two gates that are close together on the map, but not touching at the closest zoom level.
3. Zoom out so that these gates appear as a cluster.
4. Click on the cluster - it should zoom you in and show the two locations, instead of showing a location selector popup and then showing the two locations.
> Fixed issue with clusters only sometimes working

- packages/api/src/controllers/sensorController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
Ticket [LF-2712](https://lite-farm.atlassian.net/browse/LF-2712)
To Test:
1. Create a "add sensors to litefarm" CSV file with invalid reading types.
2. Upload the file and download the error message.
3. The error message format should be changed to as described by the ticket.
> LF-2712 improve error message format for reading types

- packages/api/src/controllers/sensorController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
This PR resolves https://lite-farm.atlassian.net/browse/LF-2667, https://lite-farm.atlassian.net/browse/LF-2713, https://lite-farm.atlassian.net/browse/LF-2678, and https://lite-farm.atlassian.net/browse/LF-2725
To test:
1. Either use ngrok or comment out line 209 in `sensorController.js`
2. Take a valid sensor upload file
3. Duplicate one of the sensors (it should have the same brand and external_id as another sensor in the file)
4. Add an empty row after the existing rows (this works better in a raw text editor than in excel) - you can also put the empty rows between existing rows, but the frontend validation doesn't always allow this.
5. Upload this file - this should succeed! Only the first of the two duplicate sensors should be created on the farm, and it shouldn't complain about …
> Various sensor fixes

- packages/webapp/src/containers/Notification/index.jsx
This PR makes it so that the resources associated with a notification get refreshed when the user goes to the notifications page. To test:
1. Create at least one task on your farm
2. Do an action that would generate a task notification (e.g. assign the task to yourself)
3. Open the network tab in devtools and navigate to the notifications page
4. There should be a request made once you are on the notifications page to get all the tasks for the farm
> Added notification resource refresh with docs

- packages/api/src/controllers/sensorController.js
- packages/api/src/models/sensorModel.js
- packages/api/src/routes/sensorRoute.js
- packages/webapp/src/components/Map/PreviewPopup/index.jsx
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/sensorReadingTypesSlice.js
- packages/webapp/src/store/reducer.js
Read the latest comment by Mwaya from [LF-2528](https://lite-farm.atlassian.net/browse/LF-2528)
The issue was that sensor reading preview popup was being rendered for all sensors regardless of their reading types. If a sensor's reading type is "soil water content", the preview popup should not render compact temperature view. Currently, no matter what a sensor's reading types are, compact temperature view is visible.
Currently, reading types are added to the redux store (sensor individually) when a sensor detail's page is rendered. I tried to dispatch that action when a sensor's preview is activated, but that triggers re-rendering of the map component, which messes up the zoom level of the map. So I had to find a way to store reading types of all sensors of that farm when the map is …
> LF-2528 compact temperature component type bug fix

- packages/api/src/routes/sensorRoute.js
- packages/webapp/src/containers/Map/saga.js
This PR fixes the issue where `sensor/:farm_id/reading_type` endpoint was not returning anything.
> Hotfix: sensor reading type route failing

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/PlantingLocation/index.jsx
- packages/webapp/src/components/LocationCreationModal/index.jsx
- packages/webapp/src/components/LocationCreationModal/styles.module.scss
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/mapFilterSettingSlice.js
Ticket [LF-2642](https://lite-farm.atlassian.net/browse/LF-2642)
To Test:
1. Create a new farm without adding any locations on the map.
2. Create a new crop plan.
3. When entering select location page, there should be a popup.
4. Clicking "go back" will return the user to crop plan creation flow.
5. Clicking "create location" will redirect the user to the farm map with "+" tab expanded.
> LF-2642 crop plan based pop up for adding a location

- packages/webapp/src/containers/Notification/index.jsx
This fixes a small potential bug where the `getUpdateFromNotification` wouldn't return a String.
> Small bugfix

- packages/api/src/controllers/sensorController.js
Just a switch to the order of validation for header vs empty file validation
To test:
- Upload a file in a language different to the user's preference using Postman, Insomnia etc
- You should get header errors rather then empty file error
> fix: order of validation for empty file error vs other errors

- packages/webapp/src/components/Form/Input/utils.js
- packages/webapp/src/components/InviteUser/index.jsx
To test:
- Go to invite a new user to your farm
- Enter a name with a first name and/or last name greater than 255 characters
- You should get an appropriate inline error
> fix: invite user form name length validation

- packages/shared/validation/sensorCSV.js
To test:
- Change user preference to spanish
- With a tool like Postman or Insomnia, upload a valid sensor csv with the reading type "potencial_hídrico_del_suelo"
- This should succeed
> fix: spanish reading types issue

- packages/webapp/src/components/Map/Footer/index.jsx
Upon creating a new account, going to the map (either directly or indirectly from location creation popup) crashes the map.
To Test:
1. Create a new account.
2. Go to tasks and try creating a new task.
3. When a location creation popup comes up, click "create location".
4. You will see the map spotlight. Once you go through the rest of the spotlight, you will see the map with "+" tab expanded.
Try steps 1 - 4 for crop plans (creating a crop plan will prompt you to create a crop location first).
> fix: map spotlight crashes the map

- packages/webapp/src/containers/Map/constants.js
David wanted the long press to be shorter than what it currently is (0.8 seconds).
To Test:
1. Have sensors on the farm map.
2. Long press a sensor and the preview should pop up after holding the mouse down for 0.5 seconds.
> fix: change longpress to 0.5 seconds

- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/useDrawingManager.js
Ticket: [LF-2571](https://lite-farm.atlassian.net/browse/LF-2571)
To test:
- Create a new account
- Go to farm map
- Start process to create a new area
- Stop double click on initial point to stop drawing
- You should get zero area warning modal and no adjust area modal
- Same for new line
> LF-2571: drag points pop-up should only appear for accepted polygon

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/constants.js
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/index.jsx
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/components/Modals/BulkSensorUploadModal/FileUploader.jsx
- packages/webapp/src/components/Modals/BulkSensorUploadModal/index.jsx
To Test,
1. Open the app on the android device. 
2. go to the farm maps page.
3. select a non-CSV file and check if the validation error is shown.
For more details:
https://lite-farm.atlassian.net/browse/LF-2711
Adding screenshot:
> Lf 2711/add sensor upload in line error when non csv file is attached

- packages/webapp/src/components/Task/PureTaskCrops/index.jsx
To Test,
1. go to the crop plan page.
2. check the crop by its language-specific variety name.
3. check if the English version of variety is not getting filtered in the list.
For more details, Please check: 
https://lite-farm.atlassian.net/browse/LF-2622
> LF-2622 : Fix the language search issue in the crop plan page

- packages/webapp/src/components/Form/Unit/unit.module.scss
To Test:
1. go to crop management flow. select row.
2. you would see the following page, with UI fix:
Before
After
> LF-2430 : Fixed the UI shift issue

- packages/webapp/src/components/LocationDetailLayout/AreaDetails/Field/index.jsx
- packages/webapp/src/components/LocationDetailLayout/AreaDetails/Garden/index.jsx
- packages/webapp/src/components/LocationDetailLayout/AreaDetails/Greenhouse/index.jsx
To Test:
1. Be on an organic certification-pursuing farm
2. Select a field, garden, or greenhouse from the map. Select edit.
3. Select “Transitioning” from the “What type of field is this?” list
4. Select a transition date different from the preselected date
5. Select one of the other options, either “None organic” or “Organic”
6. Switch back to “Transitioning”
Expected result:
The previously selected date is maintained
Actual result:
The current date is preselected again.
https://lite-farm.atlassian.net/browse/LF-2575
> Lf 2575 : Fix: user selected date should be maintained for field garden and greenhouse when transitioning is unselected

- packages/webapp/src/components/Form/Unit/unit.module.scss
To Test,
1. go to http://localhost:3000/crop/<management_plan_id>/add_management_plan/row_method.
2. check if the UI is fixed for the text-overflow label above the unit's component input field.
Before: 
After:
> LF-2581: Fixed text label overflow issue of units component

- packages/webapp/src/components/Form/Unit/index.jsx
- packages/webapp/src/components/Form/Unit/unit.module.scss
To Test:
go to crop management flow. select row.
you would see the following page, with a UI fix:
Before:
After:
> Fixed the cross display issue on the unit components

- packages/webapp/src/components/Task/PureTaskCrops/index.jsx
To Test,
1. go to the crop plan page.
2. check the crop by its language-specific variety name.
3. check if the English version of variety is not getting filtered in the list.
For more details, Please check: 
https://lite-farm.atlassian.net/browse/LF-2622
> LF-2622 Fix: Task creation crop search including English crop names

- packages/webapp/src/components/Map/MarkerCluster/index.jsx
To Test,
1. go to the farm map.
2. click on the export icon i.e last option in the bottom navigation bar.
3. click on the download map button 
check if you can find numbers on the clustered sensors plotted in the farm map
Before 
After
For more details, please check: 
https://lite-farm.atlassian.net/browse/LF-2735
> LF-2735: fixed the cluster number that was not getting displayed on farm map export click

- packages/webapp/src/components/Form/Unit/index.jsx
I returned the font color to the value set in `ReactSelect` referred to as default styles in `Unit`. Seems to work in views mentioned in Jira for: area creation, task creation, and crop plan creation.
> singleValue for units should be black not grey

- packages/webapp/src/components/Modals/OrganicStatusMismatchModal/index.jsx
To Test:
1. Click outside of the modal and check if the user can able to move to the next step or not.
2. If the modal is dismissed and the user stays on the very same page, this means the bug is fixed.
> Fix : on modal outside click the user is not taken to the next step

- packages/webapp/src/components/Form/Unit/index.jsx
- packages/webapp/src/components/Form/Unit/unit.module.scss
@kikemarquez8 
What this solves:
- input container blocking the units multi-select
- mismatch between pseudo-container sizes and combined input and units size.
- future z-index problems
My changes:
1. UNIT line 81, 384 and CSS line 125 - This deals with the the 'pseudoInputContainer' not sizing properly to acommodate the lack of multi-select arrow
2. UNIT line 114, and CSS line 141-145 - This puts the decision to background color off of the 'pseudoInputContainer' which is higher in the z-index causing the cover up back onto the calue container
3. UNIT line 382 - Disables the vertical divider for all disabled units not just where units' options.length <=1.
4. Removes z-index's and extra CSS - line32 of CSS causing overlap onto dropdown- Basically I recently learned of this principle of: …
> A different fix for missing units

- packages/api/src/controllers/sensorController.js
- packages/api/src/models/sensorModel.js
To Test:
1. add sensors to your farm or go to the farm having sensors.
2. call the following API from your postman: 
POST URL: <base_url>/sensor/reading/partner/1/farm/<farm_id>
headers: authorization: <farm_id>sensor_secret
check the soft delete condition so that we get the correct location_id for the recently added sensor to a new farm.  
1. Please connect with me on call to see if it's working.
2. https://lite-farm.atlassian.net/browse/LF-2454
Adding Screenshot for better understanding:
> Addition of soft delete condition to get location_id for sensor readings 

- packages/webapp/src/components/Task/TaskLocations/index.jsx
**Description:**
Fix for [LF-2864](https://lite-farm.atlassian.net/jira/software/c/projects/LF/issues/LF-2864?filter=myopenissues) handle deselect of location on click of selected location.
**To Test**
Add a new task [one of: Transplant task or Irrigation task]. When you reach the location selection part of task creation you should be able to deselect a location by clicking on that same selected location.
**Code details**
OnSelectLocation now checks if the selected location is already the first in the array. Now nested under an isMulti check.
> LF-2864 - refactor TaskLocation to handle deselect

- packages/webapp/src/components/Map/PreviewPopup/index.jsx
To Test,
1. Add a sensor to the farm
2. on the farm map page, long click on the sensor point.
3. check if the error is handled 
Before: 
After:
> Added error handling of soil water potential unit in the preview tab

- packages/api/db/migration/20221207172217_alter_field_work_type_table.js
Based on the following comment: 
Here is the new migration change I have made.
To Test,
1. run the latest migration 
2. go to the field_work_type table and check deleted column is present with the default value as false.
> Addition of the deleted column to the field_work_type table

- packages/webapp/src/containers/CropVarieties/index.jsx
- packages/webapp/src/containers/CropVarieties/useCropVarietyCatalogue.js
Crop variety catalogue should now be using the crop_variety_photo_url instead of any default crop_photo_url.
**Testing**
For UI testing - probably have to wait until it is merged into beta unless your local interacts with AWS.
Backend - The only way I could test this was to enter debugging mode and view that a url is indeed being supplied to the crop_variety_photo_url
[Jira ticket](https://lite-farm.atlassian.net/browse/LF-2701?atlOrigin=eyJpIjoiNGFkZDY1Y2RhNTRmNGI1ZmE2MDVhNTU3N2U1NDZlM2IiLCJwIjoiaiJ9)
> Lf 2701 custom crop photo for new crop crop not displaying on crop varieties or crop catalogue page if added via edit

- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
persist application depth and % of location to be irrigated values for the depth measurement type when user clicks out of the model
> fix water use calculator

- packages/webapp/src/components/Form/Checkbox/checkbox.module.scss
- packages/webapp/src/components/Form/Checkbox/index.jsx
[Jira Ticket LF-2930](https://lite-farm.atlassian.net/browse/LF-2930)
Adding tooltipContent functionality to Checkbox Form element
**What was done**
Pushed the tooltipContent attribute through Checkbox and into the existing Main component in /Typography.
Removed excess styling causing alignment issues when adding a tooltip.
Another component being used by checkbox: `<Main />`. It uses a toolTipContent as a bool so the 'undefined' was necessary to prevent always being rendered. Used `<PurePlantingDate />` as similar use of Main's tooltip.
**How it was tested**
1. Added _tooltipContent="your tooltip content here"_ to one Checkbox on a form and compared to one without tooltip. (Irrigation task is a good candidate for this).
2. Made sure alignment is good in multiple existing …
> Lf 2930 form element checkbox does not have the option for a tooltip

- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/EditSensor.jsx
- packages/webapp/src/containers/Map/saga.js
- packages/webapp/src/containers/SensorReadings/index.jsx
There are two bugs for creating a sensor:
- after a sensor is created, the app crashes by clicking the sensor icon on the map
- the app crashes when a sensor is created with the reading type "soil_water_content"
What is done:
- after creating a sensor, update `sensorReadingTypes`(`getAllSensorReadingTypes()`) state in redux
- enable `sensorReadings` component to handle the sensorReadingType `soil_water_content`
Jira link: https://lite-farm.atlassian.net/browse/LF-2933
Please delete options that are not relevant.
1. go to `/map`, click "+" button and create a sensor. 
2. click the sensor icon on the map.
3. you should see graph/empty box for the reading type(s) of the sensor you just created.
1. create a sensor with the reading type `soil_water_content`, and do 2-3.
If reading types of the …
> LF-2933: After selecting a recently uploaded sensor I get a white screen

- packages/webapp/src/components/Modals/WaterUsageCalculatorModal/index.jsx
- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
This changes the Water use calculator removes a few unnecessary ternary operators that were setting default values to '1' . This was allowing calculations without the necessary values to compute. 
It also fixes a minor spelling mistake.
Jira link: [LF2919](https://lite-farm.atlassian.net/browse/LF-2919?atlOrigin=eyJpIjoiNWZkYjE3MDNhZDI4NGNlYjg5NDY0MGMwZTQ4ZGJhNDYiLCJwIjoiaiJ9)
**Checklist:**
> Lf 2919 inconsistent behaviour between depth and volume water usage calculator

- packages/api/src/controllers/managementPlanController.js
- packages/api/tests/managementPlan.test.js
This PR fixes the bug where a crop management plan could not be created using a cover crop. Previous to this fix, when adding a crop plan and selecting "Is this being grown as a cover crop or for harvest?" > "As a cover crop", plan creation (saving) failed, returning a 400 status and validation error.
Jira link: https://lite-farm.atlassian.net/browse/LF-2931
The issue:
- Creating a new crop management plan with a cover crop also generates a new field work task for its termination. The code controlling this was attempting to set a non-existent property 'type' on the field work task
- This part of the codebase was currently uncovered by the API testing suite
The solution:
- An additional query was introduced to retrieve the field_work_type_id from the field work type table, and this was …
> Lf 2931 unable to create a crop management plan for a plant that can be grown as a cover crop

- packages/webapp/pnpm-lock.yaml
The pnpm-lock.yaml in packages/webapp is out of sync with its package.json, causing this error on `pnpm install --frozen-lockfile`
> Cannot install with “frozen-lockfile” because pnpm-lock.yaml is not up-to-date with package.json
This commits an updated pnpm-lock.yaml from a fresh `pnpm install` that will not cause this error.
Jira link: https://lite-farm.atlassian.net/browse/LF-2950
- Locally: deleting node_modules and running `pnpm install --frozen-lockfile` with this lockfile causes no errors.
Mostly N/A as the lockfile is automatically generated by pnpm
> LF-2950 Add updated pnpm-lock.yaml following pnpm install

- packages/webapp/src/components/Documents/Add/index.jsx
<h2>Description</h2>
Set "This file does not expire" to true if user does not provided an "Valid until" date in add document page.
Jira link: [LF-2656](https://lite-farm.atlassian.net/browse/LF-2656)
<h2>Type of change</h2>
<h2>How has this been tested?</h2>
1. Go to documents page and click in "+Add a new document" link.
2. In put a name, but don't add a "Valid until" date nor select "This file does not expire".
3. Click in "Save" button.
[LF-2656]: https://lite-farm.atlassian.net/browse/LF-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 2656 not entering a date on document upload archives the document

- .github/pull_request_template.md
- add the copyright link in Confluence page
- move "Please delete options that are not relevant." up to the top
> LF-2850(2): Add copyright link

- packages/shared/validation/sensorCSV.js
fix: sensor CSV now checks row uniqueness by brand:external_id if available, else it uses sensor name
> LF-2957-Bulk-sensor-upload-ignores-sensors-beyond-the-first

- packages/api/src/models/sensorModel.js
fix: sensors from no integrating partners are assumed that are always new since there is no external_id to match if it has been previously deleted
> LF-2951-Retired-sensors-become-active-again-when-attempting-to-upload-new-sensors

- packages/webapp/src/containers/Finances/OtherExpense/index.jsx
Reformat date to display in correct format as per user's browser localization.
Jira link: https://lite-farm.atlassian.net/browse/LF-2842
**Steps to recreate:**
1.  Log in to your farm
2. Navigate to finances
3. Filter for a date range with expenses
4. Click “Other expenses”
**Desired:**
- Date is displayed in correct format for user browser localization
**Observed:**
- Displays in yyyy-mm-dd
Follow [this](https://www.aleksandrhovhannisyan.com/blog/changing-locale-in-chrome-with-dev-tools/) guide to change locale in chrome for testing.
**Checklist:**
> Lf 2842 reformat date display based on regional preference

- packages/api/.env.default
- packages/api/src/templates/sendEmailTemplate.js
Currently, LiteFarm emails (sent when, e.g., joining a farm or inviting users) are only sent from system@litefarm.org and require the Beta/Production gmail API keys and refresh token to work.
This PR adds the option of sending, in the development environment only, emails from another account with either 1) the correct OAuth2 credentials or 2) an app password set up through Google. Instructions for generating those credentials were added to `.env.default` along with more precise instructions about what the beta/production keys are for. To set up OAuth2, the currently unused `LITEFARM_SERVICE_EMAIL` environment variable was re-introduced.
This change is entirely opt-in; emails should continue to work as before whether the developer's `.env` file contains the official beta/production keys or …
> LF-2976 (Feat) Allow sending LiteFarm emails from personal accounts in development environment

- packages/webapp/src/components/Task/FieldWorkTask/index.jsx
User is able to complete creating field work task flow without selecting field work. The button should be disabled if "type of field work" is not selected.
Jira link: https://lite-farm.atlassian.net/browse/LF-2952
**Steps to reproduce:**
1. go to `/task`
2. select 'field work task' and continue with the flow
3. On final screen, user should not be able to continue without selecting “type of field work”.
**Checklist:**
> Lf 2952 user is able to complete creating field work task flow without selecting field work

- packages/api/src/controllers/taskController.js
- packages/api/tests/task.test.js
@MwayaB spotted that `override_hourly_wage` needs to be updated to `true` when `wage_at_moment` is set.
Thank you Mwaya!!!
On the UI, when assigning a task and override a wage for the task, `override_hourly_wage` in the task table is updated to `true`.
**Checklist:**
> LF-2938: [fix] Set 'override_hourly_wage' to true when setting wage_at_moment 

- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
- packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
This irrigation task PR includes the following:
- In the “Mark complete” flow, when a user select “Yes” to “Did you have to make any changes to this task?” Each of the default checkboxes should be visible but disabled
-  When a user goes to complete an irrigation task that was created with default checkboxes checked, the task completion page will show which boxes the user checked and the checkboxes are disabled. However, if a user select "Yes" to make changes to this task, the check boxes uncheck themselves and are still disabled. In either cases, they won't set default values again once the task is complete. Default values are only set during creation.
- In the original file, there was a hard coded constant with all the default irrigation types for translation. The …
> Lf 2955 spike investigate current irrigation task architecture

- packages/webapp/.npmrc
- packages/webapp/package.json
This PR increases the memory allocated to node to see if that fixes the heap memory errors on running vite build in our integration deployment script.
Jira link:
**Checklist:**
> Increase memory allocation for vite build

- packages/webapp/package.json
This allocates even more memory to node for the vite build script - 32GB
Please see https://github.com/LiteFarmOrg/LiteFarm/pull/2495, which still produced a JavaScript heap memory error (with 4GB of memory allocated).
This will be tested by running deploy upon merge.
**Checklist:**
> Increase memory allocation for vite build #2

- docker-compose.beta.yml
- packages/webapp/package.json
- packages/webapp/prod.Dockerfile
This is a continuation of our troubleshooting of the deployment of the integration branch to beta.litefarm.org.
**Background**
For information on the original build error:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2495
Unsuccessful attempts to address this build error:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2496
- https://github.com/LiteFarmOrg/LiteFarm/pull/2497
This PR successfully addressed the memory error and allowed build to complete:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2500
However, the API of this deployment began crashing shortly after.
**The current PR**
- Moves the memory allocation to the correct place in the build run script (thank you @JimmyRowland)
- Removes memory allocation from the frontend dockerfile
- Swaps the building of the …
> Revise docker build by moving memory allocation to build script and swapping container build order

- packages/webapp/src/components/Typography/index.tsx
We recently removed `"noImplicitAny": false` from our tsconfig.json in
- https://github.com/LiteFarmOrg/LiteFarm/pull/2460
This PR fixes two instances of implicit any in the Typography component file, which was causing tsc errors on the deployment of:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2471
Ran `pnpm run build` (which calls `tsc`) locally.
**Checklist:**
> Add types to the TextWithExternalLink component to fix implicit any

- packages/webapp/src/containers/LocationDetails/LineDetails/FenceDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/LineDetails/WatercourseDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/PointDetails/GateDetailForm/saga.js
- packages/webapp/src/containers/LocationDetails/PointDetails/WaterValveDetailForm/saga.js
On completion of drawing line elements: fence and watercourse and point details: gate and valve  -- modals would remain on screen after completion of the drawing form.
By switching the history.back() to history.push('/map') the correct behaviour is observed. history.back should be used for 'back-like' actions.
Jira link: [LF-2973](https://lite-farm.atlassian.net/browse/LF-2973?atlOrigin=eyJpIjoiNTA2NTcxMjllNjBjNDgzYThhODhkMTNlNTc4MjllY2UiLCJwIjoiaiJ9)
- On integration the behaviour to be fixed is: 
- draw one of the elements mentioned in the description on …
>  LF-2973-confirm-page-still-showing-after-saving-a-point-or-a-line

- packages/webapp/prod.Dockerfile
As of version 8.0.0, pnpm no longer supports Node versions under 16.14. This causes an error on deploy as we had been using Node 16.13.2 in our frontend dockerfile.
This PR updates the dockerfile node version to 16.15.0, the same Node version used in our API dockerfile.
For more info, see:
- https://github.com/pnpm/pnpm/issues/6297
Tested on local Docker build.
**Checklist:**
> Upgrade node version to 16.15.0 in webapp dockerfile

- packages/webapp/src/components/Modals/WaterUsageCalculatorModal/index.jsx
- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
- packages/webapp/src/containers/Task/saga.js
- packages/webapp/src/stories/Modal/WaterUsageCalculatorModal.stories.jsx
- packages/webapp/src/test-utils/storybook/unit.jsx
- packages/webapp/src/util/convert-units/unit.js
- Fix total water usage calculation (Please check if the formulas are correct!)
- Use `defaultValue` and `to` props for `Unit` component to set default values (flow rate, location size, and application depth). `setValues` are removed.
- Update irrigated area unit depending on “% of location to be irrigated”
- Pass `location` from its parent component rather than doing `useSelector` in the child component (this is to be able to write storybook tests)
- Delete `location_size` before sending an API request for irrigation task creation (this should have been done in [LF-3055](https://lite-farm.atlassian.net/browse/LF-3055))
- Fixed `location_area` constant (now it’s the same as `area_total_area`)
- Update `UnitTest` class so that it can be used for modals. 
`canvas` cannot be …
> LF-3054: Fix calculation for total water usage in water usage calculation modal

- packages/webapp/src/components/AddCropVariety/styles.module.scss
This was throwing a warning on build. Just a typo.
The following warning was present on build in the deploy script. this fixes the typo.
Github actions job logs (may be gone if you are visiting from the future): https://github.com/LiteFarmOrg/LiteFarm/actions/runs/4612997486/jobs/8154522605
**Checklist:**
> Fix font-Size warning in deploy script build log

- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
This PR is to fix the issue that an irrigation task is created without `irrigation_type_id`.
The issue is seen when an irrigation task is created without the user's action of "selecting an irrigation type".
I added  `setValue` to set default irrigation task id so that `irrigation_type_id` is included in the API's payload when the user creates an irrigation task without "selecting" a type.
Jira link: https://lite-farm.atlassian.net/browse/LF-3057
(you need to have a default irrigation type)
1. go to `/tasks`
2. click “+ Create a task”
3. click “Irrigation”
4. input a date
5. select a location
6. click “Continue” without touching “Type of Irrigation” select
7. “Save”
8. Check the payload of `POST: /task/irrigation_task` API. …
> LF-3057: Irrigation task is created without irrigation_type_id when select is untouched

- packages/webapp/src/components/Task/FieldWorkTask/index.jsx
This PR is to enable the user to complete a field work task without needing to make changes to the task. The form has data retrieved from database whose format is invalid. In this PR, the format of the retrieved data is reformatted in useEffect.
Details:
The format of "Type of filed work"(`typeValue`) retrieved from the database is different from what is expected.
The one in the red box in the screenshot is the retrieved data which is invalid. By clicking an option, `typeValue` gets the right format of data (the one in the blue box), and the field is considered as "valid".
The rule of this field is to have "value" field.
Jira link: https://lite-farm.atlassian.net/browse/LF-3115
Please describe the tests that you ran to …
> LF-3115: Unable to mark a field work task completed without toggling "Did you have to make any changes to this task?"

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
This PR adds the referenced phrase which was missing in the translation files.
To view this screen, reset your password using a reset password link, and then try to use that same reset password link a second time.
Jira link: https://lite-farm.atlassian.net/browse/LF-3151
**Checklist:**
> LF-3151 EXPIRED_TOKEN.RESET_PASSWORD_LINK needs to be dynamic

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/AddCropVariety/ComplianceInfo/index.jsx
- packages/webapp/src/components/AddCropVariety/index.jsx
- packages/webapp/src/components/AddNewCrop/index.jsx
Modal was not popping up on cancel in add crop and add crop variety workflow.
Translation should be lower case as it is inserted mid-sentence.
Jira link: [LF-2042](https://lite-farm.atlassian.net/browse/LF-2042)
**Checklist:**
[LF-2042]: https://lite-farm.atlassian.net/browse/LF-2042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 2042 no cancel pop up when creating a new crop

- packages/webapp/src/components/Form/Unit/useUnit.jsx
When `hookFormValue` in `useUnit` is set to `undefined`, it is automatically changed to `NaN`. This triggers a `useEffect` unexpectedly. This PR is to set the initial `hookFormValue` to `NaN` instead of `undefined`.
(Please see the ticket for what issue this causes.)
Jira link: https://lite-farm.atlassian.net/browse/LF-3123
**Checklist:**
> LF-3123: First number put into Estimated flow rate input in water calculator disappears

- packages/webapp/src/containers/bulkSensorReadingsSlice.js
Sensor readings view keeps showing the loading animation when an open weather API returns an error because `bulkSensorReadingsFailure` action does not change `loading` state to `false`. 
You can find a csv to add a sensor that can be used for testing the fix [here](https://lite-farm.atlassian.net/browse/LF-2971?focusedCommentId=15160).
Actual error:
Jira link: https://lite-farm.atlassian.net/browse/LF-2971
**Checklist:**
> LF-2971: Handle undefined weatherStationName

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/Form/Radio/index.jsx
- packages/webapp/src/components/Form/RadioGroup/index.jsx
- packages/webapp/src/components/Pill/index.jsx
- packages/webapp/src/components/Pill/styles.module.scss
- packages/webapp/src/components/Task/TaskComplete/index.jsx
Jira link: https://lite-farm.atlassian.net/browse/LF-2776
1. Create a task and select it
2. Mark as Completed and step forward to the new Completed Date
3. See Jira for how new completed date component should work
**OBS**
I had to add some additional fixes for edge cases.
1. `Due date >= Today`: Disable "Due date" and use "Today" as default date choice as the completion date cannot be in future and if `Due date == Today` there isn't any point to have both active.
2. When completing an irrigation task that targets a wild crop. There is no location available so completion logic fails. Separate fix PR here: https://github.com/LiteFarmOrg/LiteFarm/pull/2535
Also see this …
> LF-2776 New completion date component for task completion flow

- packages/webapp/public/locales/en/message.json
- packages/webapp/public/locales/es/message.json
- packages/webapp/public/locales/fr/message.json
- packages/webapp/public/locales/pt/message.json
- packages/webapp/src/containers/CustomSignUp/saga.js
Currently, once 3 password reset emails have been sent (the max that can be sent in 24 hours) the error snackbar reads: "Error with sending password reset email, please contact LiteFarm for assistance."
This is not correct; there was no error and LiteFarm should not be contacted. 
This PR creates a new snackbar message for this situation: "A password reset link has been emailed to you, please check your inbox and spam folder."
Notes:
- The original error message has been retained for when the API has returned an unspecified error (not something I have ever seen on this endpoint, but might as well keep it to be safe)
- Neither message fits very well in the snackbar, particularly on mobile; a separate ticket [LF-3188](https://lite-farm.atlassian.net/browse/LF-3188) has been …
> LF-3166 Unclear and unhelpful error snackbar displays when maximum number of password reset emails have been sent

- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/components/Typography/index.tsx
- packages/webapp/src/components/Typography/typography.module.scss
Update `IconLink` component to be able to click the trash icon for task deletion.
Jira link: a small addition to https://lite-farm.atlassian.net/browse/LF-2776
**Checklist:**
> Update icon link component

- packages/webapp/src/components/Task/TaskComplete/index.jsx
…gic.
The double negation was confusing. The correct logic was, if the task needs changes and is not (field work and other) then use the existing logic. If it is field work and other use this special logic. 
What was happening was everything that was not field work and other was going to that logic. 
Jira link:
**Checklist:**
> Fixing issue where all non field work tasks where using field work logic

- packages/webapp/src/components/Profile/People/index.jsx
- packages/webapp/src/containers/Documents/util.js
Update filtering logic to make it work for non alphanumerical letters.
Jira link:
- https://lite-farm.atlassian.net/browse/LF-3158
- https://lite-farm.atlassian.net/browse/LF-3159
**Checklist:**
> LF-3158: Searching in non latin alphabet does not return matches appropriately

- packages/api/src/controllers/cropController.js
- packages/webapp/src/containers/AddCropVariety/saga.js
Backend piece of LF-3091. I did not add new error messaging as it is now handled differently on the frontend. i did not edit updateCrop() in the controller as it has no frontend use case currently.
Jira link:
- disabled frontend check in PureAddNew in checkUniqueCropAndSubmit function changing showDuplicateCropError() to handleContinue()
- add new crop will fail
**Checklist:**
> Lf 3091 the user is able to create a duplicate of the crop that already exists in the farm if he lefts fields genus species blank db

- packages/webapp/src/components/MapDrawer/index.jsx
This PR removes the ability to add sensors from the farm map by commenting out the sensor option in the map drawer.
Jira link: https://lite-farm.atlassian.net/browse/LF-3203
**Checklist:**
> LF-3203 Comment out sensor from the farm map "+" drawer

- packages/webapp/src/components/Crop/PlantingLocation/index.jsx
- packages/webapp/src/containers/Crop/AddManagementPlan/PlantingLocation/index.jsx
This PR corrects a bug in the location mismatch modal ("You've indicated you'll be planting a (non-)organic crop in a (non-)organic location. Do you want to proceed?") whereby crops with organic status `null` triggered the modal on both organic and non-organic locations.
(Note: Crops with organic status `null` are those created while a farm was not pursuing organic certification.)
This PR updates the modal logic so that:
- the modal is never shown for farms not currently pursuing organic certification
- crops with organic status `null` trigger the modal only on organic locations; i.e. are treated as non-organic for the purposes of this modal
Jira link: https://lite-farm.atlassian.net/jira/software/c/projects/LF/issues/LF-3189
**How Has This Been …
> LF-3189 Pop up message showing mismatch between organic / non-organic crop and location is firing incorrectly

- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
- packages/webapp/src/containers/Task/saga.js
`PureIrrigationTask` was not compatible with wild crops that do not have `locations`.
- handle empty locations `[]`
- disable the depth calculator for wild crops (wild crops do not have locations, and the depth calculator uses location's `total_area` for its calculation)
- handle a task for wild crops which does not have location_id when forming an API payload for task completion
Jira link: https://lite-farm.atlassian.net/browse/LF-3030
**Checklist:**
> LF-3030: Cannot select wild crop for irrigation task

- packages/api/src/controllers/cropVarietyController.js
- packages/webapp/src/containers/AddCropVariety/saga.js
- packages/webapp/src/containers/EditCropVariety/index.jsx
Backend portion of preventing duplicate variety names. This only allows unique variety common names within the crop_id. Does not test uniqueness on other variety properties.
Jira link:
**Checklist:**
> LF-3092-backend

- packages/api/src/controllers/cropVarietyController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/AddCropVariety/index.jsx
- packages/webapp/src/containers/AddCropVariety/AddCropVariety.jsx
- packages/webapp/src/containers/AddCropVariety/saga.js
- packages/webapp/src/containers/EditCropVariety/index.jsx
This PR adds a uniqueness constraint to adding a variety in the frontend, so that the Add Variety form cannot be submitted if the given Variety Common Name already exists for that given crop on this farm.
The same constraint has also been added to the API for both the Add Variety and Edit Variety screens. _The frontend validation for Edit Variety should be added at some point in the future._
**This ticket has a language component for the validation error displayed when a Variety is not unique.**
Jira link: https://lite-farm.atlassian.net/browse/LF-3092
**Checklist:**
> LF-3092 The user is able to create a duplicate variety of the same crop

- packages/api/src/middleware/validation/assignTask.js
This PR adds a check for an undefined task in assignTask.js that is capable of crashing the API with a TypeError.
A React Hooks-related error in the frontend was making it easier to create partially deleted tasks that were deleted in the database but not the Redux store. Reassigning these tasks would cause a TypeError that crashes the API.
With the React Hooks error addressed (see PR #2633) these partially-deleted tasks will be much harder to generate. But there is no downside to including this check 🙂 
I crashed the API on my local reliably and verified that this file was at fault.
**Checklist:**
> Add check to API to prevent crash on partially deleted tasks

- packages/api/src/controllers/userController.js
When an invite is accepted using GoogleSSO, a new `user_id` is generated at the point of account creation in the format specific to GoogleSSO accounts. (For a password-based account, the `user_id` generated at the moment of invite is retained).
If tasks are assigned to an invited user before they have accepted their invitation, they will not be able to create their account using Google SSO because their original `user_id` will exist in the `task` and `notifcation_user` tables and the database will give a Foreign Key Violation error when the original record is deleted in the Objection.js transaction.
This PR fixes this issue by updating the `user_id` referenced in the `tasks` and  `notification_user` tables as is already done for several other tables within the transaction. …
> LF-3218 An error is displayed: "LOGIN.ERROR.LOGIN_FAIL" once the invited user tries to accept the invitation using the Google SSO method

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Documents/Add/index.jsx
- packages/webapp/src/containers/Documents/DocumentUploader/index.jsx
This PR decreases the filesize upload limit for the document view from 25MB to 10MB. Kevin has investigated this and determined it as a reasonable limit. 10MB also reflects the point at which thumbnail creation on the Imaginary starts to fail within this flow.
It also removes the warning about page limit from the filesize modal (where it does not logically belong) and fixes the page (i.e files that can be uploaded per document) limit at 5 instead of 6.
Jira link: https://lite-farm.atlassian.net/browse/LF-3157
**Checklist:**
> LF-3157 Images and documents that are too large fail without explanation

- packages/api/db/migration/20230425182236_update_cook_islands_currency.js
This PR creates a migration for the database change that has already been manually implemented on production (but not Beta) where the Cook Islands currency has been updated to the New Zealand Dollar.
Jira link: https://lite-farm.atlassian.net/browse/LF-2969
Tested by running the migration script and viewing the database. Tested against both versions of the database -- the change already live (as in prod) or the change not yet updated (as in beta).
**Checklist:**
> LF-2969 Migrate Cook Islands currency and iso

- packages/webapp/src/components/CreateUserAccount/index.jsx
- packages/webapp/src/components/InvitedUserCreateAccount/index.jsx
This PR adds the missing `onKeyPress={integerOnKeyDown}` prop to the Birth Year Input in CreateUserAccount and InvitedUserCreateAccount.
Jira link: https://lite-farm.atlassian.net/browse/LF-3111
**Checklist:**
> LF-3111 Birth year should only allow integers

- packages/webapp/src/containers/EditCropVariety/index.jsx
The `handleGoBack` for PureEditCropVariety had a hardcoded URL, causing an infinite back loop.
This PR updates it to `history.back()` as is used in the other handleGoBack methods.
Jira link: https://lite-farm.atlassian.net/browse/LF-3176
**Checklist:**
> LF-3176 Back arrow loop

- packages/api/db/migration/20230426222612_update_turkey_name.js
This PR updates the `countries` table to reflect Türkiye's official change of name.
The discrepancy between our database table and what Google Maps returned was causing an error on new farm creation (see [LF-3225](https://lite-farm.atlassian.net/browse/LF-3225)). Neither this error nor this change affects previously established farms.
Jira link: https://lite-farm.atlassian.net/browse/LF-3228
You can test creating a new farm in Türkiye using this latitude and longitude (or you may type in an address of your choosing within the country):
```
39.738027, 29.909981
```
**Checklist:**
[LF-3225]: https://lite-farm.atlassian.net/browse/LF-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> LF-3228 Add migration script for updating Turkey to Türkiye

- packages/webapp/src/components/Form/Unit/useUnit.jsx
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/stories/Form/Unit/Unit.stories.jsx
- When "Confirm" button on the "Line box" modal is clicked, override the existing data with the latest data. (the bug is that the latest data is overridden with the old data)
- Revert and update storybook tests I updated in this commit https://github.com/LiteFarmOrg/LiteFarm/pull/2584/commits/4fe0d3ee3ecae5ecf14df75ab38d55c06ccce06b. (It looks like I forgot to run the tests after making all the changes, so I didn't realize that they were failing...)
- When confirming on the modal and redrawing, the visible value disappears although the hidden value exists. (please see the recording) This happens because in one of the `useEffect` in `useUnit` hook, `hookFormValue` (= hidden value gotten by `watch()`) is different from the current hidden value (can be gotten by …
> LF-3061: Redraw does not work for watercourse and buffer zone once confirmed

- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/Form/Unit/index.jsx
- packages/webapp/src/components/hooks/useElementWidth.jsx
Calculate the currency width to adjust padding left of `Unit` and `Input` components so that any currency gets appropriate space.
- create `useElementWidth` hook
- replace the calculation `currency.length * 8` with the width returned by `useElementWidth`
Jira link: https://lite-farm.atlassian.net/browse/LF-3216
hard-cord `currency` in `/packages/webapp/src/components/Finances/UpdateEstimatedCropRevenue/index.jsx`
**Checklist:**
> LF-3216: Overlap between currency symbol and units on estimated revenue view

- packages/webapp/src/components/Map/SelectionHandler/index.jsx
- packages/webapp/src/containers/Map/useSelectionHandler.js
The area icons where css-fixed to fit on the space available on PureSelectionHandler (aka popup) when there more than one area on a specific place. 
As when the popup was redesign for sensors it was requested on the peer review that it shouldn't be limited only for 4 sensors, on this PR those limits are deleted for areas an lines too.
Lastly, Caro told me a while ago about a 1px mismatch between the arrow point and the popup.  It was going to be fixed in another open ticket regarding the popup with sensors, but I added that small change to this PR.
Jira link: https://lite-farm.atlassian.net/browse/LF-3221
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …
> Lf 3221 the icons for the different areas overflowed the disambiguation box

- packages/webapp/src/components/Form/Checkbox/checkbox.module.scss
- packages/webapp/src/components/Form/Checkbox/index.jsx
In Checkbox component, css `transform` is used to adjust the position of the label, but the width of the label is not adjusted. To make the fix simpler, use "flex" instead of "position: absolute". 
Jira link: https://lite-farm.atlassian.net/browse/LF-2915
**Checklist:**
> LF-2915: Fix checkbox label overflow

- packages/webapp/src/components/AddCropVariety/index.jsx
- packages/webapp/src/components/AddNewCrop/index.jsx
- packages/webapp/src/components/EditCropVariety/index.jsx
- packages/webapp/src/containers/ImagePickerWrapper/index.jsx
- packages/webapp/src/containers/ImagePickerWrapper/saga.js
This PR adds a loading spinner to image selection and replacement in AddCrop, AddCropVariety, and EditCropVariety. Logic to manage the loading spinner state has been added to ImagePickerWrapper, the image uploader component that all three of these views use.
Due to differences in page layout, only EditCropVariety also needed a wrapper div to contain the loading spinner.
Note: To test the full behaviour successfully, you will need the LiteFarm imaginary token (for thumbnail creation) + MinIO.
Jira link: https://lite-farm.atlassian.net/browse/LF-2980
**Checklist:**
> LF-2980 Add "loading" image when uploading a custom varietal image

- packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/index.jsx
- packages/webapp/src/containers/Finances/EditExpense/TempEditExpense/styles.module.scss
- packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/AddExpense/styles.module.scss
New expense item character limit increased to 100. Input box autosizes up to 4 lines (in mobile, only 2 in web, as that's where it hits 100 characters). Imported InputAutoSize from Form component to accomplish autosizing.
Jira link:
https://lite-farm.atlassian.net/browse/LF-2975
**Checklist:**
> Lf 2975 increase character limit for item name in expenses to 100 characters bm

- packages/webapp/src/components/LocationDetailLayout/LocationPageHeader.jsx
- packages/webapp/src/components/LocationDetailLayout/PureLocationDetailLayout.jsx
- packages/webapp/src/components/Map/DrawingManager/index.jsx
- packages/webapp/src/components/Map/LineMapBoxes/index.jsx
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/useDrawingManager.js
- packages/webapp/src/containers/hooks/useHookFormPersist/hookFormPersistSlice.js
This PR is for fixing the bug that whenever you were on the form for creating any area (Residence, Barn, etc), line (watercourse, buffer zone, etc) or marker (gate, water valve), and you clicked Back, and the confirmed again, the form was with its original values and not the ones that you have modified.
To fix this the upsertFormData form hookFormPersistSlice is now dispatched when the user clicks back on the form to return to the map.  
But the form has some calculated values (areas, perimeters for the polygons but also for some of the line types).  To be able to use the recalculates values if the user changed something (by using "Redraw" button, moving points or inserting new values for the line types) it was added to the store the isRedrawing slice. 
Some event …
> Lf 3106 details from drawn shape are not persisted when going back to draw step in flow

- packages/webapp/src/components/AddCropVariety/index.jsx
- packages/webapp/src/containers/AddCropVariety/AddCropVariety.jsx
When no custom varietal image is uploaded, the varietal should inherit the image of the parent crop.
Logic to handle this inheritance did exist, but it was in the data-transformation step which is only applied to non-certification farms. Therefore, certification-pursuing farms did not see crop image inheritance.
This PR moves that logic to Add Crop Variety by setting the parent crop image as the default value in the React Hook Form, so image inheritance will be applied regardless of certification status. The image preview was updated to only display if the crop variety image was changed off of this default.
Jira link: https://lite-farm.atlassian.net/browse/LF-3114
**Checklist:**
> LF-3114 When creating a varietal without adding a new image, the image should be inherited from the crop_type

- packages/webapp/src/components/Form/Radio/index.jsx
- packages/webapp/src/components/Form/Radio/radio.module.scss
The custom styling we apply to our radio buttons was being created in CSS with a pseudo-element applied to a span. This solution works at 100%, but is brittle and breaks at other zooms, including the system-wide scaling that might be applied by Windows.
This PR replaces the pseudo-element solution with a simple SVG, which performs much more reliably at different scalings.
Jira link: https://lite-farm.atlassian.net/browse/LF-3131
@Duncan-Brain can you please test this on your Windows computer with the system-wise scaling set to 125%? I don't have a windows computer to check that case.
**Checklist:**
> LF-3131 Radio toggle checkbox not centered

- packages/webapp/src/assets/images/farmMapFilter/Sensor.svg
The sensor SVG used in these three views:
- map drawer
- notification list (if you have an async sensor upload)
- selection handler (grouped locations on the map)
used the `<feBlendMode />` filter component, which is not supported in Safari (iOS/macOS). Therefore that icon was missing from those views in that browser. (Note the sensor icon on the map itself is different and not an SVG.)
This PR replaces the sensor SVG with another that doesn't use `<feBlendMode />`. To avoid touching any code in those three views, I added a bit of transform and line weight to make the sensor appear as close as possible to the original (it's not exact, but it's _pretty_ close).
Jira link: https://lite-farm.atlassian.net/browse/LF-2993
I …
> LF-2993 On iOS sensor icon does not appear next to "Sensor" in the "+" Drawer

- packages/shared/validation/sensorCSV.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Sensor/EditSensor.jsx
_"On Google Maps, anything north of 85° N, or south of about 83° S, isn't visible at all"_ (https://www.quora.com/Why-doesnt-Google-Maps-show-the-North-Pole#:~:text=Google%20Maps%20(along%20with%20other,isn't%20visible%20at%20all.)) When a sensor is created with latitude < -85 or 85 < latitude, the sensor icon is displayed on the grey area of the map. This PR is to update the sensor latitude validations to accept a range of -85 to 85.
- update validation for sensor creation/modification
- update error messages shown in an error message file
Jira link: https://lite-farm.atlassian.net/browse/LF-3242
**Checklist:**
> LF-3242: The map became broken after the user uploads the valid csv file using Postman(API )

- packages/webapp/src/components/Map/PreviewPopup/utils.js
When farm's unit system is `imperial` and temperature data is "null", `convertCelsiusToFahrenheit` function returns `32` (see the old line 15), and the temperature chart shows 32F when there is no data. This PR updates `convertCelsiusToFahrenheit` and `getTemperatureValue` to return `NaN` when a non-number is passed to the function.
Jira link: https://lite-farm.atlassian.net/browse/LF-3160
**Checklist:**
> LF-3160: Misleading temperature line for sensors without temperature data

- packages/webapp/src/components/Map/PreviewPopup/utils.js
This is the exact same issue as was addressed in this PR:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2669
The only difference is that here soil water potential (units of pressure) needed the null check rather than temperature. Therefore I have copied @SayakaOno's code precisely, for complete parallelism 😁 
Jira link: https://lite-farm.atlassian.net/browse/LF-3027
**Checklist:**
> LF-3027 Sensor readings continuing into predicted region when farm system of measurement is set to imperial

- packages/shared/validation/sensorCSV.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
This PR harmonizes the sensor CSV columns and sensor reading types across the frontend translation files and the validation scripts in `/shared`. A new ticket, [LF-3286](https://lite-farm.atlassian.net/browse/LF-3286), has been opened to address the shared package folder and the issue of a single source of truth.
The specific changes include:
- Resolving all discrepancies favouring the correct version, typically the validation, after consultation with native speakers
- Removal of BULK_UPLOAD_SENSORS.SENSOR_READING_TYPES from the translation files as they were not used in the codebase
- Addition of a "MISSING" tag for a Spanish translation that incidentally held English.
Jira link: https://lite-farm.atlassian.net/browse/LF-3274
**How Has This Been …
> LF-3274 Valid sensor files don't upload in non-English languages

- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/index.jsx
In the sensor details tab, two APIs keep being called. This PR updates dependency of the useEffect that causes the issue. (in the useEffect, the two APIs are called and `sensorInfo` is  updated, but `sensorInfo` is also dependency of the useEffect)
Jira link: https://lite-farm.atlassian.net/browse/LF-3258
**Checklist:**
> LF-3258: APIs keep being called in sensor details view

- packages/webapp/src/components/Task/HarvestingTask/index.jsx
- packages/webapp/src/stories/Pages/Task/TaskDetail/TaskDetail.stories.jsx
- packages/webapp/src/test-utils/storybook/unit.jsx
The harvest quantity input shows an error after inputting a large number and checking the checkbox below (the field is disabled) even though the value is reset to `''`. This PR adds validation after the value is reset.
I merged https://github.com/LiteFarmOrg/LiteFarm/pull/2540 to add tests. To run:
- ```pnpm test-storybook /src/stories/Pages/Task/TaskDetail/TaskDetail.stories.jsx```
- [storybook UI](http://localhost:6006/?path=/story/page-addcleaningtask--harvest-task)
Jira link: https://lite-farm.atlassian.net/browse/LF-3244
**Checklist:**
> LF-3244: Quantity input for harvest task shows an error when disabled

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/containers/SensorReadings/constants.js
- packages/webapp/src/containers/SensorReadings/index.jsx
- packages/webapp/src/containers/SensorReadings/saga.js
In the temperature chart, the current lowest and highest observed temperature are shown whereas they should be the forecasted high and low temperature for the day.
- call the [daily forecast API](https://openweathermap.org/forecast16) to get the forecasted high and low temperature for the day
- update useEffect dependency to show high/low temperature in the sensor chart
Jira link:
- https://lite-farm.atlassian.net/browse/LF-3028
- https://lite-farm.atlassian.net/browse/LF-3256
**Checklist:**
> LF-3028: Mismatch between visualized high and low temps and reported high and low temps

- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/containers/Task/TaskComplete/StepOne.jsx
`farm` prop that `AddProduct` component takes needs to have `farm_id`, `country_id` and `interested`. Two components are currently passing incomplete `farm` prop, and `AddProduct` component is not showing required/optional for the supplier field correctly. The code was copied from this file:
https://github.com/LiteFarmOrg/LiteFarm/blob/1c17d3a7fe058eb30076f6717052f8b389704c44/packages/webapp/src/containers/Task/TaskDetails/index.jsx
This fix can be tested in the read-only and complete task views for clean, pest control or soil amendment task (you need to have a product).
Jira link: https://lite-farm.atlassian.net/browse/LF-3246
**Checklist:**
> LF-3246: The field "Supplier" becomes optional after the user enters the "Edit" menu of the "Clean" task

- packages/api/src/middleware/validation/deleteLocation.js
This PR fixes the bug where users were unable to retire locations on the farm map if said location has deleted tasks
Jira link:
**Checklist:**
> added check for deleted tasks to location dependency validator

- packages/webapp/src/components/Task/FieldWorkTask/index.jsx
In the field work task read-only and before_complete views, the value used for `ReactSelect` is an array at first where it should be an object. There were two functions 1. `formatDefaultTypeValue` that would take out the first item from the array and 2. `displayLabel` that would correct the label of the object. This PR combines these two functions.
It looks like this was "TODO" according to the old comment. Since "pest control" is mentioned, I will ask QA to test it.
Jira link: https://lite-farm.atlassian.net/browse/LF-3289
**Checklist:**
> LF-3289: "Type" of Field work not dynamic on details page

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/SensorReadingsLineChart/index.jsx
- packages/webapp/src/components/SensorReadingsLineChart/styles.module.scss
- packages/webapp/src/containers/SensorReadings/index.jsx
- packages/webapp/src/containers/SensorReadings/saga.js
- packages/webapp/src/containers/SensorReadings/styles.module.scss
- packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
- packages/webapp/src/containers/SensorReadingsLineChart/styles.module.scss
This PR implements the new chart styling, with the x-axis and y-axis labels removed, units implemented as a chart subtitle, legend moved below the chart, and significantly increased width on small screens.
I also removed the forecasted weather data from PureSensorReadingLineChart as there is a ticket (LF-3290) to make it its own component, which I'm assuming will be imported into SensorReadings. @SayakaOno please let me know if I messed something up for how you were thinking of implementing that!
Jira link: https://lite-farm.atlassian.net/browse/LF-3291
P.S. I re-implemented "Ambient weather for" because it was on the UI image from the Jira ticket; whether that should be kept or not probably requires a quick group chat/check.
**How Has This Been …
> LF-3291 Small visual tweaks to soil water potential reading component

- packages/api/src/controllers/sensorController.js
- packages/api/src/middleware/validation/validateWebhook.js
Previously our validation middleware for the Ensemble sensor webhook had a loophole such that it could be circumvented by supplying (in the route) anything that would `parseInt` to a falsy value for the `partner_id`. The middleware would call `next()` and the controller would default the falsy value to 1, allowing readings to be posted without the validation check. This PR removes that loophole.
Thanks for spotting @Duncan-Brain!
Jira link: https://lite-farm.atlassian.net/browse/LF-3298
I tested by registering a fresh Ensemble sensor webhook and verifying that it still works. I did not test the hacking via route because it would have to be Ensemble (or someone spoofing Ensemble) that does that 🙂 
**Checklist:**
> LF-3298 Repair sensor reading route authentication

- packages/webapp/src/components/SensorReadingsLineChart/index.jsx
- packages/webapp/src/containers/SensorReadings/constants.js
- packages/webapp/src/containers/SensorReadings/saga.js
- packages/webapp/src/containers/SensorReadings/utils.js
- packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
This moves the sensor charts to hourly time points. Dots are added to the line chart when fewer than 90% of hourly time points are present.
A small final adjustment uses a smoother curve on data containing more than 50%, but less than 90%, of hourly data points on small chart widths (i.e. mobile screens).
Please note the sparse data display conditions are a bit of a placeholder -- they should be revisited when real data feeds are available. The chart in general will also look best if viewed after the xAxis and yAxis changes in LF-3291 are applied.
Jira link: https://lite-farm.atlassian.net/browse/LF-3284
**Checklist:**
> LF-3284 Modify visualization algorithm for sensor readings data

- packages/webapp/src/containers/SensorReadings/constants.js
Update geocoding API URL to `https`.
Error:
Jira link: N/A
**Checklist:**
> Fix REVERSE_GEOCODING_API_URL

- packages/webapp/src/components/Task/FieldWorkTask/index.jsx
This bug was fixed in https://github.com/LiteFarmOrg/LiteFarm/pull/2571 and re-introduced in https://github.com/LiteFarmOrg/LiteFarm/pull/2684. (my PRs 🙈)
`FIELD_WORK_TYPE` does not initially have `value` which is invalid and "Continue" button is disabled. After `FIELD_WORK_TYPE` is formatted and gets `value`, validation is not run automatically, and the button remains disabled. This PR adds `shouldValidate` for `setValue` to run validation for the new `FIELD_WORK_TYPE`.
Jira link: https://lite-farm.atlassian.net/browse/LF-3115
**Checklist:**
> LF-3115(2): Unable to mark a field work task completed without toggling "Did you have to make any changes to this task?"

- packages/webapp/src/containers/SensorReadingsLineChart/index.jsx
The check for the existence of "no data" in the sensors was using the hardcoded (English) string `(no data)` instead of the string translated into each language.
This PR updates the check to be against the translated string instead.
Jira link: https://lite-farm.atlassian.net/browse/LF-3310
**Checklist:**
> LF-3310 An Empty soil water content diagram is shown to the user when he changes the language of his farm to anything else than ENGLISH

- .github/workflows/beta-export-deploy.yml
This PR has 3 changes: 
1. Added a `script_stop` function. This will stop script after the first failure, and the job will show as failed. In the previous version, if for example, the `git pull` step fails, it will still run the rest of the script and we will see a green check mark thinking the job has been completed. 
2. Instead of restarting the service, it deletes the service then starts it again, in case there isn't any service to restart.
3. Exposed our deployment script for easy management, since there is little reason to hide the script.  
Jira link: [LF-2758](https://lite-farm.atlassian.net/browse/LF-2758?atlOrigin=eyJpIjoiMWJkMGY1ZTgzMjkyNDliZGFiYTA3MDU3ZWY4ZGI5MTIiLCJwIjoiaiJ9)
Please describe the tests that you …
> LF-2758 export server cicd

- .github/workflows/deploy.yml
- beta-deploy.sh
The code change here is very slight (`git pull origin integration` in place of `git pull`) but this PR also relocates the beta deployment script from `deploy.sh` on the droplet (outside of our repository code) into our repository.
The `set -eu` addition is part of [LF-3067](https://lite-farm.atlassian.net/browse/LF-3067); please see that ticket for details.
Jira link: https://lite-farm.atlassian.net/browse/LF-3185
This is another ticket that can only be tested by observing the beta deployment GitHub Actions workflow.
**Checklist:**
[LF-3067]: https://lite-farm.atlassian.net/browse/LF-3067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LF-3185 Update deployment script to only pull integration rather than the whole repo

- packages/webapp/nginx.conf
Set a rate limiter (10 requests per second) on Nginx.
```
limit_req_zone <key> zone=<name>:<size> rate=<rate>
```
https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone
Jira link: https://lite-farm.atlassian.net/browse/LF-2954
I used [Iván's sample project](https://github.com/iperdomo/nginx-rate-limit-example) to test the rate limiting set up. (I have not been able to setup the repo with Docker yet) I ran:
```
watch --interval 0.2 curl http://api.localhost
```
in multiple tabs. (I have not found the best way)
@kathyavini 
It would be appreciated if you could try running this command to see if requests are limited:
```
seq 1 30 | xargs -n1 -I -P5  curl "http://localhost:5001/login/user/test@test.com"
``` …
> LF-2954 Limit the number of API requests in a certain timespan

- packages/api/src/middleware/acl/hasFarmAccess.js
- packages/api/src/routes/taskRoute.js
- packages/api/tests/task.test.js
Most of the tasks of the ticket is covered in https://github.com/LiteFarmOrg/LiteFarm/pull/2716.
- Add management plan ids and location_id check on transplant task creation endpoint.
- Fix `fromTaskManagementPlanAndLocation` function to handle empty `location_id`. (I just noticed that `location_id` of planting management plan could be null.
Note: There is no routes to update location_id or management plan id of tasks.
Jira link: https://lite-farm.atlassian.net/browse/LF-1963
**Checklist:**
> LF-1963: Add management plan ids farm id check on all task creation and patch routes

- packages/webapp/src/containers/AddFarm/index.jsx
- render `GoogleMap` after the script is loaded.
- add state `scriptLoaded`
- set country when the form has `gridPoints`. (otherwise "Continue" button is disabled)
Jira link: https://lite-farm.atlassian.net/browse/LF-3137
**Checklist:**
> LF-3137: Intermittent google maps issue only for the developers purposes

- packages/api/src/middleware/validation/completeManagementPlanTaskCheck.js
- packages/api/tests/managementPlan.test.js
Issue: User could not complete crop plan when one or more tasks was deleted, and other tasks were abandoned or completed. 
Fix: The issue was because of the validation check for the complete management plan endpoint did not check whether a task is marked deleted or not, so deleted tasks were counted as pending tasks. This check is now added.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3344
**Checklist:**
> LF-3344: Added check for deleted tasks in validation of endpoint

- README.md
- packages/api/.env.default
- packages/api/.knex/knexfile.js
This ticket is a follow-up to the addition of the postgres database to the `docker compose up` in
- https://github.com/LiteFarmOrg/LiteFarm/pull/2728
While we remain in (or at least continue to support) a hybrid state in terms of bringing our local development environment into Docker, we need the ability to move off of the default Postgres port (5432) to connect the non-containerized API to the containerized database, which exposes 5433.
This PR adds a port variable to the database configuration so that `:5432` is not used in every case. _Note that the alternative approach, also valid, would be to update the `docker-compose.yml` to expose the default port._
This is only needed for those who are not already running the API from within the Docker network. If your API is in …
> LF-3394 Add database port variable to development environment and update documentation

- packages/webapp/package.json
> Optional boolean to change the environment variable to
>  CYPRESS_COVERAGE instead of VITE_COVERAGE. For ease of use with
> `@cypress/code-coverage``.
https://github.com/ifaxity/vite-plugin-istanbul#parameters
We don't have Cypress in the `webapp` package anymore
The `CYPRESS_COVERAGE` could make sense when the `cypress` module was part of `webapp` package
Jira link: https://lite-farm.atlassian.net/browse/LF-3381
**Checklist:**
> LF-3381 Remove Cypress related environment variable

- packages/webapp/src/components/CardWithStatus/TaskCard/TaskCard.jsx
- packages/webapp/src/containers/Task/TaskCard/index.jsx
- packages/webapp/src/stories/TaskCard/TaskCard.stories.jsx
- format date in `TaskCard` based on user's preferred language
- send `language` from its parent component
- update TaskCard stories
Jira link: https://lite-farm.atlassian.net/browse/LF-2841
The fastest way to test is to change the language in local storage.
**Checklist:**
> LF-2841: On task tile, date displayed in EN (both format and language) when in non-EN language

- packages/webapp/src/components/CardWithStatus/TaskCard/TaskCard.jsx
- packages/webapp/src/components/CardWithStatus/TaskCard/styles.module.scss
Added a couple validations to TaskCard so when a revoked user still assigned to a task, their name will be displayed with a "(inactive)" mark and also greys out the icon and name. This was an issue in terms of not handling the behavior described in the ticket  but it was discussed in the same ticket this should be the behavior although I might be loosing some bits of the conversation.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3266
3 scenarios were tested on the Task view:
1. Task assigned to an active user -> name displays as always
1. Task unassigned -> unassigned format displays as always
1. Task assigned to inactive user -> new format in place
**Checklist:**
Screenshot of the implementation:
> LF-3266 - Enhancers | Inactive users: display 

- packages/webapp/src/components/Form/Input/utils.js
Jira link: https://lite-farm.atlassian.net/browse/LF-3393
The problem seems to have been with the default behaviour of `new Date(string)` and `Date.parse(string)`, which parses dates as if they were in UTC timezone if there is no timezone in the date string. This causes an issue when compared with `new Date()` which creates a date in your local timezone.
**Checklist:**
> Fix timezone handling in isNotInFuture util function

- packages/api/db/migration/20230714100652_add_management_plan_group.js
* We have explored the idea of having a different table holding the information of a management plan group.
* ~~The most straight forward version is to just include 3 columns: `group_id`, `repetition_number`, `repetition_count`. With this 3 columns we are able to know if a plan was removed (e.g. count of current plans with the same `group_id` < `repetition_count`) and we don't introduce extra complexity for the frontend.~~
* After a conversation with the team, we agreed to add `management_plan_group` table
* Adds a `management_plan_group` table
* Adds a FK from `management_plan->management_plan_group` 
Jira link: https://lite-farm.atlassian.net/browse/LF-3398
Please describe the tests that you ran to verify your changes. …
> LF-3398 Adds `management_plan_group`

- packages/api/src/controllers/managementPlanController.js
- packages/api/src/controllers/taskController.js
Send a notification to the assignee of transplant/harvest task or management plan on its creation. (notification had not been implemented)
Jira link: https://lite-farm.atlassian.net/browse/LF-3385
Create a transplant/harvest task or a management plan and assign it. The assignee should see a badge on the notification icon.
**Checklist:**
> LF-3385: Notification is not created once the user creates transplant planting or harvest task

- packages/api/src/middleware/acl/hasFarmAccess.js
Whenever a controller needs farm_id in the headers, different errors are thrown, i.e. "user not authorize to access farm" in plain text but in some other cases the backend crashes because we tried to operate an undefined object reference. 
This is an attempt to fix the issue hoping it doesn't break the workflow.
Notice that instead of doing 
```
res.status(403).send('no farm_id given');
```
I'm returning a json object with an error that will look like
```
res.status(400).json({ error: 'no farm_id given' });
``` 
this has to return 
```
{
"error": "no farm_id given"
}
```
with a 400 status code.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3358
I'm not sure this is a valid scenario that comes from the frontend but …
> LF-3358: avoid crash when no farm_id is given

- packages/webapp/src/Routes.jsx
- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
- packages/webapp/src/components/RepeatCropPlan/index.jsx
- packages/webapp/src/containers/Crop/RepeatCropPlan/index.jsx
This PR creates the Repeat Crop Plan container that contains and calls the Repeat Crop Plan Pure Component (LF-3362).
This ticket also sets up the persisted paths between LF-3362 and LF-3378 from the two routes into this flow (end of crop plan creation and crop plan management tasks view).
Note there is a placeholder UI -- a big yellow button -- to trigger the repeat flow from the crop plan management tasks view, as there is a separate ticket to create the new menu.
Jira link: https://lite-farm.atlassian.net/browse/LF-3431
**Checklist:**
> LF-3431 Repeat crop plan | Repeat crop plan container

- packages/api/src/controllers/managementPlanController.js
- packages/api/src/models/managementPlanGroupModel.js
- packages/api/src/models/managementPlanModel.js
- We want to avoid sending the `repetition_config` to the client as it could be a big JSON blob
- Added the property to the _hidden_ list
Adds a new key `management_plan_group` to the response, e.g.
```json
[
{
"management_plan_id": 3,
"crop_variety_id": "45c6d744-2a3b-11ee-ad45-0242ac150006",
"notes": "",
"name": "Plan 1",
"start_date": null,
"complete_date": null,
"abandon_date": null,
"complete_notes": null,
"rating": null,
"abandon_reason": null,
"management_plan_group_id": "fcf6f165-d1dd-48b8-9e48-7af339f25a25",
"repetition_number": 1,
"management_plan_group": {
"management_plan_group_id": "fcf6f165-d1dd-48b8-9e48-7af339f25a25",
"repetition_count": 1
},
"crop_management_plan": {
"management_plan_id": 3,
"***rest***": "properties..."
"planting_management_plans": [
{ …
```
> LF-3447 Adds `repetition_count` to `/management_plan/farm/:id`

- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
- packages/webapp/src/components/Crop/ManagementDetail/styles.module.scss
This PR replaces the placeholder UI (big yellow button) Repeat Crop Plan with the final three dots menu we will use for Copy Crop Plan + Repeat Crop plan.
The menu item for Copy Crop Plan has been commented out for this release, so the menu currently has just one item.
Jira link: https://lite-farm.atlassian.net/browse/LF-3368
**Checklist:**
> LF-3368 Copy crop plan | Add menu 

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Modals/CropModals/CropPlansModal.jsx
- packages/webapp/src/components/Modals/CropModals/styles.module.scss
- packages/webapp/src/components/hooks/useElementHeight.jsx
- packages/webapp/src/containers/Crop/CropManagement/useManagementPlanCardContents.js
- packages/webapp/src/containers/managementPlanSlice.js
- packages/webapp/src/stories/Modal/CropPlansModal.stories.jsx
- create `CropPlansModal`
- create `useElementHeight` hook that calculate element height
- create stories
- save repeat group info in Redux store (`useManagementPlanCardContents.js` and `managementPlanSlice.js` are updated)
_The ticket will not be completed until https://lite-farm.atlassian.net/browse/LF-3370 is done. (link texts are not shown, so there is no way to open the modal in the app)_
After running storybook, stories can be found here: http://localhost:6006/?path=/story/components-modals-cropplansmodal--modal-with-two-card
Jira link: https://lite-farm.atlassian.net/browse/LF-3371
**Checklist:**
> LF-3371 (1): Repeat crop plan show repeated plan disambiguation modal

- packages/webapp/src/components/CardWithStatus/ManagementPlanCard/ManagementPlanCard.jsx
- packages/webapp/src/components/CardWithStatus/ManagementPlanCard/styles.module.scss
- packages/webapp/src/components/Crop/Management.jsx
This PR update the `ManagementPlanCard` component to show repeat crop plan info. The text link on click will open model as in https://lite-farm.atlassian.net/browse/LF-3371. This PR has dependency on the ticket LF-3371 to be merged before the text to be shown. 
NOTE: As of now the text links does not perform any action and needs to be updated to open the model from LF-3371 once it is merged.
Jira link: https://lite-farm.atlassian.net/browse/LF-3370
**Checklist:**
> Lf 3370 repeat crop plan update crop plan card to denote a repeated plan

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
- packages/webapp/src/components/Crop/ManagementDetail/styles.module.scss
Missed three things here:
- Only admins should be able to see the menu
- (Denis spotted this of course 😉 ) If someone has their viewport set wider than the full application width, they should be able to click on the white side margins to close the window as well (I had only filled the application width with clickable area previously)
- Also menu text should be translated!
Jira link: https://lite-farm.atlassian.net/browse/LF-3368
**Checklist:**
> LF-3368 Copy Crop menu | Fix role permissions and clickable close area

- packages/webapp/src/components/RepeatCropPlan/index.jsx
- packages/webapp/src/containers/Crop/RepeatCropPlan/index.jsx
- packages/webapp/src/containers/Crop/saga.js
What I found:
When clicking the save button, `persistedPaths` were being set in the saga.
But when the component is unmounted (I believe), `persistedPaths` state is set to the initialState which is an empty array.
And `useLayoutEffect` in `useHookFormPersist` got messed up.
Solution: pass `persistedPathNames` to `useHookFormPersist` in `RepeatCropPlan` component.
Jira link: https://lite-farm.atlassian.net/browse/LF-3478
**Checklist:**
> LF-3478: The user is not able to complete the repeat crop plan flow

- packages/webapp/src/components/RepeatCropPlan/Confirmation.jsx
- packages/webapp/src/components/RepeatCropPlan/index.jsx
- packages/webapp/src/components/RepeatCropPlan/utils.js
- packages/webapp/src/util/rruleTranslation/index.js
Dynamic import fails in beta.
https://litefarm.sentry.io/issues/4356319551/?project=5761919&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
From the error in Sentry (_Failed to fetch dynamically imported module: https://beta.litefarm.org/assets/es.js_), it seems that the files need to be located under `assets`, but I could not make it work. I updated the file to import all language files.
(Sorry @kathyavini , I loved the translation cache, but I had to remove it 😢)
Jira link: https://lite-farm.atlassian.net/browse/LF-3496
**Checklist:**
> LF-3496: Move away from dynamic import in webapp

- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
- packages/webapp/src/components/Form/Input/utils.js
- packages/webapp/src/components/Task/AbandonTask/index.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
This PR fixes the error handling in the components using the`isNotInFuture` validation function.
These components were calling the validation function within the `error` prop, leading to calling the validation function twice. The second time the function gets called with an undefined value that causes a Type Error crash -- and previously this also led to buggy validation that was not caught (i.e. on App you can't actually trigger the "Required" validation error).
Jira link: https://lite-farm.atlassian.net/browse/LF-3446
**Checklist:**
> LF-3446 White screen is displayed during the completion of any task when the user changes the completion date

- packages/webapp/src/components/RepeatCropPlan/index.jsx
Putting a decimal input into the repeat crop plan `repetitions` Input (which can be done *only on mobile* due to the existing and known bug that `integerOnKeyDown` doesn't function on Chrome Android) causes a crazy number of repetitions to be generated by RRule.
There are probably several ways to fix this, including flooring/sanitizing the value when it's used in the calculation functions, but I have taken the basic approach of flooring the Input value `onBlur` for the two Number with Stepper inputs in this form.
I think the same approach could probably be used for the more general case of decimals on Chrome Android, but that is a separate ticket so should be addressed if/when it comes up in the release queue 🙂 
Jira link: https://lite-farm.atlassian.net/browse/LF-3489 …
> LF-3489 On mobile devices decimal values can be input for crop plan repetitions, creating scary output on confirmation screen

- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
Hide the pencil icon when the user cannot assign the task. (The user can assign the task when he/she is admin or assignee, or the task is not currently assigned.)
Jira link: https://lite-farm.atlassian.net/browse/LF-3475
**Checklist:**
> LF-3475: The error is displayed when the Farm worker tries to update the "Assignee" of the task

- packages/webapp/src/components/RepeatCropPlan/index.jsx
Thank you @SayakaOno for pointing out that the `onBlur` handler (used for setting min/max in all cases and for flooring decimal values on mobile) will never be triggered if the form is submitted directly from the input with the `enter` key or `-->` on Android!
This PR fixes this by:
- moving the decimal removal to `onChange`. I tried for quite a while to replicate the UX of `integerOnKeyDown` but could not; this doesn't remove the decimal until the _next_ key has been entered, but I think that's the best that can be done
- added validation for min/max and for integer values to prevent form submission via `enter` or `-->` before the `onBlur` has had time to register (the integer validation should be redundant with the `onChange` handler but it's there just in case)
Jira …
> LF-3489a On mobile devices decimal values can be input for crop plan repetitions, creating scary output on confirmation screen

- packages/webapp/src/components/Forms/Sale/index.jsx
On the Add sale screen, when a crop varietal pill is selected we register the change to the form. However, when a crop varietal pill is unselected, we don't currently unregister, which means the data from that pill remains in the form submission and causes the validation function to fail. This MR adds unregistering the unselected crop varietal pills.
Jira link:
https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/10?modal=detail&selectedIssue=LF-3384
Tested manually on my local setup, verified that when going to the Add sale screen the form …
> LF-3384: Fix Save on new sale when removing crop varietals

- packages/webapp/src/components/RepeatCropPlan/index.jsx
The unique crop plan name validation error was only shown upon interaction with that field according to original ticket requirements.
This can give the user the confusing state of the continue button being invalid for unexplained reasons when repeating the same crop plan twice, after having used the default "Repetitions of... " name on the initial repetition.
This PR updates the validation error to also show immediately upon load.
Jira link: https://lite-farm.atlassian.net/browse/LF-3500
**Checklist:**
> LF-3500 Crop plan repeat action can't be done more than once for the same plan

- packages/webapp/src/containers/Task/saga.js
This adds the deleteTransplantTaskSuccess to the delete task saga.
It took me a while for some reason to find this existing function. Other things tried/considered:
- refreshing managementPlan and tasks
- selector for plantingManagementPlans that did not include pmp's where associated task id is deleted
- hard deleting planting management plan of transplant task
Jira link: [LF-3474](https://lite-farm.atlassian.net/browse/LF-3474)
**Checklist:**
[LF-3474]: https://lite-farm.atlassian.net/browse/LF-3474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
> LF-3474-Add deleteTransplantTaskSuccess to delete task saga

- packages/api/src/controllers/userFarmController.js
The `upgradePseudoUser` controller didn't send a `first_name` within the first argument object expected by `createTokenSendEmail()`. It should be sent as it is used it the email.
I kept the existence check for `user` in this pattern as it is used in the same object for `user.language_preference`. I'm not sure why user would ever be undefined in this flow but I assume there was a reason it was set up like that, so I'll keep it! 🙂 
Jira link: https://lite-farm.atlassian.net/browse/LF-3499
**Checklist:**
> LF-3499 Email triggered from "Convert this worker to a user with account" flow doesn't include user's name

- packages/api/src/models/sensorModel.js
Depth is not a required header in the CSV when uploading a sensor. However, currently when editing a sensor where the depth has not been set, if it's kept null the PATCH request throws a validation error saying it should be a number. This updates the schema for the sensor model so it allows null on top of number type.
Jira link:
https://lite-farm.atlassian.net/jira/software/c/projects/LF/boards/10?modal=detail&selectedIssue=LF-3469
Tested on my local environment. Uploaded a CSV without the depth header, then tried editing the sensor. After this change, …
> LF-3469: allow null depth in sensor model

- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
- packages/webapp/src/components/RepeatCropPlan/index.jsx
- call `setPersistedPaths` in RepeatCropPlan component so that the form data will persist when coming back from the confirmation view.
- remove `setPersistedPaths` in ManagementPlanTask since it would happen twice because of the change above.
- check previous state of start date and repeat interval in RepeatCropPlan's useEffect so that "weekday" will not be reset when coming back from the confirmation view.
Jira link: https://lite-farm.atlassian.net/browse/LF-3486
**Checklist:**
> LF-3486: Going < from repeat confirmation does not maintain custom day of the week

- packages/webapp/src/components/RepeatCropPlan/utils.js
- fix start date adjustment calculation (avoid using `toISOString` since it involves timezones)
- update `occurrences` array to make the `/repeat_plan` API call with `start_dates` in "YYYY-MM-DD" format (thanks @Duncan-Brain for writing the function (and JSDoc) to be able to take dates in this format!!!) so that `getAdjustedDate` in `/packages/api/src/util/copyCropPlan.js` will work as expected
Jira link: https://lite-farm.atlassian.net/browse/LF-3485
**Checklist:**
> LF-3485: Wrong starting date of the repeated crop plan is displayed once the user completes the creation flow

- packages/api/src/models/irrigationTaskModel.js
Fixes the case where a wild crop cannot be repeated due to irrgation task model. This is a new case of validation error from resulting from the Node18 eol.
Worth considering why we have location_id on the irrigation task model.
Jira link: [LF-3514](https://lite-farm.atlassian.net/browse/LF-3514)
**Checklist:**
[LF-3514]: https://lite-farm.atlassian.net/browse/LF-3514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LF-3514 - Add null case to model to allow for wild crop.

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/containers/Documents/DocumentTile/index.jsx
- packages/webapp/src/containers/Documents/index.jsx
Removed the failing download icon and added an info icon that reads:  View detail page to download multiple files. 
Jira link: https://lite-farm.atlassian.net/browse/LF-3457
**Checklist:**
> Removing download icon from document tile view. Adding info icon

- packages/webapp/src/components/Crop/ManagementDetail/EditManagementPlanDetail.jsx
- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanDetail.jsx
- packages/webapp/src/containers/Crop/ManagementDetail/EditManagementDetails.jsx
- packages/webapp/src/containers/Crop/ManagementDetail/ManagementDetails.jsx
This PR fixes the whitescreen (Type Error) concurrency crash that could be triggered by being on either the "Details" or "Edit" views of a management plan at the time that it is deleted by another user.
It adds the following:
1. A refresh of the management plan store on the details view (as we already have implemented on the tasks view)
2. Checks for the existence of the plan object on the two Pure Components
3. Pathing logic such that I *think* the user will always be routed to only one "unknown record" splash screen and then to the management plans list, regardless of which screen they were on when the delete occurred
Jira link: https://lite-farm.atlassian.net/browse/LF-3482
Please describe the tests that you ran to verify …
> LF-3482 User is redirected to wrong page/state when trying to edit a deleted record

- packages/webapp/src/components/Task/PestControlTask/index.jsx
This PR handles the white screen issue which occurs when 'Pest control methods' is changed from ( Biological Control , Flame Weeding , Hand Weeding , Pruning , Other ) to ( Foliar Spray, Soil Fumigation or Systemic Spray )
Jira link: https://lite-farm.atlassian.net/browse/LF-3351
Now you should be able to change between the 'Pest control methods' on 'Mark Complete' flow of a task.
**Checklist:**
> LF-3351-White-screen-is-displayed-once-the-user-changes-Pest-control-method-type-during-the-Completion-flow-of-the-Pest-Control-task

- packages/webapp/src/containers/Task/index.jsx
Co-authors @SayakaOno and @Duncan-Brain 
This fixes the white screen type error crash on the task view page that happens from tasks referencing deleted management plans.
This PR updates the task redux store state prior to updating the management plan store state.
Jira link: https://lite-farm.atlassian.net/browse/LF-3527
**Checklist:**
> LF-3527 TypeError: o.crop_variety is undefined

- packages/webapp/src/components/Crop/ManagementDetail/ManagementPlanTasks.jsx
Hide the copy repeat menu for a plan that has no tasks.
Jira link: https://lite-farm.atlassian.net/browse/LF-3528
**Checklist:**
> LF-3528: The white screen is displayed when the user tries to create the repeated crop plan for a crop plan without any tasks in it.

- packages/webapp/src/components/Form/Unit/index.jsx
- packages/webapp/src/components/Form/Unit/unit.module.scss
Make "Harvest to date" label one line.
Jira link: https://lite-farm.atlassian.net/browse/LF-3513
**Checklist:**
> LF-3513: Harvest to date label should be on one line

- packages/webapp/src/components/Tile/IconLabelTile.jsx
- packages/webapp/src/components/Tile/Tiles.jsx
- packages/webapp/src/components/Tile/constants.js
- packages/webapp/src/components/Tile/styles.module.scss
- packages/webapp/src/stories/Tile/IconLabelTile.stories.jsx
- packages/webapp/src/stories/Tile/Tiles.stories.jsx
- Create `LabelIconTile` and `Tiles` component that can be used for:
- task type view (refactor [ticket](https://lite-farm.atlassian.net/browse/LF-3567))
- expense type view
- revenue type view
- [IconLabelTile stories](http://localhost:6006/?path=/docs/components-tile-iconlabeltile--docs)
- [Tiles stories and tests](http://localhost:6006/?path=/docs/components-tile-tiles--docs)
- (the scss file was copied from `packages/webapp/src/components/Task/PureTaskTypeSelection/styles.module.scss`)
Jira link: https://lite-farm.atlassian.net/browse/LF-3552
storybook tests (the link is in the description)
**Checklist:**
> LF-3552: Create reusable tile view component

- packages/api/db/migration/20230817142109_add_custom_expense_types_spotlight.js
- packages/api/src/controllers/showedSpotlightController.js
- packages/api/src/models/showedSpotlightModel.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Typography/index.tsx
- packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/styles.module.scss
- packages/webapp/src/containers/Finances/NewExpense/ManageCustomExpenseTypesSpotlight/index.jsx
- packages/webapp/src/containers/Finances/styles.module.scss
- packages/webapp/src/containers/showedSpotlightSlice.js
- Added "Manage custom type" icon link at the end of the Add Expense page.
- Added spotlight to highlight this icon link.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3559
Tested locally by going to Add expense page and checking that the new icon link renders at the end of the page correctly, the spotlight is shown the first time, and once it's dismissed it doesn't display again when reloading the page.
**Checklist:**
> LF-3559 add manage custom expense type spotlight

- packages/webapp/public/locales/en/message.json
- packages/webapp/public/locales/es/message.json
- packages/webapp/public/locales/fr/message.json
- packages/webapp/public/locales/pt/message.json
- packages/webapp/src/apiConfig.js
- packages/webapp/src/containers/Finances/saga.js
- packages/webapp/src/containers/revenueTypeSlice.js
- packages/webapp/src/store/reducer.js
This PR creates the new Redux Toolkit (RTK) slice and the saga functions for revenue types, corresponding to the db table created in PR #2857.
I took the custom expense type API PR (#2849) by @gursimran-singh as the model for how I expect the new API endpoints to look.
Jira link: https://lite-farm.atlassian.net/browse/LF-3586
I tested these rendering by the selectors in the client (with some dummy JSX) and some temporary API routes on the backend -- please ping on Slack if you would like the dummy code for frontend or backend. Ideally these should be tested …
> LF-3586 make the revenue type slice and add the revenue types selector and sagas

- packages/webapp/src/assets/colors.scss
- packages/webapp/src/components/Card/SummaryCard/index.jsx
- packages/webapp/src/components/Card/card.module.scss
- packages/webapp/src/stories/Card/SummaryCard.stories.jsx
- add a new green colour (it's `Green-700` in [figma](https://www.figma.com/file/96NZ02oYe3jpet1roUp0s0/Mockups?type=design&node-id=3228-9302&mode=design&t=HYTw3PqVv7vmy3GT-0), but it already exists, so I changed it to `green800`...)
- create SummaryCard component
- create [stories](http://localhost:6006/?path=/docs/components-summarycard--docs)
Jira link: https://lite-farm.atlassian.net/browse/LF-3616
**Checklist:**
> LF-3616: Create reusable summary tile component

- packages/api/src/controllers/baseController.js
- packages/api/src/controllers/farmExpenseTypeController.js
- packages/api/src/models/expenseTypeModel.js
- packages/api/src/routes/farmExpenseTypeRoute.js
- packages/api/tests/expense_type.test.js
To create Api's to add, edit, delete custom expense types. Following are the response types of each endpoint
1. `POST /expense_type` to create new expense type
- If for combination of expense name and farm id exists but is either deleted or not, then no new record is created and deleted is set to false for the existing record. 204 status code is sent in this case.
- If for above combination, no record is present in DB, then new expense type is created and 201 status code is sent.
2. `PUT /expense_type/[expense_type_id]` to update expense type
- While editing, if we change custom expense type to which is already present for that particular farm, then 409 status code is sent.
- On successful update 204 status code is sent.
3. `DELETE /expense_type/[expense_type_id]` to …
> Lf 3551 create api's for custom expense types

- packages/api/db/migration/20230831015743_create_revenue_type_table.js
- packages/api/src/middleware/validation/sale.js
- packages/api/tests/sale.test.js
This fixes the database error seen on first insert(s) into the new `revenue_type` table due to the auto-incrementing primary key which was ignored in favour of insertion.
This PR **amends the migration file**. Affected databases (beta, developer local environments) should be rolled back to before when this migration was run (likely 1 or two 2 batches -- please see your own database's `knex_migrations` table) and then run again once this PR is merged. You will lose your existing custom revenue types (on beta none exist yet as the API to create them has not been merged).
Jira link: https://lite-farm.atlassian.net/browse/LF-3651
Was written and tested on local database with all authors @Duncan-Brain and @SayakaOno and …
> LF-3651 Revenue type table unique violation error on auto-incrementing primary key

- packages/api/src/controllers/baseController.js
- packages/api/src/controllers/revenueTypeController.js
- packages/api/src/routes/revenueTypeRoute.js
- packages/api/tests/revenue_type.test.js
A working GET Revenue Type API was already created alongside the other CRUD methods for Revenue Type.
This PR only updates the GET route path and the name of the controller, to:
- match custom expense type
- be more explicit that the types are fetched on a per-farm basis (as was already the case)
- connect to the existing saga which expects this route
EDIT: After @Duncan-Brain pointed out we were clogging up the transaction pool by running queries outside of the existing established transaction, see thread [here](https://github.com/LiteFarmOrg/LiteFarm/pull/2877/files#r1333494616), I have passed the transaction object to the baseController methods for these controllers as well.
Jira link: https://lite-farm.atlassian.net/browse/LF-3591
**How Has This Been …
> LF-3591 Create the revenueType backend api (route and controller) and the get all types function

- packages/api/.env.default
- packages/api/.knex/knexfile.js
Context: I was having to make this change manually each time I worked wth `npm test` locally and it was driving me nuts!
When we updated our readme instructions to recommend using a Dockerized Postgres, we needed to change our local dev configuration to allow connecting to that database, which was done in this PR:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2737
What should also have been done at that time was applying the same to the test database, as used in `migrate:testing:db` and `npm test`. Otherwise `test_farm` can only be populated on a native installation Postgres which, if the readme instructions were followed exactly, might not even exist.
Note that this **refers to local testing** -- the pipeline (CI tests) has its own knex config.
As before it's an entirely …
> LF-3660 Add optional port variable to test config

- packages/api/src/controllers/revenueTypeController.js
THIS IS A FUN ONE! 😁 
Express won't send any content regardless of what was supplied in `res.send()` if the status code is 204 No Content 🙂 
When "adding" (un-retiring) a deleted record, the POST controller was sending back `res.status(204).send(record)` and the saga was getting merely empty data with message 'No Content'.
Blog post on it: [Express response.status(204) Won’t Return Content](https://bambielli.com/til/2017-03-26-express-res-204/)
MDN Docs: [204 No Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)
Jira link: https://lite-farm.atlassian.net/browse/LF-3663
Issue is easily seen with a debugger in the POST saga after the result is returned from the API.
**Checklist:**
> LF-3663 The white screen will be displayed once the user will create the revenue type with an exact name that he has previously deleted

- packages/webapp/src/components/Finances/AddExpense/ExpenseItemsForType.jsx
- packages/webapp/src/components/Finances/AddExpense/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
- show data the user entered in `AddExpense` when he/she goes back to the expense type selection view and to the form again. (the function to generate default values is updated to use persistedFormData)
- if the user removes all items for the type (please refer the screenshot below), when he/she goes back to the type selection view, the type should be unselected.
- when all items are removed, remove the type from `selectedExpense`
- when the first item is added, add the type back to `selectedExpense`.
Jira link: https://lite-farm.atlassian.net/browse/LF-3626
**Checklist:**
> LF-3626: Persist data in expense form

- packages/webapp/src/containers/Finances/ActualRevenue/index.jsx
- packages/webapp/src/containers/Finances/index.jsx
- packages/webapp/src/containers/Finances/util.js
Fix the total revenue and general revenue values after logging out.
- revenue types are loaded in `Fnances` and `ActualRevenue` to:
- show general revenue values correctly (types were loaded in the tile page, so once you logout and go to the actual revenue page directly, types were empty)
- update `calcActualRevenue` function to include `value` for general type revenues.
Jira link: https://lite-farm.atlassian.net/browse/LF-3599
**Checklist:**
> LF-3599: Fix total revenue calculation and general revenue values

- packages/webapp/src/containers/Finances/CustomRevenueType/AddCustomRevenue.jsx
- packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
- packages/webapp/src/containers/Finances/CustomRevenueType/ReadOnlyCustomRevenue.jsx
- packages/webapp/src/containers/Finances/ManageCustomRevenueTypes/index.jsx
- Wrap PureSimpleCustomType in revenue views to trigger page navigation.
- Fix ManageRevenueTypes path in useEffect.
Jira link: https://lite-farm.atlassian.net/browse/LF-3662
**Checklist:**
> LF-3662: "< " Back arrow redirectes to the wrong page when the user saves the "Custom Revenue Type" 

- packages/webapp/src/components/Modals/ModalComponent/v1/index.jsx
- packages/webapp/src/components/Modals/ModalComponent/v1/styles.module.scss
- packages/webapp/src/components/Modals/ResetPassword/index.jsx
- packages/webapp/src/containers/CustomSignUp/saga.js
- packages/webapp/src/containers/ResetPassword/index.jsx
- packages/webapp/src/containers/customSignUpSlice.js
Replaced the error snackbar with an inline error message by creating a new state variable in redux to hold the error message. 
Modified modal component to accept an error prop to be rendered underneath the button.
Jira link: https://lite-farm.atlassian.net/browse/LF-3190
**Checklist:**
> LF-3190-change-too-many-password-resets-to-be-in-line-error-rather-than-snack-bar

- packages/webapp/src/containers/MediaWithAuthentication/index.jsx
- Change import statement for jszip in the hopes that will fix the beta issue. This isn't really documented in the lib's docs so it's a bit of a stab in the dark.
- Added some code to remove the elements we create to download files from the DOM after the file has been download. This is to prevent having several elements be present if someone clicks on Download multiple times.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3524
Tested locally, although I'll need to test in beta once it's merged.
**Checklist:**
> LF-3524 change import statement for jszip

- packages/webapp/src/containers/Insights/saga.js
When no response is returned from the API, the catch block in the saga will fail attempting to read the error from the response.
Jira link:
I only managed to repro the situation by setting my Network to Offline in Chrome dev tools, although there may be other ways to reproduce the same behavior.
When this happens, there should be no errors in the console and instead we should show the error modal.
**Checklist:**
> LF-3675 handle case when no response is returned

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Finances/Transaction/ExpandedContent/CropSaleTable.jsx
- packages/webapp/src/components/Finances/Transaction/ExpandedContent/index.jsx
- packages/webapp/src/components/Finances/Transaction/ExpandedContent/styles.module.scss
- packages/webapp/src/components/Finances/Transaction/Mobile/List.jsx
- packages/webapp/src/components/Finances/Transaction/Mobile/styles.module.scss
- packages/webapp/src/components/Table/v2/index.jsx
- packages/webapp/src/containers/Finances/TransactionList/index.jsx
- packages/webapp/src/containers/Finances/useTransactions.js
- packages/webapp/src/containers/Finances/util.js
- packages/webapp/src/stories/Table/TableV2.stories.jsx
- packages/webapp/src/tests/buildTransactions.test.jsx
- create `CropSale` transaction table
- pass `mobileView` `currencySymbol` to `ExpandedContent` (`mobileView` is for the future, and the style for the desktop view will not be shown and has not been finalized)
Some other improvements
- remove unused properties in TableV2 stories
- remove accessor prop that is incompatible with sorting from V2 table
- fix `ExpandableItem`'s `key`. (`index` was being used, and it was expanding a different transaction after the date range is updated)
- remove hovered colour of the expandable item when expanding
- update transactionDate's tag to `h4` (the title of the page "Finances" is `h3` so I chose `h4`)
Jira link: https://lite-farm.atlassian.net/browse/LF-3761
**Checklist:**
> LF-3761: Implement crop sales expandable content

- packages/webapp/src/components/DateRangeSelector/styles.module.scss
Update customDateRangeSelector's z-index so that the component is displayed over the carrousel.
Jira link: https://lite-farm.atlassian.net/browse/LF-3797
**Checklist:**
> LF-3797: Finance custom date range dropdown is shown under CardsCarrousel

- packages/webapp/src/containers/AddCropVariety/saga.js
- packages/webapp/src/containers/EditCropVariety/index.jsx
After editing crop varietal, go back to the previous page. If the previous page is not crop detail page, replace current url with crop detail page so that history.back will leads to the page before crop detail page
Jira link:
https://lite-farm.atlassian.net/browse/LF-3568
Tested 
crop_varieties/crop/168
crop/02fc91b2-9f5b-11ed-ab82-01644e28fa9e/management
crop/02fc91b2-9f5b-11ed-ab82-01644e28fa9e/detail
crop/02fc91b2-9f5b-11ed-ab82-01644e28fa9e/edit_crop_variety
submit -> back
crop/02fc91b2-9f5b-11ed-ab82-01644e28fa9e/management
**Checklist:**
> LF-3568: edit varietal history stack issue

- packages/webapp/src/components/Form/ReactSelect/index.jsx
This is a fun bug!!
This [commit](https://github.com/LiteFarmOrg/LiteFarm/pull/2913/files#diff-9b510ffac5e2f98e7a188cd29fe6409be58bfd51d9a33be2b4cec8aade222fb5) by @SayakaOno fixed the logic assigning `isSearchable` in the `<ReactSelect />`.
Currently we have only one "creatable" React Select in App (for Product). Here the `isSearchable` prop was never passed, but the faulty original logic:
`isSearchable={options?.length > 8 || isSearchable}`
meant that if there were fewer than 8 options, `isSearchable={undefined}` was passed, and the `<CreateableSelect />` took its default value of `isSearchable={true}`
Now that the logic has been fixed, `isSearchable` was false when the number of options was less than 8.
However a `<CreateableSelect />` needs to have …
> LF-3788 The user is not able to type out a product name during the creation of the soil amendment task or clean task

- packages/webapp/src/components/CreateUserAccount/index.jsx
- packages/webapp/src/containers/SSOUserCreateAccountInfo/index.jsx
This PR moves the `<SSOUserCreateAccountInfo />` container off of the `<PureInvitedUserCreateAccountPage />` component (which has no language field) to the `<PureCreateUserAccount />` component (which does).
Jira link: https://lite-farm.atlassian.net/browse/LF-3779
The `language_preferences` field of the `users` table was previously always taking the field default value of `'en'` and should now store what was selected during account creation
**Checklist:**
> LF-3779 The field "Language preference" is missing when the user is creating the account using SSO method

- packages/webapp/src/components/Task/PureAddCustomTask/index.jsx
- packages/webapp/src/components/Task/PureEditCustomTask/index.jsx
Add missing useHookFormPersist to add custom task page and edit custom task page so that when history.back is called, the last url will be removed from hookFormPersistReducer.historyStack
Jira link:
https://lite-farm.atlassian.net/browse/LF-3575
create a custom task -> back arrow -> cancel button -> task page
retire a custom task -> back arrow -> cancel button -> task page
**Checklist:**
> LF-3575: add custom task navigation bugs

- packages/webapp/src/components/Form/Unit/index.jsx
Fix the unit dropdown that is shown under "Continue" button by portaling the select menu to the document.body level of the DOM.
References:
- https://stackoverflow.com/questions/55830799/how-to-change-zindex-in-react-select-drowpdown
- https://react-select.com/advanced#portaling
Jira link: https://lite-farm.atlassian.net/browse/LF-3601
**Checklist:**
> LF-3601: The user is not able to change the unit of measurement after he adds another harvest use during the completion of the harvest task

- packages/webapp/src/containers/Outro/index.jsx
LF-3516 link outro back button to certification summary page if user pursues certification
Jira link:
https://lite-farm.atlassian.net/browse/LF-3516
select different types of certification, go to outro, back should lead to summary page
**Checklist:**
> LF-3574 outro back button link bug

- packages/webapp/src/components/Finances/PureExpenseDetail/index.jsx
- packages/webapp/src/util/moment.js
The bug is that when viewing an expense that was created with timezone UTC+X, where X>1, it shows the date of the day before.  
This was caused by the use of a function that truncated the timezone of the data retrieved from the server, so to fix it, I just used a function that converted to the user timezone considering the TZ of the data passed by the backend.
Jira link: https://lite-farm.atlassian.net/browse/LF-3758
The change was tested by changing to different timezones that are on the day after the one that my database is storing the data, and creating expenses on these timezones to check if it would take the right time.  (My db stores on UTC-6 and now is 22h40m, so I change to UTC+3, and UTC+7, on integration branch I …
>  LF-3758 When the user creates an expense, the date will not be displayed correctly in Expense detailed view

- packages/webapp/src/components/CardsCarrousel/index.jsx
- packages/webapp/src/components/CardsCarrousel/styles.module.scss
- packages/webapp/src/components/Drawer/index.jsx
- packages/webapp/src/components/Drawer/style.module.scss
- packages/webapp/src/components/Finances/AddTransactionButton/index.jsx
- packages/webapp/src/containers/Filter/Transactions/index.jsx
- packages/webapp/src/containers/Finances/Report/index.jsx
- packages/webapp/src/containers/Finances/Report/styles.module.scss
- packages/webapp/src/containers/Finances/TransactionFilter/index.jsx
- packages/webapp/src/containers/Finances/TransactionFilter/styles.module.scss
- packages/webapp/src/containers/Finances/styles.module.scss
- packages/webapp/src/hooks/useIsAboveBreakpoint.js
- Show finances dashboard filter and report modals in drawer in smaller screens.
- Reused @SayakaOno's logic to show/display something depending on a breakpoint and extracted it to reusable hook. CSS wasn't working here because the modal is based on MUI and it wasn't possible to hide the backdrop with CSS.
- Unrelated change -- adjust carrousel styling to make all cards the same width and make container scrollable in smaller screens. Fixed key warning.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3803
**Checklist:**
> LF-3803 show filters and report in drawer

- packages/webapp/src/containers/Finances/util.js
When I made the change to make crop transactions their own category in the transaction type enum, I missed updating the util that calculates the actual revenue to include both categories.
Jira link:
https://lite-farm.atlassian.net/browse/LF-3802
**Checklist:**
> LF-3802 include crop revenues in actual revenue calc

- packages/webapp/src/components/Menu/FloatingButtonMenu/styles.module.scss
Update FloatingButtonMenu z-index to 1000.
I set it to be carrousel < FloatingButtonMenu < drawer.
Jira link: https://lite-farm.atlassian.net/browse/LF-3805
**Checklist:**
> LF-3805: Add transaction menu is shown below expanded table header on mobile

- packages/api/src/server.js
Issue is that on finance view, today's sales appeared on "Yesterday" section, this was because the POST sent was only sending the date without TZ and the backend was making a mess when interpreting the time.
So in this PR I changed the sales POST to have the TZ (and the backend to accept the timezoned date).
Jira link: https://lite-farm.atlassian.net/browse/LF-3799
I have test to create sales on a custom revenew type and on the default one, configuring my computer to have a TZ where the day is the same as my backend configuration, and a TZ where it is the next day, and as the TZ is now being taken into account, it seems to work ok.
**Checklist:**
> LF-3799-Transactions-added-with-today-s-date-are-shown-as-Yesterday

- packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
- packages/webapp/src/containers/Finances/Report/index.jsx
- packages/webapp/src/containers/Finances/Report/reportFormattingUtils.js
- packages/webapp/src/containers/Finances/selectors.js
Type filters are initially `undefined` (and transactions are unfiltered) until the user interacts with one of the type filter modals (/drawers). Since the user can export a transaction report without setting a type filter, a "fake" filter object had to be constructed to give the Excel worksheet and the `filter_config` database column the correct "all types active" data for this situation.
Jira link: https://lite-farm.atlassian.net/browse/LF-3806
I tested this by looking at the output on the Excel report, second worksheet. The goal was to have the output indistinguishable from when the filters were manually applied as "Select All".
**Checklist:**
> LF-3806 Report is sent an undefined filter config when the dashboard or report filter settings have not been modified

- packages/api/db/migration/20231110195632_add-retire-vs-delete-distinction-to-finance-types.js
- packages/api/src/controllers/baseController.js
- packages/api/src/controllers/farmExpenseTypeController.js
- packages/api/src/controllers/revenueTypeController.js
- packages/api/src/models/expenseTypeModel.js
- packages/api/src/models/revenueTypeModel.js
- packages/api/tests/expense_type.test.js
- packages/api/tests/revenue_type.test.js
- packages/webapp/public/locales/en/message.json
- packages/webapp/src/components/Form/hookformValidationUtils.js
- packages/webapp/src/containers/Finances/CustomExpenseType/AddSimpleCustomExpense.jsx
- packages/webapp/src/containers/Finances/CustomExpenseType/EditSimpleCustomExpense.jsx
- packages/webapp/src/containers/Finances/CustomRevenueType/AddCustomRevenue.jsx
- packages/webapp/src/containers/Finances/CustomRevenueType/EditCustomRevenue.jsx
- packages/webapp/src/containers/Finances/ExpenseDetail/index.jsx
- packages/webapp/src/containers/Finances/RevenueDetail/index.jsx
- packages/webapp/src/containers/Finances/saga.js
- packages/webapp/src/containers/Finances/selectors.js
- packages/webapp/src/containers/Finances/useCustomExpenseTypeTileContents.js
- packages/webapp/src/containers/Finances/util.js
- packages/webapp/src/containers/revenueTypeSlice.js
This is the follow-up PR to the one that reserved the names of retired types and removed the under-the-hood unretire functionality:
- https://github.com/LiteFarmOrg/LiteFarm/pull/2970
This PR creates a distinction between types that should be retired (= have an associated expense/revenue at the time of retiring, should stay in the filters, are name reserved) vs deleted (= have no associated expense/revenues, should not appear in the filters, are not name reserved). The components are:
- Adding a new retired property to the database tables and models
- (This is just for beta and local environments) a **reversible** data migration that classifies previously 'retired' types into the correct category -- retired or deleted -- depending on whether they have records associated …
> LF-3666b Add retire vs delete distinction to finance types

- packages/webapp/src/components/Task/PureTaskCrops/index.jsx
- packages/webapp/src/containers/Task/TaskDate/index.jsx
In this page above, the user is not allowed to "continue" to the next page without selecting a plan. The bug is that a plan that is not available as an option on this page is "selected" under the hood. This PR adds a check if the plan is available as an option before "selecting" it.
Details:
When creating a harvest task from a crop plan, the crop plan you selected is selected as a "plan that will be affected" by default. If you change the location to create a harvest task for another plan, the crop plan you selected should be deselected because the plan is not for the location you selected. (you will not see the plan as an option, but it remains "selected")
I added a check if the crop plan selected in the previous page is available for the location before setting it as …
> LF-3608: Although the success pop up message is displayed, the harvest task won't be created, it actually creates an empty harvest task.

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
Restores YET MORE translations.
Jira link: https://lite-farm.atlassian.net/browse/LF-3778
**Checklist:**
> LF-3778c Clean up unused translations using i18n script

- packages/api/src/controllers/userController.js
This one was a bit weird! The symptom is that the `language_preference` property is missing from the `userFarm` Redux entity when the `userFarmSelector` is called from `<Account />`, but ONLY if you go there directly after creating a new farm, rather than after logging in. In the Jira ticket there is one "symptom-level" fix for this issue.
The cause is that this GET request in `postFarmSaga` doesn't return the `language_preference` property:
``` 
call(axios.get, userUrl + '/' + user_id, header),`
```
This is the `getUserByID` controller. What I consider a bit weird is that it's actually not called anywhere else in app except within this Add Farm saga / flow (or at least, that's how it appears after a frontend code search) 🤷 
Jira link: …
> LF-3814 The white screen is displayed once the user Updates the user info without actually selected the preferred LiteFarm Language

- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
`<input type="file" />` does not retain previously selected file data. So if you select a file, click the input again to select a file and click "cancel", `e.target.files` (`fileInputRef.current.files[0]` in the actual code) does not have any file information.
This PR adds a state to keep the file data that will be used for uploading.
Jira link: https://lite-farm.atlassian.net/browse/LF-3809
**Checklist:**
> LF-3809: No actions are triggered once the user clicks on the "Upload" button, once the user added the csv file

- packages/api/src/models/greenhouseModel.js
The other two locations that refer to a 'transition_date' in their API models (`fieldModel.js` and `gardenModel.js`) have some code that converts the 'transition_date' datetime string into a date by stripping off the time information.
Without that bit, the transition date format being sent to the database (e.g. `"2023-11-07T00:00:00.000"`) was triggering the model validation error `'greenhouse.transition_date: must match format "date"'`. There is definitely more than one way to fix this but I chose to keep the parallelism to the other corresponding locations.
Jira link: https://lite-farm.atlassian.net/browse/LF-3821
I followed the steps in the linked video 🙂 
**Checklist:**
> LF-3821 Failure when editing greenhouse details

- packages/webapp/nginx.conf
The current rate limit is 50r/s whereas about 70 requests are sent on the home page, which makes the finance page (and other pages) crash.
This PR raise the limit to 100r/s.
Jira link:
- https://lite-farm.atlassian.net/browse/LF-3823 🙏 
- https://lite-farm.atlassian.net/browse/LF-3825 🙏 
**Checklist:**
> Update rate limit to 100r/s

- packages/webapp/src/containers/CustomSignUp/index.jsx
Small fix to unmount the `<PureEnterPasswordPage />` component when its visibility is toggled.
Jira link: https://lite-farm.atlassian.net/browse/LF-3817
**Checklist:**
> LF-3817 Unmount PureEnterPasswordPage when visibility changes

- packages/api/src/controllers/managementPlanController.js
- packages/shared/constants/error.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
- packages/webapp/src/components/Modals/UnableToAbandonPlanModal/index.jsx
- packages/webapp/src/components/Modals/UnableToCompletePlanModal/index.jsx
- packages/webapp/src/containers/Crop/CompleteManagementPlan/AbandonManagementPlan.jsx
- packages/webapp/src/containers/Crop/CompleteManagementPlan/CompleteManagementPlan.jsx
- packages/webapp/src/containers/Crop/CompleteManagementPlan/saga.js
- packages/webapp/vite.config.ts
Fixed concurrency issue where if a user completes a crop plan and the other one tries to abandon it without reloading the screen, or vice versa, we should prevent this from happening and show an error modal.
Jira link:
Tested locally by attempting the concurrent completing/abandoning with two different accounts.
**Checklist:**
> LF-3423: disallow abandoning completed plan and viceversa

- packages/webapp/public/locales/fr/translation.json
- packages/webapp/src/components/Finances/Transaction/Mobile/List.jsx
- packages/webapp/src/components/Form/Button/button.module.scss
- packages/webapp/src/containers/Finances/Report/reportFormattingUtils.js
- packages/webapp/src/containers/Finances/index.jsx
- packages/webapp/src/containers/Finances/useTransactions.js
- packages/webapp/src/containers/saga.js
- packages/webapp/src/stories/Button/DropdownButton.stories.jsx
- packages/webapp/src/tests/buildTransactions.test.jsx
- I noticed sometimes with slow networks, the transactions started showing up before the expense/revenue types loaded and the types showed up as `undefined.EXPENSE_NAME`. I altered the order of the fetching so we get the types first and the expenses/sales second, but I also added a fallback just in chase so we'll show an empty string if the type is undefined and gracefully load the types.
- Fixed buttons font which for some reason is different from the rest of the app.
- Fixed a story that's failing because of an incorrect import.
- Fixed French translation extra comma.
Jira link:
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for …
> Small fixes

- packages/webapp/src/containers/Filter/Transactions/index.jsx
- packages/webapp/src/containers/Finances/AddSale/RevenueTypes/useSortedRevenueTypes.jsx
- packages/webapp/src/containers/Finances/Report/index.jsx
- packages/webapp/src/containers/Finances/Report/reportFormattingUtils.js
- packages/webapp/src/containers/Finances/selectors.js
This PR:
- Adds the 'retired' suffix to the filter pills (and the list of selected filters in the Excel report settings worksheet)
- Sorts all expense and revenue types (in type selection, filters, and report settings) completely alphabetically, rather than default > custom
Jira link: https://lite-farm.atlassian.net/browse/LF-3815
**Checklist:**
> LF-3815 Distinguish retired and un retired types in filter views

- packages/webapp/src/containers/Finances/AddSale/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/AddExpense/index.jsx
What I think its going on is the persistedFormData is not being saved fast enough for the AddSale component to retrieve it on the first render and since it's trying to destructure an object on that render it fails. As a temporary fix, just using the object instead of destructuring works.
Also removing <= validation on finances that should be "<"
Jira link:
**Checklist:**
> LF-3800 Fixing White screen when user tries to add custom revenue.

- packages/webapp/src/components/Home/home.module.scss
- packages/webapp/src/containers/Home/index.jsx
- packages/webapp/src/containers/MediaWithAuthentication/index.jsx
- packages/webapp/src/containers/hooks/useMediaWithAuthentication.js
Fix for the image not appearing on home page after user uploads custom image.
**Changes**
Created a custom hook from the MediaWithAuthentication component so the url can be directly passed into PureFarm which sets the background image using css. Also added a fade transition to avoid the image popping in suddenly.
Jira link: https://lite-farm.atlassian.net/browse/LF-2200
This is hard to test locally because it relies on the cloudflare worker and thats only used in beta and production. 
**Checklist:**
> Lf 2200 allow the user to upload a custom image for the lf homepage background

- packages/webapp/src/containers/Finances/actions.js
- packages/webapp/src/containers/Finances/constants.js
- packages/webapp/src/containers/Finances/index.jsx
- packages/webapp/src/containers/Finances/reducer.js
- packages/webapp/src/containers/Finances/saga.js
- packages/webapp/src/containers/Finances/selectors.js
- packages/webapp/src/containers/saga.js
- packages/webapp/src/containers/taskSlice.js
Reorganizes the calling of sagas between switching farm and finances; puts finances behind a loading spinner until data fetching is compete; clears task data between farms.
Note: TypeError shown below may persist with a low reproduction rate.
Jira link: https://lite-farm.atlassian.net/browse/LF-3825
Mostly wrapped the TypeErrors in `try { } ... catch { }` and verified it was a mix of old + new farm data causing the crash. Only when switching farms, only on Slow 3G throttling.
**Checklist:**
> LF-3825 the white screen is displayed on the mobile phone device once the user switches the farms and opens the finance dashboard

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
Again 😳 
Jira link: https://lite-farm.atlassian.net/browse/LF-3778
**Checklist:**
> LF-3778d Clean up unused translations using i18n script

- packages/api/src/controllers/taskController.js
- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/containers/Task/TaskAssignment/index.jsx
- packages/webapp/src/containers/Task/saga.js
When two users are logged on to the same farm and one user begins the task creation flow at a particular location while another user attempts to retire the same location, the tasks are created at a location that does not exist on the farm
Jira link:https://lite-farm.atlassian.net/browse/LF-3215
- Start to create a new task
- Before finishing the task creation flow, delete the location by setting the "deleted = true" in database to mimic the behaviour that another user has deleted the location at the same time.
- Try to save the task. Error will occur and a modal will be displayed giving info of the error.
**Checklist:**
> Lf 3215 a user creating a task at a location concurrently with another user retiring said location creates a task at a location that does not exist

- packages/webapp/src/containers/Finances/AddSale/RevenueTypes/index.jsx
- packages/webapp/src/containers/Finances/NewExpense/ExpenseCategories/index.jsx
- packages/webapp/src/containers/Finances/util.js
Use translations for default expense types' expense names for searching instead of types' `expense_name`.
Jira link: https://lite-farm.atlassian.net/browse/LF-3870
**Checklist:**
> LF-3870: Search for expense does not work for all types

- packages/api/src/util/generateFinanceReport.js
This isn't an issue that we would have seen on production (provided all translation strings currently marked as "MISSING" are supplied!)
ExcelJS names the worksheet titles with a translated string that we provide. Two worksheets cannot have the same name. However, in PT and FR currently, those translations are `"MISSING"` and the worksheet generation was failing with error:
`'Worksheet name already exists: MISSING'`
To prevent the worksheet generation from failing in this case (and in the future if when we add new languages but haven't finished the translation work) I added a small function to provide a fallback in English.
Jira link: https://lite-farm.atlassian.net/browse/LF-3866
Tested the cases of 1) translation string …
> LF-3866 Could not download finance report

- packages/webapp/src/containers/MediaWithAuthentication/index.jsx
Literal stab in the dark to attempt to fix the problem since I can't repro. I noticed that when I implemented the zip file downloads, I changed this
`element.download = title;`
to this
```
element.download = `${title}.${extensionName}`;
```
It seems out of all the changes it could be the most likely to be the culprit, although it's impossible to tell without testing it.
Jira link: https://lite-farm.atlassian.net/browse/LF-3878
**Checklist:**
> LF-3878 attempt at fixing file extensions with underscore

- packages/api/src/controllers/farmExpenseTypeController.js
- packages/api/src/controllers/revenueTypeController.js
Fixes both finance type update controllers to reflect the fact that records can now have the same name as long as one is `deleted`.
Jira link: https://lite-farm.atlassian.net/browse/LF-3883
**Checklist:**
> LF-3883 Can't edit the description of a type that shares the name of a deleted type

- packages/webapp/src/components/Form/InputDuration/index.jsx
Import `getLocalizedDateString` from the right file.
The file we were importing from was accidentally changed [here](https://github.com/LiteFarmOrg/LiteFarm/pull/3004/files#diff-614834b019de4f385436d70d51f41545183db3811f9ea1279efb18a11cc8c119).
Jira link:
- https://lite-farm.atlassian.net/browse/LF-3902
- https://lite-farm.atlassian.net/browse/LF-3885
**Checklist:**
> LF-3902 The white screen is displayed during the creation of a crop plan once the user will click on the "Germination" or "Initial harvest" field.

- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/controllers/cropController.js
- packages/api/src/controllers/cropVarietyController.js
- packages/api/src/controllers/documentController.js
- packages/api/src/middleware/farm.js
- packages/api/src/util/digitalOceanSpaces.js
- Migrated from old v2 sdk to v3.
- In v3 you only install the dependencies you need instead of the whole aws-sdk package which in this case is @aws-sdk/client-s3. This package is only 3.4mb compared to 90mb used before (according to npmjs).
Jira link: https://lite-farm.atlassian.net/browse/LF-3389
Existing upload functionality still works for crops, documents and farm images.
**Checklist:**
> Lf 3389 migrate aws sdk from v 2 to v 3

- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/common/logger.js
Update: we modified our Sentry permissions temporarily to allow troubleshooting from localhost. The [issue](https://litefarm.sentry.io/issues/4701829430/events/0096482202c7409b8d5311d028ab6d64/) format and stack trace look good and useable so I think it's fine to run on beta!
Note: this relates to PR #3023 in that it piggy-backs on the Winston logger to get our errors to Sentry, but should be a standalone code change (i.e. doesn't depend on that PR's code changes). 
This PR adds a [custom Winston transport](https://github.com/winstonjs/winston#adding-custom-transports) to send Error objects passed to Winston to Sentry, using `Sentry.captureException(error)`, see [Sentry docs](https://docs.sentry.io/platforms/node/usage/#capturing-errors)). Because our needs were minimal, I …
> LF-3914 Post (some) handled errors to Sentry

- packages/webapp/nginx.conf
_This can only be tested on beta. Whether it solves the MIME type crashes should be tested by looking at the behaviour of merging a PR that triggers a frontend rebuild; I will open a PR for this shortly._
This follows the exact recommendations in the vite-pwa documentation under [Vite PWA | Deployment | NGINX](https://vite-pwa-org.netlify.app/deployment/nginx.html). It specifies to always re-validate the most important pwa files (index.html, the webmanifest, and the service worker file sw.js) but to keep the cached assets (which are hashed, so this is safe to do) as long as possible.
Please see linked ticket (and its parent) for more details and justification.
Jira link: https://lite-farm.atlassian.net/browse/LF-3921
Must be …
> LF-3921a Update Nginx configuration to match vite-pwa recommendations

- .github/workflows/lint_translation_files.yml
- packages/webapp/.eslintrc.json
- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
I found that some checks are already running against json files in pre-commit. I assumed asking translators to do `npm install` to run pre-commit would not be a good idea and decided to add a github workflow so that we will not be able to merge PRs that have invalid JSON files.
- install [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json)
- update `.eslintrc.json` to use eslint-plugin-json
- create a github workflow
Jira link: https://lite-farm.atlassian.net/browse/LF-3085
Created PRs with:
- trailing comma
```
{
...,
{
"TEST": "test",
}
...
}
```
- double commas
```
{
...,
{
"TEST": "test",,
"TEST2": "test"
}
...
}
```
- invalid characters (E2809C)
```
{
...,
{
"TEST": “test”
}
...
}
```
**Checklist:**
> LF-3085: Add a linter for translations files

- packages/webapp/src/assets/mixin.scss
- packages/webapp/src/components/Navigation/NavBar/index.jsx
- packages/webapp/src/components/Navigation/NoFarmNavBar/styles.module.scss
This is the visual change to test:
- #3031 
It removes the gradient from the farm selection page, and restores a white background to the logged in header. In the previous code test PR, I had removed the navBar background entirely, which rendered it transparent, as @den4ik1203 discovered 🙂 
Jira link: https://lite-farm.atlassian.net/browse/LF-3923
This is for testing on merge to beta.
**Checklist:**
> LF-3923b Remove header gradient from farm selection page

- packages/webapp/src/assets/mixin.scss
- packages/webapp/src/components/Navigation/NavBar/index.jsx
- packages/webapp/src/components/Navigation/NoFarmNavBar/styles.module.scss
Reverts the visual changes from:
- #3034 
There is nothing wrong with the changes, I just would like to re-create the crash @SayakaOno discovered being on the farm creation flow when the changes went live. I will open two new PRs to revert and then restore the visual change.
Jira link: https://lite-farm.atlassian.net/browse/LF-3923
**Checklist:**
> LF-3923c Revert visual changes from LF-3923b

- packages/api/src/common/logger.js
- packages/api/src/controllers/cropVarietyController.js
- packages/api/src/controllers/documentController.js
- packages/api/src/controllers/insightController.js
- packages/api/src/controllers/managementPlanController.js
- packages/api/src/controllers/organicHistoryController.js
- packages/api/src/controllers/taskController.js
I wrongly maligned our logger, [Winston](https://github.com/winstonjs/winston), as responsible for eating the missing message and stack trace properties on the Error object, because I did not know that those two properties on JS Error objects were not enumerable! (See this StackOverflow: [Winston not displaying error details](https://stackoverflow.com/questions/51630896/winston-not-displaying-error-details))
The reason I thought Winston was responsible was the addition of the level and services properties after logging, and indeed Winston v3 does *by design* mutate the original Error object. See this issue on the [Winston repo issue tracker](https://www.github.com/winstonjs/winston/issues?q=is%3Aissue+Don%27t+modify+arguments+passed+to+logging+methods) -- sorry linking to …
> LF-3881 Return better errors by default from the API

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Card/NewReleaseCard/NewReleaseCard.jsx
- packages/webapp/src/components/Card/NewReleaseCard/styles.module.css
- packages/webapp/src/components/Card/NewReleaseCard/styles.module.scss
- packages/webapp/src/util/constants.js
Only code changes:
- Fixed handling of the translation on the New Release Card, so that it tracks the application version and is updated in tandem with client update, not before
- Changes to CSS of that card (decreasing padding to fit more version digits, moving inline CSS to module)
Existing functionality being tested:
- Included a version change in this PR to test the _existing_ logout functionality (please see Jira ticket for details)
- As far as I can tell, the webapp is already configured correctly to force logout when the app version constant is changed. As we don't change versions on integration, I have never seen this behaviour before on beta and would like to observe it
Jira link: https://lite-farm.atlassian.net/browse/LF-3942
**How Has This …
> LF-3942 Fix release card update timing and test logout

- packages/webapp/src/App.jsx
- packages/webapp/src/components/ChooseFarm/index.jsx
- packages/webapp/src/components/Navigation/SideMenu/index.jsx
- packages/webapp/src/components/Navigation/TopMenu/TopMenu.jsx
- packages/webapp/src/components/Navigation/TopMenu/styles.module.scss
- packages/webapp/src/components/Navigation/index.jsx
- packages/webapp/src/components/Profile/People/index.jsx
- packages/webapp/src/components/WeatherBoard/assets/weatherBoard.module.scss
- packages/webapp/src/containers/Navigation/index.jsx
- packages/webapp/src/styles.module.scss
This PR fixes three things that got broken by the navigation update.
1. adjust the snackbar position so that it is placed in the centre of the main content. (I moved `isCompactSideMenu` state up to `App` component which I didn't like. Let me know if you have suggestions)
2. fix farm selection buttons to fit in the main content. I had to pass styles, which we probably don't want to.
3. fix roles translations in people page
4. fix overflowing `WeatherBoard` on the home page
5. add a link to the homepage to the logo on mobile `TopMenu`
Jira link: https://lite-farm.atlassian.net/browse/LF-3932
**Checklist:**
> LF-3932: Fix broken styles due to navigation update

- packages/webapp/src/components/Navigation/index.jsx
*As tested in group*
Using `git bisect` commit 7f631d24bc5526cf7aaf7eefe63488f871fadd11 was identified as being responsible for the current translation issues. Also confirmed at that time that it is actually the namespacing in this hook (i.e. the inclusion of 'messages' in that array) which controls the availability of the translation elsewhere in app.
Note: we are NOT entirely sure why this should be, but we are restoring to the previous state/behaviour. We also, for consistency, added the reference to the one omitted translation file (`revenue`). We are not currently seeing errors on revenue translations, but did at one point [fairly recently](https://litefarm.slack.com/archives/C014931NRFY/p1701365564357259).
Jira link: https://lite-farm.atlassian.net/browse/LF-3944 …
> LF-3944 Some translations become broken when the user refreshes the page and snackbar translations are always missing

- packages/webapp/src/components/Finances/FinancesCarrousel/index.jsx
- packages/webapp/src/hooks/useGetMenuItems.jsx
- packages/webapp/src/routes/FinancesRoutes.jsx
- packages/webapp/src/util/siteMapConstants.ts
When clicking on a subitem of Finances in the nav bar other than Transactions, the Finances menu item wasn't highlighted as active after hotfix 3.6.2.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4023
**Checklist:**
> LF-4023 fix finances menu item not highlighted

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/CreateUserAccount/index.jsx
- packages/webapp/src/components/InviteUser/index.jsx
- packages/webapp/src/components/InvitedUserCreateAccount/index.jsx
- packages/webapp/src/components/Profile/Account/index.jsx
- packages/webapp/src/components/Profile/EditUser/index.jsx
- packages/webapp/src/hooks/useGenderOptions.jsx
- packages/webapp/src/stories/Pages/Profile/Account.stories.jsx
- create `useGenderOptions` hook and use it in components
- add gender and birth year inputs to `Account` component
- update the account [story](http://localhost:6006/?path=/story/form-profile-account--primary)
- update label `User Address` to `Address` and change the order of the inputs based on Loïc's [suggestion](https://lite-farm.atlassian.net/browse/LF-4027?focusedCommentId=16860)
Jira link: https://lite-farm.atlassian.net/browse/LF-4027
**Checklist:**
> LF-4027: Add gender and birth year to user profile

- packages/api/db/migration/20240125135642_add_user_last_name_default.js
- packages/api/src/controllers/loginController.js
- packages/api/src/models/userModel.js
Add default of `''` to `last_name` colum in `users` table.
We're currently not setting a default at the db level and have a fallback of '' on the client when we send out the user information from an invitation. To avoid having to set this fallback in each place where we add a user, I defaulted the column and made the field not required at the model level.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4037
Tested bug by creating a Google account without a last name and verifying that I could use it to log into Litefarm.
**Checklist:**
> LF-4037: add default to last name

- packages/webapp/src/components/Profile/Account/index.jsx
When the user with a non-LF language changes their profile without setting a language, `language_preference` becomes `undefined` ~~in the Redux store~~ and the `litefarm_lang` key in local storage is set to undefined in saga, which causes a crash in the home page. (Thank you Joyce!)
https://github.com/LiteFarmOrg/LiteFarm/blob/37d34dfd0fcc623567583f9c1ba48fef9ea84641/packages/webapp/src/containers/WeatherBoard/utils/index.jsx#L28-L34
(⬆️ `lang` being `undefined` causes a crash)
**Changes**
- update `useLanguageOptions` hook to keep `language_preference` as is. Currently the selected option is becoming `null` for a non-LF language.
- add `option` tag to the last name input label.
NOTE:
I realized that the selected gender does not reflect the newly saved language preference, …
> LF-4038: The app crashes on the home page once the user saves the user profile without preferred language

- .github/workflows/cypress_tests.yml
Alongside the recently merged Cypress PR #3100 we have set up a merge queue on integration. To my great sadness using the merge queue (`merge_group` workflow trigger) did not in fact trigger the GitHub workflow upon the most recent merge.
This [StackOverflow](https://stackoverflow.com/questions/76655935/when-does-a-github-workflow-trigger-for-merge-group-and-is-it-restricted-by-bran) and the linked GitHub discussion suggest that -- as of July 2023 but the discussion has not been amended otherwise in the intervening months -- `merge_group` on its own is insufficient; the `pull_request` trigger must also be added and then filtered out.
I have copied the example.
**UPDATE:** But I dislike that a notification is still sent/check is still listed for the filtered out job...! …
> Include both pull_request and merge_group triggers

- packages/webapp/src/containers/Finances/useCropSaleInputs.jsx
- packages/webapp/src/containers/managementPlanSlice.js
This PR fixes the issue where revenue for a crop sale does not show the crop when the crop management plan for that crop is not active or planned. This can happen when the user deletes, abandons or completes a plan after generating a revenue.
Changes:
- Added a selector to select all management plans 
- Modified useSelector inside useCropSaleInputs to include management plans for crop(s) associated with that particular sale irrespective of their management plan status. 
Jira link: https://lite-farm.atlassian.net/browse/LF-3792
**Checklist:**
> Lf 3792 the sale will no longer be visible once the crop plan will be deleted completed or abandoned

- packages/webapp/src/containers/Map/useMapAssetRenderer.js
- packages/webapp/src/containers/Map/useSelectionHandler.js
Fixes the issue where user can't select a fence on the map when its a vertical line or clicking on the vertical portion of a fence. 
This issue may be caused by a bug in google maps api where the method isLocationOnEdge (inside useSelectionHandler.js line 127) is not able to detect clicks for vertical lines - see related stackoverflow question: https://stackoverflow.com/questions/19113399/google-maps-api-v3-islocationonedge-doesnt-work
Changes: 
- Bypassed the google maps api by removing handleSelection() inside polyline click event listener and replaced it with history.push (the handleSelection method calls history.push internally).
Jira link: https://lite-farm.atlassian.net/browse/LF-3828
Please describe the tests that you …
> LF-3828 fix selecting vertical line on map

- packages/webapp/src/containers/saga.js
This adds RTK Query tag invalidation to `clearOldFarmStateSaga()` which is called during farm switching. For rationale and alternative approaches considered, please see Jira ticket.
Jira link: https://lite-farm.atlassian.net/browse/LF-4141
**Checklist:**
> LF-4141 The animal inventory of the previous farm is shown to the user once he changes the farm without logging out

- packages/api/src/controllers/animalBatchController.js
- packages/api/src/controllers/animalController.js
- packages/api/src/controllers/animalGroupController.js
- packages/api/src/controllers/customAnimalBreedController.js
- packages/api/src/controllers/customAnimalTypeController.js
- packages/api/src/util/errorCodes.js
- packages/api/tests/animal.test.js
- packages/api/tests/animal_batch.test.js
- packages/api/tests/animal_group.test.js
On creation of the objection error handler it was mentioned by @SayakaOno that we should update all animal controllers to be consistent. (and a modest -50 lines of code ;) )
Now every endpoint in animals with a trx and excess checks should be covered.
Also added in a test that was missing from batch and controller -- should not be able to add a default breed with a custom type.
To test: For exhaustive testing remove one check at a time and check that it is still handled.
Jira link: [LF-4092](https://lite-farm.atlassian.net/jira/software/c/projects/LF/issues/LF-4092)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
> LF-4092 - update animal controllers to use handle objection error

- packages/api/tests/animal.test.js
- packages/api/tests/animal_batch.test.js
`faker.lorem.word()` returns non-unique strings, which causes unexpected `409 conflict` in animal types. (I believe that was the cause of the test failure: https://github.com/LiteFarmOrg/LiteFarm/actions/runs/8573143951/job/23497247488?pr=3180)
I made some changes to append a number to a generated string.
It rarely happens, so I tested using `.each()` (`test.each(Array(100).fill(null))('xxx', async () => {})`)
> Fix failing animal test

- packages/webapp/src/components/Icons/icons.jsx
PR #3180 fails to build on merge due to a case-mismatch between the import and filename. Builds locally, so I assume MacOS is more forgiving of this than Linux/Docker.
Jira link: https://github.com/LiteFarmOrg/LiteFarm/pull/3180
Should be tested on build
**Checklist:**
> LF-4187b Fix Crop Sale icon import

- packages/webapp/src/components/Animals/FixedHeaderContainer/index.tsx
- packages/webapp/src/components/Animals/FixedHeaderContainer/styles.module.scss
- packages/webapp/src/containers/Animals/Inventory/index.tsx
- packages/webapp/src/stories/FixedHeaderContainer/FixedHeaderContainer.stories.tsx
Update `FixedHeaderContainer` to take `kind` and wrap `children` conditionally.
- Update `overflow` set to `Paper` to `auto`. (I realized that it wouldn't work for components that need to be scrollable. `<Inventory />` still works with `auto`)
- [stories](http://localhost:6006/?path=/story/components-fixedheadercontainer--paper) (only work on desktop view)
(It was much easier than expected... I overestimated it 🙇‍♀️ )
Jira link: https://lite-farm.atlassian.net/browse/LF-4162
Pass `ContainerKind.OVERFLOW` to the component in `Inventory` and checked how it looked.
**Checklist:**
> LF-4162: Update FixedHeaderContainer to accommodate animal creation wizard

- .github/workflows/cypress_tests.yml
Bump Cypress node version to the same one used across app. I think we just missed this when implementing the new test suite, and not that Cypress requires Node 16 in some way (it runs locally on Node 18).
Jira link: https://lite-farm.atlassian.net/browse/LF-4209
Test on GitHub actions workflow please.
**Checklist:**
> LF-4209 Bump node version to 18.16.1 in Cypress GitHub action workflow

- packages/webapp/src/containers/Task/TaskAssignment/index.jsx
The 400 error message is displayed once the user goes back during creating the task( any type of the task ) and then forth.
The reason was just a syntax error that prevented the application from deleting the `already_completed` property from the POST request payload.
Jira link: https://lite-farm.atlassian.net/browse/LF-4232
**Checklist:**
> LF 4232: Fix 400 error when the user goes back during the task creation process

- packages/webapp/src/containers/userFarmSlice.ts
Updates `userFarmSelector` to override `has_consent`.
(https://github.com/LiteFarmOrg/LiteFarm/pull/3222 didn't work for farm worker accounts because the API returns different responses between admin and farm worker accounts)
Jira link: https://lite-farm.atlassian.net/browse/LF-4256
> LF-4256 (2): Old consent version is shown after setting has consent to false

- packages/webapp/public/locales/en/translation.json
Deletion of unused keys from the `en` translation file, identified via crowdin normalization in #3274
- one belonged to the previous expense/revenue view: https://github.com/LiteFarmOrg/LiteFarm/pull/2851
- other looks like belongs on the view for adding an organic crop but has been missing in two languages for [> 3 years](https://github.com/LiteFarmOrg/LiteFarm/pull/926/files#diff-d7c3637e6dcddb5e0a7e3f3f60baf2ebecd3f59685bccb84d26517ea89c4f817)
**Checklist:**
> Patch 3.6.5 Translations Delete

- packages/api/src/controllers/taskController.js
Unable to create a task when selecting a wild crop in the task creation flow.
**Issue:**
A 400 error was being returned from api due to a postgres error when quering the db to check for a deleted location before creating a task. When creating a task that targets a wild crop, the wild crop doesn't have a location associated to it so the request body has an empty locations property of `[]`, which means `req.body.locations[0]` is undefined and sending undefined to postgres results in an internal error that is caught in the catch block, sending a 400 response.
**Fix:**
To fix this I made a simple check to ensure that locations is not empty before checking if the location is deleted.
**Question:**
As a user on the app, I don't think its possible to create a task (that is not …
> LF-3884 check if location exists in request body

- packages/webapp/src/containers/saga.js
Please see [Jira ticket](https://lite-farm.atlassian.net/browse/LF-4279) and [this Slack thread](https://litefarm.slack.com/archives/C014931NRFY/p1719341970251249) for details.
If for any reason Open Weather rejects our API key on July 1st (extremely extremely unlikely, but might want to stay prepared given that we received an erroneous deprecation notice in the first place), this code change means that the weather dashboard on the homepage will not load, _instead of LiteFarm becoming unusable_.
Logout on API key failure happens because we have an axios interceptor that triggers logout whenever it receives a 401 error. I'm about 99.9% sure that it was never the intention of this interceptor to log us out of the application if any external API returns a 401, because that is …
> LF-4279 Fix logout on OpenWeather API 401

- packages/webapp/src/components/Expandable/useExpandableItem.js
- packages/webapp/src/components/Form/CompositionInputs/NumberInputWithSelect.tsx
- packages/webapp/src/components/Form/CompositionInputs/index.tsx
- packages/webapp/src/components/Form/CompositionInputs/styles.module.scss
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/useInputsInfo.ts
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/styles.module.scss
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/types.ts
- packages/webapp/src/stories/Form/CompositionInputs/CompositionInputs.stories.tsx
- packages/webapp/src/stories/Pages/Task/AddSoilAmendmentProducts/AddSoilAmendmentProducts.stories.tsx
I rebased the branch! ⚠️ 🙏  
- Update `useExpandableItem` to handle empty props.
- Update `CompositionInputs` and `NumberInputWithSelect` to
- handle single unit. (If there are no unit options, `unit` field will not be registered for `react-hook-form`)
- update `justifyContent` to centre the selected unit. (It will still be right-aligned when disabled.) 
- display error message conditionally.
- Add unit options to nutrients. (ppm, mg/kg)
- Add inputs for:
- purpose
- fertiliser type
- moisture/dry matter contents
- additional nutrients
- Improve the condition to disable "add another product" button
- Update [stories](http://localhost:6006/?path=/docs/page-task-addsoilamendmentproducts--docs)
Jira link: https://lite-farm.atlassian.net/browse/LF-4251
**How …
> LF-4251: Add more inputs to AddSoilAmendmentProducts component

- packages/webapp/src/components/Task/AddSoilAmendmentProducts/index.tsx
- packages/webapp/src/components/Task/PureTaskDetails/index.jsx
Fix for https://github.com/LiteFarmOrg/LiteFarm/pull/3299#discussion_r1681600368
Use the soil_amendment_task_products `defaultValues` (currently used for `append()`) for the first product.
> LF-4221 Fix soil_amendment_task_products defaultValues

- packages/webapp/src/components/Form/NumberInput/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/useQuantityApplicationRate.ts
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/index.tsx
- packages/webapp/src/util/task.ts
These are adjustments pertaining to the QuantityApplicationRate PR #3289 and the full form integration PR #3294
Summary of changes:
1. set `is_weight` using the `defaultValues` structure appended to new field array entries
2. pass the same `defaultValues` to useForm to populate the first field array entry (thank you @SayakaOno)
3. fix total_area persistence (non-update on location selection changes) by removing the defaultValue prop on `<Unit />` and restoring the useEffect in the QuantityApplicationRate hook
4. Fix percent location non-persistence (incorrect resetting to 100 on location selection changes) by fixing `<NumberInput />` initialValue logic
5. Pass current percent location location to useEffect calculation that should run on location changes
6. Define form …
> LF-4221 and LF-4249 Adjustments

- packages/webapp/src/util/task.ts
Update formatSoilAmendmentTaskToDBStructure to avoid these type warnings:
```
Type 'string' is not assignable to type 'UnitOption'.ts(2322)
```
```
Type 'FormSoilAmendmentTask' is not assignable to type 'DBSoilAmendmentTask'.
Types of property 'furrow_hole_depth_unit' are incompatible.
Type 'UnitOption | undefined' is not assignable to type 'string | undefined'.
Type 'UnitOption' is not assignable to type 'string'.ts(2322)
```
> LF-4221 Update formatSoilAmendmentTaskToDBStructure to avoid type warning

- packages/webapp/src/util/task.ts
In the task completion flow, the `formatSoilAmendmentTaskToFormStructure function` is now updated to handle cases where it runs against already formatted data. This ensures proper handling when users navigate back from the last page to the previous page.
- Added a type guard to check if the task is already formatted.
- Updated the `formatSoilAmendmentTaskToFormStructure function` to handle both `DBSoilAmendmentTask` and `FormSoilAmendmentTask` types appropriately.
Jira link: N/A
**Checklist:**
> LF-4221 Update `formatSoilAmendmentTaskToFormStructure` to handle `FormSoilAmendmentTask type`

- packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
- packages/webapp/src/util/task.ts
- Allow the user to complete old soil amendment tasks without `method_id`, which is required for task creation.
- Add default value 100 for old soil amendment tasks' `percent_of_location_amended`
Jira link: N/A
**Checklist:**
> LF-4221: Fix soil amendment task completion flow

- packages/webapp/src/components/Task/TaskComplete/index.jsx
- packages/webapp/src/containers/Task/constants.js
- packages/webapp/src/util/task.ts
As Duncan mentioned, the cause was that `soil_amendment_task` is not sent to the saga when the user completes the task without any changes.
- Update `formatSoilAmendmentProductToDBStructure` and `formatSoilAmendmentTaskToDBStructure` to handle `undefined`.
- Update `format` function in `TaskComplete` not to send `soil_amendment_products` to the `saga` when `need_changes` is `false` to keep it consistent with task type details (e.g. `soil_amendment_task`). I also refactored the function for better readability.
- Fix the constant `TASK_TYPE_PRODUCT_MAP`
Jira link: N/A
**Checklist:**
> LF-4221: Fix soil amendment completion flow

- packages/webapp/src/components/Form/InFormButtons/index.tsx
- packages/webapp/src/components/Form/InFormButtons/styles.module.scss
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/Buttons.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/styles.module.scss
- Truncate text in InFormButtons
- Remove padding
- Set display to `inline-block` 
- Update InFormButtons to take `className`
- Add max-width to the buttons in `InFormButtons`. Without max-width, the container width extends to accommodate the buttons' width.
I can't do better than this now 😣😣😣😣😣🤮 If you have any suggestions, please let me know!
Jira link: https://lite-farm.atlassian.net/browse/LF-4341
**Checklist:**
> LF-4341: The text overlaps the borders of the save button on mobile device

- packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/AreaApplicationSummary.tsx
How did this get through bug bash when we had testers using Portuguese? 😅 
The PT translation of field is `campo/parcela`
If someone knows off the top of their head why `shouldUnescape: true` is necessary here and not in the AreaDetails (where the same string is sent to the `label` of `<Input />`, I'd love to know! But for now, just pushing the fix 🙂 
Jira link: https://lite-farm.atlassian.net/browse/LF-4345
**Checklist:**
> LF-4345 PT displaying escaped characters in area application summary text

- packages/api/src/controllers/taskController.js
- packages/api/src/models/taskModel.js
- packages/api/src/models/userFarmModel.js
To summarize our discussion (please also see Jira ticket for details):
- This is not a regression; the bug is about 2 years old
- It would only be triggered in the situation Denis showed us today (completing a task assigned to a worker without an account), ONLY IF
- The managing account has multiple userFarms and the first one returned by the query in `getUserRoleId()` (see PR) happens to be non-admin. This is highly unlikely in a non-QA context, but the fix is straightforward so it has been applied
- The neighbouring function had the same bug so it was fixed at the same time
Jira link: https://lite-farm.atlassian.net/browse/LF-4346
To set up the situation that would cause the issue, I used a user account whose first …
> LF-4346 The user is not able to complete a task any task for a farm worker account without an email

- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/types.ts
- packages/webapp/src/util/task.ts
@SayakaOno I was thinking like this! But I didn't mean for you to have to close the other one...!
... it got closed! 😢 But this method was based on trying to avoid cache due to the complications described in original PR here
- #3338 
and thinking of the most quick and dirty way to get the OTHER value into `formatPurposeIdsToRelationships`, where it needed to be, and from which I had removed it in #3324, causing this bug.
Jira link: https://lite-farm.atlassian.net/browse/LF-4348
This was the faulty API request situation that had to be fixed:
```js
[
{
purpose_id: 4,
other_purpose: 'Other purpose text field', // should not be sent here
},
{
purpose_id: 5,
other_purpose: 'Other purpose text field', // this one is correct
},
] …
```
> LF-4348 Demo branch -- Pass other_purpose_id as a form field

- .github/workflows/crowdin-download.yml
- .github/workflows/crowdin-upload.yml
As just discussed a few minutes ago 🙂
- Add the {{ matrix.locales }} to each PR title to disambiguate them
- Make upload translations and auto-approve uploaded ~GitHub variables~ [dispatch inputs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs) (with fallback to false)  so they can be changed without having to merge new versions of these files
Testing plan:
- variables have been set on the repository level
- this is opened against integration; once merged I will test toggling the environmental variables and running the upload to make sure it behaves as expected
- if successful I will open a new PR to merge to main
Jira link: https://lite-farm.atlassian.net/browse/LF-4349
**Type of …
> LF-4349 Finish crowdin setup to support the addition of new languages

- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
- Set ``OTHER_PURPOSE_ID` in useEffect.
- Remove `value` and `defaultValue` from the input to avoid the controlled/uncontrolled warning.
- Remove out-dated comment.
Jira link: https://lite-farm.atlassian.net/browse/LF-4351
**Checklist:**
> LF-4351: Other purpose text is not saved

- packages/api/src/controllers/cropController.js
- packages/api/src/controllers/cropVarietyController.js
-80 lines of reused code
This uses the utility instead of storing the same logic in multiple controllers.
To test: Make sure local image bucket is running
Jira link: [LF-4387](https://lite-farm.atlassian.net/browse/LF-4387)
**Checklist:**
[LF-4387]: https://lite-farm.atlassian.net/browse/LF-4387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 4387 migrate upload public images functions to new reusable function

- packages/webapp/public/locales/en/translation.json
- packages/webapp/public/locales/es/translation.json
- packages/webapp/public/locales/fr/translation.json
- packages/webapp/public/locales/pt/translation.json
- packages/webapp/src/components/Task/PureIrrigationTask/index.jsx
- packages/webapp/src/components/Task/PureIrrigationTask/styles.module.scss
Users were not able to open the "Water calculator" (_Create a task_ > _Irrigation task_)  if the water measurement method was "Depth".
It is expected that the **Calculate Water Usage** link will be disabled (+ a warning) for wild crops if the measure of water use is set to **Depth**:
Jira link: https://lite-farm.atlassian.net/browse/LF-3951
**Checklist:**
> LF-3951: Show water calculator with wild crops

- packages/webapp/src/components/Finances/AddExpense/styles.module.scss
- packages/webapp/src/components/Task/TaskReadOnly/styles.module.scss
- packages/webapp/src/components/Typography/index.tsx
- packages/webapp/src/components/Typography/typography.module.scss
The **Delete task** button clickable area was taking the full width of its container + the set padding. This PR limits the size of the button (and therefore its clickable area) to just its content width.
Jira link: https://lite-farm.atlassian.net/browse/LF-3416
**Checklist:**
> LF-3416: Fix "Delete task" button clickable area

- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
- packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/usePopulateDetails.ts
[Deploy](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/10565072484) and [Cypress](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/10565068112) failed on `pnpm install` due to the import of `groupBy` from lodash. Why does build not fail here but not locally? I don't know!
But the other `groupBy` was imported from `lodash-es` (es for ES modules, not for Spanish) so I'll try the same here.
Also uninstalled the lodash types and installed lodash-es types, so that the type error might, in the future, be a reminder to use lodash-es 🤷 
Jira link: https://lite-farm.atlassian.net/browse/LF-4164
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …
> LF-4164 Import from and install types for lodash-es instead of lodash

- packages/webapp/src/components/Animals/DetailCards/Other.tsx
- packages/webapp/src/components/ImagePicker/index.tsx
- packages/webapp/src/components/ImagePicker/useImagePickerUpload.tsx
- packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
- packages/webapp/src/containers/ImagePickerWrapper/saga.js
- packages/webapp/src/stories/Animals/Details/AnimalDetails.stories.tsx
- packages/webapp/src/stories/Animals/Details/BatchDetails.stories.tsx
- packages/webapp/src/stories/Animals/Details/Other.stories.tsx
- packages/webapp/src/stories/Animals/Details/mockData.ts
The current `ImagePicker` is designed to save the file itself rather than the image URL. This PR introduces a hook and updates the `ImagePicker` to support saving the image URL instead.
- Create `useImagePickerUpload` hook, with logic extracted from `ImagePickerWrapper`. (Instead of compressing the file when the file size exceeds, `FileSizeExceedModal` is displayed as Navdeep implemented it)
- Update `ImagePicker` to use the function returned from the `useImagePickerUpload` hook.
- Add animals URLs to imageRouteURL for `uploadImageSaga`.
- Integrate `useImagePickerUpload` hook in `AnimalDetails`.
- Update stories
- [animals](http://localhost:6006/?path=/docs/components-addanimalsdetails--docs)
- [batches](http://localhost:6006/?path=/docs/components-addbatchdetails--docs) …
> Image picker update

- packages/api/src/models/animalUseModel.js
- packages/api/tests/animal_use.test.js
- packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
- packages/webapp/src/store/api/types/index.ts
- Fix `default_type_id` type in animal_uses API to number (it was used as map keys and converted to string)
- Make the test more strict (I shouldn't have used `==`!!!)
- Adjust frontend code
Jira link: N/A
**Checklist:**
> Fix default_type_id type in animal uses API

- packages/api/src/models/userModel.js
- packages/webapp/src/components/CreateUserAccount/index.jsx
- packages/webapp/src/components/InviteUser/index.jsx
Previously, when the user tries to create an account with leading spaces in the name field it would cause an error on creation. The issue has been fixed by trimming any leading spaces in the field on blur. 
[Jira link](https://lite-farm.atlassian.net/browse/LF-4272)
**Checklist:**
> LF-4272 trim sign-up name whitespace

- .github/workflows/crowdin-download.yml
- .github/workflows/crowdin-upload.yml
- packages/api/src/controllers/sensorController.js
- packages/shared/locales/en/sensorCSV.json
- packages/shared/locales/es/sensorCSV.json
- packages/shared/locales/fr/sensorCSV.json
- packages/shared/locales/pt/sensorCSV.json
- packages/shared/validation/csv.js
- packages/shared/validation/sensorCSV.js
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
- packages/webapp/src/components/Modals/BulkSensorUploadModal/FileUploader.jsx
This adds the sensors translations to a locales directory to be translated in crowdin and resolves the historical BUG of a mismatch between the template csv and the parsed csv.
Notes:
- the main challenge was around the dynamic import, import syntax is different on the frontend from back due to vite + typescript compiler with no such thing on the backend. Therefore this one function was split up between the frontend and backend or else would have also been placed in the shared utility script.
Jira link: [LF-4402](https://lite-farm.atlassian.net/browse/LF-4402)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
> Lf 4402 translate sensor csv js into new languages

- packages/webapp/src/components/Profile/Account/index.jsx
- packages/webapp/src/hooks/useLanguageOptions.ts
When I migrated to the new `useLanguageOptions` hook in this PR:
- #3409 
I completely missed that [`components/Profile/Account`](https://github.com/LiteFarmOrg/LiteFarm/pull/3409/files#diff-adc43217d2139fe8fc72c8096103eca677b9a891e0d4782e3bad58cdf024a94a) expected to see the options in a map format, not in the React Select Options array format expected by [`components/InviteUser`](https://github.com/LiteFarmOrg/LiteFarm/pull/3409/files#diff-c131ae3ffab7c7735734d33b70fedf20c1b6eeb7adb947f8f86bb3665d0dca87) and [`components/Profile/EditUser`](https://github.com/LiteFarmOrg/LiteFarm/pull/3409/files#diff-0781e5e695603bdc7fdfbddfe0fa6c13483cce035b1924cbd5bc6801483c24ff).
The hook only returns the array shape, so the code that sets the `languagePreferenceOptionRef` no longer …
> LF-4056b Fix for language selector dropdown

- packages/webapp/src/components/Form/ReactSelect/Select.tsx
I didn't realize (sorry I think it was mentioned but I wasn't looking at the right part of the screen!) how badly the side menu jumps when the language dropdown is opened! Even with just German added, the effect is unpleasant enough I would recommend trying to fix this for release.
Luckily what @antsgar suggested as ideal behaviour is already an [available prop](https://react-select.com/props#select-props) on the ReactSelect. I think the only question would be whether we want to add it to language in particular or the base Select across the board. I vote for across the board, not including the Unit or CreatableSelect, but am happy to discuss on Monday.
Jira link: https://lite-farm.atlassian.net/browse/LF-4438
**Checklist:**
> LF-4438 Language dropdown ruins layout of page

- packages/api/src/jobs/locales/i18n.js
- packages/api/src/jobs/locales/i18next-parser.config.js
- packages/api/src/templates/sendEmailTemplate.js
- packages/webapp/src/components/WelcomeScreen/index.jsx
- packages/webapp/src/containers/Consent/index.jsx
- packages/webapp/src/hooks/useLanguageOptions.ts
- packages/webapp/src/locales/i18n.js
- packages/webapp/src/locales/i18next-parser.config.cjs
This PR comments out the WIP languages from the app before the German release. This includes:
1. removing from the language dropdown
2. removing (via the allowlist, called `supportedLngs`) from the i18n configuration
3. commenting out a few other places that used places that used the local storage language directly (e.g. the welcome message and the consent forms)
Note: 2 & 3 are necessary because local storage languagge has always been set from from `navigator.language` -- meaning that the browser being set to one of the new languages was enough to show translated content, regardless of whether it was selectable in the language options dropdown.
Jira link: https://lite-farm.atlassian.net/browse/LF-4437
**Checklist:**
> LF-4437 Remove incomplete languages from dropdown before German release

- packages/api/src/jobs/locales/i18n.js
- packages/api/src/jobs/locales/i18next-parser.config.js
- packages/api/src/templates/sendEmailTemplate.js
- packages/webapp/src/components/WelcomeScreen/index.jsx
- packages/webapp/src/containers/Consent/index.jsx
- packages/webapp/src/hooks/useLanguageOptions.ts
- packages/webapp/src/locales/i18n.js
- packages/webapp/src/locales/i18next-parser.config.cjs
Just reverts the commenting out of the Indic languages so sanity testing can continue on beta in those languages.
I have kept the allow list (`supportedLngs` in the i18n config) to make it easier to partially add more languages in the future.
Jira link: non
**Checklist:**
> Restore Indic languages to patch branch

- .github/workflows/automated_tests.yml
As dicussed this morning, just adjusting our API tests GitHub actions workflow to trigger on pushes to branches that match the pattern `patch/**` [Syntax from here](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore).
Still not sure whether it needs to go on integration, `patch/translation`, or both in order to trigger, but probably both? Starting with integration as it also has the node bump.
**Checklist:**
> Run API tests on patch branches

- packages/webapp/src/components/Form/DaysOfWeekSelect/styles.module.scss
Increases the gap between days of week buttons to 24px. 
A couple pics snapped on chrome dev setting of Iphone 14 Pro max
Jira link: [LF-4426](https://lite-farm.atlassian.net/browse/LF-4426)
**Checklist:**
[LF-4426]: https://lite-farm.atlassian.net/browse/LF-4426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LF-4426 update gap

- packages/api/src/controllers/sensorController.js
- packages/webapp/src/components/Map/Modals/BulkSensorUploadModal/useValidateBulkSensorData.js
Sorry 🙏  I must have missed testing the fallback to English -- all the vite examples assign dynamic imports to variables so I assumed they were handled gracefully.
I noticed this while testing Joyces sensors error text PR.
I did not translate the console errors as that is how we typically do it in code.
Jira link:
**Checklist:**
> Lf 4402 fix fallback

- packages/webapp/src/assets/colors.scss
- packages/webapp/src/components/Button/FloatingActionButton/styles.module.scss
- packages/webapp/src/components/Menu/FloatingButtonMenu/index.jsx
- packages/webapp/src/components/Menu/FloatingButtonMenu/styles.module.scss
- Fix the position of the floating menu by adjusting the `anchorRef`.
- Implement the active state of the button as designed.
- replace hex with `var`.
- switch CSS for hover style and active style so that hover style won't override the active state CSS. 
- sorry for the formatting!
Jira link: https://lite-farm.atlassian.net/browse/LF-4405
**Checklist:**
> LF-4405: floating menu button looks different from what is designed

- packages/webapp/src/containers/Animals/AddAnimals/utils.ts
- packages/webapp/src/store/api/apiSlice.ts
Ooooh animals again 😁 
This PR makes sure that adding a new animal/batch also re-fetches custom types and breeds (in case one was added), and also adds optional chaining to cover the initial `null` value and resultant crash until the re-fetch is completed.
Jira link: https://lite-farm.atlassian.net/browse/LF-4413
Checked the values around the crashing `iconKey: typeString.toUpperCase(),` Tag invalidation does produce the right `typeString`, but not before that code is called once with a `null` value and crashes.
**Checklist:**
> LF-4413 The white screen is displayed once the user tries to complete the creation of the new animal type

- packages/webapp/src/components/Form/SexDetails/SexDetailsCountInput/index.tsx
Previously, when a user tries to specify sex when adding animals, the UI field will accept a decimal input. This was caused by the hook `useNumberInput` which creates the input props and has a default `allowDecimal` value of true. By passing a `allowDecimal` value of false it sets the input `pattern` regex to not permit decimal values. 
Jira link: [LF-4409](https://lite-farm.atlassian.net/browse/LF-4409)
**Checklist:**
[LF-4409]: https://lite-farm.atlassian.net/browse/LF-4409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LF-4409 disallow decimals in animals sex number input

- packages/webapp/src/components/Navigation/styles.module.scss
This PR makes the `mainColumn` fully responsive to the browser size, preventing it from pushing the side menu.
Here’s the problem:
https://github.com/user-attachments/assets/99af173a-b018-4cec-82a2-fb88689de4a1
I learned about the solution while struggling with truncating text properly for the animal header ([LF-4381](https://lite-farm.atlassian.net/browse/LF-4381)). (It took me a few days to realize that `mainColumn` was the element that needed this fix 😭)
This article was very helpful for understanding the purpose of `min-width: 0`!
https://css-tricks.com/flexbox-truncated-text/#aa-the-solution-is-min-width-0-on-the-flex-child
Jira link: N/A
**Checklist:**
[LF-4381]: …
> Fix layout

- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
@formatjs released a new version of the datetimeformat package including the fix discussed in #3462. Bumping the package version so we get the fix in for the release.
Jira link:
Forced an undefined date on the WeatherBoard container and checked that an "Invalid Date" string is displayed instead of the app crashing.
**Checklist:**
> bump formatjs version

- packages/api/db/migration/20241016204145_create_animal_movement_task_tables.js
Create migration for animal movement task.
- Create `animal_movement_task` table
- Create `animal_movement_task_purpose_relationship` table
- Create `animal_movement_purpose` table
- Create `animal_movement_task_animal_relationship` table
- Create `animal_movement_task_animal_batch_relationship` table
- Add `ANIMAL_MOVEMENT` type to `task_type` table
- Add `location_id` column to `animal` and `animal_batch` tables
Jira link: https://lite-farm.atlassian.net/browse/LF-4470
**Checklist:**
> LF-4470: Write database migration for animal movement task

- packages/webapp/src/components/Animals/Inventory/index.tsx
- packages/webapp/src/containers/Animals/Inventory/index.tsx
When user is a worker, they should not be able to add animals, so hiding this button when user role is worker.
Jira link: https://lite-farm.atlassian.net/browse/LF-4411
**Checklist:**
> LF-4411: Hide add animals button when user is worker

- packages/api/db/migration/20241118191954_add_constraint_to_task_abandonment_reason.js
- packages/api/src/middleware/validation/checkTask.js
- packages/api/src/models/taskModel.js
- packages/api/tests/task.test.js
- packages/webapp/public/locales/en/translation.json
This PR adds support for the new abandonment reason when all animals are removed from a task. The key will be added as part of delete/remove animals/batches APIs.
- Add a migration to add constraint to validate the `abandonment_reason` in the `task` table. (This wasn't necessary, but I added it to avoid adding a wrong key. Wrong keys don't exist in the prod or beta DB, so it should be safe to add this constraint.)
- Add a translation key for the new reason
- Add the new reason to `TaskModel`
- Add the `checkAbandonTask` middleware not to allow the new key to be added from clients
- Add a test 
This task was simpler than expected since the keys are hard-coded in the webapp, and the read-only page and task creation page don't share the same code.
- Creation …
> LF-4531: Set up new task abandonment reason for tasks with removed animals

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Finances/PureFinanceTypeSelection/CantFindCustomType/index.tsx
- packages/webapp/src/components/Finances/PureFinanceTypeSelection/CantFindCustomType/styles.module.scss
- packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
- packages/webapp/src/components/Task/PureTaskTypeSelection/styles.module.scss
- packages/webapp/src/stories/CantFindCustomType/CantFindCustomType.stories.tsx
This adds the "CantFindCustomTask" block we use in Expense + Revenue Type Selection into Tasks. It was a lower priority nice-to-have, but with the discussion around adding animals to custom tasks, it might be especially nice. There is no code complexity to the change so I have opened it.
**Done in this PR:**
- Simple conversion to TS of `<CantFindCustomTask />` because even I was confused by the meaning of the props I had set up on this component ("miscellaneousConfig"??)
- Simple [Storybook story](http://localhost:6006/?path=/docs/components-cantfindcustomtype--docs) since previously it had only been integrated within the PureFinanceTypeSelection story. This is also to make the props a bit clearer
- breakpoint adjust to fix this small layout bug which I think had just …
> LF-4475 [Nice to have] Update layout for manage custom tasks

- packages/api/src/controllers/taskController.js
- packages/webapp/src/containers/Task/saga.js
- packages/webapp/src/containers/Task/sagaUtils.js
- packages/webapp/src/containers/slice/taskSlice/animalMovementTaskSlice.js
- packages/webapp/src/containers/taskSlice.js
- packages/webapp/src/store/reducer.js
- packages/webapp/src/util/task.ts
- Add `animalMovementTaskSlice`.
- Update `taskSlice` to include `animals` and `animal_batches` in tasks.
- Update `taskSlice`, `onLoadingTaskStartSaga` and `getTasksSuccessSaga` for `GET` requests.
- The translation key is `MOVEMENT_TASK`, but the subtask name in the `GET` response body is `animal_movement_task`, whereas they match for other task types. To handle this, I created a `getSubtaskName` function. I should've been more careful with naming...
- Update `createTaskSaga` for `POST` requests.
- I created  a `sagaUtils` file and added helper functions there.
Additionally, this is not directly related to the ticket, but I updated `flattenInternalIdentifier` to remove the `animal_union_batch` property from animals and batches, which I forgot to address when working on …
> LF-4479: [GET&POST] Update Task saga to account for new animal movement task

- packages/webapp/src/components/Form/SexDetails/index.tsx
Add missing dependency to `SexDetails` `useMemo`.
(This addresses the [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3534#pullrequestreview-2465801603) in https://github.com/LiteFarmOrg/LiteFarm/pull/3534)
Jira link: https://lite-farm.atlassian.net/browse/LF-4549
**Checklist:**
> LF-4549: Sex-Detail Field Not Editable on Edit Animal Details Page

- packages/webapp/src/components/Animals/AnimalSingleViewHeader/index.tsx
- packages/webapp/src/components/Table/Cell/CellTypes/HoverPillOverflow.tsx
- packages/webapp/src/components/Table/Cell/CellTypes/Plain.tsx
- packages/webapp/src/components/Table/Cell/styles.module.scss
- packages/webapp/src/containers/Animals/Inventory/index.tsx
- packages/webapp/src/containers/Animals/Inventory/styles.module.scss
- packages/webapp/src/containers/Animals/Inventory/useAnimalInventory.tsx
- packages/webapp/src/containers/Animals/Inventory/useFilteredInventory.ts
- packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
- packages/webapp/src/containers/Filter/Animals/index.tsx
- packages/webapp/src/containers/Filter/types.ts
- packages/webapp/src/store/api/types/index.ts
- packages/webapp/src/stories/Animals/AnimalSingleViewHeader.stories.tsx
- packages/webapp/src/stories/Animals/mockData.ts
- packages/webapp/src/stories/Table/TableCells.stories.jsx
- packages/webapp/src/types/index.ts
Inventory table
- Move the Location type to a common file
- Add `location_id` to Animal and AnimalBatch types and adjust mockData
- Update `useAnimalInventory` to include location
- Add Location column to animal inventory table
- Update `useFilteredInventory` to handle locations filter
- Add `location` string to animal inventory searchable string
- Update `Plain` cell component to take `content`(ReactNode) for greater flexibility
- Update "none" text style in the group column to normal font  (it was previously in italic)
- Fix broken [story](http://localhost:6006/?path=/story/components-tables-cells--fake-table-with-cells)
Header
- Modify `AnimalSingleViewHeader`'s props (separated `locationText` from `animalOrBatch`) and adjust …
> LF-4481:  Add Location to animal inventory UI

- packages/api/src/controllers/taskController.js
- packages/api/tests/task.test.js
- Update `getTasksForFarm` to retrieve custom tasks for the farm.
- Add tests for GET and POST task(s) requests.
Jira link: https://lite-farm.atlassian.net/browse/LF-4555
**Checklist:**
> LF-4555: Update getTasksForFarm to return all custom tasks in GET API response

- packages/api/src/middleware/acl/hasFarmAccess.js
- packages/api/src/routes/taskRoute.js
Custom tasks without locations could not previously be completed because they would fail on the hasFarmAccess middleware check, causing 403 and logout. This PR adds a function to hasFarmAccess to pull the farm_id from the task_type, and replaces the previous check, which used location_tasks, with this new check on the custom task complete route.
Jira link: https://lite-farm.atlassian.net/browse/LF-4553
You can observe the middleware behaviour by removing the `location_tasks` entry for a custom task (you need to be on the readonly or complete view because will lose it from the task list -- unless you're on Sayaka's modified GET branch!), and completing it.
**Checklist:**
> LF-4553 Allow completing custom tasks with no associated locations

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/containers/Task/taskCardContentSelector.js
Minor frontend view changes needed to work with tasks with no locations:
1. Task card selector logic should specify "No location" instead of the fallback "Multiple locations"
2. Readonly view should only show the map if pins or locations are associated with the task
3. ~[TBD, code not yet pushed] Filter by location logic should exclude tasks that have no location instead of matching them to every location~ - Will create a fresh ticket to address the nice-to-have filter updates; not included here
Jira link: https://lite-farm.atlassian.net/browse/LF-4554
You can view tasks without locations on the branch without GET, or by adding this line to the taskEntitiesSelector to remove locations from custom tasks once they have already …
> LF-4554 Adjust frontend task view to handle tasks with no locations

- packages/webapp/src/tests/sort.test.js
- packages/webapp/src/util/sort.ts
- Update `descendingComparator` to handle `undefined` and `null` as expected.
- Add tests. (`pnpm run test sort`)
Jira link: https://lite-farm.atlassian.net/browse/LF-4538
**Checklist:**
> LF-4538: Breed sorting does not work in inventory table

- packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
- packages/webapp/src/components/Task/TaskAnimalInventory/index.jsx
- packages/webapp/src/containers/Animals/Inventory/index.tsx
Adds capability to create a task from the animal inventory action menu. Should only show animal related tasks (movement / custom tasks).
Jira link:
https://lite-farm.atlassian.net/browse/LF-4482
**Checklist:**
> LF-4482 support creating task from animal inventory (nice to have)

- packages/api/src/middleware/acl/hasFarmAccess.js
- packages/api/src/routes/taskRoute.js
- packages/api/tests/mock.factories.js
- packages/api/tests/task.test.js
In testing the other custom task PRs open now in combination, I realized that many PATCH routes, e.g
```js
router.patch(
'/assign/:task_id',
hasFarmAccess({ params: 'task_id' }),
checkScope(['edit:task']),
validateAssigneeId,
checkTaskStatusForAssignment,
taskController.assignTask,
);
```
Do not distinguish between custom tasks and regular tasks at the level of the route (complete is the exception). The easier middleware solution which I wish I had thought of last week, would be to just update `hasFarmAccess({ params: 'task_id' }),` to query for `farm_id` in addition to the other join queries it does. This was inspired from @SayakaOno's handling of the GET 🙂 
This approach is much simpler and prevents the 403 on all the task-associated routes without having to use …
> LF-4553b Allow patching date and assignee on custom tasks without location

- packages/webapp/src/containers/Filter/Tasks/index.jsx
- packages/webapp/src/containers/Task/index.jsx
A quick fix to restore movement tasks to the task list 🙂 
Since `getSupportedTaskTypesSet()` expects two arguments now:
- https://github.com/LiteFarmOrg/LiteFarm/pull/3574/
The previous calls that were meant to return all tasks types were written `getSupportedTaskTypes(true)` so they need updating! No sweat! 😅 
Jira link:
**Checklist:**
> LF-4558 Give second argument to getSupportedTaskTypes

- packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
- packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
In testing the new custom task type flow end-to-end, I noticed the custom task types were not offering the ability to edit the associated animals, and realized that was because StepOne (before complete) is not shown at all for custom tasks, which lack a Details component (previously the only part of the task that could be editable, until Animals were added).
This adds that step so animals can be added or removed on complete.
Jira link: https://lite-farm.atlassian.net/browse/LF-4567
I used Duncan's frontend branch, the middleware adjust, and the other pieces now in integration to test end to end flow of tasks with animals with and without locations.
**Checklist:**
> LF-4567 Allow custom tasks with animals to be editable on complete

- packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
The `generateInventoryId` function was crashing before the useEffect redirect ran.
Incidentally if you remove the useEffect and redirect in the function body (or the hook), you can get both crash AND redirect!  (I.e. type error crash in console but won't notice because the redirect masks it immediately). I thought that was kind of fun 😁  It's not a good solution though.
Jira link: https://lite-farm.atlassian.net/browse/LF-4595
**Checklist:**
> LF-4595 The app crashes when trying to access deleted animal’s details page

- packages/webapp/src/containers/Task/TaskLocations/index.jsx
There was a condition originally on the`TaskAllLocations` component (which was previously used by custom tasks too) that read
```js
if (
(taskTypesBypassCrops.includes(persistedFormData.task_type_id) &&
!readOnlyPinCoordinates?.length) ||
!hasManagementPlans
) {
```
When `TaskCustomLocations` was split up from `TaskAllLocations`, this condition was refactored to
```js
if (
!readOnlyPinCoordinates?.length) ||
!hasManagementPlans
) {
```
However the check for read only pin coordinates was only meant to apply if the task type matched one that should bypass the crops screen. After the refactor, it was applying for custom tasks too and was causing the skipping of the crop selection screen and the linking of the task to the management plan.
Jira link: …
> LF-4575 fix custom tasks not attached to crop plans

- packages/api/src/controllers/taskController.js
- packages/api/src/models/animalBatchModel.js
- packages/api/src/models/animalModel.js
- packages/api/tests/animalTask.test.js
- Conditionally update animals' location when a movement task is completed.
- Retrieve completed movement tasks newer than the task about to be completed, and if there are, keep the existing location.
- Add tests (`npm run test animalTask`)
Jira link: https://lite-farm.atlassian.net/browse/LF-4579
**Checklist:**
> LF-4579: Recording a movement task in the past messes up animals location

- packages/webapp/src/components/Animals/DetailCards/Other.tsx
Was never a blocker but it came up twice in bug bash, and was a trivial fix on the way to tackling the animal inventory image ticket. It is also part of the spec I just forgot to implement:
- Image upload component should have been hidden entirely in readonly animal details view if no image has been added
Jira link: https://lite-farm.atlassian.net/browse/LF-4606
**Checklist:**
> LF-4606  “Click to upload link” should not display or should “look” disabled if not in editing mode [Duplicate - See Usability section]

- packages/webapp/src/components/ImagePicker/index.tsx
- packages/webapp/src/components/ImagePicker/styles.module.scss
- packages/webapp/src/components/Profile/Farm/index.jsx
This bug seems to have introduced when `FarmImagePicker` was replaced with `ImagePicker` in https://github.com/LiteFarmOrg/LiteFarm/pull/3390. Since farm images are private, we need to generate a URL using `useMediaWithAuthentication` as Navdeep mentioned [here](https://github.com/LiteFarmOrg/LiteFarm/pull/3192#discussion_r1586391467).
I'm not sure how to test this locally, so we can merge if we're comfortable with this change.
Jira link: https://lite-farm.atlassian.net/browse/LF-4570
**Checklist:**
> LF-4570: Farm image preview is broken on beta

- packages/webapp/src/components/Filter/FilterDateRange/index.jsx
**Description** 
The date range filter component wasn't calling the `onChange` function when the switch was toggled on/off. I'm guessing this was either always broken or got broken when I refactored a bunch of the filters code for the Finances release.
Jira link:
https://lite-farm.atlassian.net/browse/LF-4580
**Checklist:**
> LF-4575 fix date range filter

- packages/webapp/src/components/Tooltip/index.tsx
Reduces the delay to which the popup self removes. It was 900s, I put it to 5s, default is 1.5s.
I have not tested this on all tooltips, presumably there is some with long text -- but the worst case scenario I can see is you click again vs interfering with other elements.
Jira link: [LF-4609](https://lite-farm.atlassian.net/browse/LF-4609)
**Checklist:**
[LF-4609]: https://lite-farm.atlassian.net/browse/LF-4609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LF-4609 Reduce touch delay for tooltip going away

- packages/webapp/src/components/Table/Cell/styles.module.scss
- packages/webapp/src/components/Table/styles.module.scss
Checkbox hitbox was improved in:
- https://github.com/LiteFarmOrg/LiteFarm/pull/3602
by making sure that the onClick handler fills the whole checkbox cell. However, the checkbox cell still needed to be increased to 44px (increased by 12px) in order to meet Loïc's specifications.
I moved the icon left the same amount so the view remains unchanged.
Jira link: https://lite-farm.atlassian.net/browse/LF-4612
**Checklist:**
> LF-4612b Accidental click outside checkbox goes to details view and loses check progress

- packages/webapp/src/components/Table/Cell/styles.module.scss
- packages/webapp/src/components/Table/TableV2.jsx
- packages/webapp/src/components/Table/styles.module.scss
Thank you @SayakaOno for remembering the checkbox-less view 🙏 🙏 🙏 
Jira link: https://lite-farm.atlassian.net/browse/LF-4612
**Checklist:**
> LF-4612c Fix margin on icons without checkbox

- packages/webapp/src/containers/Consent/locales/es/Worker.Consent.md
Sorry, I merged the previous PR before noticing that this section header had lost its formatting 🙏
**Checklist:**
> Consent v7 - Restore bolded section header to es-worker-consent

- .github/workflows/lint_translation_files.yml
- .github/workflows/webapp_unit_tests.yml
- packages/webapp/pnpm-lock.yaml
This PR is to fix the address the `Ignoring not compatible lockfile` error our webapp automated tests are now showing.
Errors here:
- https://github.com/LiteFarmOrg/LiteFarm/actions/runs/12455267140
- https://github.com/LiteFarmOrg/LiteFarm/actions/runs/12455267143
I thought the lockfile just had to be regenerated, but there is apparently also a pnpm version incompatibility that has to be resolved. Failing tests were fixed on 6.26.1 but the dockerfiles, passing tests, etc. are on version: latest.
I have
- put failing tests on `latest`
- regenerated the pnpm lockfile using pnpm@latest (v9.15.2)
But I'm surprised we don't want to fix our pnpm version so I am drafting the PR until we have decided that.
Update: we do want to fix the pnpm version but it does not have to be …
> Fix failing frontend GitHub workflows after 3.7.3 patch and backport

- packages/api/src/server.js
We added server-side CORS in this PR:
- https://github.com/LiteFarmOrg/LiteFarm/pull/3551
But limiting development environment domain to localhost was overly restrictive; it produces CORS errors when connecting to the server from e.g. a mobile device connecting over the local network. We do have an `.env` variable in webapp where we can point to the local network name, but no such variable in api.
Restricting domain is not necessary for dev environment so I have just lifted the restriction.
Ran into the issue testing something on mobile; tested the fix the same way.
**Checklist:**
> Remove server.js CORS for development environment

- packages/api/db/migration/20250123153038_refactor_farm_addon.js
- packages/api/tests/testEnvironment.js
Migrates existing "integration" table to new construct of "addon". Did not drop or edit any sensors tables at all.
Adds new permissions.
This adds a few renames:
- renamed `farm_external_integration` -> `farm_addon`
- renamed `integrating_partner` -> `addon_partner`
- our new standard seems to be not referencing the table name in the column names - updated those in `addon_partner`
- `org_id` kept as `org_uuid` since the column is of that type and is more clear - maybe we will generalise in the future as we get more integrations.
Jira link: [LF-4689](https://lite-farm.atlassian.net/browse/LF-4689)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any …
> Lf 4689 database migration

- packages/api/src/controllers/sensorController.js
- packages/api/src/util/ensemble.js
(As mentioned in tech daily Jan 23rd) These readability refactors on the Ensemble portion of the controller code were done as part of the ticket scope of the original controller ticket. The changes are limited to using a constant where there was a hardcoded string, refactoring out a few `.reduce()` functions for readability, and clarifying a few return statements that were set up misleadingly. A lot of the Ensemble code (probably whole add flow, maybe webhook function as well) is going to be removed in our "remove old sensors code" task, but I wanted to merge the refactors because:
- if we are ever going to refer to that old code when expanding sensors, I think it should help us understand what was done in the original flow
- I have been using the changes (actually it …
> LF-4625 Readability Refactors on Ensemble controller code

- packages/webapp/src/components/TileDashboard/MoreComponent/styles.module.scss
If you have lots of animal type and click on overflow button(more), the box showing remaining animal types goes under the table header. Which is fixed in this PR.
Jira link: https://lite-farm.atlassian.net/browse/LF-4601
- [] New feature (non-breaking change which adds functionality)
Add lots of animal type if not there. Click on the more button. The popup now is above the table header.
**Checklist:**
> LF-4601 Fixed: KPI needs to be higher than table header

- packages/webapp/public/locales/en/common.json
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/App.jsx
- packages/webapp/src/components/Form/ContextForm/HeaderWithBackAndClose.tsx
- packages/webapp/src/components/Form/ContextForm/Loading.tsx
- packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
- packages/webapp/src/components/Form/ContextForm/index.tsx
- packages/webapp/src/components/Form/ContextForm/styles.module.scss
- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/PostSensor.tsx
- packages/webapp/src/containers/LocationDetails/PointDetails/SensorDetail/v2/styles.module.scss
- packages/webapp/src/routes/index.jsx
- packages/webapp/src/stories/ContextForm/ContextForm.stories.tsx
- packages/webapp/src/util/siteMapConstants.ts
Rough implementation of the sensor addition flow. The goal is to set up the basic structure and functionality to prevent a large PR later.
- Update `ContextForm`:
- Add a `SIMPLE_HEADER` variant ([story](http://localhost:6006/?path=/story/components-contextform--simple-text-header)), which might not be used.
- Display a loading view when needed ([story](http://localhost:6006/?path=/story/components-contextform--stepper-form-with-custom-action-on-continue)). The loading icon could be implemented properly.
- (TODO: Some adjustments including hiding "Previous" button and the header styling)
- Add `PostSensor` container (`/create_location/sensor`)
- I don't think the URL perfectly matches the content at this point, but I followed the convention for future feature expansion. …
> LF-4631 (1): Implement sensor addition UI flow

- packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
- packages/webapp/src/components/Animals/DetailCards/General.tsx
- packages/webapp/src/components/Form/hookformValidationUtils.js
User was able to create an animal type or breed with more that 255 characters. This PR resolves this and throws an error to show the limitation to the user while creating animal.
Jira link: https://lite-farm.atlassian.net/browse/LF-4619
Try to create animal type or breed with more that 255 characters, it will throw an error and restricts user from moving forward with creation of animal.
**Checklist:**
> LF-4619 Added validation to throw error when animal type or breed name exceeds 255 characters

- packages/webapp/src/components/Form/Checkbox/checkbox.module.scss
Checkbox get selected even if we click outside of the text. This PR resolves this bug. Now if we click outside the text, the checkbox will not be selected.
Jira link: https://lite-farm.atlassian.net/browse/LF-4418
- Navigate to the Animals page.
- Click on the “+” button > Add animals.
- Click outside the field “Create individual animal profiles”
Now, checkbox will not get selected.
**Checklist:**
> LF-4418 Fixed: checkbox label taking more space than the text

- packages/webapp/src/components/Animals/AddAnimalsDetails/index.tsx
- packages/webapp/src/components/Animals/AddAnimalsFormCard/AddAnimalsFormCard.tsx
- packages/webapp/src/components/Animals/AddAnimalsFormCard/AnimalSelect.tsx
- packages/webapp/src/components/Animals/DetailCards/General.tsx
- packages/webapp/src/components/Animals/DetailCards/Origin.tsx
- packages/webapp/src/components/Animals/DetailCards/Other.tsx
- packages/webapp/src/components/Animals/DetailCards/Unique.tsx
- packages/webapp/src/components/Animals/Inventory/index.tsx
- packages/webapp/src/components/Animals/RemoveAnimalsModal/index.tsx
- packages/webapp/src/components/Form/ContextForm/WithPageTitle.tsx
- packages/webapp/src/components/Form/ReactSelect/CreatableSelect.tsx
- packages/webapp/src/components/Form/hookformValidationUtils.ts
- packages/webapp/src/components/ImagePicker/useImagePickerUpload.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/ProductDetails.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/ProductCard/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/index.tsx
- packages/webapp/src/components/Task/AddSoilAmendmentProducts/QuantityApplicationRate/useQuantityApplicationRate.ts
- packages/webapp/src/components/Task/MovementTask/index.tsx
- packages/webapp/src/components/Task/SoilAmendmentTask/index.tsx
- packages/webapp/src/containers/Animals/AddAnimals/AddAnimalDetails/index.tsx
- packages/webapp/src/containers/Animals/Inventory/index.tsx
- packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
- packages/webapp/src/stories/AddAnimalsSummaryCard/AddAnimalsSummaryCard.stories.tsx
This PR contains two type fixes discussed in this PR:
- #3680 
1. One is the type error on a validator function which was suppressed with `@ts-ignore` in the PR above, and is explained [here](https://github.com/LiteFarmOrg/LiteFarm/pull/3680#discussion_r1943747052). It was a legitimate issue (although [not well documented](https://www.react-hook-form.com/api/useform/register/#options) and only inferrable from the example code) in that React Hook Form's `validate` function wants its second argument, if supplied, to be a `formState`, which caused this deploy error from earlier:
```
Types of parameters 'length' and 'formValues' are incompatible.
Type 'FieldValues' is not assignable to type 'number'.
53           validate: hookFormSelectOptionMaxLength,
~~~~~~~~
```
This is …
> TypeScript cleanup -- hookFormValidationUtils.ts and ts-expect-error

- packages/api/package.json
This is the follow-up to the PR and the solution was tested live (successfully) during tech daily Feb 6
- #3682 
When merging that PR we saw that the `/dist` folder was successfully built within the container image. The issue was that `tsc` copies the directory structure of its source, and in the Docker image the path has been set up as `/app/src/server.js` instead of `api/src/server.js`. This PR just changes the `start:prod` script path to match this.
As a side effect you cannot use `npm run start:prod` locally after this change but as it was meant to be used in hosted container I don't see this as an issue.
@Duncan-Brain I did not delete the `npm run start` script here because it is used by the Cypress tests.
Jira link: https://lite-farm.atlassian.net/browse/LF-4722 …
> LF-4722b Fix start:prod path to match container structure

- packages/api/src/controllers/farmAddonController.js
- packages/api/src/routes/farmAddonRoute.js
Adds a get endpoint for addons. Returns 200 if an addon exists with addon_partner_id or if not specified. Return 404 if there is no addon present on farm.
Jira link: [LF-4694](https://lite-farm.atlassian.net/browse/LF-4694)
**Checklist:**
[LF-4694]: https://lite-farm.atlassian.net/browse/LF-4694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 4694 create get endpoint to check if an ensemble addon exists b

- packages/api/package.json
Sorry I missed that this was removed!
The `API: Attach to Node` Run and Debug launch configuration still works fine in both JS and TS files, it just needs its inspect port.
Jira link: https://lite-farm.atlassian.net/browse/LF-4725
(It's not really a bug or a feature. We just lost the ability to attach debugger to backend and this restores it).
I wasn't sure if launch config had to be altered to make sure the source file was found, but I had no issues with a debugger statement in both `server.ts` (a file that gets 'compiled') and a regular controller (JS) as soon as the inspect was restored.
**Checklist:**
> LF-4725 Restore ability to --inspect (debug) the API

- packages/api/db/migration/20250203144322_add_base_properties_to_farm_addon.js
- packages/api/src/controllers/farmAddonController.js
- packages/api/src/middleware/validation/checkFarmAddon.js
- packages/api/src/models/farmAddonModel.js
- packages/api/src/util/ensemble.js
This PR adds base properties to the `farm_addon` object. 
Also necessitates the addition of an `id` primary key to distinguish between deleted records.
Notes:
- bumped up in my queue because it will really affect how DELETE endpoint works
- Partial unique index constraint (PUI) used to guarantee maximum 1 single non deleted entry for a composite key. Use of this constraint is an indication to rethink the architecture. PUI is specifically difficult when working with multiple records at a time - like `soil_amendment_task_products`.  Looking back soil amendment task products should not have base properties - it should use hard delete -- so I forget why I added base properties there maybe I was still learning. Here it makes sense to have base properties on `farm_addon`, so the …
> Lf 4703 nice to have add base properties to farm addon

- packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
- packages/webapp/src/components/Menu/MeatballsMenu/index.tsx
- packages/webapp/src/containers/Animals/SingleAnimalView/index.tsx
Fix Single animal view
- Header
- Update `WithStepperProgressBar` to conditionally hide/show a header based on `headerComponent`.
- Pass `headerComponent: null` to `ContextForm` from `SingleAnimalView` 
- Meatballs menu
- Send the missing `options` prop to `FloatingMenu`
- Fix `forwardRef` typing for `Menu` component props
Jira link: https://lite-farm.atlassian.net/browse/LF-4732
**Checklist:**
> LF-4732: White screen appears when clicking three dots button on animal profile page

- packages/webapp/src/components/Form/hookformValidationUtils.ts
Fixing a very small bug I stumbled across.
We recently added max-length validation to the animal breed + type that inadvertently also made them required; this just repairs that.
Jira link: https://lite-farm.atlassian.net/browse/LF-4734
**Checklist:**
> LF-4734 It is not possible to continue animal creation flow without specifying animal breed

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/OverviewStats/index.tsx
- packages/webapp/src/components/OverviewStats/styles.module.scss
- packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
- packages/webapp/src/stories/OverviewStats/OverviewStats.stories.tsx
- packages/webapp/src/util/index.js
Some small adjustments to the ESci Sensor List as discussed today with Loïc:
- All strings to be in sentence case (only first word capitalized)
- KPI labels should match sensor types; remove 'Canopy temperature' string since it will no longer be used
- Exclude missing types from OverviewStats tiles instead of showing a zero value
- "bento-style" flexbox behaviour if the OverviewStats KPIs span two rows
@SayakaOno I did not keep the ability to show zero counts as a prop on OverviewStats and maybe I should have 🤔 Please let me know if I've ruined your vision for OverviewStats 😅🙏 
**Checklist:**
> ESci Sensor List KPI and string adjustments

- packages/webapp/src/components/Crop/CompleteManamgenentPlan/PureCompleteManagementPlan.jsx
Fix completion notes vs abandonment notes display issue
Jira link:
https://lite-farm.atlassian.net/browse/LF-4743
**Checklist:**
> LF-4743 "Completion notes" instead of "Abandonment notes" is displayed once the user tries to abandon the crop plan.

- packages/api/src/controllers/farmAddonController.js
- packages/webapp/public/locales/en/message.json
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/containers/AddSensors/Partners.tsx
- packages/webapp/src/containers/Profile/Farm/Addons/index.tsx
- packages/webapp/src/store/api/apiSlice.ts
- packages/webapp/src/store/api/types/index.ts
This PR connects the delete endpoint from @Duncan-Brain's PR #3692 to the frontend of app, wrapping up the disconnect user story and the whole FarmAddon arc (🎉!)
There weren't any snackbars on this flow in Figma so I didn't include them, but have been wondering about that. I think it would be okay to exclude because there is no 'success' snackbar for adding an addon (you are routed to the sensor list instead) and with the disconnect confirmation modal it would be a bit of a 'noisy' screen with two popups in a row. But it also kind of depends on how much it is supposed to feel like deleting another entity (e.g. task, animal, transaction) which always snackbar 🤔  I think I'm okay with the snackbar-less UX here, but what do you guys think? Should we check with Loïc?
Jira …
> LF-4701 Call DELETE endpoint when clicking disconnect from Farm Addon

- packages/webapp/src/components/Form/Button/button.module.scss
- packages/webapp/src/containers/AddSensors/Partners.tsx
This is the PR to address visual issues described in #3696 that weren't strictly related to the delete functionality. Addressed:
1. The focus > hover button layout shift at narrow desktop widths [shown here](https://github.com/LiteFarmOrg/LiteFarm/pull/3696#pullrequestreview-2645957264) (thank you @SayakaOno for spotting this)
2. This flash of content / blip on `<Partners />` which I'll demostrate here with 4x cpu throttling for clarity -- both the text input and the form buttons are showing momentarily if the connection is active and the RTK query cache is missing (e.g. on first login).  Within the PR code, `useEffect()` address the buttons while the conditional rendering is for the text input flash. Both make use of `isLoading` which it was my mistake to not include …
> Farm Addon & Partner visual adjustments

- packages/webapp/src/containers/Map/styles.module.scss
Footer was hiding map buttons -- I must have missed it.
**Checklist:**
> Add padding to bottom of map to account for map menu

- .github/workflows/automated_tests.yml
- .github/workflows/beta-export-deploy.yml
- .github/workflows/deploy.yml
- .github/workflows/lint_translation_files.yml
- .github/workflows/rollout.yml
This was the recommended course of action emailed to us and notified via today's brownout -- see Jira or [action workflow failure here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/13660101822).
As droplets are still on 20.04 this is not ideal (test environment not matching beta + prod environments) but remains to be seen if this discrepancy is a problem (and in any case we have to do it to run our workflows).
Jira link: https://lite-farm.atlassian.net/browse/LF-4749
None, I'm opening the PR to see how the workflows behave.
**Checklist:**
> LF-4749 Bump Ubuntu actions runner to 24.04

- packages/webapp/src/App.jsx
- packages/webapp/src/components/Icons/icons.tsx
- packages/webapp/src/components/LocationPicker/LocationViewer.tsx
- packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
- packages/webapp/src/components/LocationPicker/styles.module.scss
- packages/webapp/src/components/Map/DrawingManager/index.jsx
- packages/webapp/src/components/Map/Header/index.jsx
- packages/webapp/src/components/Map/Header/index.tsx
- packages/webapp/src/components/Map/Header/styles.module.scss
- packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
- packages/webapp/src/components/Sensor/v2/EsciSensorList/styles.module.scss
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/styles.module.scss
- packages/webapp/src/containers/SensorList/index.tsx
- packages/webapp/src/containers/SensorList/useGroupedSensors.ts
- packages/webapp/src/routes/index.jsx
- packages/webapp/src/stories/Pages/Map/Header/MapHeader.stories.jsx
- packages/webapp/src/types/index.ts
- packages/webapp/src/util/siteMapConstants.ts
This creates a LocationViewer component -- it includes a header bar with close button and selected locations.
The full width effect is on the route and not on the component. 
Jira link: [LF-4742](https://lite-farm.atlassian.net/browse/LF-4742)
**Checklist:**
[LF-4742]: https://lite-farm.atlassian.net/browse/LF-4742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 4742 link ensemble sensor list to map

- packages/api/src/util/ensemble.js
This is not a full-fledged solution for the problem of the Ensemble API maybe being in flux, this is just restoring our Sensor List for now.
`paramter_types` is no longer returned from the device endpoint. Actually I don't think the info has been replaced yet -- I see a property `paramaters` but it is `null`. Maybe `parameter_types` will be restored? I'm not sure.
As of yet I don't think the frontend uses it so it may be safe to remove entirely in the future when we revisit the Ensemble device endpoint closer to release.
There are Sentry errors and everything for this :) Based on the timing I guess the Ensemble API was changed yesterday.
**Checklist:**
> Adjust Ensemble sensor GET to handle missing paramter_types

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/AddSensors/Partners.tsx
Referenced Figma [here](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=26281-105321&m=dev). There were only two legitimately new strings, plus several variations on strings already in app. (Nonetheless I just kept them as Loïc had them in this view and added the variations).
Fixed one tiny interpolated string issue that will not impact on what gets sent to CrowdIn but will change capitalization in app.
Jira link: https://lite-farm.atlassian.net/browse/LF-4754
Strings only with no components; not tested.
**Checklist:**
> LF-4754 Add all new strings related to Field Technology to integration

- packages/webapp/public/locales/en/translation.json
Add strings for wind direction. (I ran `pnpm i18n`, which sorted the file.)
They can be nested under `SENSOR.READING`, but since there is a possibility we'll use them elsewhere (or not?), I placed them at the top level.
Jira link: https://lite-farm.atlassian.net/browse/LF-4756
> LF-4756(2): Strings for wind direction

- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
- packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
- packages/webapp/src/containers/Map/index.jsx
- packages/webapp/src/containers/Map/useMapAssetRenderer.js
- packages/webapp/src/util/google-maps/cleanupListeners.ts
- packages/webapp/src/util/google-maps/debugListeners.ts
Based on [this conversation](https://github.com/LiteFarmOrg/LiteFarm/pull/3731#discussion_r2047585402) in Github.
Event listeners have always been added to our Google Map objects in each of our map components without cleanup when the component unmounts. In general this seems like a bad idea, although I dislike that the Google Maps API documentation is not really clear about the recommended cleanup pattern (e.g. there is no mention of cleanup at all in the `event.addListener()` [example code or description](https://developers.google.com/maps/documentation/javascript/events#EventListeners)) which made me wonder if Google Maps was even handling it under the hood 🤷
The cleanup was evaluated with the debugging functions (below) which verified that `hasListeners()` became false, …
> LF-4797 Clean up Google maps event listeners added with `maps.event.addListener()`

- packages/webapp/src/components/ActionMenu/index.tsx
- packages/webapp/src/components/ActionMenu/styles.module.scss
- packages/webapp/src/components/Animals/AddAnimalsForm/MoreAnimalsCard.tsx
- packages/webapp/src/components/Animals/AddAnimalsForm/styles.module.scss
- packages/webapp/src/components/Animals/AnimalSingleViewHeader/styles.module.scss
- packages/webapp/src/components/Expandable/styles.module.scss
- packages/webapp/src/components/Form/ContextForm/styles.module.scss
- packages/webapp/src/components/Form/LockedInput/index.tsx
- packages/webapp/src/components/Form/LockedInput/styles.module.scss
- packages/webapp/src/components/Icons/styles.module.scss
- packages/webapp/src/components/IrrigationPrescription/styles.module.scss
- packages/webapp/src/components/List/ListItems/IconDescription/styles.module.scss
- packages/webapp/src/components/ManageESciSection/styles.module.scss
- packages/webapp/src/components/MapDrawer/MapDrawerMenuItem.jsx
- packages/webapp/src/components/MapDrawer/styles.module.scss
- packages/webapp/src/components/Tile/SensorTile/styles.module.scss
- packages/webapp/src/components/TileDashboard/DashboardTile/styles.module.scss
- packages/webapp/src/containers/Animals/Inventory/styles.module.scss
A cleanup task from [this PR discussion](https://github.com/LiteFarmOrg/LiteFarm/pull/3738#pullrequestreview-2784805138) that I figured would touch enough files to be better in its own PR.
This removes the white background from `<Icon />` which apparently
- was never used in any view
- was overwritten ~10x~ 14x in the codebase instead of us just removing the background 😅
How did it happen? I have no idea. We should have removed it long ago!
Note: PR also contains automatic linting on the SCSS files, not sure why our dev team isn't on same settings there 🤔 
Jira link: https://lite-farm.atlassian.net/browse/LF-4800
**Checklist:**
> LF-4800 Remove white background colour from <Icon /> component and clean up related code

- packages/api/db/migration/20250430202219_add_irrigation_prescription_id_and_permissions.js
- packages/api/src/models/irrigationTaskModel.js
- packages/api/src/routes/irrigationPrescriptionRequestRoute.ts
- packages/api/src/routes/sensorRoute.js
- Adds a column to store the ESci Irrigation Prescription primary key on the `irrigation_task` table
- As previously decided in group discussion, this should not be copied in copy crop plan so is omitted from the template mapping schema
- Updates `get:sensors` permission (recently added for the new sensor routes) to `get:smart_irrigation` for shared use between the sensor + IP routes of the new project, see [this GitHub comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3723#discussion_r2032184628)
Jira link: https://lite-farm.atlassian.net/browse/LF-4764
Inspected database table + schema, checked sensor routes with new permissions
**Checklist:**
> LF-4764 Add irrigation_prescription_external_id to irrigation_task table

- packages/api/src/controllers/taskController.js
- packages/api/tests/task.test.js
This PR commits the linting changes to `taskController.js` and `task.test.js` and handles the es-lint errors preventing commit to those files by either bypassing (in the test file, which had 88 eslint errors) or fixing (in the controller, which had two). This is so that:
- the files can be committed to with the current version of our linting packages
- the diff is not impossibly messy to read when the meaningful changes are added in LF-4769.
**Checklist:**
> LF-4769 Pre-PR Linting Commit -- taskController and task.test.js

- .github/pull_request_template.md
We're no longer adding `MISSING` strings to translation files, so I've replaced the PR checklist item with a more appropriate one.
Please let me know if you have any feedback!
Jira link: N/A
> Adjust PR Checklist

- packages/webapp/src/components/Map/PreviewPopup/index.jsx
- packages/webapp/src/containers/Map/LocationSelectionModal/index.jsx
- Add fallback object for reading_types selector result
- Update condition for showing `<PurePreviewPopup />` so it doesn't appear when ESci sensor icons are clicked
Jira link: https://lite-farm.atlassian.net/browse/LF-4785
**Checklist:**
> LF-4785: Fix crash when long pressing ESci sensor icon

- packages/webapp/src/components/Form/ContextForm/WithStepperProgressBar.tsx
- packages/webapp/src/containers/AddSensors/index.tsx
We were passing `isEditing` and `setIsEditing` to `<ContextForm />` to hide the form navigation buttons. However, when `setIsEditing` is passed, `ContextForm` skips calling `history.back()` on cancel (`onCancel`).
This PR adds a new `hideFormNavigationButtons` prop on `WithStepperProgressBar` to control button visibility.
Jira link: https://lite-farm.atlassian.net/browse/LF-4773
**Checklist:**
> LF-4773: Cancel and back buttons are not working on the add sensors flow

- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/Form/Input/input.module.scss
- packages/webapp/src/stories/Form/Input/Input.stories.jsx
The clear icon was previously positioned inside the wrapper that also contained the label and error message. When no label or error was present, its absolute positioning caused it to appear misaligned.
This PR moves the icon into the wrapper that only contains the input field, ensuring correct positioning in all cases.
Stories:
- [with error without label](http://localhost:6006/?path=/story/components-input--with-error-without-label)
- [Date input](http://localhost:6006/?path=/story/components-input--date)
- [Date input with error](http://localhost:6006/?path=/story/components-input--date-with-error)
Jira link: https://lite-farm.atlassian.net/browse/LF-4707
**Checklist:**
> LF-4707: Clear error icon position is off on input without a label

- packages/api/db/migration/20250514175826_create_soil_sample_location.js
This migration:
- Adds the new database table with one column (`location_id`) as in the DB diagram
- Adds the typical location permissions (all locations cannot be added/edited by workers)
- Adds the type to the figure check
Loïc has [confirmed](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil?node-id=40203-127413&m=dev#1256712377) that there are no other columns on this table (= properties on soil sample location details). The `lat`/`lng` will be shown, but that resides on the `point` table.
Jira link: https://lite-farm.atlassian.net/browse/LF-4828
Database inspection + have the rest of the user story locally.
**Checklist:**
> LF-4828 Add database migration to support new location type

- packages/webapp/src/containers/Task/saga.js
- packages/webapp/src/containers/slice/taskSlice/animalMovementTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/cleaningTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/fieldWorkTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/harvestTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/irrigationTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/pestControlTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/plantTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/soilAmendmentTaskSlice.js
- packages/webapp/src/containers/slice/taskSlice/transplantTaskSlice.js
While working on https://github.com/LiteFarmOrg/LiteFarm/pull/3752, I noticed that when switching farms, task type tasks were not being updated in the Redux store as expected. The reducer used `upsertMany`, which merges tasks instead of replacing them. As a result, tasks from the previous farm were still present after switching.
This caused a bug when checking if any irrigation task had an IP - it was being evaluated against tasks from a different farm as well.
I fixed the `getIrrigationTasksSuccess` reducer in the PR above. This PR applies the same fix to the remaining task types.
Jira link: https://lite-farm.atlassian.net/browse/LF-4818
**Checklist:**
> LF-4818: Fix get task type tasks success reducers

- packages/webapp/src/components/LocationPicker/SingleLocationPicker/index.jsx
- packages/webapp/src/containers/LocationDetails/PointDetails/SoilSampleLocationDetailForm/EditSoilSampleLocation.jsx
- packages/webapp/src/containers/LocationDetails/PointDetails/SoilSampleLocationDetailForm/saga.js
- packages/webapp/src/routes/SoilSampleLocationDetailsRoutes.jsx
- packages/webapp/src/routes/index.jsx
This completes the frontend of the new location type by adding the routing, sagas for edit (and delete), and the last component (`EditSoilSampleLocationDetailForm`) to the frontend.
As before, this is based on exactly copying the existing point locations.
Jira link: https://lite-farm.atlassian.net/browse/LF-4831
**Checklist:**
> LF-4831 UI flow to view and edit soil sample location

- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/components/Task/TaskReadOnly/styles.module.scss
- packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
- packages/webapp/src/stories/IrrigationPrescription/mockData.tsx
- packages/webapp/src/util/geoUtils.ts
This Displays the IP detail and files on the task read only view.
Adds dynamic mock to show some details on local locations instead of near ubc.
Jira link: [LF-4772](https://lite-farm.atlassian.net/browse/LF-4772)
**Checklist:**
[LF-4772]: https://lite-farm.atlassian.net/browse/LF-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Lf 4772 display ip details and file on task detail view

- packages/api/db/migration/20250520185926_create_soil_sample_task_table.js
This is the migration for the new task type. The PR:
- Adds the task type to the `task_type` table (this holds custom types as well so the generated id will depend on the db environment)
- Creates the table for the new task type
- Assumes the task locations will be associated via the `location_tasks` table (i.e. in the normal way) for both field + soil sample locations
- Uses an array for the sampling depths. This array is implemented in `jsonb` which is our codebase pattern for other tables with array datatypes (e.g. `grid_points` of area or `variables` of notification)
- Update May 21st: this will end up being an array of _objects_ (indicating `upperDepth` and `lowerDepth` of a depth range) but from the perspective of the database, the datatype and checks are unchanged …
> LF-4832 Add database migration to support new task type

- packages/webapp/src/components/Task/SoilSampleTask/styles.module.scss
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/containers/Task/saga.js
- packages/webapp/src/containers/slice/taskSlice/soilSampleTaskSlice.js
- packages/webapp/src/containers/taskSlice.js
- packages/webapp/src/store/reducer.js
- packages/webapp/src/util/siteMapConstants.ts
- Set up slices, reducers, sagas to process soil sample tasks. (copied from another task type)
- Add `PureSoilSampleTask` to `TaskReadOnly`.
- Adjust `PureSoilSampleTask` styling.
Jira link: https://lite-farm.atlassian.net/browse/LF-4835
**Checklist:**
> LF-4835: Soil sampling task read-only view

- packages/api/src/routes/taskRoute.js
- packages/api/tests/mock.factories.js
- packages/api/tests/task.test.js
- packages/api/tests/utils/taskUtils.js
- packages/api/tests/utils/testDataSetup.ts
- packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
This is the boilerplate (no unique checks) implementation of the complete endpoint for soil sample task. The frontend only needed a single change (addition of the details component into `TaskComplete/StepOne` so I have included that too.
With that change, the complete flow should be totally functional, and just needs the document part, which is a separate set of tickets.
Jira link: https://lite-farm.atlassian.net/browse/LF-4839
**Checklist:**
> LF-4839 Add endpoint to complete a soil sampling task

- packages/webapp/src/containers/Map/mapFilterSettingSlice.js
- packages/webapp/src/containers/Map/useMapAssetRenderer.js
- packages/webapp/src/containers/Map/useMaxZoom.js
- packages/webapp/src/containers/locationSlice.js
This fixes a bug where task filters are breaking from external sensors due to a `localeCompare` on label.
This separates out the externalPoints from the point selector (and therefore locationsSelector)
This removes external points from:
- filters, task options, etc which is probably preferred
- adds external points to all cases where pointselector (maps) was used EXCEPT locationsSelector (tasks, animals)
- should a bug occur in tasks or animals (unlikely), the fix should be the same as these here but in the container `{...locations, ...externalPoints}`
@kathyavini 
Jira link:
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your …
> Tasks crash - extract out external points from the point selector

- packages/webapp/src/components/Filter/FilterMultiSelectV2/index.tsx
More of a band-aid than a comprehensive solution, this restores the task list for bug bashing on the Ensemble sensor arrays, which are crashing the tasks filter due to missing label.
A more complete solution would double-check if the name property previously returned was important here AND/OR be more careful about selectors to remove sensor arrays from the pointSelector entirely.
But no harm in also making the filter more robust to missing labels.
**Checklist:**
> [Quick Bugfix] Add optional chaining on label localeCompare

- packages/api/db/migration/20250527173006_cleanup_previous_sensors_implementation.js
***My db crashed and in order to add this to beta we need to rollback the last migration on beta.
1. Adds two more missing task relationships, it is good to be complete and cover all cases since we don't know state of all LiteFarm developers local databases. Are there any more that we skipped because they were not on beta?
This is the case where we are deleting a task that is also related to an animal. (Custom task)
2. Fix migrate:testing:db
- testing database migration fails because there is an empty array being attempted to insert
Jira link: …
> Migration failure delete task animal relationships too

- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
Upgrade `google-map-react` to 2.2.5. (The new version was published to npm! 2.2.2 was skipped.)
This resolves `findDOMNode is deprecated and will be removed in the next major release.` warning.
Jira link: https://lite-farm.atlassian.net/browse/LF-4809
**Checklist:**
> LF-4809 Upgrade google-map-react to 2.2.2

- packages/webapp/src/components/Documents/Add/index.jsx
Addresses the [deploy failure](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/15596857822/job/43929126972) on the merge of:
- #3800 
by fixing the import syntax (we use `lodash-es` and import from it). I'm surprised neither dev environment nor local `pnpm build` complained 🤷
Couldn't really test; will merge
**Checklist:**
> Fix import of lodash isEqual in documents

- packages/api/src/util/ensemble.js
- packages/webapp/src/components/LocationFieldTechnology/index.jsx
- packages/webapp/src/components/Sensor/v2/EsciSensorList/index.tsx
- packages/webapp/src/components/Sensor/v2/utils.ts
- packages/webapp/src/containers/SensorList/useGroupedSensors.ts
- packages/webapp/src/containers/SensorReadings/v2/index.tsx
- packages/webapp/src/store/api/types/index.ts
This passes down the system that a profile is nested under (I don't think sensors not within profiles have systems), and displays it in the UI.
It also fixes (restores) the Field Technology grouping headers that I destroyed by deleting the fake sensor array "name" (the property that used to say "Sensor Array 1", etc). We looked at that on the Bug Bash table, but I don't think a ticket was made for it, so I have just linked the system name ticket.
Jira link: https://lite-farm.atlassian.net/browse/LF-4872
**Checklist:**
> LF-4872 Show irrigation system name somewhere on the sensor list

- packages/webapp/src/containers/SensorReadings/v2/Charts/useFormattedSensorReadings.ts
- packages/webapp/src/containers/SensorReadings/v2/utils.ts
- packages/webapp/src/tests/sensorChartUtils.test.js
- Update `formatSensorDatapoints` function to insert a placeholder if the first data point doesn't start at startDate
- Add tests (run `pnpm test sensorChartUtils`
This won't change the x-axis but will adjust the left padding.
(I force-pushed to fix a commit message)
Jira link: https://lite-farm.atlassian.net/browse/LF-4873
**Checklist:**
> LF-4873: Issues in custom date range filter for sensor readings

- packages/webapp/src/components/LocationTasks/index.jsx
- packages/webapp/src/components/LocationTasks/styles.module.scss
- packages/webapp/src/containers/LocationDetails/LocationTasks/index.jsx
Adds the floating action button to add a task to the location tasks menu tab.
Notes
- also looked to see if it was on management plan tasks -- it is not but "Add task" link is present. Presumably adding the floating button would clash with the complete buttons?
- In management plan tasks the "Add task" button is restricted to `isAdmin`. But not in tasks or location tasks -- not sure the reason for this
Jira link: [LF-4862](https://lite-farm.atlassian.net/browse/LF-4862)
**Checklist:**
[LF-4862]: https://lite-farm.atlassian.net/browse/LF-4862?atlOrigin=eyJpIj …
> LF-4862 Add back the add task button to location task screen

- packages/webapp/src/components/Tile/SensorTile/SensorKPI.tsx
- packages/webapp/src/containers/SensorList/useGroupedSensors.ts
- packages/webapp/src/containers/SensorReadings/v2/utils.ts
- packages/webapp/src/tests/sensorChartUtils.test.js
- packages/webapp/src/util/rounding.js
As requested by Ensemble -- we were showing these values at a higher level of precision than the actual measurements warrant. They asked us to show all values to the tenths place.
This also adds rounding on the depth value shown in the sensor KPI, which is a [separate ticket](https://lite-farm.atlassian.net/browse/LF-4867) but easiest to solve both with a the new rounding function `roundToOne`
Jira link: https://lite-farm.atlassian.net/browse/LF-4871
**Checklist:**
> LF-4871 Sensor KPIs & sensor readings tooltips should be to one decimal place not two

- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Modals/NoSoilSampleLocationsModal/index.jsx
- packages/webapp/src/components/Task/PureTaskTypeSelection/PureTaskTypeSelection.jsx
This PR adjusts the "No eligible soil sample locations" modal for workers based on the corresponding modal for no locations ("No locations for tasks" / "You’ll need management to create at least one location before you can create a task."). It updates the string and fixes the buttons so workers are not directed to the map.
Jira link: https://lite-farm.atlassian.net/browse/LF-4876
**Checklist:**
> LF-4876 The worker is directed to create a location for a soil sample task even though he is not allowed to do this

- packages/api/src/util/ensembleService.ts
- packages/api/src/util/ensembleService.types.ts
- packages/api/src/util/generateMockPrescriptionDetails.ts
- packages/api/tests/irrigation_prescription.test.ts
- packages/webapp/.storybook/state.js
- packages/webapp/package.json
- packages/webapp/pnpm-lock.yaml
- packages/webapp/src/components/IrrigationPrescription/IrrigationPrescriptionMapView.tsx
- packages/webapp/src/components/IrrigationPrescription/index.tsx
- packages/webapp/src/components/LocationPicker/SingleLocationPicker/drawLocations.js
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
- packages/webapp/src/containers/IrrigationPrescription/index.tsx
- packages/webapp/src/containers/Map/constants.js
- packages/webapp/src/containers/Map/mapStyles.js
- packages/webapp/src/containers/Map/styles.module.scss
- packages/webapp/src/store/api/types/index.ts
- packages/webapp/src/stories/IrrigationPrescription/IrrigationPrescriptionMapView.stories.tsx
- packages/webapp/src/util/geoUtils.ts
These are the updates needed to represent pivots that only traverse partial circles (i.e. pie slices, which Turf.js calls [sectors](https://turfjs.org/docs/api/sector)) in irrigation prescriptions. The code had to be updated in three ways to handle the `pivot.arc` object, listed below. If `pivot.arc` or start/end angle is omitted, the original code -- for a full circle -- will be used in each of these places:
1. The map view needs to render a sector instead of the full circle. The Google Maps circle geometry didn't include the ability to define sectors natively, so the super-useful Turf package has been used once again to create a polygon of lat/lng coordinates based on centre, radius, and angles. Map styles were updated for this polygon type to match the original pivot …
> LF-4885 Handle pivot arcs

- packages/api/package-lock.json
- packages/api/package.json
- packages/api/src/controllers/timeNotificationController.js
- packages/api/src/models/locationModel.js
- packages/api/src/services/addonPartner.ts
- packages/api/src/util/ensembleService.ts
- packages/api/tests/timeNotification.test.js
- packages/api/tests/utils/testDataSetup.ts
This PR fixes two bugs with IP notifications:
1. We had been returning only the latest IP _per farm_, when a given farm potentially has 2-3+ new IPs per day, depending on the number of pivot-containing locations defined.
2. (Noticed this when testing notifications, but it's an oversight affecting all IPs) IPs from deleted locations weren't being filtered out. That filtering has been added to the location model method that we have been using to identify + filter the correct farm. This means notifications, the list GET, and the details GET will all no longer return IPs if their listed location has been deleted.
This PR also includes updates to the test cases on IP notifications to reflect the above.
Jira link: https://lite-farm.atlassian.net/browse/LF-4886 …
> LF-4886 Users should get one IP notification per location, not per day

- packages/api/src/controllers/taskController.js
- packages/api/src/middleware/validation/checkTask.js
- packages/api/src/routes/taskRoute.js
- packages/api/tests/testEnvironment.js
_(This is a blocker for [LF-4815](https://lite-farm.atlassian.net/browse/LF-4815), but otherwise, no rush!)_
Update the `completeTask` method in `taskController` to add `revision_date` and `revised_by_user_id` if the task is being re-completed (= the task already has a `complete_date`).
NOTE:
- Harvest task type will be handled in [LF-4819](https://lite-farm.atlassian.net/browse/LF-4819)
- Task completion is not always working properly ([LF-3134](https://lite-farm.atlassian.net/browse/LF-3134)), so tests will be added once that issue is resolved.
Details:
- The `checkTask` middleware already checks whether a task is completed or abandoned. I added `res.locals.isReCompleting` there to avoid duplicating that logic in the controller.
- `checkTask` was previously only used for …
> LF-4817 (1): Set revision date and revision author when re-completing a task

- packages/webapp/src/containers/AddFarm/currency/commonCurrency.json
This PR fixes the issue where the Finance page incorrectly displayed the currency for Zambia as USD ($) instead of the correct Zambian Kwacha (ZK).
Jira link:https://lite-farm.atlassian.net/browse/LF-4887
**Checklist:**
> LF-4887 Zambia Currency (ZMW) Displays as USD on Finance Page

- packages/api/db/user_data_requests/02-export_user_data.sql
- packages/api/db/user_data_requests/03-delete_user_data.sql
- packages/api/db/user_data_requests/common/00-scoped_table_lists.sql
- packages/api/db/user_data_requests/common/01-user_data_indices.sql
So sorry @SayakaOno -- I didn't set out to give you 900 lines of SQL to review when I was thinking about the fastest way to implement deletion 🙇 I also had forgotten about export at that time. I don't think this is an ideal method, and I'll mention some future improvements at the end of this description, but I think for now improving this isn't a very high priority overall.
I would lightly recommend reading the scripts in execution (numbered) order.
```
db/user_data_requests/
├──common/
├── 00-scoped_table_lists.sql 
└── 01-user_data_indices.sql
├── 02-export_user_data.sql 
└── 03-delete_user_data.sql
```
The logic behind the scripts is that for user export, basically we want to to loop through a pattern that looks like this:
```sql
SELECT json_build_object(
'userLog', ( …
```
> LF-4889 User data deletion and export scripts

- packages/api/src/util/ensembleService.ts
- packages/api/tests/irrigation_prescription.test.ts
The water consumption calculation was relying on `% 360` to calculate the proportion of the circle covered, and so incorrectly returned 0 for all full circles instead of 1. A test case was added.
Jira link: https://lite-farm.atlassian.net/browse/LF-4896
**Checklist:**
> LF-4896 Water consumption is incorrectly showing as 0 for URI prescriptions with 0 to 360º arcs

- packages/api/src/controllers/taskController.js
- packages/api/src/models/taskModel.js
- packages/api/src/services/task.ts
- packages/api/src/util/ensembleService.ts
- packages/api/tests/mock.factories.js
- packages/api/tests/task.test.js
- packages/api/tests/utils/taskUtils.js
- packages/webapp/src/containers/Task/TaskReadOnly/index.jsx
This PR adds patching an Ensemble IP as `approved: false` after we delete a task that had an `irrigation_prescription_external_id` associated with it, keeping the Ensemble state in sync with LiteFarm.
The PR includes:
- tiny update to `patchIrrigationPrescriptionApproval()` so we can use it for passing both kinds of patch
- the `triggerPostTaskDeletedActions()` side-effect function that mirrors `triggerPostTaskCreatedActions`
- The logic is slightly more involved only because the deleted task (unlike the created task) is not returned with the whole graph of task type + task type-specific tables
- this missing graph is also the reason for the slight modification of the `deleteTaskAndTaskProduct` model method, to return some task type information
- test case + one supporting …
> LF-4888 Modify task deletion to accept IP id and update task status on deletion

- packages/webapp/src/components/Form/Input/index.jsx
- packages/webapp/src/components/Form/Input/input.module.scss
- packages/webapp/src/stories/Form/Input/Input.stories.jsx
Fix the input component to display unit.
This bug was introduced in [v3.6.0](https://github.com/LiteFarmOrg/LiteFarm/releases/tag/v3.6.0) (Jan 4, 2024) when a background-color was added to the input ([change](https://github.com/LiteFarmOrg/LiteFarm/commit/188ea18033955eeb73e01c160e66b853eba3b332#diff-5a6c95d26a738de469dde15213a917c5371419433cca79068b676e5dd4541766)).
Previously, the unit was positioned absolutely relative to the container with the label, which caused it to be hidden by the background colour.
Without a label, this would cause the unit to be misaligned, similar to the clear button issue (https://github.com/LiteFarmOrg/LiteFarm/pull/3764).
Even though this issue hasn't seen in the app,  I **moved the unit to the input wrapper and adjusted its position** …
> LF-4903: It is not quite clear how you are going to override wage

- packages/webapp/src/containers/Task/saga.js
- packages/webapp/src/containers/Task/sagaUtils.js
- packages/webapp/src/tests/taskSagaUtils.test.js
Call `getProductsSaga` when creating an already completed task with a new product (`createTaskSaga`).
- Add and use `postTaskRequestHasNewProduct` function to determine whether `getProductsSaga` should be called.
Test: `npm run test taskSagaUtils`
Jira link: https://lite-farm.atlassian.net/browse/LF-4228
**Checklist:**
> LF-4228: Product and supplier fields are not populated once user tries to complete soil amendment task with newly created product

- packages/api/tests/mock.factories.js
- packages/api/tests/task.test.js
- packages/api/tests/utils/taskCompletionTestCases.js
- packages/api/tests/utils/taskUtils.js
Add tests for task re-completion and update task completion tests.
- mock.factories
- Rename `activity` (task's old name) to `task`
- Update `irrigation_taskFactory` to include `irrigation_type_id` by default
- Although `null` is allowed, but it never actually becomes `null`
- This change addresses Joyce's [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3839#discussion_r2237687757) on irrigation task completion tests and should help write cleaner tests
- task.test
- replace the `for` loop in the task completion tests with `test.each` to fix strange debugger behaviour ([reference](https://github.com/LiteFarmOrg/LiteFarm/pull/3839#pullrequestreview-3064358642))
- Test cases were formatted first; besides that, the only change is to make the last `expect` more flexible …
> LF-4817(2): Tests for revision date and revision author when re-completing a task

- packages/webapp/public/locales/en/common.json
- packages/webapp/public/locales/en/translation.json
- packages/webapp/src/components/Task/RevisionPrompt/index.tsx
- packages/webapp/src/components/Task/RevisionPrompt/styles.module.scss
- packages/webapp/src/components/Task/TaskReadOnly/index.jsx
Add `RevisionPrompt` component and show it in task read-only view when the task has been completed and the user can complete the task.
Jira link: https://lite-farm.atlassian.net/browse/LF-4812
**Checklist:**
> LF-4812: Show button to re-trigger completion in read only task view

- packages/webapp/src/containers/Animals/Inventory/KPI/index.tsx
- packages/webapp/src/containers/Animals/Inventory/useAnimalsExist.tsx
Fix crashes offline by defaulting array values to `[]` when undefined.
Animals/batches/animal types might be pre-cached later, but this shouldn't hurt.
The fixes were tested on the offline POC branch mentioned in this [ticket](https://lite-farm.atlassian.net/browse/LF-4941).
(Offline testing was tricky with these bugs, so I decided to addressed them)
Jira link: https://lite-farm.atlassian.net/browse/LF-4947
I used Joyce's offline POC [branch](https://github.com/LiteFarmOrg/LiteFarm/tree/LF-4941-spike-technical-requirements-of-offline-capability).
**Checklist:**
> LF-4947:  Animals page and create task page display error screen when user is offline

- packages/webapp/src/components/Task/TaskComplete/HarvestComplete/HarvestUses.jsx
- packages/webapp/src/components/Task/TaskComplete/HarvestComplete/Quantity.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
Pre-fill `PureHarvestCompleteQuantity`, `HarvestUses`, `PureTaskComplete` for re-completion.
Jira link: https://lite-farm.atlassian.net/browse/LF-4814
**Checklist:**
> LF-4814: Pre-fill task completion flow forms with previous values

- packages/webapp/src/components/Task/TaskComplete/index.jsx
I was in the mood for a lightweight bug 😂🙏 Missed this completely the other day, sorry 🙇 
`null` happiness is indeed the right data model for having selected "I prefer not to say", but only on a task that has already been completed.
Jira link: https://lite-farm.atlassian.net/browse/LF-4958
**Checklist:**
> LF-4958 "I prefer not to say" Option Is Preselected by Default When Starting Task Completion

- packages/webapp/src/components/Task/TaskComplete/StepOne.jsx
- packages/webapp/src/components/Task/TaskComplete/index.jsx
This one wasn't quite as smooth and fun a bugfix as the other, since everything with `hookFormPersist` completely confuses me 🤣 
But in a nutshell, the issue was that in `PureCompleteStepOne`, the default form values are taken from either the (database saved) `selectedTask` -or- the `persistedFormData`, based on `need_changes`:
```js
const defaultsToUse = formatTaskReadOnlyDefaultValues(
persistedFormData.need_changes ? persistedFormData : selectedTask,
);
```
This is exactly the right behaviour for the task-specific details fields, but not for the complete fields, on which `need_changes` has no relevance (we always want the `persistedFormData` to take precedence if it exists).
When unmounting `/before_complete`, `useHookFormPersist` updates the persistedFormData will the …
> LF-4957 Rating, Notes, and Time Spent Not Persisted During Task Re-Completion

- packages/webapp/src/routes/Onboarding.jsx
- packages/webapp/src/routes/index.jsx
I noticed while upgrading `react-router-dom` that users could access routes that should be hidden.
This PR:
- removes `/people` and `/farm` for worker accounts (sidebar navs are hidden)
- comments out `/add_task/edit_custom_task_update` (this should've been hidden as part of "Comment out route for edit custom task type" [ticket](https://lite-farm.atlassian.net/browse/ST-367))
- remove unused imports (address Joyce's [comment](https://github.com/LiteFarmOrg/LiteFarm/pull/3862#discussion_r2325858604), thank you!! 🙏)
Jira link:
- https://lite-farm.atlassian.net/browse/LF-4922
- https://lite-farm.atlassian.net/browse/LF-4923
- https://lite-farm.atlassian.net/browse/LF-4940
**Checklist:**
> Routes cleanup
